# Generated by Django 5.0.2 on 2025-03-06 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0115_alter_apphseperformancereportchemicalused_expire_dt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HseTraditionalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('year', models.IntegerField(verbose_name='year')),
                ('month', models.IntegerField(verbose_name='month')),
                ('state', models.IntegerField(choices=[(1, 'draft'), (2, 'confirmed'), (3, 'IT_STATE_APPROVED')], default=1, verbose_name='record_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=255, verbose_name='market_name')),
                ('percent', models.FloatField(verbose_name='percent')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environmental_requirements', to='hse_traditional.hsetraditionalreport')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=255, verbose_name='market_name')),
                ('what', models.TextField(verbose_name='what')),
                ('who', models.CharField(max_length=255, verbose_name='who')),
                ('hazard_identified', models.TextField(verbose_name='hazard_identified')),
                ('closed_date', models.DateField(verbose_name='closed_date')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environmental_inspections', to='hse_traditional.hsetraditionalreport')),
            ],
        ),
        migrations.CreateModel(
            name='ArrangementOfMarkets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=255, verbose_name='market_name')),
                ('notes', models.TextField(verbose_name='notes')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrangement_of_markets', to='hse_traditional.hsetraditionalreport')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('brief', models.TextField(verbose_name='brief')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='hse_traditional.hsetraditionalreport')),
            ],
        ),
        migrations.CreateModel(
            name='QuickEmergencyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(verbose_name='issue')),
                ('communication_factors', models.TextField(verbose_name='communication_factors')),
                ('notes', models.TextField(verbose_name='notes')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_emergency_teams', to='hse_traditional.hsetraditionalreport')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingAwareness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_id', models.CharField(max_length=255, verbose_name='training_id')),
                ('subject', models.TextField(verbose_name='subject')),
                ('attendees', models.IntegerField(verbose_name='attendees')),
                ('notes', models.TextField(verbose_name='notes')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_awarenesses', to='hse_traditional.hsetraditionalreport')),
            ],
        ),
        migrations.CreateModel(
            name='WasteManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=255, verbose_name='market_name')),
                ('item_description', models.TextField(verbose_name='item_description')),
                ('material_by_ton', models.FloatField(verbose_name='material_by_ton')),
                ('markets', models.TextField(verbose_name='markets')),
                ('comment', models.TextField(verbose_name='comment')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_managements', to='hse_traditional.hsetraditionalreport')),
            ],
        ),
    ]
