# Generated by Django 5.0.2 on 2025-03-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastemanagement',
            name='markets',
        ),
        migrations.AddField(
            model_name='arrangementofmarkets',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='percent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingawareness',
            name='market_name',
            field=models.CharField(default='', max_length=255, verbose_name='market_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingawareness',
            name='traning_type',
            field=models.IntegerField(choices=[(1, 'Training'), (2, 'Awareness')], default=1, verbose_name='training_type'),
            preserve_default=False,
        ),
    ]
