# Generated by Django 5.0.2 on 2025-03-06 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0115_alter_apphseperformancereportchemicalused_expire_dt'),
        ('hse_traditional', '0002_remove_wastemanagement_markets_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HseTraditionalAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('type', models.CharField(choices=[('safty', 'Safty'), ('enviromental', 'Environmental')], max_length=20, verbose_name='accident_type')),
                ('state', models.IntegerField(choices=[(1, 'draft'), (2, 'confirmed'), (3, 'approved')], default=1, verbose_name='record_state')),
                ('what', models.TextField(verbose_name='what')),
                ('when', models.DateTimeField(verbose_name='when')),
                ('where', models.TextField(verbose_name='where')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='source_state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HseTraditionalAccidentDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.TextField(verbose_name='damage')),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damages_list', to='hse_traditional.hsetraditionalaccident')),
            ],
        ),
        migrations.CreateModel(
            name='HseTraditionalAccidentInjury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injuries', models.TextField(verbose_name='injuries')),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='injuries_list', to='hse_traditional.hsetraditionalaccident')),
            ],
        ),
        migrations.CreateModel(
            name='HseTraditionalAccidentWho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.TextField(verbose_name='who')),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='who_list', to='hse_traditional.hsetraditionalaccident')),
            ],
        ),
        migrations.CreateModel(
            name='HseTraditionalAccidentWhy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why', models.TextField(verbose_name='why')),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='why_list', to='hse_traditional.hsetraditionalaccident')),
            ],
        ),
    ]
