# Generated by Django 5.0.2 on 2025-03-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0003_hsetraditionalaccident_hsetraditionalaccidentdamage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsetraditionalaccidentwho',
            name='who',
            field=models.CharField(max_length=150, verbose_name='who'),
        ),
    ]
