# Generated by Django 5.0.2 on 2025-03-09 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0007_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmediateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='immediate_actions', to='hse_traditional.hsetraditionalreport')),
            ],
            options={
                'verbose_name': 'Immediate Action',
                'verbose_name_plural': 'Immediate Actions',
            },
        ),
    ]
