# Generated by Django 5.0.2 on 2025-03-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0009_remove_immediateaction_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsetraditionalcorrectiveaction',
            name='state',
            field=models.IntegerField(choices=[(1, 'draft'), (12, 'confirmed_emp'), (22, 'confirmed_mngr'), (3, 'approved')], default=1, verbose_name='record_state'),
        ),
    ]
