# Generated by Django 5.0.2 on 2025-03-09 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0115_alter_apphseperformancereportchemicalused_expire_dt'),
        ('hse_traditional', '0010_alter_hsetraditionalcorrectiveaction_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblStateRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hse_tra_state', to='company_profile.lkpstate', verbose_name='state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hse_tra_state', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'state representative',
                'verbose_name_plural': 'state representatives',
            },
        ),
        migrations.AddConstraint(
            model_name='tblstaterepresentative',
            constraint=models.UniqueConstraint(fields=('user', 'state'), name='unique_user_state'),
        ),
    ]
