# Generated by Django 5.0.2 on 2025-03-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0011_tblstaterepresentative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hsetraditionalcorrectiveaction',
            name='what',
        ),
        migrations.RemoveField(
            model_name='hsetraditionalcorrectiveaction',
            name='where',
        ),
    ]
