# Generated by Django 5.0.2 on 2025-03-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0012_remove_hsetraditionalcorrectiveaction_what_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='brief',
            field=models.TextField(verbose_name='Describe briefly , وصف مختصر'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Achievements   الإنجازات'),
        ),
        migrations.AlterField(
            model_name='arrangementofmarkets',
            name='market_name',
            field=models.CharField(max_length=255, verbose_name='Market name / اسم السوق'),
        ),
        migrations.AlterField(
            model_name='arrangementofmarkets',
            name='notes',
            field=models.TextField(verbose_name='Notes ملاحظات'),
        ),
        migrations.AlterField(
            model_name='arrangementofmarkets',
            name='percent',
            field=models.IntegerField(verbose_name='Percent % النسبة'),
        ),
        migrations.AlterField(
            model_name='environmentalinspection',
            name='closed_date',
            field=models.DateField(verbose_name='Closed date الاغلاق'),
        ),
        migrations.AlterField(
            model_name='environmentalinspection',
            name='hazard_identified',
            field=models.TextField(verbose_name='Hazard identified تحديد المخاطر'),
        ),
        migrations.AlterField(
            model_name='environmentalinspection',
            name='what',
            field=models.TextField(verbose_name='What ماذا'),
        ),
        migrations.AlterField(
            model_name='environmentalinspection',
            name='who',
            field=models.CharField(max_length=255, verbose_name='Who من'),
        ),
        migrations.AlterField(
            model_name='environmentalrequirements',
            name='market_name',
            field=models.CharField(max_length=255, verbose_name='Market name / اسم السوق'),
        ),
        migrations.AlterField(
            model_name='environmentalrequirements',
            name='percent',
            field=models.FloatField(verbose_name='Percent % النسبة'),
        ),
        migrations.AlterField(
            model_name='hsetraditionalaccident',
            name='type',
            field=models.CharField(choices=[('safty', 'Safty - سلامة'), ('enviromental', 'Environmental - بيئي')], max_length=20, verbose_name='accident_type'),
        ),
        migrations.AlterField(
            model_name='hsetraditionalaccident',
            name='what',
            field=models.TextField(verbose_name='what - ماذا'),
        ),
        migrations.AlterField(
            model_name='hsetraditionalaccident',
            name='when',
            field=models.DateTimeField(verbose_name='when - متى'),
        ),
        migrations.AlterField(
            model_name='hsetraditionalaccident',
            name='where',
            field=models.TextField(verbose_name='where - اين'),
        ),
        migrations.AlterField(
            model_name='quickemergencyteam',
            name='communication_factors',
            field=models.TextField(verbose_name='Communication factors'),
        ),
        migrations.AlterField(
            model_name='quickemergencyteam',
            name='notes',
            field=models.TextField(verbose_name='Notes ملاحظات'),
        ),
        migrations.AlterField(
            model_name='trainingawareness',
            name='attendees',
            field=models.IntegerField(verbose_name='Attendees الحضور'),
        ),
        migrations.AlterField(
            model_name='trainingawareness',
            name='market_name',
            field=models.CharField(max_length=255, verbose_name='Market name / اسم السوق'),
        ),
        migrations.AlterField(
            model_name='trainingawareness',
            name='notes',
            field=models.TextField(verbose_name='Notes ملاحظات'),
        ),
        migrations.AlterField(
            model_name='trainingawareness',
            name='subject',
            field=models.TextField(verbose_name='Subject الموضوع'),
        ),
        migrations.AlterField(
            model_name='trainingawareness',
            name='traning_type',
            field=models.IntegerField(choices=[(1, 'Training - تدريب'), (2, 'Awareness - إرشاد')], verbose_name='نوع التدريب -  type of training'),
        ),
        migrations.AlterField(
            model_name='wastemanagement',
            name='comment',
            field=models.TextField(verbose_name='Comment تعليق'),
        ),
        migrations.AlterField(
            model_name='wastemanagement',
            name='item_description',
            field=models.TextField(verbose_name='Item description وصف'),
        ),
        migrations.AlterField(
            model_name='wastemanagement',
            name='market_name',
            field=models.CharField(max_length=255, verbose_name='Market name / اسم السوق'),
        ),
        migrations.AlterField(
            model_name='wastemanagement',
            name='material_by_ton',
            field=models.FloatField(verbose_name='Material by ton الخام بالطن'),
        ),
    ]
