# Generated by Django 5.0.2 on 2025-03-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0013_alter_achievement_brief_alter_achievement_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsetraditionalcorrectiveaction',
            name='state',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'confirmed_emp'), (22, 'confirmed_mngr'), (3, 'approved')], default=1, verbose_name='record_state'),
        ),
    ]
