# Generated by Django 5.0.2 on 2025-03-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0014_alter_hsetraditionalcorrectiveaction_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingawareness',
            name='training_id',
        ),
    ]
