# Generated by Django 5.0.2 on 2025-03-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0015_remove_trainingawareness_training_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsetraditionalreport',
            name='state',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'confirmed'), (3, 'approved')], default=1, verbose_name='record_state'),
        ),
    ]
