# Generated by Django 5.1.7 on 2025-04-22 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0016_alter_hsetraditionalreport_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='HseTraditionalAccidentManagerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_comments', to='hse_traditional.hsetraditionalaccident')),
            ],
            options={
                'verbose_name': 'ملاحظات مدير الإدارة',
                'verbose_name_plural': 'ملاحظات مدير الإدارة',
            },
        ),
    ]
