# Generated by Django 5.1.7 on 2025-04-22 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0017_hsetraditionalaccidentmanagercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsetraditionalcorrectiveaction',
            name='where',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='where'),
            preserve_default=False,
        ),
    ]
