# Generated by Django 5.1.7 on 2025-04-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0018_hsetraditionalcorrectiveaction_where'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsetraditionalcorrectiveaction',
            name='where',
            field=models.DateField(verbose_name='where'),
        ),
    ]
