# Generated by Django 5.1.7 on 2025-04-22 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0019_alter_hsetraditionalcorrectiveaction_where'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hsetraditionalcorrectiveaction',
            name='where',
        ),
        migrations.AddField(
            model_name='hsetraditionalcorrectiveaction',
            name='when',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='when'),
            preserve_default=False,
        ),
    ]
