# Generated by Django 5.2.1 on 2025-07-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0020_remove_hsetraditionalcorrectiveaction_where_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsetraditionalaccident',
            name='category',
            field=models.IntegerField(choices=[(1, 'وفاة'), (2, 'اصابة'), (3, 'مركبات/اليات')], default=2, verbose_name='تصنيف الحادث'),
        ),
    ]
