# Generated by Django 5.2.1 on 2025-07-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0021_hsetraditionalaccident_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('telegram_user_id', models.CharField(max_length=100, verbose_name='Telegram user id')),
            ],
        ),
    ]
