# Generated by Django 5.2.1 on 2025-07-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0022_notifieduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifieduser',
            name='telegram_user_id',
            field=models.IntegerField(verbose_name='Telegram user id'),
        ),
    ]
