# Generated by Django 5.2.1 on 2025-07-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0023_alter_notifieduser_telegram_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifieduser',
            name='telegram_user_id',
            field=models.FloatField(verbose_name='Telegram user id'),
        ),
    ]
