# Generated by Django 5.2.7 on 2025-10-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0024_alter_notifieduser_telegram_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsetraditionalcorrectiveaction',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrective_actions', to='hse_traditional.hsetraditionalreport', verbose_name='تقرير شهري'),
        ),
    ]
