# Generated by Django 5.2.7 on 2025-10-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0025_hsetraditionalcorrectiveaction_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hsetraditionalcorrectiveaction',
            old_name='report',
            new_name='source_report',
        ),
    ]
