# Generated by Django 5.2.12 on 2026-04-09 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0138_alter_apphseaccidentreport_options'),
        ('hse_traditional', '0026_rename_report_hsetraditionalcorrectiveaction_source_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HseTraditionalInitialIncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('incident_date', models.DateField(verbose_name='التاريخ')),
                ('incident_time', models.TimeField(verbose_name='زمن وقوع الحادث')),
                ('locality', models.CharField(max_length=255, verbose_name='المحلية')),
                ('market_mine', models.CharField(max_length=255, verbose_name='سوق/منجم')),
                ('type', models.IntegerField(choices=[(1, 'انهيار بئر'), (2, 'سقوط صخور'), (3, 'سقوط وانزلاق اثناء الرفع/داخل البئر اثناء المشي'), (4, 'حادث حركة/مركبة/آلية'), (5, 'حريق/انفجار'), (6, 'نقص اوكسجين/اختناق بالغازات'), (7, 'غرق'), (8, 'صعقة كهربية'), (9, 'اخرى')], verbose_name='نوع الحادث')),
                ('classification', models.IntegerField(choices=[(1, 'جسيم'), (2, 'متوسط'), (3, 'بسيط')], verbose_name='تصنيف الحادث')),
                ('result', models.IntegerField(choices=[(1, 'وفاة'), (2, 'وفاة واصابة'), (3, 'اصابة'), (4, 'تلف/ضرر')], verbose_name='نتيجة الحادث')),
                ('summary', models.TextField(verbose_name='ملخص عن الحادث وعدد الاصابات/الوفيات/المفقودين')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='الولاية')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'تبليغ مبدئي عن حادث',
                'verbose_name_plural': 'تبليغات مبدئية عن حوادث',
            },
        ),
    ]
