# Generated by Django 5.2.12 on 2026-04-09 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0138_alter_apphseaccidentreport_options'),
        ('hse_traditional', '0027_hsetraditionalinitialincidentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsetraditionalinitialincidentreport',
            name='incident_state',
            field=models.CharField(choices=[('northern', 'الشمالية'), ('river_nile', 'نهر النيل'), ('red_sea', 'البحر الاحمر'), ('kassala', 'كسلا'), ('gedaref', 'القضارف'), ('blue_nile', 'النيل الازرق'), ('south_kordofan', 'جنوب كردفان')], default='northern', max_length=50, verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='hsetraditionalinitialincidentreport',
            name='source_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='source_state'),
        ),
    ]
