# Generated by Django 5.2.12 on 2026-04-09 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0138_alter_apphseaccidentreport_options'),
        ('hse_traditional', '0028_hsetraditionalinitialincidentreport_incident_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hsetraditionalinitialincidentreport',
            name='incident_state',
        ),
        migrations.AlterField(
            model_name='hsetraditionalinitialincidentreport',
            name='source_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='الولاية'),
        ),
    ]
