# Generated by Django 5.2.12 on 2026-04-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_traditional', '0029_remove_hsetraditionalinitialincidentreport_incident_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsetraditionalinitialincidentreport',
            name='state',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'confirmed'), (3, 'approved')], default=1, verbose_name='record_state'),
        ),
    ]
