# Generated by Django 5.2.8 on 2025-12-03 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0126_payrollsummary_mokaf2'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.IntegerField(verbose_name='كود الموظف')),
                ('employee_name', models.CharField(max_length=150, verbose_name='اسم الموظف  ')),
                ('email', models.CharField(max_length=150, verbose_name=' البريد الالكتروني للموظف ')),
                ('job_title', models.CharField(max_length=100, verbose_name=' المسمى الوظيفي')),
                ('direct_manager', models.CharField(blank=True, max_length=100, null=True, verbose_name=' المدير المباشر')),
                ('direct_manager_email', models.CharField(blank=True, max_length=100, null=True, verbose_name=' ')),
                ('period_from', models.DateField(verbose_name='من')),
                ('period_to', models.DateField(verbose_name='الي')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تم الانشاء في ')),
                ('attendance_discipline', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name=' الالتزام بالحضور والانضباط')),
                ('follow_instructions', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='احترام التعليمات ')),
                ('task_responsibility', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name=' تحمل المسؤولية وتعدد المهام')),
                ('teamwork', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name=' التعاون والعمل ضمن فريق')),
                ('communication', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name=' التواصل الفعال')),
                ('main_tasks_quality', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='انجاز المهام الرئيسية بجودة وكفاءة ')),
                ('extra_tasks', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name=' إنجاز المهام الاضافية خارج التوصيف ')),
                ('work_pressure', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name=' القدرة علي التكيف مع ضغط العمل ')),
                ('policies_commitment', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name=' الالتزام بالاجراءات والسياسات')),
                ('creativity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='الابداع في تقديم الحلول ')),
                ('overall_performance', models.CharField(blank=True, max_length=20, null=True, verbose_name=' مستوي الانجاز العام')),
                ('emergency_response', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name=' مدي الاستجابة لعمل لطبيعة العمل ')),
                ('coverage_percentage', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name=' نسبة تغطية الفجوة')),
                ('strengths', models.TextField(verbose_name=' نقاط القوة لدى الموظف ')),
                ('challenges', models.TextField(verbose_name=' التحديات')),
                ('training_needs', models.TextField(verbose_name=' الاحتياجات التدريبية ')),
                ('manager_notes', models.TextField(verbose_name='تعليق المدير المباشر')),
                ('average_attendance', models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جدًا'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], max_length=20, null=True, verbose_name='متوسط نسبة الحصور والانصراف')),
                ('attendance_punctnality', models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جدًا'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], max_length=20, null=True, verbose_name='الالتزام بمواعيد الدوام')),
                ('violation_count', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='عدد المخالفات الادارية المسجلة')),
                ('warnings_count', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='عدد الانزارات او التنبيهات الادارية')),
                ('employee_effective', models.CharField(blank=True, choices=[('yes', 'نعم'), ('no', 'لا')], max_length=20, null=True, verbose_name='هل ترى أن الموظف كان فاعلاً ')),
                ('recommendations_continue', models.CharField(blank=True, choices=[('yes', 'نعم'), ('no', 'لا')], max_length=20, null=True, verbose_name='هل توصي باستمراره ضمن فريق العمل ')),
                ('substantive_note', models.TextField(blank=True, null=True, verbose_name='هل هنالك ملاحظات جوهرية على أدائه ')),
                ('manager_average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='متوسط تقييم المدير ')),
            ],
            options={
                'verbose_name': 'تقييم العاملين فترة الطوارئ',
                'verbose_name_plural': 'تقييمات العاملين فترة الطوارئ',
            },
        ),
        migrations.CreateModel(
            name='Employee_Data_Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الموظف')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('direct_manager_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد المدير المباشر')),
                ('job_title', models.CharField(max_length=255, verbose_name='المسمى الوظيفي ')),
            ],
            options={
                'verbose_name': 'بيانات موظف مستوردة من بيانات المباشرين',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(choices=[('Blue_Nile', 'النيل الازرق'), ('Kassala', 'كسلا'), ('Red_Sea', 'البحر الاحمر'), ('River_Nile', 'نهر النيل'), ('Al_Qadarif', 'القضارف'), ('South_Kordofan', 'جنوب كردفان'), ('West_Kordofan', 'غرب كردفان'), ('North_Kordofan', 'شمال كردفان'), ('White_Nile', 'النيل الابيض'), ('Central_Darfur', 'وسط دارفور'), ('East_Darfur', 'شرق دارفور'), ('South_Darfur', 'جنوب دارفور'), ('West_Darfur', 'غرب دارفور'), ('Northern', 'الولاية الشمالية')], max_length=100, verbose_name='الولاية')),
                ('other_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='تحديد الوظيفة الأخرى')),
                ('work_duration', models.CharField(choices=[('اقل_سنةmi', 'أقل من سنة'), ('1_3', 'من 1 إلى 3 سنوات'), ('3_5', 'من 3 إلى 5 سنوات'), ('more_5', 'أكثر من 5 سنوات')], max_length=50, verbose_name='مدة العمل بالشركة')),
                ('clarity_statement', models.IntegerField(choices=[(1, 'أوافق بشدة'), (2, 'أوافق'), (3, 'محايد'), (4, 'لا أوافق'), (5, 'لا أوافق بشدة')], verbose_name='الهيكل التنظيمي الجديد واضح ومفهوم لجميع العاملين')),
                ('roles_responsibilities', models.IntegerField(choices=[(1, 'أوافق بشدة'), (2, 'أوافق'), (3, 'محايد'), (4, 'لا أوافق'), (5, 'لا أوافق بشدة')], verbose_name='هناك تحديد دقيق للصلاحيات والمسؤوليات لكل وظيفة')),
                ('communication_lines', models.IntegerField(choices=[(1, 'أوافق بشدة'), (2, 'أوافق'), (3, 'محايد'), (4, 'لا أوافق'), (5, 'لا أوافق بشدة')], verbose_name='خطوط التواصل الإداري واضحة وسلسة')),
                ('job_title_match', models.IntegerField(choices=[(1, 'أوافق بشدة'), (2, 'أوافق'), (3, 'محايد'), (4, 'لا أوافق'), (5, 'لا أوافق بشدة')], verbose_name='المسمى الوظيفي يتماشى مع طبيعة المهام')),
                ('decision_making', models.IntegerField(choices=[(1, 'أوافق بشدة'), (2, 'أوافق'), (3, 'محايد'), (4, 'لا أوافق'), (5, 'لا أوافق بشدة')], verbose_name='الهيكل الحالي يسهل اتخاذ القرار الإداري')),
                ('reduces_overlap', models.IntegerField(choices=[(1, 'أوافق بشدة'), (2, 'أوافق'), (3, 'محايد'), (4, 'لا أوافق'), (5, 'لا أوافق بشدة')], verbose_name='يقلل من التداخل والازدواجية في المهام')),
                ('coordination', models.IntegerField(choices=[(1, 'أوافق بشدة'), (2, 'أوافق'), (3, 'محايد'), (4, 'لا أوافق'), (5, 'لا أوافق بشدة')], verbose_name='يسهل التنسيق والعلاقات بين الإدارات والوحدات')),
                ('service_quality', models.IntegerField(choices=[(1, 'أوافق بشدة'), (2, 'أوافق'), (3, 'محايد'), (4, 'لا أوافق'), (5, 'لا أوافق بشدة')], verbose_name='يساهم في تحسين جودة الخدمات المقدمة والإجراءات')),
                ('strategic_alignment', models.IntegerField(choices=[(1, 'أوافق بشدة'), (2, 'أوافق'), (3, 'محايد'), (4, 'لا أوافق'), (5, 'لا أوافق بشدة')], verbose_name='الهيكل يتماشى مع أهداف الخطة التشغيلية للشركة')),
                ('adaptability', models.IntegerField(choices=[(1, 'أوافق بشدة'), (2, 'أوافق'), (3, 'محايد'), (4, 'لا أوافق'), (5, 'لا أوافق بشدة')], verbose_name='قابل للتحديث والتعديل حسب المتغيرات')),
                ('resource_allocation', models.IntegerField(choices=[(1, 'أوافق بشدة'), (2, 'أوافق'), (3, 'محايد'), (4, 'لا أوافق'), (5, 'لا أوافق بشدة')], verbose_name='يسمح بتوزيع الموارد البشرية بكفاءة')),
                ('service_delivery', models.IntegerField(choices=[(1, 'أوافق بشدة'), (2, 'أوافق'), (3, 'محايد'), (4, 'لا أوافق'), (5, 'لا أوافق بشدة')], verbose_name='يساعد في تقديم خدمات أكثر فاعلية')),
                ('challenges', models.TextField(blank=True, null=True, verbose_name='1. ما أبرز التحديات التي لاحظتها منذ تطبيق الهيكل الجديد؟')),
                ('suitability', models.TextField(blank=True, null=True, verbose_name='2. هل ترى أن الهيكل الجديد مناسب لطبيعة العمل في ولايتك / إدارتك؟ ولماذا؟')),
                ('improvements', models.TextField(blank=True, null=True, verbose_name='3. ما التعديلات أو التحسينات التي تقترحها على الهيكل التنظيمي؟')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('overall_evaluation', models.CharField(blank=True, max_length=20, null=True, verbose_name=' التقييم بصورة عامة للهيكل  ')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='متوسط تقييم')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.hikalwazifi', verbose_name='الإدارة / القسم')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.mosamawazifi', verbose_name='المسمى الوظيفي')),
            ],
        ),
    ]
