# Generated by Django 5.2.8 on 2025-11-25 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0124_employeesalafiatsandog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.IntegerField(blank=True, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('job_number', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('direct_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('attendance_discipline', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('follow_instructions', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('task_responsibility', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('teamwork', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('communication', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('main_tasks_quality', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('extra_tasks', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('work_pressure', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('policies_commitment', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('creativity', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('overall_performance', models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جدًا'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], max_length=20, null=True)),
                ('emergency_response', models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جدًا'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], max_length=20, null=True)),
                ('coverage_percentage', models.CharField(blank=True, choices=[('high', 'عالية'), ('medium', 'متوسطة'), ('low', 'ضعيفة')], max_length=20, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('training_needs', models.TextField(blank=True, null=True)),
                ('manager_notes', models.TextField(blank=True, null=True)),
                ('average_attendance', models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جدًا'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], max_length=20, null=True)),
                ('attendance_punctnality', models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جدًا'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], max_length=20, null=True)),
                ('violation_count', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('warnings_count', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('employee_effective', models.CharField(blank=True, choices=[('yes', 'نعم'), ('no', 'لا')], max_length=20, null=True)),
                ('recommendations_continue', models.CharField(blank=True, choices=[('yes', 'نعم'), ('no', 'لا')], max_length=20, null=True)),
                ('Substantive_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Data_Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الموظف')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('direct_manager_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد المدير المباشر')),
                ('job_title', models.CharField(max_length=255, verbose_name='المسمى الوظيفي ')),
            ],
            options={
                'verbose_name': 'بيانات موظف مستوردة من بيانات المباشرين',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(choices=[('Blue_Nile', 'النيل الازرق'), ('Kassala', 'كسلا'), ('Red_Sea', 'البحر الاحمر'), ('River_Nile', 'نهر النيل'), ('Al_Qadarif', 'القضارف'), ('South_Kordofan', 'جنوب كردفان'), ('West_Kordofan', 'غرب كردفان'), ('North_Kordofan', 'شمال كردفان'), ('White_Nile', 'النيل الابيض'), ('Central_Darfur', 'وسط دارفور'), ('East_Darfur', 'شرق دارفور'), ('South_Darfur', 'جنوب دارفور'), ('West_Darfur', 'غرب دارفور'), ('Northern', 'الولاية الشمالية')], max_length=100, verbose_name='الولاية')),
                ('other_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='تحديد الوظيفة الأخرى')),
                ('work_duration', models.CharField(blank=True, choices=[('اقل_سنةmi', 'أقل من سنة'), ('1_3', 'من 1 إلى 3 سنوات'), ('3_5', 'من 3 إلى 5 سنوات'), ('more_5', 'أكثر من 5 سنوات')], max_length=50, null=True, verbose_name='مدة العمل بالشركة')),
                ('clarity_statement', models.IntegerField(blank=True, choices=[(5, 'أوافق بشدة'), (4, 'أوافق'), (3, 'محايد'), (2, 'لا أوافق'), (1, 'لا أوافق بشدة')], null=True, verbose_name='الهيكل التنظيمي الجديد واضح ومفهوم لجميع العاملين')),
                ('roles_responsibilities', models.IntegerField(blank=True, choices=[(5, 'أوافق بشدة'), (4, 'أوافق'), (3, 'محايد'), (2, 'لا أوافق'), (1, 'لا أوافق بشدة')], null=True, verbose_name='هناك تحديد دقيق للصلاحيات والمسؤوليات لكل وظيفة')),
                ('communication_lines', models.IntegerField(blank=True, choices=[(5, 'أوافق بشدة'), (4, 'أوافق'), (3, 'محايد'), (2, 'لا أوافق'), (1, 'لا أوافق بشدة')], null=True, verbose_name='خطوط التواصل الإداري واضحة وسلسة')),
                ('job_title_match', models.IntegerField(blank=True, choices=[(5, 'أوافق بشدة'), (4, 'أوافق'), (3, 'محايد'), (2, 'لا أوافق'), (1, 'لا أوافق بشدة')], null=True, verbose_name='المسمى الوظيفي يتماشى مع طبيعة المهام')),
                ('decision_making', models.IntegerField(blank=True, choices=[(5, 'أوافق بشدة'), (4, 'أوافق'), (3, 'محايد'), (2, 'لا أوافق'), (1, 'لا أوافق بشدة')], null=True, verbose_name='الهيكل الحالي يسهل اتخاذ القرار الإداري')),
                ('reduces_overlap', models.IntegerField(blank=True, choices=[(5, 'أوافق بشدة'), (4, 'أوافق'), (3, 'محايد'), (2, 'لا أوافق'), (1, 'لا أوافق بشدة')], null=True, verbose_name='يقلل من التداخل والازدواجية في المهام')),
                ('coordination', models.IntegerField(blank=True, choices=[(5, 'أوافق بشدة'), (4, 'أوافق'), (3, 'محايد'), (2, 'لا أوافق'), (1, 'لا أوافق بشدة')], null=True, verbose_name='يسهل التنسيق والعلاقات بين الإدارات والوحدات')),
                ('service_quality', models.IntegerField(blank=True, choices=[(5, 'أوافق بشدة'), (4, 'أوافق'), (3, 'محايد'), (2, 'لا أوافق'), (1, 'لا أوافق بشدة')], null=True, verbose_name='يساهم في تحسين جودة الخدمات المقدمة والإجراءات')),
                ('strategic_alignment', models.IntegerField(blank=True, choices=[(5, 'أوافق بشدة'), (4, 'أوافق'), (3, 'محايد'), (2, 'لا أوافق'), (1, 'لا أوافق بشدة')], null=True, verbose_name='الهيكل يتماشى مع أهداف الخطة التشغيلية للشركة')),
                ('adaptability', models.IntegerField(blank=True, choices=[(5, 'أوافق بشدة'), (4, 'أوافق'), (3, 'محايد'), (2, 'لا أوافق'), (1, 'لا أوافق بشدة')], null=True, verbose_name='قابل للتحديث والتعديل حسب المتغيرات')),
                ('resource_allocation', models.IntegerField(blank=True, choices=[(5, 'أوافق بشدة'), (4, 'أوافق'), (3, 'محايد'), (2, 'لا أوافق'), (1, 'لا أوافق بشدة')], null=True, verbose_name='يسمح بتوزيع الموارد البشرية بكفاءة')),
                ('service_delivery', models.IntegerField(blank=True, choices=[(5, 'أوافق بشدة'), (4, 'أوافق'), (3, 'محايد'), (2, 'لا أوافق'), (1, 'لا أوافق بشدة')], null=True, verbose_name='يساعد في تقديم خدمات أكثر فاعلية')),
                ('challenges', models.TextField(blank=True, null=True, verbose_name='1. ما أبرز التحديات التي لاحظتها منذ تطبيق الهيكل الجديد؟')),
                ('suitability', models.TextField(blank=True, null=True, verbose_name='2. هل ترى أن الهيكل الجديد مناسب لطبيعة العمل في ولايتك / إدارتك؟ ولماذا؟')),
                ('improvements', models.TextField(blank=True, null=True, verbose_name='3. ما التعديلات أو التحسينات التي تقترحها على الهيكل التنظيمي؟')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.hikalwazifi', verbose_name='الإدارة / القسم')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.mosamawazifi', verbose_name='المسمى الوظيفي')),
            ],
        ),
    ]
