# Generated by Django 5.2.8 on 2025-12-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='attendance_punctnality',
            field=models.IntegerField(blank=True, choices=[('5', 'ممتاز'), ('4', 'جيد جدًا'), ('3', 'جيد'), ('2', 'مقبول'), ('1', 'ضعيف')], max_length=20, null=True, verbose_name='الالتزام بمواعيد الدوام'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='average_attendance',
            field=models.IntegerField(blank=True, choices=[('5', 'ممتاز'), ('4', 'جيد جدًا'), ('3', 'جيد'), ('2', 'مقبول'), ('1', 'ضعيف')], max_length=20, null=True, verbose_name='متوسط نسبة الحصور والانصراف'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='employee_effective',
            field=models.CharField(blank=True, choices=[('1', 'نعم'), ('0', 'لا')], max_length=20, null=True, verbose_name='هل ترى أن الموظف كان فاعلاً '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='recommendations_continue',
            field=models.CharField(blank=True, choices=[('1', 'نعم'), ('0', 'لا')], max_length=20, null=True, verbose_name='هل توصي باستمراره ضمن فريق العمل '),
        ),
    ]
