# Generated by Django 5.2.8 on 2025-11-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyevaluation',
            name='direct_manager_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
