# Generated by Django 5.2.8 on 2025-11-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0002_emergencyevaluation_direct_manager_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyevaluation',
            options={'verbose_name': 'تقييم العاملين فترة الطوارئ'},
        ),
        migrations.AddField(
            model_name='emergencyevaluation',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' البريد الالكتروني للموظف '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='Substantive_note',
            field=models.TextField(blank=True, null=True, verbose_name='هل هنالك ملاحظات جوهرية على أدائه '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='attendance_discipline',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name=' الالتزام بالحضور والانضباط'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='attendance_punctnality',
            field=models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جدًا'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], max_length=20, null=True, verbose_name='الالتزام بمواعيد الدوام'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='average_attendance',
            field=models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جدًا'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], max_length=20, null=True, verbose_name='متوسط نسبة الحصور والانصراف'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='challenges',
            field=models.TextField(blank=True, null=True, verbose_name=' التحديات'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='communication',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name=' التواصل الفعال'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='coverage_percentage',
            field=models.CharField(blank=True, choices=[('high', 'عالية'), ('medium', 'متوسطة'), ('low', 'ضعيفة')], max_length=20, null=True, verbose_name=' نسبة تغطية الفجوة'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تم الانشاء في '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='creativity',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='الابداع في تقديم الحلول '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='direct_manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' المدير المباشر'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='direct_manager_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='emergency_response',
            field=models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جدًا'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], max_length=20, null=True, verbose_name=' مدي الاستجابة لعمل لطبيعة العمل '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='employee_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='كود الموظف'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='employee_effective',
            field=models.CharField(blank=True, choices=[('yes', 'نعم'), ('no', 'لا')], max_length=20, null=True, verbose_name='هل ترى أن الموظف كان فاعلاً '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='employee_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم الموظف  '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='extra_tasks',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name=' إنجاز المهام الاضافية خارج التوصيف '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='follow_instructions',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='احترام التعليمات '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='job_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الموظف'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='main_tasks_quality',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='انجاز المهام الرئيسية بجودة وكفاءة '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='manager_notes',
            field=models.TextField(blank=True, null=True, verbose_name='تعليق المدير المباشر'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='overall_performance',
            field=models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جدًا'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], max_length=20, null=True, verbose_name=' مستوي الانجاز العام'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='period_from',
            field=models.DateField(blank=True, null=True, verbose_name='من'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='period_to',
            field=models.DateField(blank=True, null=True, verbose_name='الي'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='policies_commitment',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name=' الالتزام بالاجراءات والسياسات'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='recommendations_continue',
            field=models.CharField(blank=True, choices=[('yes', 'نعم'), ('no', 'لا')], max_length=20, null=True, verbose_name='هل توصي باستمراره ضمن فريق العمل '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='strengths',
            field=models.TextField(blank=True, null=True, verbose_name=' نقاط القوة لدى الموظف '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='task_responsibility',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name=' تحمل المسؤولية وتعدد المهام'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='teamwork',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name=' التعاون والعمل ضمن فريق'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='training_needs',
            field=models.TextField(blank=True, null=True, verbose_name=' الاحتياجات التدريبية '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='violation_count',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='عدد المخالفات الادارية المسجلة'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='warnings_count',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='عدد الانزارات او التنبيهات الادارية'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='work_pressure',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name=' القدرة علي التكيف مع ضغط العمل '),
        ),
    ]
