# Generated by Django 5.2.8 on 2025-12-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0002_alter_emergencyevaluation_attendance_punctnality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='attendance_punctnality',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=20, null=True, verbose_name='الالتزام بمواعيد الدوام'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='average_attendance',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=20, null=True, verbose_name='متوسط نسبة الحصور والانصراف'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='employee_effective',
            field=models.IntegerField(blank=True, choices=[('1', 'نعم'), ('0', 'لا')], null=True, verbose_name='هل ترى أن الموظف كان فاعلاً '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='recommendations_continue',
            field=models.IntegerField(blank=True, choices=[('1', 'نعم'), ('0', 'لا')], null=True, verbose_name='هل توصي باستمراره ضمن فريق العمل '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='violation_count',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='عدد المخالفات الادارية المسجلة'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='work_duration',
            field=models.CharField(choices=[('Less_than_year', 'أقل من سنة'), ('1_3', 'من 1 إلى 3 سنوات'), ('3_5', 'من 3 إلى 5 سنوات'), ('more_than_5', 'أكثر من 5 سنوات')], max_length=50, verbose_name='مدة العمل بالشركة'),
        ),
    ]
