# Generated by Django 5.2.7 on 2025-11-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0003_alter_emergencyevaluation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyevaluation',
            old_name='Substantive_note',
            new_name='substantive_note',
        ),
    ]
