# Generated by Django 5.2.8 on 2025-12-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0003_alter_emergencyevaluation_attendance_punctnality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyevaluation',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='حالة التأكيد'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='attendance_punctnality',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='الالتزام بمواعيد الدوام'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='average_attendance',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='متوسط نسبة الحصور والانصراف'),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='email',
            field=models.CharField(max_length=150, unique=True, verbose_name=' البريد الالكتروني للموظف '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='employee_effective',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1')], null=True, verbose_name='هل ترى أن الموظف كان فاعلاً '),
        ),
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='recommendations_continue',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1')], null=True, verbose_name='هل توصي باستمراره ضمن فريق العمل '),
        ),
    ]
