# Generated by Django 5.2.8 on 2025-12-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0004_emergencyevaluation_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyevaluation',
            name='email',
            field=models.CharField(max_length=150, verbose_name=' البريد الالكتروني للموظف '),
        ),
    ]
