# Generated by Django 5.2.8 on 2025-12-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0005_alter_emergencyevaluation_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyevaluation',
            name='is_confirmed',
        ),
    ]
