# Generated by Django 5.2.8 on 2025-12-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0006_remove_emergencyevaluation_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyevaluation',
            name='manager_average_score',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='overall_evaluation',
        ),
    ]
