# Generated by Django 5.2.8 on 2025-12-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0007_remove_emergencyevaluation_manager_average_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyevaluation',
            name='manager_average_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='متوسط تقييم المدير '),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='average_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='متوسط تقييم'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='overall_evaluation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=' التقييم بصورة عامة للهيكل  '),
        ),
    ]
