# Generated by Django 5.2.8 on 2025-12-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0008_emergencyevaluation_manager_average_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data_emergency',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
    ]
