# Generated by Django 5.2.8 on 2025-12-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0009_alter_employee_data_emergency_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data_emergency',
            name='edara_3ama',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الادارة العامة'),
        ),
    ]
