# Generated by Django 5.2.8 on 2025-12-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0010_employee_data_emergency_edara_3ama'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' البريد الالكتروني للموظف '),
        ),
    ]
