# Generated by Django 5.2.8 on 2025-12-28 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0129_payrollsummary_salary_mokaf2'),
        ('hr_employee_survey', '0011_surveyresponse_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Sim_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الموظف')),
                ('sim_number', models.IntegerField(verbose_name='رقم الشريحة ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.hikalwazifi', verbose_name='الإدارة / القسم')),
            ],
            options={
                'verbose_name': 'بيانات موظف مستوردة من بيانات المباشرين',
            },
        ),
    ]
