# Generated by Django 5.2.8 on 2025-12-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0012_employee_sim_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_sim_card',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الإدارة / القسم'),
        ),
    ]
