# Generated by Django 5.2.7 on 2025-12-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0013_alter_employee_sim_card_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_data_emergency',
            options={'verbose_name': 'بيانات موظف لتقييم 2025'},
        ),
        migrations.AlterModelOptions(
            name='employee_sim_card',
            options={'verbose_name': 'بيانات شريحة موظف 2025'},
        ),
    ]
