# Generated by Django 5.2.7 on 2025-12-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0014_alter_employee_data_emergency_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_sim_card',
            name='sim_number',
            field=models.CharField(max_length=15, verbose_name='رقم الشريحة '),
        ),
    ]
