# Generated by Django 5.2.7 on 2025-12-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee_survey', '0015_alter_employee_sim_card_sim_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_sim_card',
            name='sim_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='رقم الشريحة '),
        ),
    ]
