# Generated by Django 5.0.2 on 2024-12-30 10:44

import executive_office.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive_office', '0003_inbox_state_inboxtasks_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxtasks',
            name='attachment_file',
            field=models.FileField(default='', null=True, upload_to=executive_office.models.task_path, verbose_name='attachment_file'),
        ),
    ]
