# Generated by Django 5.0.2 on 2024-12-30 10:57

import executive_office.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive_office', '0004_inboxtasks_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxtasks',
            name='attachment_file',
            field=models.FileField(blank=True, default='', null=True, upload_to=executive_office.models.task_path, verbose_name='attachment_file'),
        ),
    ]
