# Generated by Django 5.0.2 on 2024-12-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive_office', '0005_alter_inboxtasks_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxtasks',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='title'),
        ),
    ]
