# Generated by Django 5.0.2 on 2024-12-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive_office', '0006_inboxtasks_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='title'),
        ),
    ]
