# Generated by Django 5.0.2 on 2024-12-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive_office', '0008_alter_inbox_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxtasks',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
