# Generated by Django 5.0.2 on 2024-12-30 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive_office', '0009_alter_inboxtasks_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceduretype',
            options={'verbose_name': 'procedure_type2', 'verbose_name_plural': 'procedure_types'},
        ),
        migrations.AlterField(
            model_name='proceduretypetaskstemplate',
            name='procedure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='executive_office.proceduretype', verbose_name='procedure_type2'),
        ),
    ]
