# Generated by Django 5.0.2 on 2024-12-30 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive_office', '0010_alter_proceduretype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='procedure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='executive_office.proceduretype', verbose_name='procedure_type2'),
        ),
    ]
