# Generated by Django 5.0.2 on 2024-12-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive_office', '0011_alter_inbox_procedure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='subject',
            field=models.CharField(default='*', max_length=150, verbose_name='subject'),
            preserve_default=False,
        ),
    ]
