# Generated by Django 5.0.2 on 2024-12-31 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0084_alter_appborrowmaterial_company_from_str'),
        ('executive_office', '0012_inbox_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='executive_office.inbox', verbose_name='inbox')),
            ],
            options={
                'verbose_name': 'inbox company',
                'verbose_name_plural': 'inbox companies',
            },
        ),
    ]
