# Generated by Django 5.0.2 on 2024-09-04 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LkpState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='LkpSoag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_api.lkpstate', verbose_name='state')),
            ],
            options={
                'verbose_name': 'Soag',
                'verbose_name_plural': 'Soag',
            },
        ),
        migrations.CreateModel(
            name='TblCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('soag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_api.lkpsoag', verbose_name='Soag')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_api.lkpstate', verbose_name='state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collector',
                'verbose_name_plural': 'Collectors',
            },
        ),
        migrations.CreateModel(
            name='TblInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('mo3adin_name', models.CharField(max_length=100, verbose_name='mo3adin_name')),
                ('quantity_per_shoal', models.IntegerField(verbose_name='quantity_per_shoal')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_api.tblcollector', verbose_name='Collector')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
