# Generated by Django 5.0.2 on 2024-09-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblinvoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.RenameField(
            model_name='tblinvoice',
            old_name='quantity_per_shoal',
            new_name='quantity_in_shoal',
        ),
    ]
