# Generated by Django 5.2.7 on 2026-06-23 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0139_lkpstate_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSudanGoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('category', models.CharField(choices=[('concession', 'شركات الامتياز'), ('waste', 'شركات المخلفات')], max_length=20, verbose_name='الفئة')),
                ('price_per_gram_sdg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الجرام بالجنيه')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'سعر الذهب - بنك السودان',
                'verbose_name_plural': 'أسعار الذهب - بنك السودان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DollarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('rate_type', models.CharField(choices=[('official', 'الدولار الرسمي'), ('parallel', 'الدولار بالسوق الموازي')], max_length=20, verbose_name='نوع السعر')),
                ('price_in_sdg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر بالجنيه')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'سعر صرف الدولار',
                'verbose_name_plural': 'أسعار صرف الدولار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalGoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('price_per_gram_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الجرام بالدولار')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'سعر الذهب العالمي',
                'verbose_name_plural': 'أسعار الذهب العالمية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StateGoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('price_per_gram_sdg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الجرام بالجنيه')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='الولاية')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'سعر الذهب بالولاية',
                'verbose_name_plural': 'أسعار الذهب بالولايات',
                'ordering': ['-created_at'],
            },
        ),
    ]
