# Generated by Django 5.2.7 on 2026-06-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalgoldprice',
            name='karat',
            field=models.PositiveSmallIntegerField(choices=[(24, 'عيار 24'), (21, 'عيار 21')], default=24, verbose_name='العيار'),
        ),
    ]
