# Generated by Django 5.2.7 on 2026-06-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_globalgoldprice_karat'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalgoldprice',
            name='price_per_ounce_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الأوقية بالدولار'),
        ),
    ]
