# Generated by Django 5.2.7 on 2026-06-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_alter_pricesstateuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stategoldprice',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظات'),
        ),
    ]
