# Generated by Django 5.2.7 on 2026-06-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_stategoldprice_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banksudangoldprice',
            name='category',
        ),
    ]
