# Generated by Django 5.2.7 on 2026-08-09 08:14

import datetime
from django.db import migrations, models


def backfill_date_from_created_at(apps, schema_editor):
    """Backfill date from created_at for existing history records."""
    for model_name in ('banksudangoldprice', 'dollarprice', 'globalgoldprice', 'stategoldprice'):
        model = apps.get_model('prices', model_name)
        for obj in model.objects.all():
            obj.date = obj.created_at.date()
            obj.save(update_fields=['date'])


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0008_dollarprice_buy_sell_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksudangoldprice',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='dollarprice',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='globalgoldprice',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='stategoldprice',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='التاريخ'),
        ),
        migrations.RunPython(backfill_date_from_created_at, migrations.RunPython.noop),
    ]
