# Generated by Django 5.1.7 on 2025-04-21 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0003_alter_apphseperformancereportauditorcomment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHSECorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrective_action', models.CharField(verbose_name='الإجراء التصحيحي')),
                ('from_dt', models.DateField(verbose_name='من')),
                ('to_dt', models.DateField(verbose_name='إلى')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hse_companies.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'الإجراء التصحيحي',
                'verbose_name_plural': 'الإجراءات التصحيحية',
            },
        ),
    ]
