# Generated by Django 5.1.7 on 2025-04-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0004_apphsecorrectiveaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apphsecorrectiveaction',
            options={'ordering': ['-id'], 'verbose_name': 'Application: HSE Corrective Action', 'verbose_name_plural': 'Application: HSE Corrective Actions'},
        ),
        migrations.AddField(
            model_name='apphsecorrectiveaction',
            name='state',
            field=models.IntegerField(choices=[(1, 'تحرير مشرف الولاية'), (2, 'تأكيد مدير الإدارة المختصة '), (3, 'إعتماد مدير الإدارة العامة')], default=1, verbose_name='record_state'),
        ),
    ]
