# Generated by Django 5.1.7 on 2025-04-22 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0005_alter_apphsecorrectiveaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apphsecorrectiveaction',
            options={'ordering': ['-id'], 'verbose_name': 'الإجراء التصحيحي HSE Corrective Action', 'verbose_name_plural': 'الإجراءات التصحيحية HSE Corrective Actions'},
        ),
        migrations.AlterField(
            model_name='apphsecorrectiveaction',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hse_companies.apphseperformancereport', verbose_name='Application: HSE Performance Report'),
        ),
        migrations.AlterField(
            model_name='apphsecorrectiveaction',
            name='state',
            field=models.IntegerField(choices=[(1, 'تحرير مشرف الولاية'), (2, 'تأكيد مشرف الولاية'), (3, 'تأكيد مدير الإدارة المختصة '), (4, 'إعتماد مدير الإدارة العامة')], default=1, verbose_name='record_state'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereport',
            name='state',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'تأكيد المشرف'), (3, 'إعتماد مشرف الولاية')], default=1, verbose_name='record_state'),
        ),
    ]
