# Generated by Django 5.1.7 on 2025-04-22 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0117_lkpsector_lkpstate_sector'),
        ('hse_companies', '0006_alter_apphsecorrectiveaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='apphseperformancereport',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'company'), name='unique_report_per_month'),
        ),
    ]
