# Generated by Django 5.1.7 on 2025-04-23 09:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0007_apphseperformancereport_unique_report_per_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHSECorrectiveActionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة التنفيذ')),
                ('company_comment', models.TextField(verbose_name='تعليق الشركة')),
                ('auditor_comment', models.TextField(verbose_name='تعليق المشرف الميداني')),
                ('state', models.IntegerField(choices=[(1, 'draft'), (2, 'تأكيد المشرف'), (3, 'إعتماد مشرف الولاية')], default=1, verbose_name='record_state')),
                ('corrective_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hse_companies.apphsecorrectiveaction', verbose_name='الإجراء التصحيحي')),
            ],
            options={
                'verbose_name': 'إفادة عن اجراء تصحيحي',
                'verbose_name_plural': 'إفادة عن إجراءات تصحيحية',
            },
        ),
    ]
