# Generated by Django 5.1.7 on 2025-04-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0009_apphsecorrectiveaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentinfo',
            name='state',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'تأكيد المشرف'), (3, 'إعتماد مشرف الولاية')], default=1, verbose_name='record_state'),
        ),
    ]
