# Generated by Django 5.1.7 on 2025-04-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0010_incidentinfo_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentinfo',
            name='incident_category',
            field=models.SmallIntegerField(choices=[(1, 'Occupational Health'), (2, 'Safety'), (3, 'Environment')], verbose_name='فئة الحادث Incident Category'),
        ),
    ]
