# Generated by Django 5.1.7 on 2025-04-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0011_alter_incidentinfo_incident_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentanalysis',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='incidentanalysis',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='incidentanalysis',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='incidentanalysis',
            name='updated_by',
        ),
    ]
