# Generated by Django 5.1.7 on 2025-04-25 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0012_remove_incidentanalysis_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributingfactor',
            name='incident_analysis',
        ),
        migrations.AddField(
            model_name='contributingfactor',
            name='incident',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contributing_factors', to='hse_companies.incidentinfo'),
            preserve_default=False,
        ),
    ]
