# Generated by Django 5.1.7 on 2025-04-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0013_remove_contributingfactor_incident_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributingfactor',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributing_factors', to='hse_companies.incidentinfo'),
        ),
    ]
