# Generated by Django 5.1.7 on 2025-04-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0014_alter_contributingfactor_incident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributingfactor',
            options={'verbose_name': 'الاسباب المساهمة في الحادث Contributing Causes', 'verbose_name_plural': 'الاسباب المساهمة في الحادث Contributing Causes'},
        ),
        migrations.AlterModelOptions(
            name='factorsassessment',
            options={'verbose_name': 'تحليل اسباب وقوع الحادث Causes Analysis of the Incident', 'verbose_name_plural': 'تحليل اسباب وقوع الحادث Causes Analysis of the Incident'},
        ),
        migrations.AlterModelOptions(
            name='leasonlearnt',
            options={'verbose_name': 'الدروس المستفادة Lessons Learnt', 'verbose_name_plural': 'الدروس المستفادة Lessons Learnt'},
        ),
    ]
