# Generated by Django 5.1.7 on 2025-04-25 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0015_alter_contributingfactor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasonlearnt',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leasons_learnt', to='hse_companies.incidentinfo'),
        ),
    ]
