# Generated by Django 5.1.7 on 2025-04-27 06:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0016_alter_leasonlearnt_incident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentinfo',
            name='bodily_location',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='control_cost',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='damage_nature',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='first_aid_details',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='first_aider_name',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='injured_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='injured_employment_basis',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='injured_experience_years',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='injured_position',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='injured_surname',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='lost_days',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='lost_time_injury',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='material_spill_details',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='nature_of_injury',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='other_expenses',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='ppe_ear_protection',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='ppe_face_protection',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='ppe_gloves',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='ppe_helmet',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='ppe_mask',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='ppe_other',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='ppe_safety_cloth',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='ppe_safety_shoes',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='property_description',
        ),
        migrations.RemoveField(
            model_name='incidentinfo',
            name='total_cost',
        ),
        migrations.CreateModel(
            name='IncidentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="تكلفة الاليات/المركبات/الاشخاص المستخدمة في التحكم في الحادث Cost of Equipment's/vehicle’s/human’s used to control Incident")),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تكلفة الحادث Cost of the accident')),
                ('other_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='اي مصاريف اخرى Other expenses')),
                ('currency', models.CharField(choices=[('sdg', 'sdg'), ('euro', 'euro'), ('dollar', 'dollar')], default='sdg', max_length=10, verbose_name='currency')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_cost', to='hse_companies.incidentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentInjured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injured_surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='إسم المصاب Injured Surname')),
                ('injured_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='الوظيفة Position')),
                ('injured_experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name=' الخبرة بالأعوام Experience in Years')),
                ('injured_date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد Date of Birth')),
                ('injured_employment_basis', models.SmallIntegerField(blank=True, choices=[(1, 'دوام كامل Full Time'), (2, 'دوام جزئي Part Time'), (3, 'يومية Casual'), (4, 'متعاقد Contractor')], null=True, verbose_name='نوع التوظيف Basis of Employment')),
                ('lost_time_injury', models.BooleanField(default=False, verbose_name='هل تسببت الإصابة في التغيب عن العمل؟ Did this incident cause of Lost Time of working days?')),
                ('lost_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='في حال كانت الإجابة نعم حدد عدد الأيام حتى تاريخ هذا التقرير If yes, specify Number of lost days up to this report')),
                ('ppe_gloves', models.BooleanField(default=False, verbose_name='قفازات Gloves')),
                ('ppe_helmet', models.BooleanField(default=False, verbose_name='خوذة Helmet')),
                ('ppe_safety_cloth', models.BooleanField(default=False, verbose_name='لبس السلامة Safety cloth')),
                ('ppe_safety_shoes', models.BooleanField(default=False, verbose_name='حذاء السلامة Safety Shoes')),
                ('ppe_face_protection', models.BooleanField(default=False, verbose_name='نظارة/واقي وجهGlass/face Protection')),
                ('ppe_ear_protection', models.BooleanField(default=False, verbose_name=' واقي الاذن Ear Protection')),
                ('ppe_mask', models.BooleanField(default=False, verbose_name='كمامة Mask')),
                ('ppe_other', models.CharField(blank=True, max_length=100, null=True, verbose_name='اخرى Other')),
                ('nature_of_injury', models.TextField(blank=True, null=True, verbose_name='طبيعة الاصابة او المرض ( مثلا تمزق ، كسر، جرح) Nature of Injury or Illness (e.g. fracture, strain/sprain, bruising)')),
                ('bodily_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان الاصابة بالجسم او المرض(مثلا اليد اليمنى، اسفل الظهر، الرئتين) Bodily Location of Injury or Illness (e.g. right leg, lower back)')),
                ('first_aid_details', models.TextField(blank=True, null=True, verbose_name='تفاصيل الاسعافات الاولية المقدمة للمصاب Details of Any First Aid Treatment Provided')),
                ('first_aider_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المسعف Name of First Aider')),
                ('hospital_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='في حالة تم نقله للمستشفى، اسم المستشفى If admitted to Hospital,hospital name')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_injured', to='hse_companies.incidentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='وصف للالية/الملكية المتضررة Description of Property/Equipment Damage')),
                ('damage_nature', models.TextField(blank=True, null=True, verbose_name='طبيعة الضرر للالية/الملكية Nature of Property/Equipment Damage')),
                ('material_spill_details', models.TextField(blank=True, null=True, verbose_name='تفاصيل كمية المواد المتسربة ونوعها Details of materials spill and quantities, its type')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_property', to='hse_companies.incidentinfo')),
            ],
        ),
    ]
