# Generated by Django 5.1.7 on 2025-04-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0017_remove_incidentinfo_bodily_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentcost',
            options={'verbose_name': 'تكاليف الحادث Cost Estimation', 'verbose_name_plural': 'تكاليف الحادث Cost Estimation'},
        ),
        migrations.AlterModelOptions(
            name='incidentinjured',
            options={'verbose_name': 'تفاصيل الشخص المصاب Details of Injured Person', 'verbose_name_plural': 'تفاصيل الشخص المصاب Details of Injured Person'},
        ),
        migrations.AlterModelOptions(
            name='incidentproperty',
            options={'verbose_name': 'تفاصيل الملكية/الالية او المركبة المتضررة/كمية المواد المتسربة Details of Property/Equipment or vehicle Damage/Quantity of Spill', 'verbose_name_plural': 'تفاصيل الملكية/الالية او المركبة المتضررة/كمية المواد المتسربة Details of Property/Equipment or vehicle Damage/Quantity of Spill'},
        ),
    ]
