# Generated by Django 5.1.7 on 2025-05-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0018_alter_incidentcost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentinjured',
            name='injured_surname',
            field=models.CharField(default='', max_length=100, verbose_name='إسم المصاب Injured Surname'),
            preserve_default=False,
        ),
    ]
