# Generated by Django 5.1.7 on 2025-05-20 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0128_tblcompanyproductionlicense_geom'),
        ('hse_companies', '0020_incidentinjureddetails_incidentinjuredperson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblStateRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hse_cmpny_state', to='company_profile.lkpstate', verbose_name='state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hse_cmpny_state', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'state representative',
                'verbose_name_plural': 'state representatives',
                'constraints': [models.UniqueConstraint(fields=('user', 'state'), name='hse_cmpny_unique_user_state')],
            },
        ),
    ]
