# Generated by Django 5.2.1 on 2025-07-02 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0129_alter_tblcompanyproductionlicense_geom'),
        ('hse_companies', '0022_alter_incidentinfo_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apphseperformancereport',
            name='unique_report_per_month',
        ),
        migrations.AddField(
            model_name='apphseperformancereport',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproductionlicense', verbose_name='license'),
        ),
        migrations.AddConstraint(
            model_name='apphseperformancereport',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'company', 'license'), name='unique_report_per_month'),
        ),
    ]
