# Generated by Django 5.2.1 on 2025-08-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0023_remove_apphseperformancereport_unique_report_per_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphsecorrectiveaction',
            name='corrective_action',
            field=models.TextField(verbose_name='الإجراء التصحيحي'),
        ),
    ]
