# Generated by Django 5.2.1 on 2025-09-24 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0024_alter_apphsecorrectiveaction_corrective_action'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apphseperformancereport',
            name='unique_report_per_month',
        ),
    ]
