# Generated by Django 5.2.1 on 2025-09-24 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0131_alter_appaddarea_reject_comments_and_more'),
        ('hse_companies', '0025_remove_apphseperformancereport_unique_report_per_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='apphseperformancereport',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'company', 'license'), name='unique_report_per_month'),
        ),
    ]
