# Generated by Django 5.2.7 on 2026-02-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0026_apphseperformancereport_unique_report_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributingfactor',
            name='factor_type',
            field=models.SmallIntegerField(choices=[(1, 'بيئة العمل Work environment'), (2, ' الادوات، الالات او المنشاة Tools, equipment or plant'), (3, 'اجراءات العمل/القواعد Work procedures/rules'), (4, ' التواصل/المعلومات Communication/information'), (5, 'المناولة اليدوية Manual handling'), (6, 'النظافة والترتيب Housekeeping'), (7, 'اجهزة السلامة/التحذير Warning/safety devices'), (8, 'التدريب/مستوى المهارات Training/skill level'), (9, 'عوامل شخصية Personal factors'), (10, 'عوامل خارجية External factors'), (11, 'ادوات السلامة الشخصية Personal protective equipment'), (12, 'اخرى Other')], default=1, verbose_name='الاسباب المساهمة في الحادث Contributing Causes'),
        ),
    ]
