# Generated by Django 5.2.7 on 2026-02-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0027_alter_contributingfactor_factor_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentinfo',
            options={'ordering': ['-date_time_occurred'], 'verbose_name': 'تقرير التحقيق عن حادث', 'verbose_name_plural': 'تقرير التحقيق عن الحوادث'},
        ),
    ]
