# Generated by Django 5.2.7 on 2026-04-16 11:52

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0138_alter_apphseaccidentreport_options'),
        ('hse_companies', '0028_alter_incidentinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='apphsecorrectiveaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='apphsecorrectiveaction',
            name='is_company_root',
            field=models.BooleanField(default=False, verbose_name='Is Company Root'),
        ),
        migrations.AddField(
            model_name='apphsecorrectiveaction',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apphsecorrectiveaction',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apphsecorrectiveaction',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hse_companies.apphsecorrectiveaction', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='apphsecorrectiveaction',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apphsecorrectiveaction',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apphsecorrectiveaction',
            name='corrective_action',
            field=models.TextField(blank=True, verbose_name='الإجراء التصحيحي'),
        ),
        migrations.AlterField(
            model_name='apphsecorrectiveaction',
            name='from_dt',
            field=models.DateField(blank=True, null=True, verbose_name='من'),
        ),
        migrations.AlterField(
            model_name='apphsecorrectiveaction',
            name='to_dt',
            field=models.DateField(blank=True, null=True, verbose_name='إلى'),
        ),
    ]
