# Generated by Django 5.2.7 on 2026-04-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0029_apphsecorrectiveaction_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apphsecorrectiveaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='apphsecorrectiveaction',
            name='is_company_root',
        ),
        migrations.RemoveField(
            model_name='apphsecorrectiveaction',
            name='level',
        ),
        migrations.RemoveField(
            model_name='apphsecorrectiveaction',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='apphsecorrectiveaction',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='apphsecorrectiveaction',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='apphsecorrectiveaction',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='apphsecorrectiveaction',
            name='corrective_action',
            field=models.TextField(verbose_name='الإجراء التصحيحي'),
        ),
        migrations.AlterField(
            model_name='apphsecorrectiveaction',
            name='from_dt',
            field=models.DateField(default='2026-01-01', verbose_name='من'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apphsecorrectiveaction',
            name='to_dt',
            field=models.DateField(default='2026-01-01', verbose_name='إلى'),
            preserve_default=False,
        ),
    ]
