# Generated by Django 5.2.7 on 2026-05-31 12:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0142_merge_20260429_1656'),
        ('hse_companies', '0031_create_hse_read_only_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblCompanyEvaluationEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('evaluation_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التقييم')),
                ('env_mercury_condenser_smelting', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='وجود مكثف زئبق في غرفة الصهر')),
                ('env_mercury_condenser_cell', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='وجود مكثف زئبق في الخلية')),
                ('env_sanitation_system', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='نظام صرف الصحي')),
                ('env_containment_basins', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='أحواض الاحتواء')),
                ('env_cyanide_mixer', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='خلاط السيانيد')),
                ('env_solution_connections_safety', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='سلامة توصيلات المحاليل')),
                ('env_solution_basins_insulation', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='عزل احواض المحاليل')),
                ('env_noise_control_mechanism', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='آلية التحكم في الضوضاء')),
                ('env_dust_control_mechanism', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='آلية التحكم في الغبار')),
                ('env_tailings_storage', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='مخزن الكرته')),
                ('env_basins_fencing', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='تسوير الاحواض')),
                ('env_landfill', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='مكب النفايات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='env_evaluations', to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkplocality', verbose_name='locality')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'تقييم البيئة',
                'verbose_name_plural': 'تقييمات البيئة',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='TblCompanyEvaluationGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('evaluation_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التقييم')),
                ('gen_monthly_reports_commitment', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='الالتزام بالتقارير الشهرية')),
                ('gen_corrective_actions_commitment', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='الإلتزام بتنفيذ الإجراءات التصحيحية')),
                ('gen_company_site_fencing', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='تسوير موقع الشركة')),
                ('gen_waste_management_plan', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='خطة إدارة النفايات')),
                ('gen_emergency_plan', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='خطة طواريء ERP & EAP')),
                ('gen_hse_plan', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='خطة HSE')),
                ('gen_hse_policy', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='سياسة HSE')),
                ('gen_esia', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='ESIA')),
                ('gen_qualified_hse_officer', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='وجود مسؤول بيئة وسلامة مؤهل')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gen_evaluations', to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkplocality', verbose_name='locality')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'تقييم المطلوبات العامة',
                'verbose_name_plural': 'تقييمات المطلوبات العامة',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='TblCompanyEvaluationSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('evaluation_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التقييم')),
                ('safe_mine_barriers', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='حواجز المناجم')),
                ('safe_mine_faces', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='واجهات المناجم')),
                ('safe_mine_lighting', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='إضاءة المناجم')),
                ('safe_food_storage', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='مخزن المواد الغذائية')),
                ('safe_kitchen', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='المطبخ')),
                ('safe_dining_hall', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='صالة الطعام')),
                ('safe_meals', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='الوجبات الغذائية')),
                ('safe_accommodation_rooms', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='غرف السكن')),
                ('safe_accommodation_toilets', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='دورات مياه السكن')),
                ('safe_drinking_water_quality', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='جودة مياه الشرب')),
                ('safe_hcn_detector', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='وجود HCN Dector')),
                ('safe_smelting_room_compliance', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='مطابقة غرفة الصهر')),
                ('safe_chemical_storage_compliance', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='مطابقة مخزن المواد الكيميائية')),
                ('safe_cyanide_storage_compliance', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='مطابقة مخزن السيانيد')),
                ('safe_vehicles_machinery_safety', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='سلامة المركبات والآليات')),
                ('safe_work_environment_quality', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='جودة بيئة العمل')),
                ('safe_specialized_training', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='وجود تدريب مختص')),
                ('safe_electrical_connections_safety', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='سلامة التوصيلات الكهربائية')),
                ('safe_ppe', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='PPE')),
                ('safe_ptw', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='PTW')),
                ('safe_safety_signs', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='علامات السلامة الإرشادية والتحذيرية')),
                ('safe_initial_medical_check', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='الفحص الطبي الأولي')),
                ('safe_periodic_medical_check', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='الفحص الطبي الدوري')),
                ('safe_first_aid_boxes', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='صناديق الاسعافت الأولية')),
                ('safe_firefighting_system', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='نظام مكافحة حرائق')),
                ('safe_health_unit', models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='وحدة صحية')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safe_evaluations', to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkplocality', verbose_name='locality')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'تقييم السلامة',
                'verbose_name_plural': 'تقييمات السلامة',
                'ordering': ['-evaluation_date'],
            },
        ),
    ]
