# Generated by Django 5.2.7 on 2026-05-31 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0139_lkpstate_code'),
        ('hse_companies', '0032_tblcompanyevaluationenvironment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcompanyevaluationenvironment',
            options={'verbose_name': 'تقييم البيئة', 'verbose_name_plural': 'تقييمات البيئة'},
        ),
        migrations.AlterModelOptions(
            name='tblcompanyevaluationgeneral',
            options={'verbose_name': 'تقييم المطلوبات العامة', 'verbose_name_plural': 'تقييمات المطلوبات العامة'},
        ),
        migrations.AlterModelOptions(
            name='tblcompanyevaluationsafety',
            options={'verbose_name': 'تقييم السلامة', 'verbose_name_plural': 'تقييمات السلامة'},
        ),
        migrations.RemoveField(
            model_name='tblcompanyevaluationenvironment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tblcompanyevaluationenvironment',
            name='evaluation_date',
        ),
        migrations.RemoveField(
            model_name='tblcompanyevaluationenvironment',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='tblcompanyevaluationenvironment',
            name='state',
        ),
        migrations.RemoveField(
            model_name='tblcompanyevaluationgeneral',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tblcompanyevaluationgeneral',
            name='evaluation_date',
        ),
        migrations.RemoveField(
            model_name='tblcompanyevaluationgeneral',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='tblcompanyevaluationgeneral',
            name='state',
        ),
        migrations.RemoveField(
            model_name='tblcompanyevaluationsafety',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tblcompanyevaluationsafety',
            name='evaluation_date',
        ),
        migrations.RemoveField(
            model_name='tblcompanyevaluationsafety',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='tblcompanyevaluationsafety',
            name='state',
        ),
        migrations.CreateModel(
            name='TblCompanyEvaluationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('evaluation_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التقييم')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkplocality', verbose_name='locality')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'جلسة تقييم الشركة (HSE)',
                'verbose_name_plural': 'جلسات تقييم الشركات (HSE)',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.AddField(
            model_name='tblcompanyevaluationenvironment',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environment', to='hse_companies.tblcompanyevaluationsession', verbose_name='جلسة التقييم'),
        ),
        migrations.AddField(
            model_name='tblcompanyevaluationgeneral',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general', to='hse_companies.tblcompanyevaluationsession', verbose_name='جلسة التقييم'),
        ),
        migrations.AddField(
            model_name='tblcompanyevaluationsafety',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety', to='hse_companies.tblcompanyevaluationsession', verbose_name='جلسة التقييم'),
        ),
    ]
