# Generated by Django 5.2.7 on 2026-06-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0033_alter_tblcompanyevaluationenvironment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcompanyevaluationsession',
            options={'ordering': ['-evaluation_date'], 'verbose_name': 'تقييم الشركة (HSE)', 'verbose_name_plural': 'تقييمات الشركات (HSE)'},
        ),
    ]
