# Generated by Django 5.2.7 on 2026-06-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0034_alter_tblcompanyevaluationsession_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='apphseperformancereport',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم محرر التقرير'),
        ),
        migrations.AddField(
            model_name='apphseperformancereport',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='هاتف محرر التقرير'),
        ),
        migrations.AddField(
            model_name='incidentinfo',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم محرر التقرير'),
        ),
        migrations.AddField(
            model_name='incidentinfo',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='هاتف محرر التقرير'),
        ),
    ]
