# Generated by Django 5.2.7 on 2026-06-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0035_add_reporter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='apphseperformancereport',
            name='approver_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم معتمد التقرير'),
        ),
        migrations.AddField(
            model_name='apphseperformancereport',
            name='approver_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='هاتف معتمد التقرير'),
        ),
        migrations.AddField(
            model_name='incidentinfo',
            name='approver_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم معتمد التقرير'),
        ),
        migrations.AddField(
            model_name='incidentinfo',
            name='approver_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='هاتف معتمد التقرير'),
        ),
    ]
