# Generated by Django 5.2.7 on 2026-06-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0036_add_approver_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcompanyevaluationsafety',
            name='safe_mine_barriers',
        ),
        migrations.RemoveField(
            model_name='tblcompanyevaluationsafety',
            name='safe_mine_faces',
        ),
        migrations.RemoveField(
            model_name='tblcompanyevaluationsafety',
            name='safe_mine_lighting',
        ),
    ]
