# Generated by Django 5.2.7 on 2026-06-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_companies', '0037_remove_mine_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanyevaluationsafety',
            name='safe_mine_barriers',
            field=models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='حواجز المناجم'),
        ),
        migrations.AddField(
            model_name='tblcompanyevaluationsafety',
            name='safe_mine_faces',
            field=models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='واجهات المناجم'),
        ),
        migrations.AddField(
            model_name='tblcompanyevaluationsafety',
            name='safe_mine_lighting',
            field=models.IntegerField(choices=[(0, 'المعيار غير موجود أصلاً'), (1, 'دون الوسط - غير مقبول (تقل عن 33%)'), (2, 'متوسط - مقبول ويحتاج إلى تحسين (34% - 66%)'), (3, 'أعلى من الوسط - جيد إلى ممتاز (تزيد عن 67%)')], default=0, verbose_name='إضاءة المناجم'),
        ),
    ]
