# Generated by Django 5.2.7 on 2025-11-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeedsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('items_list', models.TextField()),
                ('r1_recommendation', models.TextField(blank=True, null=True)),
                ('r2_recommendation', models.TextField(blank=True, null=True)),
                ('m1_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
