# Generated by Django 5.2.7 on 2025-11-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needsrequest',
            name='m1_approved',
        ),
        migrations.AddField(
            model_name='needsrequest',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='needsrequest',
            name='rejection_cause',
            field=models.TextField(blank=True, null=True),
        ),
    ]
