# Generated by Django 5.2.7 on 2025-11-03 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_request', '0002_remove_needsrequest_m1_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needsrequest',
            name='items_list',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_item_name', models.CharField(max_length=255)),
                ('approved_item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('needs_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='needs_request.needsrequest')),
            ],
        ),
    ]
