# Generated by Django 5.2.7 on 2025-11-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_request', '0003_remove_needsrequest_items_list_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
