# Generated by Django 5.2.7 on 2025-11-03 08:00

from django.db import migrations, models
import django.db.models.deletion

def copy_suggested_item_names(apps, schema_editor):
    Item = apps.get_model('needs_request', 'Item')
    SuggestedItem = apps.get_model('needs_request', 'SuggestedItem')
    for item in Item.objects.all():
        suggested_item, _ = SuggestedItem.objects.get_or_create(name=item.suggested_item_name)
        item.suggested_item = suggested_item
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('needs_request', '0005_populate_suggested_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='suggested_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='needs_request.suggesteditem'),
            preserve_default=False,
        ),
        migrations.RunPython(copy_suggested_item_names),
        migrations.RemoveField(
            model_name='item',
            name='suggested_item_name',
        ),
    ]
