# Generated by Django 5.2.7 on 2025-11-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_request', '0006_auto_20251103_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needsrequest',
            old_name='r1_recommendation',
            new_name='dgdhra_recommendation',
        ),
        migrations.RenameField(
            model_name='needsrequest',
            old_name='r2_recommendation',
            new_name='dgfa_recommendation',
        ),
        migrations.AddField(
            model_name='needsrequest',
            name='doa_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='needsrequest',
            name='it_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='needsrequest',
            name='sd_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='needsrequest',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sd_comment', 'Supply Department Comment'), ('doa_comment', 'Director of Administrative Comment'), ('it_comment', 'Information Technology Comment'), ('dgdhra_recommendation', 'Director of the General Department of Human Resources and Administration Recommendation'), ('dgfa_recommendation', 'Director of the General Department of Financial Affairs Recommendation'), ('agmfa_approval', 'Assistant General Manager for Financial and Administrative Affairs Approval'), ('gm_approval', 'General Manager Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=50),
        ),
    ]
