# Generated by Django 5.2.7 on 2025-11-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_request', '0008_alter_needsrequest_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsrequest',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('dga_approval', 'Director of the General Administration Approval'), ('dga_rejection', 'Director of the General Administration Rejection'), ('sd_comment', 'Supply Department Comment'), ('doa_comment', 'Director of Administrative Comment'), ('it_comment', 'Information Technology Comment'), ('dgdhra_recommendation', 'Director of the General Department of Human Resources and Administration Recommendation'), ('dgfa_recommendation', 'Director of the General Department of Financial Affairs Recommendation'), ('agmfa_approval', 'Assistant General Manager for Financial and Administrative Affairs Approval'), ('agmfa_rejection', 'Assistant General Manager for Financial and Administrative Affairs Rejection'), ('gm_approval', 'General Manager Approval'), ('gm_rejection', 'General Manager Rejection')], default='draft', max_length=50),
        ),
    ]
