# Generated by Django 5.2.7 on 2025-11-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_request', '0009_alter_needsrequest_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsrequest',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('dga_approval', 'موافقة مدير الإدارة العامة'), ('dga_rejection', 'رفض مدير الإدارة العامة'), ('sd_comment', 'تعليق قسم التوريد'), ('doa_comment', 'تعليق مدير الشؤون الإدارية'), ('it_comment', 'تعليق مدير تقنية المعلومات'), ('dgdhra_recommendation', 'توصية مدير الإدارة العامة للموارد البشرية والإدارية'), ('dgfa_recommendation', 'توصية مدير الإدارة العامة للشؤون المالية'), ('agmfa_approval', 'موافقة مساعد المدير العام للشؤون المالية والإدارية'), ('agmfa_rejection', 'رفض مساعد المدير العام للشؤون المالية والإدارية'), ('gm_approval', 'موافقة المدير العام'), ('gm_rejection', 'رفض المدير العام')], default='draft', max_length=50),
        ),
    ]
