# Generated by Django 5.2.7 on 2025-11-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs_request', '0010_alter_needsrequest_approval_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='suggested_item',
            new_name='requested_item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='approved_item_name',
        ),
    ]
