# Generated by Django 5.2.7 on 2025-11-04 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_request', '0012_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsrequest',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='needs_request.department'),
        ),
    ]
