# Generated by Django 5.2.7 on 2025-11-05 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_request', '0013_alter_needsrequest_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_manager_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='executive_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executive_manager_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='needs_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='needs_request.needsrequest'),
        ),
        migrations.AlterField(
            model_name='item',
            name='requested_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='needs_request.suggesteditem'),
        ),
        migrations.AlterField(
            model_name='needsrequest',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='needs_request.department'),
        ),
    ]
