# Generated by Django 5.2.7 on 2025-11-08 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_request', '0015_alter_needsrequest_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='approved_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_in_items', to='needs_request.suggesteditem'),
        ),
        migrations.AlterField(
            model_name='item',
            name='requested_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_in_items', to='needs_request.suggesteditem'),
        ),
    ]
