# Generated by Django 5.2.7 on 2025-11-08 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_request', '0016_item_approved_item_alter_item_requested_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='approved_item',
        ),
        migrations.AddField(
            model_name='item',
            name='no_of_approved_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='no_of_requested_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='requested_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='needs_request.suggesteditem'),
        ),
    ]
