# Generated by Django 5.2.7 on 2025-11-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_request', '0017_remove_item_approved_item_item_no_of_approved_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggesteditem',
            name='is_it_related',
            field=models.BooleanField(default=False),
        ),
    ]
