# Generated by Django 5.2.7 on 2025-11-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_request', '0018_suggesteditem_is_it_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='needsrequest',
            name='cause',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
