# Generated by Django 5.2.7 on 2025-12-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_request', '0019_needsrequest_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='needsrequest',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
    ]
