# Generated by Django 5.1.7 on 2025-04-16 08:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OsmanState',
            fields=[
                ('OBJECTID', models.AutoField(primary_key=True, serialize=False)),
                ('scode', models.CharField(max_length=4)),
                ('source', models.CharField(max_length=50)),
                ('name_arb', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=40)),
                ('adm2_ne', models.CharField(max_length=25)),
                ('cnt_will_i', models.BigIntegerField()),
                ('adm2_na', models.CharField(max_length=25)),
                ('adm2', models.IntegerField()),
                ('smrc_amm_d', models.FloatField()),
                ('areakm2', models.FloatField()),
                ('areakm2z35', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='SmallMining',
            fields=[
                ('OBJECTID', models.AutoField(primary_key=True, serialize=False)),
                ('license_nu', models.CharField(max_length=254, null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('mineral', models.CharField(blank=True, max_length=50, null=True)),
                ('valid', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('nots', models.CharField(blank=True, max_length=150, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
