# Generated by Django 5.0.2 on 2024-03-16 18:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmallMining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_nu', models.CharField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('mineral', models.CharField(max_length=50)),
                ('valid', models.CharField(max_length=50)),
                ('end_date', models.DateField()),
                ('area', models.FloatField()),
                ('nots', models.CharField(max_length=150)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
