# Generated by Django 5.1.7 on 2025-04-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_cordinates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmanstate',
            name='adm2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osmanstate',
            name='adm2_na',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='osmanstate',
            name='adm2_ne',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='osmanstate',
            name='areakm2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osmanstate',
            name='areakm2z35',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osmanstate',
            name='cnt_will_i',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osmanstate',
            name='name_arb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='osmanstate',
            name='scode',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='osmanstate',
            name='shape_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osmanstate',
            name='shape_leng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osmanstate',
            name='smrc_amm_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osmanstate',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='osmanstate',
            name='state',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
