# Generated by Django 5.1.7 on 2025-04-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_cordinates', '0002_alter_osmanstate_adm2_alter_osmanstate_adm2_na_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osmanstate',
            old_name='geom',
            new_name='POLYGON',
        ),
    ]
