# Generated by Django 5.1.7 on 2025-04-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_cordinates', '0003_rename_geom_osmanstate_polygon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osmanstate',
            old_name='POLYGON',
            new_name='geometry',
        ),
    ]
