# Generated by Django 5.0.2 on 2024-03-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_cordinates', '0004_alter_smallmining_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallmining',
            name='mineral',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='smallmining',
            name='valid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
