# Generated by Django 5.0.2 on 2024-03-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_cordinates', '0005_alter_smallmining_mineral_alter_smallmining_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallmining',
            name='license_nu',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
