# Generated by Django 5.1.7 on 2025-04-16 09:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_cordinates', '0005_rename_geometry_osmanstate_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmanstate',
            name='shape',
            field=django.contrib.gis.db.models.fields.PolygonField(db_index=True, srid=4326),
        ),
    ]
