# Generated by Django 5.0.2 on 2024-03-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_cordinates', '0007_alter_smallmining_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallmining',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smallmining',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
