# Generated by Django 5.0.2 on 2024-03-16 20:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_cordinates', '0008_alter_smallmining_area_alter_smallmining_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallmining',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=32636),
        ),
    ]
