# Generated by Django 5.0.2 on 2024-03-17 11:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_cordinates', '0009_alter_smallmining_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallmining',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=32636),
        ),
    ]
