# Generated by Django 5.1.7 on 2025-04-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_cordinates', '0010_alter_smallmining_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallmining',
            name='objectid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
