# Generated by Django 5.1.7 on 2025-04-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_cordinates', '0011_smallmining_objectid'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='smallmining',
        #     name='id',
        # ),
        migrations.AlterField(
            model_name='smallmining',
            name='objectid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
