# Generated by Django 5.1.7 on 2025-04-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_cordinates', '0012_remove_smallmining_id_alter_smallmining_objectid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smallmining',
            old_name='objectid',
            new_name='OBJECTID',
        ),
    ]
