# Generated by Django 5.1.7 on 2025-04-15 13:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_cordinates', '0013_rename_objectid_smallmining_objectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallmining',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
