# Generated by Django 5.1.7 on 2025-04-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_cordinates', '0014_alter_smallmining_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallmining',
            name='OBJECTID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
