# Generated by Django 5.1 on 2024-11-20 08:01

import django.db.models.deletion
import production_control.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0081_alter_tblcompanyproduction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldProductionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('form_no', models.CharField(max_length=20, verbose_name='form_no')),
                ('state', models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_confirmed')], default=1, verbose_name='record_state')),
                ('attachement_file', models.FileField(upload_to=production_control.models.company_applications_path, verbose_name='gold_production_form_file')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Gold Production Form',
                'verbose_name_plural': 'Gold Production Form',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GoldProductionFormAlloy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('alloy_serial_no', models.CharField(max_length=30, verbose_name='alloy_serial_no')),
                ('alloy_weight', models.FloatField(verbose_name='alloy_weight')),
                ('alloy_jaf', models.FloatField(verbose_name='alloy_jaf')),
                ('alloy_khabath', models.FloatField(verbose_name='alloy_khabath')),
                ('alloy_added_gold', models.FloatField(blank=True, null=True, verbose_name='alloy_added_gold')),
                ('alloy_remaind', models.FloatField(blank=True, null=True, verbose_name='alloy_remaind')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production_control.goldproductionform')),
            ],
            options={
                'verbose_name': 'Gold Production Form - Alloy',
                'verbose_name_plural': 'Gold Production Form - Alloy',
            },
        ),
    ]
