# Generated by Django 5.1 on 2024-11-20 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldproductionformalloy',
            name='date',
        ),
        migrations.AddField(
            model_name='goldproductionform',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
    ]
