# Generated by Django 5.1 on 2024-11-20 11:28

import production_control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0002_remove_goldproductionformalloy_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldproductionform',
            name='attachement_file',
            field=models.FileField(blank=True, null=True, upload_to=production_control.models.company_applications_path, verbose_name='gold_production_form_file'),
        ),
    ]
