# Generated by Django 5.1 on 2024-11-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0003_alter_goldproductionform_attachement_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldproductionformalloy',
            name='alloy_shipped',
            field=models.BooleanField(default=False, verbose_name='alloy_shipped'),
        ),
    ]
