# Generated by Django 5.1 on 2024-11-24 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0004_goldproductionformalloy_alloy_shipped'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldProductionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(choices=[('entaj', 'entaj'), ('mokhalfat', 'mokhalfat'), ('emtiaz', 'emtiaz'), ('sageer', 'sageer')], max_length=15, verbose_name='company_type')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gold_production_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'gold_production_user',
                'verbose_name_plural': 'gold_production_users',
            },
        ),
    ]
