# Generated by Django 5.1 on 2024-11-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0006_goldproductionuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldproductionuser',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_confirmed')], default=1, verbose_name='record_state'),
        ),
    ]
