# Generated by Django 5.1 on 2024-11-24 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0081_alter_tblcompanyproduction_options_and_more'),
        ('production_control', '0007_goldproductionuser_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldproductionuser',
            name='company_type',
        ),
        migrations.AddField(
            model_name='goldproductionuser',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company'),
            preserve_default=False,
        ),
    ]
