# Generated by Django 5.1 on 2024-11-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0081_alter_tblcompanyproduction_options_and_more'),
        ('production_control', '0008_remove_goldproductionuser_company_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldproductionuser',
            name='company',
        ),
        migrations.CreateModel(
            name='GoldProductionUserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production_control.goldproductionuser')),
            ],
        ),
    ]
