# Generated by Django 5.1 on 2024-11-24 11:09

import django.db.models.deletion
import production_control.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0081_alter_tblcompanyproduction_options_and_more'),
        ('production_control', '0009_remove_goldproductionuser_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldproductionuserdetail',
            options={'verbose_name': 'gold_production_user_detail', 'verbose_name_plural': 'gold_production_user_details'},
        ),
        migrations.CreateModel(
            name='GoldShippingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('date', models.DateField(verbose_name='date')),
                ('form_no', models.CharField(max_length=20, verbose_name='form_no')),
                ('state', models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_confirmed')], default=1, verbose_name='record_state')),
                ('attachement_file', models.FileField(blank=True, null=True, upload_to=production_control.models.company_applications_path, verbose_name='gold_production_form_file')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Gold Shipping Form',
                'verbose_name_plural': 'Gold Shipping Form',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GoldShippingFormAlloy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alloy_weight', models.FloatField(verbose_name='alloy_weight')),
                ('alloy_serial_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production_control.goldproductionformalloy', verbose_name='alloy_serial_no')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production_control.goldshippingform')),
            ],
            options={
                'verbose_name': 'Gold Shipping Form - Alloy',
                'verbose_name_plural': 'Gold Shipping Form - Alloy',
            },
        ),
    ]
