# Generated by Django 5.1 on 2024-11-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0010_alter_goldproductionuserdetail_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldshippingformalloy',
            name='alloy_weight',
        ),
    ]
