# Generated by Django 5.1 on 2024-11-26 08:40

import production_control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0011_remove_goldshippingformalloy_alloy_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goldproductionform',
            old_name='attachement_file',
            new_name='gold_production_form_file',
        ),
        migrations.RemoveField(
            model_name='goldproductionformalloy',
            name='alloy_jaf',
        ),
        migrations.RemoveField(
            model_name='goldproductionformalloy',
            name='alloy_khabath',
        ),
        migrations.RemoveField(
            model_name='goldproductionformalloy',
            name='alloy_remaind',
        ),
        migrations.AddField(
            model_name='goldproductionform',
            name='alloy_jaf',
            field=models.FloatField(default=0, verbose_name='alloy_jaf'),
        ),
        migrations.AddField(
            model_name='goldproductionform',
            name='alloy_khabath',
            field=models.FloatField(default=0, verbose_name='alloy_khabath'),
        ),
        migrations.AddField(
            model_name='goldproductionform',
            name='alloy_remaind',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='alloy_remaind'),
        ),
        migrations.AddField(
            model_name='goldproductionform',
            name='gold_production_3hda_file',
            field=models.FileField(blank=True, null=True, upload_to=production_control.models.company_applications_path, verbose_name='gold_production_3hda_file'),
        ),
    ]
