# Generated by Django 5.1.4 on 2024-12-17 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0014_alter_goldshippingform_attachement_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldproductionuser',
            options={'verbose_name': 'moragib_distribution', 'verbose_name_plural': 'moragib_distribution'},
        ),
        migrations.CreateModel(
            name='LkpMoragib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='moragib_list', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'moragib_list',
                'verbose_name_plural': 'moragib_list',
            },
        ),
        migrations.AddField(
            model_name='goldproductionuser',
            name='moragib',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moragib_distribution', to='production_control.lkpmoragib', verbose_name='moragib'),
        ),
    ]
