# Generated by Django 5.1.4 on 2024-12-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0015_alter_goldproductionuser_options_lkpmoragib_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpmoragib',
            name='company_type',
            field=models.CharField(choices=[('entaj', 'entaj'), ('mokhalfat', 'mokhalfat'), ('emtiaz', 'emtiaz'), ('sageer', 'sageer')], default='entaj', max_length=15, verbose_name='company_type'),
            preserve_default=False,
        ),
    ]
