# Generated by Django 5.1.4 on 2024-12-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0016_lkpmoragib_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpmoragib',
            name='emp_code',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='name'),
        ),
    ]
