# Generated by Django 5.1.4 on 2024-12-17 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0017_lkpmoragib_emp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldproductionuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='goldproductionuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='goldproductionform',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_confirmed'), (3, 'state_expired')], default=1, verbose_name='record_state'),
        ),
        migrations.AlterField(
            model_name='goldproductionuser',
            name='moragib',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='moragib_distribution', to='production_control.lkpmoragib', verbose_name='moragib'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goldproductionuser',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_confirmed'), (3, 'state_expired')], default=1, verbose_name='record_state'),
        ),
        migrations.AlterField(
            model_name='goldshippingform',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_confirmed'), (3, 'state_expired')], default=1, verbose_name='record_state'),
        ),
    ]
