# Generated by Django 5.1.4 on 2024-12-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0018_remove_goldproductionuser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldproductionform',
            name='alloy_weight_expected',
            field=models.FloatField(default=0, verbose_name='alloy_weight_expected'),
        ),
    ]
