# Generated by Django 5.1.4 on 2024-12-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0019_goldproductionform_alloy_weight_expected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldproductionform',
            name='alloy_weight_expected',
            field=models.FloatField(default=0, null=True, verbose_name='alloy_weight_expected'),
        ),
    ]
