# Generated by Django 5.0.2 on 2025-01-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0020_alter_goldproductionform_alloy_weight_expected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldproductionform',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_confirmed'), (3, 'state_approved')], default=1, verbose_name='record_state'),
        ),
        migrations.AlterField(
            model_name='goldshippingform',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_confirmed'), (3, 'state_approved')], default=1, verbose_name='record_state'),
        ),
    ]
