# Generated by Django 5.0.2 on 2025-03-18 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0116_appfuelpermissiondetail_fuel_actual_qty'),
        ('production_control', '0021_alter_goldproductionform_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldproductionuserdetail',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproductionlicense', verbose_name='license_type'),
        ),
    ]
