# Generated by Django 5.1.7 on 2025-03-25 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0117_lkpsector_lkpstate_sector'),
        ('production_control', '0025_goldshippingform_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldproductionform',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='goldproductionform',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'تأكيد المراقب'), (3, 'تأكيد رئيس قسم الانتاج بالولاية'), (4, 'إعتماد مشرف القطاع'), (5, 'مراجعة الإدخال')], default=1, verbose_name='record_state'),
        ),
        migrations.AlterField(
            model_name='goldshippingform',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='goldshippingform',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'تأكيد المراقب'), (3, 'تأكيد رئيس قسم الانتاج بالولاية'), (4, 'إعتماد مشرف القطاع'), (5, 'مراجعة الإدخال')], default=1, verbose_name='record_state'),
        ),
    ]
