# Generated by Django 5.1.7 on 2025-04-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0117_lkpsector_lkpstate_sector'),
        ('production_control', '0027_goldproductionsectoruser_goldproductionstateuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldproductionstateuser',
            name='state',
        ),
        migrations.AddField(
            model_name='goldproductionstateuser',
            name='state',
            field=models.ManyToManyField(to='company_profile.lkpstate', verbose_name='state'),
        ),
    ]
