# Generated by Django 5.2.7 on 2026-02-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0028_remove_goldproductionstateuser_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldproductionform',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'تأكيد المراقب'), (3, 'تأكيد مشرف القطاع'), (4, 'إعتماد رئيس القطاع'), (5, 'مراجعة الإدخال')], default=1, verbose_name='record_state'),
        ),
        migrations.AlterField(
            model_name='goldshippingform',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'تأكيد المراقب'), (3, 'تأكيد مشرف القطاع'), (4, 'إعتماد رئيس القطاع'), (5, 'مراجعة الإدخال')], default=1, verbose_name='record_state'),
        ),
    ]
