# Generated by Django 5.0.2 on 2024-09-02 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenu_dist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblrevenu',
            options={'verbose_name': 'Revenu', 'verbose_name_plural': 'Revenu'},
        ),
        migrations.AlterField(
            model_name='lkprevenutypedetail',
            name='percent',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='percent'),
        ),
    ]
