# Generated by Django 5.0.2 on 2024-09-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenu_dist', '0002_alter_tblrevenu_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblrevenu',
            options={'verbose_name': 'Revenu distribution', 'verbose_name_plural': 'Revenu distribution'},
        ),
        migrations.AlterModelOptions(
            name='tblrevenudist',
            options={'verbose_name': 'Revenu distribution detail', 'verbose_name_plural': 'Revenu distribution details'},
        ),
        migrations.RemoveField(
            model_name='tblrevenu',
            name='revenu_type',
        ),
        migrations.AlterField(
            model_name='lkprevenutypedetail',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revenu_dist.lkppartner', verbose_name='Partner'),
        ),
        migrations.CreateModel(
            name='LkpRevenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('revenu_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revenu_dist.lkprevenutype', verbose_name='Revenu type')),
            ],
            options={
                'verbose_name': 'Revenu',
                'verbose_name_plural': 'Revenu',
            },
        ),
        migrations.AddField(
            model_name='tblrevenu',
            name='revenu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='revenu_dist.lkprevenu', verbose_name='Revenu'),
            preserve_default=False,
        ),
    ]
