# Generated by Django 5.0.2 on 2024-09-04 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenu_dist', '0004_alter_tblrevenu_name_alter_tblrevenudist_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrevenudist',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revenu_dist.lkppartner', verbose_name='Partner'),
        ),
    ]
