# Generated by Django 5.0.2 on 2024-10-17 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMoveGold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('date', models.DateField(verbose_name='date')),
                ('destination', models.IntegerField(choices=[(1, 'ssmo_name')], default=1, verbose_name='destination')),
                ('owner_name', models.CharField(max_length=100, verbose_name='owner_name')),
                ('owner_address', models.CharField(max_length=150, verbose_name='owner_address')),
                ('repr_name', models.CharField(max_length=100, verbose_name='repr_name')),
                ('repr_address', models.CharField(max_length=150, verbose_name='repr_address')),
                ('repr_phone', models.CharField(max_length=30, verbose_name='repr_phone')),
                ('repr_identity', models.CharField(max_length=50, verbose_name='repr_identity')),
                ('repr_identity_issue_date', models.DateField(verbose_name='repr_identity_issue_date')),
                ('gold_weight_in_gram', models.FloatField(verbose_name='gold_weight_in_gram')),
                ('gold_alloy_count', models.IntegerField(verbose_name='gold_alloy_count')),
                ('gold_description', models.CharField(max_length=100, verbose_name='gold_description')),
                ('state', models.CharField(choices=[(1, 'state_draft'), (2, 'state_smrc'), (3, 'state_2mn_2lm3adin'), (4, 'state_shortat_2lm3adin'), (5, 'state_2lestikhbarat_2l3askria')], default=1, max_length=10, verbose_name='record_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppMoveGoldDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alloy_id', models.CharField(max_length=100, verbose_name='alloy_id')),
                ('alloy_weight_in_gram', models.FloatField(verbose_name='alloy_weight_in_gram')),
                ('alloy_shape', models.IntegerField(choices=[(1, 'alloy_shape_rectangular'), (2, 'alloy_shape_circular')], verbose_name='alloy_shape')),
                ('alloy_note', models.CharField(max_length=150, verbose_name='alloy_note')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel.appmovegold')),
            ],
        ),
    ]
