# Generated by Django 5.0.2 on 2024-10-17 11:34

import gold_travel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0002_alter_appmovegold_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmovegold',
            name='attachement_file',
            field=models.FileField(default='', upload_to=gold_travel.models.AppMoveGold.attachement_path, verbose_name='attachement_file'),
            preserve_default=False,
        ),
    ]
