# Generated by Django 5.0.2 on 2024-10-17 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0003_appmovegold_attachement_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmovegold',
            options={'ordering': ['-id'], 'verbose_name': 'Move Gold', 'verbose_name_plural': 'Move Gold'},
        ),
        migrations.AddIndex(
            model_name='appmovegold',
            index=models.Index(fields=['owner_name'], name='gold_travel_owner_n_d12b1e_idx'),
        ),
    ]
