# Generated by Django 5.0.2 on 2024-10-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0004_alter_appmovegold_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmovegolddetails',
            options={'verbose_name': 'alloy detail', 'verbose_name_plural': 'alloy details'},
        ),
    ]
