# Generated by Django 5.0.2 on 2024-10-17 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0080_tblcompanyproductionlicense_area_initial'),
        ('gold_travel', '0005_alter_appmovegolddetails_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblStateRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='state_representative', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'state representative',
                'verbose_name_plural': 'state representatives',
            },
        ),
    ]
