# Generated by Django 5.0.2 on 2024-10-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0006_tblstaterepresentative'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstaterepresentative',
            name='authority',
            field=models.IntegerField(choices=[(2, 'authority_smrc'), (3, 'authority_2mn_2lm3adin'), (4, 'authority_shortat_2lm3adin'), (5, 'authority_2lestikhbarat_2l3askria')], default=2, verbose_name='authority'),
        ),
    ]
