# Generated by Django 5.0.2 on 2024-10-17 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0008_alter_tblstaterepresentative_user_apppreparegold'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppreparegold',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
    ]
