# Generated by Django 5.0.2 on 2024-10-17 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0010_tblstaterepresentative_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppreparegold',
            name='issuer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gold_travel.tblstaterepresentative', verbose_name='issuer'),
            preserve_default=False,
        ),
    ]
