# Generated by Django 5.0.2 on 2024-10-18 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0080_tblcompanyproductionlicense_area_initial'),
        ('gold_travel', '0011_apppreparegold_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmovegold',
            name='source_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apppreparegold',
            name='source_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state'),
            preserve_default=False,
        ),
    ]
