# Generated by Django 5.0.2 on 2024-10-21 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0080_tblcompanyproductionlicense_area_initial'),
        ('gold_travel', '0012_appmovegold_source_state_apppreparegold_source_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LkpStateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='code')),
                ('next_serial_no', models.IntegerField(verbose_name='next_serial_no')),
            ],
        ),
        migrations.AddField(
            model_name='appmovegold',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='code'),
        ),
        migrations.AddIndex(
            model_name='appmovegold',
            index=models.Index(fields=['code'], name='gold_travel_code_e99aa5_idx'),
        ),
        migrations.AddField(
            model_name='lkpstatedetails',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='state_gold_travel', to='company_profile.lkpstate', verbose_name='state'),
        ),
    ]
