# Generated by Django 5.0.2 on 2024-10-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0014_appmovegold_repr_identity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegold',
            name='repr_identity_type',
            field=models.IntegerField(choices=[(1, 'identity_passport'), (2, 'identity_personal'), (3, 'identity_national_id')], default=1, max_length=2, verbose_name='repr_identity_type'),
        ),
    ]
