# Generated by Django 5.0.2 on 2024-10-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0016_alter_appmovegold_repr_identity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmovegolddetails',
            name='alloy_id',
        ),
        migrations.AddField(
            model_name='appmovegolddetails',
            name='alloy_count',
            field=models.IntegerField(default=1, verbose_name='alloy_count'),
        ),
    ]
