# Generated by Django 5.0.2 on 2024-10-22 09:17

import gold_travel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0017_remove_appmovegolddetails_alloy_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lkpstatedetails',
            options={'verbose_name': 'gold travel state detail', 'verbose_name_plural': 'gold travel state details'},
        ),
        migrations.RemoveField(
            model_name='appmovegold',
            name='gold_alloy_count',
        ),
        migrations.RemoveField(
            model_name='appmovegold',
            name='gold_description',
        ),
        migrations.RemoveField(
            model_name='appmovegold',
            name='gold_weight_in_gram',
        ),
        migrations.RemoveField(
            model_name='appmovegolddetails',
            name='alloy_count',
        ),
        migrations.AddField(
            model_name='appmovegolddetails',
            name='alloy_id',
            field=models.CharField(default='', max_length=20, verbose_name='alloy_id'),
        ),
        migrations.AlterField(
            model_name='appmovegold',
            name='attachement_file',
            field=models.FileField(blank=True, null=True, upload_to=gold_travel.models.AppMoveGold.attachement_path, verbose_name='attachement_file'),
        ),
        migrations.AlterField(
            model_name='appmovegolddetails',
            name='alloy_note',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='alloy_note'),
        ),
    ]
