# Generated by Django 5.0.2 on 2024-10-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0018_alter_lkpstatedetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpstatedetails',
            name='has_2lestikhbarat_2l3askria',
            field=models.BooleanField(default=False, verbose_name='has_2lestikhbarat_2l3askria'),
            preserve_default=False,
        ),
    ]
