# Generated by Django 5.0.2 on 2024-10-24 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0080_tblcompanyproductionlicense_area_initial'),
        ('gold_travel', '0019_lkpstatedetails_has_2lestikhbarat_2l3askria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tblstaterepresentative',
            constraint=models.UniqueConstraint(fields=('state', 'authority'), name='unique_state_authority '),
        ),
    ]
