# Generated by Django 5.1 on 2024-11-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0020_tblstaterepresentative_unique_state_authority_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegold',
            name='repr_identity_type',
            field=models.IntegerField(choices=[(1, 'identity_passport'), (2, 'identity_personal'), (3, 'identity_national_id'), (4, 'identity_driving_license')], default=1, verbose_name='repr_identity_type'),
        ),
    ]
