# Generated by Django 5.1 on 2024-11-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0021_alter_appmovegold_repr_identity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegold',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_smrc'), (3, 'state_2mn_2lm3adin'), (4, 'state_shortat_2lm3adin'), (5, 'state_2lestikhbarat_2l3askria'), (6, 'state_ssmo')], default=1, verbose_name='record_state'),
        ),
        migrations.AlterField(
            model_name='tblstaterepresentative',
            name='authority',
            field=models.IntegerField(choices=[(2, 'authority_smrc'), (3, 'authority_2mn_2lm3adin'), (4, 'authority_shortat_2lm3adin'), (5, 'authority_2lestikhbarat_2l3askria'), (6, 'authority_smrc_nafiza')], default=2, verbose_name='authority'),
        ),
    ]
