# Generated by Django 5.1 on 2024-11-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0022_alter_appmovegold_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegold',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_smrc'), (3, 'state_2mn_2lm3adin'), (4, 'state_shortat_2lm3adin'), (5, 'state_2lestikhbarat_2l3askria'), (6, 'state_ssmo'), (7, 'state_canceled')], default=1, verbose_name='record_state'),
        ),
    ]
