# Generated by Django 5.1 on 2024-11-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0024_lkpowner_alter_appmovegold_owner_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appmovegold',
            name='gold_travel_owner_n_d12b1e_idx',
        ),
        migrations.RenameField(
            model_name='appmovegold',
            old_name='owner_name',
            new_name='owner_name_str',
        ),
    ]
