# Generated by Django 5.1 on 2024-11-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0025_remove_appmovegold_gold_travel_owner_n_d12b1e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmovegold',
            name='owner_name_lst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gold_travel.lkpowner', verbose_name='owner_name'),
        ),
    ]
