# Generated by Django 5.1 on 2024-11-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0027_alter_lkpowner_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegold',
            name='owner_name_lst',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gold_travel.lkpowner', verbose_name='owner_name'),
            preserve_default=False,
        ),
    ]
