# Generated by Django 5.1 on 2024-11-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0028_alter_appmovegold_owner_name_lst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmovegold',
            name='owner_name_str',
        ),
    ]
