# Generated by Django 5.1 on 2024-11-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0029_remove_appmovegold_owner_name_str'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmovegold',
            options={'ordering': ['-date'], 'verbose_name': 'Move Gold', 'verbose_name_plural': 'Move Gold'},
        ),
    ]
