# Generated by Django 5.1 on 2024-12-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0032_alter_appmovegold_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmovegold',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Move Gold', 'verbose_name_plural': 'Move Gold'},
        ),
    ]
