# Generated by Django 5.1 on 2024-12-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0034_alter_appmovegold_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppreparegold',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_confirmed'), (3, 'state_done')], default=1, verbose_name='record_state'),
        ),
    ]
