# Generated by Django 5.0.2 on 2025-02-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0036_appmovegold_form_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMoveGoldExportGold',
            fields=[
            ],
            options={
                'verbose_name': 'Export Gold',
                'verbose_name_plural': 'Export Gold',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gold_travel.appmovegold',),
        ),
        migrations.CreateModel(
            name='AppMoveGoldExportSilver',
            fields=[
            ],
            options={
                'verbose_name': 'Export Silver',
                'verbose_name_plural': 'Export Silver',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gold_travel.appmovegold',),
        ),
        migrations.CreateModel(
            name='AppMoveGoldREExportGold',
            fields=[
            ],
            options={
                'verbose_name': 'Re-export Gold',
                'verbose_name_plural': 'Re-export Gold',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gold_travel.appmovegold',),
        ),
        migrations.AddField(
            model_name='lkpstatedetails',
            name='reexport_next_serial_no',
            field=models.IntegerField(default=0, verbose_name='reexport_next_serial_no'),
        ),
        migrations.AddField(
            model_name='lkpstatedetails',
            name='silver_next_serial_no',
            field=models.IntegerField(default=0, verbose_name='silver_next_serial_no'),
        ),
        migrations.AlterField(
            model_name='lkpstatedetails',
            name='next_serial_no',
            field=models.IntegerField(verbose_name='export_next_serial_no'),
        ),
    ]
