# Generated by Django 5.0.2 on 2025-02-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0037_appmovegoldexportgold_appmovegoldexportsilver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lkpstatedetails',
            name='reexport_next_serial_no',
            field=models.IntegerField(default=1, verbose_name='reexport_next_serial_no'),
        ),
        migrations.AlterField(
            model_name='lkpstatedetails',
            name='silver_next_serial_no',
            field=models.IntegerField(default=1, verbose_name='silver_next_serial_no'),
        ),
    ]
