# Generated by Django 5.0.2 on 2025-03-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0038_alter_lkpstatedetails_reexport_next_serial_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpowner',
            name='state',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'inactive')], default=1, verbose_name='record_state'),
        ),
    ]
