# Generated by Django 5.1.7 on 2025-05-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0039_lkpowner_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegolddetails',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_gold_details', to='gold_travel.appmovegold'),
        ),
    ]
