# Generated by Django 5.1.7 on 2025-05-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0040_alter_appmovegolddetails_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegolddetails',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel.appmovegold'),
        ),
    ]
