# Generated by Django 5.2.7 on 2026-03-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0041_alter_appmovegolddetails_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpowner',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='lkpowner',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='owners/', verbose_name='attachment'),
        ),
        migrations.AddField(
            model_name='lkpowner',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='owner_name'),
        ),
        migrations.AddField(
            model_name='lkpowner',
            name='owner_telephone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='owner_telephone'),
        ),
    ]
