# Generated by Django 5.2.7 on 2026-03-10 10:00

import gold_travel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0042_lkpowner_address_lkpowner_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lkpowner',
            options={'ordering': ['name'], 'verbose_name': 'اسم الشركة', 'verbose_name_plural': 'اسماء الشركات'},
        ),
        migrations.AlterField(
            model_name='lkpowner',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='lkpowner',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=gold_travel.models.LkpOwner.attachement_path, verbose_name='المرفقات'),
        ),
        migrations.AlterField(
            model_name='lkpowner',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المالك'),
        ),
        migrations.AlterField(
            model_name='lkpowner',
            name='owner_telephone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='تلفون المالك'),
        ),
    ]
