# Generated by Django 5.2.7 on 2026-04-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0043_alter_lkpowner_options_alter_lkpowner_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpowner',
            name='authorized_person_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المفوض'),
        ),
        migrations.AddField(
            model_name='lkpowner',
            name='authorized_person_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='هاتف المفوض'),
        ),
        migrations.AlterField(
            model_name='lkpowner',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المدير العام'),
        ),
        migrations.AlterField(
            model_name='lkpowner',
            name='owner_telephone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='هاتف المدير العام'),
        ),
    ]
