# Generated by Django 5.0.2 on 2024-05-24 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edara3ama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='edara3ama')),
            ],
        ),
        migrations.CreateModel(
            name='MosamaWazifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='mosama_wazifi')),
            ],
        ),
        migrations.CreateModel(
            name='Drajat3lawat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('draja_wazifia', models.IntegerField(choices=[(-3, 'DRAJAT_TALTA_KHASA'), (-2, 'DRAJAT_TANIA_KHASA'), (-1, 'DRAJAT_AWLA_KHASA'), (1, 'DRAJAT_AWLA'), (2, 'DRAJAT_TANIA'), (3, 'DRAJAT_TALTA'), (4, 'DRAJAT_RAB3A'), (5, 'DRAJAT_KHAMSA'), (7, 'DRAJAT_SAB3A'), (8, 'DRAJAT_TAMNA'), (9, 'DRAJAT_TAS3A'), (10, 'DRAJAT_3ASHRA'), (12, 'DRAJAT_ATNASHAR'), (15, 'DRAJAT_KHAMSTASHR'), (17, 'DRAJAT_TA3AKOD')], verbose_name='draja_wazifia')),
                ('alawa_sanawia', models.IntegerField(choices=[(1, 'ALAWAT_AWALA'), (2, 'ALAWAT_TANIA'), (3, 'ALAWAT_TALTA'), (4, 'ALAWAT_RAB3A'), (5, 'ALAWAT_KHAMSA'), (7, 'ALAWAT_TA3AKOD')], verbose_name='alawa_sanawia')),
                ('abtdai', models.FloatField(verbose_name='abtdai')),
                ('galaa_m3isha', models.FloatField(verbose_name='galaa_m3isha')),
                ('shakhsia', models.FloatField(verbose_name='shakhsia')),
                ('ma3adin', models.FloatField(verbose_name='ma3adin')),
                ('aadoa', models.FloatField(verbose_name='aadoa')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Edarafar3ia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='edarafar3ia')),
                ('edara_3ama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.edara3ama', verbose_name='edara3ama')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=150, verbose_name='employee_name')),
                ('draja_wazifia', models.IntegerField(choices=[(-3, 'DRAJAT_TALTA_KHASA'), (-2, 'DRAJAT_TANIA_KHASA'), (-1, 'DRAJAT_AWLA_KHASA'), (1, 'DRAJAT_AWLA'), (2, 'DRAJAT_TANIA'), (3, 'DRAJAT_TALTA'), (4, 'DRAJAT_RAB3A'), (5, 'DRAJAT_KHAMSA'), (7, 'DRAJAT_SAB3A'), (8, 'DRAJAT_TAMNA'), (9, 'DRAJAT_TAS3A'), (10, 'DRAJAT_3ASHRA'), (12, 'DRAJAT_ATNASHAR'), (15, 'DRAJAT_KHAMSTASHR'), (17, 'DRAJAT_TA3AKOD')], verbose_name='draja_wazifia')),
                ('alawa_sanawia', models.IntegerField(choices=[(1, 'ALAWAT_AWALA'), (2, 'ALAWAT_TANIA'), (3, 'ALAWAT_TALTA'), (4, 'ALAWAT_RAB3A'), (5, 'ALAWAT_KHAMSA'), (7, 'ALAWAT_TA3AKOD')], verbose_name='alawa_sanawia')),
                ('tarikh_ta3in', models.DateField(verbose_name='tarikh_ta3in')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('edara_3ama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.edara3ama', verbose_name='edara_3ama')),
                ('edara_far3ia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.edarafar3ia', verbose_name='edara_far3ia')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('mosama_wazifi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.mosamawazifi', verbose_name='mosama_wazifi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
