# Generated by Django 5.0.2 on 2024-05-24 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='edara3ama',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_edara_3ama'),
        ),
        migrations.AddConstraint(
            model_name='edarafar3ia',
            constraint=models.UniqueConstraint(fields=('name', 'edara_3ama'), name='unique_edara_far3ia'),
        ),
        migrations.AddConstraint(
            model_name='employeebasic',
            constraint=models.UniqueConstraint(fields=('name', 'tarikh_ta3in'), name='unique_employee'),
        ),
        migrations.AddConstraint(
            model_name='mosamawazifi',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_mosama_wazifi'),
        ),
    ]
