# Generated by Django 5.0.2 on 2024-05-24 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_edara3ama_unique_edara_3ama_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='drajat3lawat',
            index=models.Index(fields=['draja_wazifia', 'alawa_sanawia'], name='hr_drajat3l_draja_w_c4029c_idx'),
        ),
        migrations.AddConstraint(
            model_name='drajat3lawat',
            constraint=models.UniqueConstraint(fields=('draja_wazifia', 'alawa_sanawia'), name='unique_draja_3lawa'),
        ),
    ]
