# Generated by Django 5.0.2 on 2024-05-24 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_drajat3lawat_hr_drajat3l_draja_w_c4029c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('code', models.CharField(choices=[('zaka_kafaf', 'SETTINGS_ZAKAT_KAFAF'), ('zaka_nisab', 'SETTINGS_ZAKAT_NISAB'), ('gasima', 'SETTINGS_GASIMA'), ('atfal', 'SETTINGS_ATFAL'), ('moahil', 'SETTINGS_MOAHIL'), ('sandog', 'SETTINGS_SANDOG')], max_length=15, verbose_name='code')),
                ('value', models.FloatField(verbose_name='value')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
