# Generated by Django 5.0.2 on 2024-05-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_settings_unique_setting_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebasic',
            name='atfal',
            field=models.IntegerField(default=0, verbose_name='3dad_atfal'),
        ),
        migrations.AddField(
            model_name='employeebasic',
            name='gasima',
            field=models.BooleanField(default=False, verbose_name='gasima'),
        ),
        migrations.AddField(
            model_name='employeebasic',
            name='moahil',
            field=models.CharField(choices=[('thanoi', 'MOAHIL_THANOI'), ('baklarios', 'MOAHIL_BAKLARIOS'), ('majstear', 'MOAHIL_MAJSTEAR'), ('dectora', 'MOAHIL_DECTORA')], default='baklarios', max_length=10, verbose_name='moahil'),
        ),
        migrations.AlterField(
            model_name='drajat3lawat',
            name='aadoa',
            field=models.FloatField(default=0, verbose_name='aadoa'),
        ),
        migrations.AlterField(
            model_name='drajat3lawat',
            name='abtdai',
            field=models.FloatField(default=0, verbose_name='abtdai'),
        ),
        migrations.AlterField(
            model_name='drajat3lawat',
            name='galaa_m3isha',
            field=models.FloatField(default=0, verbose_name='galaa_m3isha'),
        ),
        migrations.AlterField(
            model_name='drajat3lawat',
            name='ma3adin',
            field=models.FloatField(default=0, verbose_name='ma3adin'),
        ),
        migrations.AlterField(
            model_name='drajat3lawat',
            name='shakhsia',
            field=models.FloatField(default=0, verbose_name='shakhsia'),
        ),
    ]
