# Generated by Django 5.0.2 on 2024-05-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_employeebasic_atfal_employeebasic_gasima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebasic',
            name='moahil',
            field=models.CharField(choices=[('thanoi', 'MOAHIL_THANOI'), ('baklarios', 'MOAHIL_BAKLARIOS'), ('majstear', 'MOAHIL_MAJSTEAR'), ('dectora', 'MOAHIL_DECTORA')], default='baklarios', max_length=20, verbose_name='moahil'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='code',
            field=models.CharField(choices=[('zaka_kafaf', 'SETTINGS_ZAKAT_KAFAF'), ('zaka_nisab', 'SETTINGS_ZAKAT_NISAB'), ('gasima', 'SETTINGS_GASIMA'), ('atfal', 'SETTINGS_ATFAL'), ('sandog', 'SETTINGS_SANDOG'), ('moahil_thanoi', 'MOAHIL_THANOI'), ('moahil_baklarios', 'MOAHIL_BAKLARIOS'), ('moahil_majstear', 'MOAHIL_MAJSTEAR'), ('moahil_dectora', 'MOAHIL_DECTORA')], max_length=20, verbose_name='code'),
        ),
    ]
