# Generated by Django 5.0.2 on 2024-05-25 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_edara3ama_name_alter_edarafar3ia_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drajat3lawat',
            options={'verbose_name': 'Drajat & 3lawat', 'verbose_name_plural': 'Drajat & 3lawat'},
        ),
        migrations.AlterModelOptions(
            name='edara3ama',
            options={'verbose_name': 'Edara 3ama', 'verbose_name_plural': 'Edara 3ama'},
        ),
        migrations.AlterModelOptions(
            name='edarafar3ia',
            options={'verbose_name': 'Edara far3ia', 'verbose_name_plural': 'Edara far3ia'},
        ),
        migrations.AlterModelOptions(
            name='employeebasic',
            options={'verbose_name': 'Employee data', 'verbose_name_plural': 'Employee data'},
        ),
        migrations.AlterModelOptions(
            name='mosamawazifi',
            options={'verbose_name': 'Mosama Wazifi', 'verbose_name_plural': 'Mosama Wazifi'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'HR Setting', 'verbose_name_plural': 'HR Settings'},
        ),
        migrations.AddField(
            model_name='employeebasic',
            name='m3ash',
            field=models.FloatField(default=0, verbose_name='m3ash'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='code',
            field=models.CharField(choices=[('zaka_kafaf', 'SETTINGS_ZAKAT_KAFAF'), ('zaka_nisab', 'SETTINGS_ZAKAT_NISAB'), ('gasima', 'SETTINGS_GASIMA'), ('atfal', 'SETTINGS_ATFAL'), ('damga', 'SETTINGS_DAMGA'), ('sandog', 'SETTINGS_SANDOG'), ('moahil_thanoi', 'MOAHIL_THANOI'), ('moahil_baklarios', 'MOAHIL_BAKLARIOS'), ('moahil_majstear', 'MOAHIL_MAJSTEAR'), ('moahil_dectora', 'MOAHIL_DECTORA')], max_length=20, verbose_name='code'),
        ),
        migrations.CreateModel(
            name='PayrollMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('year', models.IntegerField(verbose_name='year')),
                ('month', models.IntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], verbose_name='month')),
                ('zaka_kafaf', models.FloatField(default=0, verbose_name='zaka_kafaf')),
                ('zaka_nisab', models.FloatField(default=0, verbose_name='zaka_nisab')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abtdai', models.FloatField(default=0, verbose_name='abtdai')),
                ('galaa_m3isha', models.FloatField(default=0, verbose_name='galaa_m3isha')),
                ('shakhsia', models.FloatField(default=0, verbose_name='shakhsia')),
                ('aadoa', models.FloatField(default=0, verbose_name='aadoa')),
                ('gasima', models.FloatField(default=0, verbose_name='gasima')),
                ('atfal', models.FloatField(default=0, verbose_name='atfal')),
                ('moahil', models.FloatField(default=0, verbose_name='moahil')),
                ('ma3adin', models.FloatField(default=0, verbose_name='ma3adin')),
                ('m3ash', models.FloatField(default=0, verbose_name='m3ash')),
                ('salafiat', models.FloatField(default=0, verbose_name='salafiat')),
                ('jazaat', models.FloatField(default=0, verbose_name='jazaat')),
                ('damga', models.FloatField(default=0, verbose_name='damga')),
                ('sandog', models.FloatField(default=0, verbose_name='sandog')),
                ('sandog_kahraba', models.FloatField(default=0, verbose_name='sandog_kahraba')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic')),
                ('payroll_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.payrollmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Jazaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('year', models.IntegerField(verbose_name='year')),
                ('month', models.IntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], verbose_name='month')),
                ('note', models.CharField(max_length=150, verbose_name='note')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('deducted', models.BooleanField(default=False, verbose_name='deducted')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Jazaat',
                'verbose_name_plural': 'Jazaat',
                'indexes': [models.Index(fields=['employee', 'year', 'month'], name='hr_jazaat_employe_7dac9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Salafiat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('year', models.IntegerField(verbose_name='year')),
                ('month', models.IntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], verbose_name='month')),
                ('note', models.CharField(max_length=150, verbose_name='note')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('deducted', models.BooleanField(default=False, verbose_name='deducted')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Salafiat',
                'verbose_name_plural': 'Salafiat',
                'indexes': [models.Index(fields=['employee', 'year', 'month'], name='hr_salafiat_employe_6fa700_idx')],
            },
        ),
    ]
