# Generated by Django 5.0.2 on 2024-05-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_drajat3lawat_options_alter_edara3ama_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jazaat',
            name='deducted',
        ),
        migrations.RemoveField(
            model_name='salafiat',
            name='deducted',
        ),
        migrations.AddField(
            model_name='jazaat',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='confirmed'),
        ),
        migrations.AddField(
            model_name='payrollmaster',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='confirmed'),
        ),
        migrations.AddField(
            model_name='salafiat',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='confirmed'),
        ),
    ]
