# Generated by Django 5.0.2 on 2024-05-25 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_remove_jazaat_deducted_remove_salafiat_deducted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payrolldetail',
            constraint=models.UniqueConstraint(fields=('payroll_master', 'employee'), name='unique_employee_payroll'),
        ),
        migrations.AddConstraint(
            model_name='payrollmaster',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='unique_payroll_year_month'),
        ),
    ]
