# Generated by Django 5.0.2 on 2024-05-25 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_payrolldetail_unique_employee_payroll_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jazaat',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'month'), name='unique_jazaat_employee_year_month'),
        ),
        migrations.AddConstraint(
            model_name='salafiat',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'month'), name='unique_salafiat_employee_year_month'),
        ),
    ]
