# Generated by Django 5.0.2 on 2024-05-25 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_jazaat_unique_jazaat_employee_year_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollmaster',
            options={'verbose_name': 'Payroll', 'verbose_name_plural': 'Payroll'},
        ),
        migrations.RemoveField(
            model_name='jazaat',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='salafiat',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='jazaat',
            name='deducted',
            field=models.BooleanField(default=False, verbose_name='deducted'),
        ),
        migrations.AddField(
            model_name='salafiat',
            name='deducted',
            field=models.BooleanField(default=False, verbose_name='deducted'),
        ),
        migrations.AlterField(
            model_name='edarafar3ia',
            name='edara_3ama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.edara3ama', verbose_name='edara_3ama'),
        ),
        migrations.AlterField(
            model_name='jazaat',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name'),
        ),
        migrations.AlterField(
            model_name='salafiat',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name'),
        ),
    ]
