# Generated by Django 5.0.2 on 2024-05-26 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_alter_payrollmaster_options_remove_jazaat_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolldetail',
            name='payroll_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.payrollmaster'),
        ),
    ]
