# Generated by Django 5.0.2 on 2024-05-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_remove_payrollmaster_zaka_kafaf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmaster',
            name='zaka_kafaf',
            field=models.FloatField(default=0, verbose_name='zaka_kafaf'),
        ),
        migrations.AddField(
            model_name='payrollmaster',
            name='zaka_nisab',
            field=models.FloatField(default=0, verbose_name='zaka_nisab'),
        ),
    ]
