# Generated by Django 5.0.2 on 2024-05-27 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_alter_salafiat_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jazaat',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=2015), django.core.validators.MaxValueValidator(limit_value=2100)], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='payrollmaster',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=2015), django.core.validators.MaxValueValidator(limit_value=2100)], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='salafiat',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=2015), django.core.validators.MaxValueValidator(limit_value=2100)], verbose_name='year'),
        ),
    ]
