# Generated by Django 5.0.2 on 2024-05-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_alter_jazaat_year_alter_payrollmaster_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebasic',
            name='code',
            field=models.CharField(default=1, max_length=10, verbose_name='employee_code'),
            preserve_default=False,
        ),
    ]
