# Generated by Django 5.0.2 on 2024-05-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_employeebasic_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebasic',
            name='code',
            field=models.IntegerField(verbose_name='employee_code'),
        ),
    ]
