# Generated by Django 5.0.2 on 2024-05-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_alter_employeebasic_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeebasic',
            options={'ordering': ['code'], 'verbose_name': 'Employee data', 'verbose_name_plural': 'Employee data'},
        ),
    ]
