# Generated by Django 5.0.2 on 2024-05-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_alter_employeebasic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edara3ama',
            options={'ordering': ['name'], 'verbose_name': 'Edara 3ama', 'verbose_name_plural': 'Edara 3ama'},
        ),
        migrations.AlterModelOptions(
            name='edarafar3ia',
            options={'ordering': ['name'], 'verbose_name': 'Edara far3ia', 'verbose_name_plural': 'Edara far3ia'},
        ),
        migrations.AlterModelOptions(
            name='jazaat',
            options={'ordering': ['-id'], 'verbose_name': 'Jazaat', 'verbose_name_plural': 'Jazaat'},
        ),
        migrations.AlterModelOptions(
            name='mosamawazifi',
            options={'ordering': ['name'], 'verbose_name': 'Mosama Wazifi', 'verbose_name_plural': 'Mosama Wazifi'},
        ),
        migrations.AlterModelOptions(
            name='payrolldetail',
            options={'ordering': ['employee__name']},
        ),
        migrations.AlterModelOptions(
            name='salafiat',
            options={'ordering': ['-id'], 'verbose_name': 'Salafiat', 'verbose_name_plural': 'Salafiat'},
        ),
    ]
