# Generated by Django 5.0.2 on 2024-05-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_alter_edara3ama_options_alter_edarafar3ia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drajat3lawat',
            options={'ordering': ['draja_wazifia', 'alawa_sanawia'], 'verbose_name': 'Drajat & 3lawat', 'verbose_name_plural': 'Drajat & 3lawat'},
        ),
    ]
