# Generated by Django 5.0.2 on 2024-05-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_alter_payrolldetail_options_employeebankaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drajat3lawat',
            name='aadoa',
        ),
        migrations.AddField(
            model_name='employeebasic',
            name='aadoa',
            field=models.BooleanField(default=False, verbose_name='gasima'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='code',
            field=models.CharField(choices=[('zaka_kafaf', 'SETTINGS_ZAKAT_KAFAF'), ('zaka_nisab', 'SETTINGS_ZAKAT_NISAB'), ('gasima', 'SETTINGS_GASIMA'), ('atfal', 'SETTINGS_ATFAL'), ('damga', 'SETTINGS_DAMGA'), ('sandog', 'SETTINGS_SANDOG'), ('aadoa', 'SETTINGS_AADOA'), ('moahil_thanoi', 'MOAHIL_THANOI'), ('moahil_baklarios', 'MOAHIL_BAKLARIOS'), ('moahil_daplom_3ali', 'MOAHIL_DAPLOM_3ALI'), ('moahil_majstear', 'MOAHIL_MAJSTEAR'), ('moahil_dectora', 'MOAHIL_DECTORA')], max_length=20, verbose_name='code'),
        ),
    ]
