# Generated by Django 5.0.2 on 2024-05-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_remove_drajat3lawat_aadoa_employeebasic_aadoa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drajat3lawat',
            options={'ordering': ['draja_wazifia', '-alawa_sanawia'], 'verbose_name': 'Drajat & 3lawat', 'verbose_name_plural': 'Drajat & 3lawat'},
        ),
        migrations.AddField(
            model_name='employeebasic',
            name='sex',
            field=models.CharField(choices=[('male', 'SEX_MALE'), ('female', 'SEX_FEMALE')], default='male', max_length=7, verbose_name='sex'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeebasic',
            name='aadoa',
            field=models.BooleanField(default=False, verbose_name='aadoa'),
        ),
    ]
