# Generated by Django 5.0.2 on 2024-05-31 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_alter_drajat3lawat_options_employeebasic_sex_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('relation', models.CharField(choices=[('parent', 'FAMILY_RELATION_PARENT'), ('child', 'FAMILY_RELATION_CHILD'), ('consort', 'FAMILY_RELATION_CONSORT')], max_length=10, verbose_name='relation')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Employee Family',
                'verbose_name_plural': 'Employee Family',
            },
        ),
        migrations.CreateModel(
            name='EmployeeMoahil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('moahil', models.CharField(choices=[('thanoi', 'MOAHIL_THANOI'), ('baklarios', 'MOAHIL_BAKLARIOS'), ('daplom_3ali', 'MOAHIL_DAPLOM_3ALI'), ('majstear', 'MOAHIL_MAJSTEAR'), ('dectora', 'MOAHIL_DECTORA')], max_length=20, verbose_name='moahil')),
                ('graduate_dt', models.DateField(verbose_name='graduate_dt')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Employee Moahil',
                'verbose_name_plural': 'Employee Moahil',
            },
        ),
    ]
