# Generated by Django 5.0.2 on 2024-05-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_employeefamily_employeemoahil'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmaster',
            name='enable_sandog_kahraba',
            field=models.BooleanField(default=False, verbose_name='enable_sandog_kahraba'),
        ),
        migrations.AddField(
            model_name='payrollmaster',
            name='enable_youm_algoat_almosalaha',
            field=models.BooleanField(default=False, verbose_name='enable_youm_algoat_almosalaha'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='code',
            field=models.CharField(choices=[('zaka_kafaf', 'SETTINGS_ZAKAT_KAFAF'), ('zaka_nisab', 'SETTINGS_ZAKAT_NISAB'), ('gasima', 'SETTINGS_GASIMA'), ('atfal', 'SETTINGS_ATFAL'), ('damga', 'SETTINGS_DAMGA'), ('sandog', 'SETTINGS_SANDOG'), ('aadoa', 'SETTINGS_AADOA'), ('enable_kahraba', 'SETTINGS_ENABLE_SANDOG_KAHRABA'), ('enable_algoat', 'SETTINGS_ENABLE_YOUM_ALGOAT_ALMOSALAHA'), ('moahil_thanoi', 'MOAHIL_THANOI'), ('moahil_baklarios', 'MOAHIL_BAKLARIOS'), ('moahil_daplom_3ali', 'MOAHIL_DAPLOM_3ALI'), ('moahil_majstear', 'MOAHIL_MAJSTEAR'), ('moahil_dectora', 'MOAHIL_DECTORA')], max_length=20, verbose_name='code'),
        ),
    ]
