# Generated by Django 5.0.2 on 2024-06-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_payrollmaster_enable_sandog_kahraba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(max_length=255, verbose_name='value'),
        ),
    ]
