# Generated by Django 5.0.2 on 2024-06-01 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_alter_settings_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebasic',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(12, '2dkhil al2sm roba3i')], verbose_name='employee_name'),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(12, '2dkhil al2sm roba3i')], verbose_name='name'),
        ),
    ]
