# Generated by Django 5.0.2 on 2024-06-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_alter_employeebasic_name_alter_employeefamily_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebasic',
            name='no3_2lertibat',
            field=models.CharField(choices=[('male', 'SEX_MALE'), ('female', 'SEX_FEMALE')], default='ta3een', max_length=10, verbose_name='no3_2lertibat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeebasic',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name='phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeebasic',
            name='sanoat_2lkhibra',
            field=models.FloatField(default=0, verbose_name='sanoat_2lkhibra'),
        ),
        migrations.AddField(
            model_name='employeebasic',
            name='tarikh_milad',
            field=models.DateField(default='1900-01-01', verbose_name='tarikh_milad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemoahil',
            name='takhasos',
            field=models.CharField(default='', max_length=100, verbose_name='takhasos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemoahil',
            name='university',
            field=models.CharField(default='', max_length=150, verbose_name='university'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeebasic',
            name='moahil',
            field=models.CharField(choices=[('thanoi', 'MOAHIL_THANOI'), ('deplom_tegani', 'MOAHIL_DEPLOM_TEGANI'), ('deplom_waseet', 'MOAHIL_DEPLOM_WASEET'), ('baklarios', 'MOAHIL_BAKLARIOS'), ('baklarios_sharaf', 'MOAHIL_BAKLARIOS_SHARAF'), ('daplom_3ali', 'MOAHIL_DAPLOM_3ALI'), ('majstear', 'MOAHIL_MAJSTEAR'), ('dectora', 'MOAHIL_DECTORA')], default='baklarios', max_length=30, verbose_name='moahil'),
        ),
        migrations.AlterField(
            model_name='employeemoahil',
            name='moahil',
            field=models.CharField(choices=[('thanoi', 'MOAHIL_THANOI'), ('deplom_tegani', 'MOAHIL_DEPLOM_TEGANI'), ('deplom_waseet', 'MOAHIL_DEPLOM_WASEET'), ('baklarios', 'MOAHIL_BAKLARIOS'), ('baklarios_sharaf', 'MOAHIL_BAKLARIOS_SHARAF'), ('daplom_3ali', 'MOAHIL_DAPLOM_3ALI'), ('majstear', 'MOAHIL_MAJSTEAR'), ('dectora', 'MOAHIL_DECTORA')], max_length=20, verbose_name='moahil'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='code',
            field=models.CharField(choices=[('zaka_kafaf', 'SETTINGS_ZAKAT_KAFAF'), ('zaka_nisab', 'SETTINGS_ZAKAT_NISAB'), ('gasima', 'SETTINGS_GASIMA'), ('atfal', 'SETTINGS_ATFAL'), ('damga', 'SETTINGS_DAMGA'), ('sandog', 'SETTINGS_SANDOG'), ('aadoa', 'SETTINGS_AADOA'), ('enable_kahraba', 'SETTINGS_ENABLE_SANDOG_KAHRABA'), ('enable_algoat', 'SETTINGS_ENABLE_YOUM_ALGOAT_ALMOSALAHA'), ('moahil_thanoi', 'MOAHIL_THANOI'), ('moahil_deplom_tegani', 'MOAHIL_DEPLOM_TEGANI'), ('moahil_deplom_waseet', 'MOAHIL_DEPLOM_WASEET'), ('moahil_baklarios', 'MOAHIL_BAKLARIOS'), ('moahil_baklarios_sharaf', 'MOAHIL_BAKLARIOS_SHARAF'), ('moahil_daplom_3ali', 'MOAHIL_DAPLOM_3ALI'), ('moahil_majstear', 'MOAHIL_MAJSTEAR'), ('moahil_dectora', 'MOAHIL_DECTORA')], max_length=30, verbose_name='code'),
        ),
    ]
