# Generated by Django 5.0.2 on 2024-06-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0031_employeebasic_no3_2lertibat_employeebasic_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebasic',
            name='no3_2lertibat',
            field=models.CharField(choices=[('ta3een', 'NO3_2LERTIBAT_TA3EEN'), ('nagl', 'NO3_2LERTIBAT_NAGL'), ('2l7ag', 'NO3_2LERTIBAT_2L7ag'), ('2ntedab', 'NO3_2LERTIBAT_2NTEDAB'), ('takleef', 'NO3_2LERTIBAT_TAKLEEF')], max_length=10, verbose_name='no3_2lertibat'),
        ),
    ]
