# Generated by Django 5.0.2 on 2024-06-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0033_alter_employeebasic_no3_2lertibat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosamawazifi',
            name='category',
            field=models.CharField(choices=[('modir_2l3am', 'CATEGORY_2LMODIR_2L3AM'), ('mosa3deen', 'CATEGORY_2LMOSA3DEEN'), ('modra2_3ameen', 'CATEGORY_MODRA2_2L2DARAT_2L3AMA'), ('modra2_far3ia', 'CATEGORY_MODRA2_2L2DARAT_2LFAR3IA'), ('ro2sa2_2gsam', 'CATEGORY_RO2SA2_2L2GSAM'), ('mozafeen', 'CATEGORY_2LMOZAFEEN'), ('3mal_sageen', 'CATEGORY_2L3MAL_SAGEEN')], default='mozafeen', max_length=20, verbose_name='category'),
            preserve_default=False,
        ),
    ]
