# Generated by Django 5.0.2 on 2024-06-02 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0034_mosamawazifi_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosamawazifi',
            name='category',
            field=models.CharField(choices=[('modir_2l3am', 'CATEGORY_2LMODIR_2L3AM'), ('mosa3deen', 'CATEGORY_2LMOSA3DEEN'), ('modra2_3ameen', 'CATEGORY_MODRA2_2L2DARAT_2L3AMA'), ('modra2_far3ia', 'CATEGORY_MODRA2_2L2DARAT_2LFAR3IA'), ('ro2sa2_2gsam', 'CATEGORY_RO2SA2_2L2GSAM'), ('mozafeen', 'CATEGORY_2LMOZAFEEN'), ('3mal_sageen', 'CATEGORY_2L3MAL_SAGEEN')], max_length=20, verbose_name='mosama_category'),
        ),
        migrations.AddIndex(
            model_name='edara3ama',
            index=models.Index(fields=['name'], name='hr_edara3am_name_7938dd_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebasic',
            index=models.Index(fields=['code'], name='hr_employee_code_f62a31_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebasic',
            index=models.Index(fields=['edara_3ama'], name='hr_employee_edara_3_455ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebasic',
            index=models.Index(fields=['draja_wazifia'], name='hr_employee_draja_w_19c91b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebasic',
            index=models.Index(fields=['alawa_sanawia'], name='hr_employee_alawa_s_e26a31_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebasic',
            index=models.Index(fields=['tarikh_milad'], name='hr_employee_tarikh__a1d596_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebasic',
            index=models.Index(fields=['tarikh_ta3in'], name='hr_employee_tarikh__26d938_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebasic',
            index=models.Index(fields=['sex'], name='hr_employee_sex_1e0418_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebasic',
            index=models.Index(fields=['no3_2lertibat'], name='hr_employee_no3_2le_cef6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebasic',
            index=models.Index(fields=['moahil'], name='hr_employee_moahil_826a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebasic',
            index=models.Index(fields=['aadoa'], name='hr_employee_aadoa_400719_idx'),
        ),
        migrations.AddIndex(
            model_name='mosamawazifi',
            index=models.Index(fields=['category'], name='hr_mosamawa_categor_990dc8_idx'),
        ),
    ]
