# Generated by Django 5.0.2 on 2024-06-02 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0035_alter_mosamawazifi_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='settings',
            index=models.Index(fields=['code'], name='hr_settings_code_f303aa_idx'),
        ),
    ]
