# Generated by Django 5.0.2 on 2024-06-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0036_settings_hr_settings_code_f303aa_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='code',
            field=models.CharField(choices=[('zaka_kafaf', 'SETTINGS_ZAKAT_KAFAF'), ('zaka_nisab', 'SETTINGS_ZAKAT_NISAB'), ('gasima', 'SETTINGS_GASIMA'), ('atfal', 'SETTINGS_ATFAL'), ('damga', 'SETTINGS_DAMGA'), ('sandog', 'SETTINGS_SANDOG'), ('aadoa', 'SETTINGS_AADOA'), ('enable_kahraba', 'SETTINGS_ENABLE_SANDOG_KAHRABA'), ('enable_algoat', 'SETTINGS_ENABLE_YOUM_ALGOAT_ALMOSALAHA'), ('moahil_thanoi', 'MOAHIL_THANOI'), ('moahil_deplom_tegani', 'MOAHIL_DEPLOM_TEGANI'), ('moahil_deplom_waseet', 'MOAHIL_DEPLOM_WASEET'), ('moahil_baklarios', 'MOAHIL_BAKLARIOS'), ('moahil_baklarios_sharaf', 'MOAHIL_BAKLARIOS_SHARAF'), ('moahil_daplom_3ali', 'MOAHIL_DAPLOM_3ALI'), ('moahil_majstear', 'MOAHIL_MAJSTEAR'), ('moahil_dectora', 'MOAHIL_DECTORA'), ('mosama_modir_2l3am', '2sti7gag 2lmobashara المدير العام'), ('mosama_mosa3deen', '2sti7gag 2lmobashara مساعدي المدير العام'), ('mosama_modra2_3ameen', '2sti7gag 2lmobashara مدراء الادارات العامة'), ('mosama_modra2_far3ia', '2sti7gag 2lmobashara مدراء الادارات الفرعية'), ('mosama_ro2sa2_2gsam', '2sti7gag 2lmobashara رؤساء الاقسام'), ('mosama_mozafeen', '2sti7gag 2lmobashara الموظفين'), ('mosama_3mal_sageen', '2sti7gag 2lmobashara العمال والسائقين')], max_length=30, verbose_name='code'),
        ),
    ]
