# Generated by Django 5.0.2 on 2024-06-03 09:04

import django.core.validators
import django.db.models.deletion
import hr.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0037_alter_settings_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='code',
            field=models.CharField(choices=[('zaka_kafaf', 'SETTINGS_ZAKAT_KAFAF'), ('zaka_nisab', 'SETTINGS_ZAKAT_NISAB'), ('gasima', 'SETTINGS_GASIMA'), ('atfal', 'SETTINGS_ATFAL'), ('damga', 'SETTINGS_DAMGA'), ('sandog', 'SETTINGS_SANDOG'), ('aadoa', 'SETTINGS_AADOA'), ('enable_kahraba', 'SETTINGS_ENABLE_SANDOG_KAHRABA'), ('enable_algoat', 'SETTINGS_ENABLE_YOUM_ALGOAT_ALMOSALAHA'), ('moahil_thanoi', 'المؤهل دون الجامعي'), ('moahil_deplom_tegani', 'المؤهل دبلوم تقني'), ('moahil_deplom_waseet', 'المؤهل دبلوم وسيط'), ('moahil_baklarios', 'المؤهل بكلاريوس عام'), ('moahil_baklarios_sharaf', 'المؤهل بكلاريوس شرف'), ('moahil_daplom_3ali', 'المؤهل دبلوم عالي'), ('moahil_majstear', 'المؤهل ماجستير'), ('moahil_dectora', 'المؤهل دكتورة'), ('mosama_modir_2l3am', 'استحقاق مباشرة المدير العام'), ('mosama_mosa3deen', 'استحقاق مباشرة مساعدي المدير العام'), ('mosama_modra2_3ameen', 'استحقاق مباشرة مدراء الادارات العامة'), ('mosama_modra2_far3ia', 'استحقاق مباشرة مدراء الادارات الفرعية'), ('mosama_ro2sa2_2gsam', 'استحقاق مباشرة رؤساء الاقسام'), ('mosama_mozafeen', 'استحقاق مباشرة الموظفين'), ('mosama_3mal_sageen', 'استحقاق مباشرة العمال والسائقين')], max_length=30, verbose_name='code'),
        ),
        migrations.CreateModel(
            name='EmployeeMobashraMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=2015), django.core.validators.MaxValueValidator(limit_value=2100)], verbose_name='year')),
                ('month', models.IntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], verbose_name='month')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('note', models.CharField(blank=True, max_length=150, verbose_name='note')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('vacation_type', models.CharField(choices=[('sanawia', 'VACATION_SANAWIA'), ('3ardah', 'VACATION_3ARDAH'), ('maradiah', 'VACATION_MARADIAH')], max_length=30, verbose_name='vacation_type')),
                ('start_dt', models.DateField(verbose_name='start_dt')),
                ('end_dt_excpected', models.DateField(verbose_name='end_dt_excpected')),
                ('end_dt_actual', models.DateField(blank=True, validators=[hr.models.validate_not_in_future_dt], verbose_name='end_dt_actual')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('mokalaf', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='mokalafvacation_set', to='hr.employeebasic', verbose_name='mokalaf_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Vacation',
                'verbose_name_plural': 'Vacation',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeMobashra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('start_dt', models.DateField(verbose_name='start_dt')),
                ('end_dt', models.DateField(blank=True, verbose_name='end_dt')),
                ('state', models.CharField(choices=[('active', 'STATE_ACTIVE'), ('vaction', 'STATE_VACATION'), ('in_active', 'STATE_INACTIVE')], max_length=10, verbose_name='state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Mobashra',
                'verbose_name_plural': 'Mobashra',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['employee', 'state'], name='hr_employee_employe_06d2de_idx'), models.Index(fields=['state'], name='hr_employee_state_7aebf4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='employeemobashramonthly',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'month'), name='unique_mobashraemployee_year_month'),
        ),
        migrations.AddIndex(
            model_name='employeevacation',
            index=models.Index(fields=['employee', 'vacation_type'], name='hr_employee_employe_f47011_idx'),
        ),
        migrations.AddIndex(
            model_name='employeevacation',
            index=models.Index(fields=['vacation_type'], name='hr_employee_vacatio_ad8fa8_idx'),
        ),
    ]
