# Generated by Django 5.0.2 on 2024-06-03 16:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0038_alter_settings_code_employeemobashramonthly_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jazaat',
            new_name='Employee2ijazaat',
        ),
        migrations.RenameIndex(
            model_name='employee2ijazaat',
            new_name='hr_employee_employe_f714cf_idx',
            old_name='hr_jazaat_employe_7dac9c_idx',
        ),
    ]
