# Generated by Django 5.0.2 on 2024-06-03 16:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0039_rename_jazaat_employee2ijazaat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salafiat',
            new_name='EmployeeSalafiat',
        ),
        migrations.RenameIndex(
            model_name='employeesalafiat',
            new_name='hr_employee_employe_f1122e_idx',
            old_name='hr_salafiat_employe_6fa700_idx',
        ),
    ]
