# Generated by Django 5.0.2 on 2024-06-03 16:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0040_rename_salafiat_employeesalafiat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee2ijazaat',
            new_name='EmployeeJazaat',
        ),
        migrations.RenameIndex(
            model_name='employeejazaat',
            new_name='hr_employee_employe_3eea17_idx',
            old_name='hr_employee_employe_f714cf_idx',
        ),
    ]
