# Generated by Django 5.0.2 on 2024-06-03 17:06

import django.db.models.deletion
import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0041_rename_employee2ijazaat_employeejazaat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevacation',
            name='end_dt_actual',
            field=models.DateField(blank=True, null=True, validators=[hr.models.validate_not_in_future_dt], verbose_name='end_dt_actual'),
        ),
        migrations.AlterField(
            model_name='employeevacation',
            name='mokalaf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mokalafvacation_set', to='hr.employeebasic', verbose_name='mokalaf_name'),
        ),
    ]
