# Generated by Django 5.0.2 on 2024-06-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0042_alter_employeevacation_end_dt_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemobashra',
            name='end_dt',
            field=models.DateField(blank=True, null=True, verbose_name='end_dt'),
        ),
    ]
