# Generated by Django 5.0.2 on 2024-06-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0043_alter_employeemobashra_end_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemobashramonthly',
            name='no_days',
            field=models.IntegerField(default=0, verbose_name='no_days'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeemobashra',
            name='state',
            field=models.CharField(choices=[('active', 'STATE_ACTIVE'), ('in_active', 'STATE_INACTIVE')], max_length=10, verbose_name='mobashara state'),
        ),
    ]
