# Generated by Django 5.0.2 on 2024-06-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0045_employeemobashramonthly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemobashramonthly',
            name='no_days',
        ),
        migrations.RemoveField(
            model_name='employeemobashramonthly',
            name='note',
        ),
        migrations.AddField(
            model_name='employeemobashramonthly',
            name='no_days_2jazaa',
            field=models.IntegerField(default=0, verbose_name='no_days_2jazaa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemobashramonthly',
            name='no_days_mobashara',
            field=models.IntegerField(default=0, verbose_name='no_days_mobashara'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemobashramonthly',
            name='no_days_month',
            field=models.IntegerField(default=0, verbose_name='no_days_month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemobashramonthly',
            name='no_days_taklif',
            field=models.IntegerField(default=0, verbose_name='no_days_taklif'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeemobashra',
            name='state',
            field=models.CharField(choices=[('active', 'STATE_ACTIVE'), ('in_active', 'STATE_INACTIVE')], default='active', max_length=10, verbose_name='mobashara state'),
        ),
        migrations.AlterField(
            model_name='employeevacation',
            name='vacation_type',
            field=models.CharField(choices=[('sanawia', 'VACATION_SANAWIA'), ('3ardah', 'VACATION_3ARDAH'), ('maradiah', 'VACATION_MARADIAH'), ('29abat_3mal', 'VACATION_29ABAT_3MAL'), ('wdo3', 'VACATION_WDO3'), ('omoma', 'VACATION_OMOMA'), ('3da', 'VACATION_3DA'), ('morafagat_marid', 'VACATION_MORAFAGAT_MARID'), ('min7_drasia', 'VACATION_MIN7_DRASIA'), ('zoaj', 'VACATION_ZOAJ'), ('7aj', 'VACATION_7AJ'), ('omra', 'VACATION_OMRA'), ('youm_97i', 'VACATION_YOUM_97I'), ('zarf_kahir', 'VACATION_ZARF_KAHIR'), ('bdon_moratab', 'VACATION_BDON_MORATAB'), ('wafah', 'VACATION_WAFAH')], max_length=30, verbose_name='vacation_type'),
        ),
    ]
