# Generated by Django 5.0.2 on 2024-06-04 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0046_remove_employeemobashramonthly_no_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmaster',
            name='daribat_2lmokafa',
            field=models.FloatField(default=0, verbose_name='daribat_2lmokafa'),
        ),
        migrations.AddIndex(
            model_name='employeejazaat',
            index=models.Index(fields=['year', 'month'], name='hr_employee_year_6c18c8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemobashramonthly',
            index=models.Index(fields=['year', 'month'], name='hr_employee_year_964e04_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemobashramonthly',
            index=models.Index(fields=['employee', 'year', 'month'], name='hr_employee_employe_712da2_idx'),
        ),
    ]
