# Generated by Django 5.0.2 on 2024-06-04 12:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0048_alter_settings_code_employeem2moria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeM2moriaMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=2015), django.core.validators.MaxValueValidator(limit_value=2100)], verbose_name='year')),
                ('month', models.IntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], verbose_name='month')),
                ('ajmali_2lmoratab', models.FloatField(verbose_name='amount')),
                ('no_days', models.IntegerField(verbose_name='no_days')),
                ('damga', models.FloatField(verbose_name='damga')),
                ('safi_2l2sti7gag', models.FloatField(verbose_name='safi_2l2sti7gag')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'month'], name='hr_employee_year_919a3a_idx'), models.Index(fields=['employee', 'year', 'month'], name='hr_employee_employe_86deeb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='employeem2moriamonthly',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'month'), name='unique_m2moriaemployee_year_month'),
        ),
    ]
