# Generated by Django 5.0.2 on 2024-06-07 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0049_employeem2moriamonthly_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payrollmaster',
            index=models.Index(fields=['year', 'month'], name='hr_payrollm_year_bff8fc_idx'),
        ),
    ]
