# Generated by Django 5.0.2 on 2024-08-06 11:19

import django.db.models.deletion
import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0050_payrollmaster_hr_payrollm_year_bff8fc_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebasic',
            name='tarikh_akhir_targia',
            field=models.DateField(blank=True, null=True, verbose_name='tarikh_akhir_targia'),
        ),
        migrations.AddField(
            model_name='employeefamily',
            name='attachement_file',
            field=models.FileField(blank=True, null=True, upload_to=hr.models.attachement_path, verbose_name='attachement'),
        ),
        migrations.AddField(
            model_name='employeejazaat',
            name='attachement_file',
            field=models.FileField(blank=True, null=True, upload_to=hr.models.attachement_path, verbose_name='attachement'),
        ),
        migrations.AddField(
            model_name='employeem2moria',
            name='attachement_file',
            field=models.FileField(blank=True, null=True, upload_to=hr.models.attachement_path, verbose_name='attachement'),
        ),
        migrations.AddField(
            model_name='employeemoahil',
            name='attachement_file',
            field=models.FileField(blank=True, null=True, upload_to=hr.models.attachement_path, verbose_name='attachement'),
        ),
        migrations.AddField(
            model_name='employeevacation',
            name='attachement_file',
            field=models.FileField(blank=True, null=True, upload_to=hr.models.attachement_path, verbose_name='attachement'),
        ),
        migrations.CreateModel(
            name='Gisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='gisim')),
                ('edara_far3ia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.edarafar3ia', verbose_name='edara_far3ia')),
            ],
            options={
                'verbose_name': 'Gisim',
                'verbose_name_plural': 'Gisim',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employeebasic',
            name='gisim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.gisim', verbose_name='gisim'),
        ),
        migrations.CreateModel(
            name='Wi7da',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Wi7da')),
                ('gisim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.gisim', verbose_name='gisim')),
            ],
            options={
                'verbose_name': 'Wi7da',
                'verbose_name_plural': 'Wi7da',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employeebasic',
            name='wi7da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.wi7da', verbose_name='wi7da'),
        ),
    ]
