# Generated by Django 5.0.2 on 2024-08-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0051_employeebasic_tarikh_akhir_targia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edara3ama',
            name='tab3ia_edaria',
            field=models.IntegerField(choices=[(1, 'TAB3IA_EDARIA_MODIR3AM'), (2, 'TAB3IA_EDARIA_FANI'), (3, 'TAB3IA_EDARIA_MALI')], default=1, verbose_name='tab3ia_edaria'),
        ),
    ]
