# Generated by Django 5.0.2 on 2024-08-11 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0055_employeefamily_tarikh_el2dafa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefamily',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4, '2dkhil al2sm roba3i')], verbose_name='name'),
        ),
    ]
