# Generated by Django 5.0.2 on 2024-08-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0056_alter_employeefamily_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebasic',
            name='status',
            field=models.IntegerField(choices=[(1, 'STATUS_ACTIVE'), (2, 'STATUS_MA3ASH'), (3, 'STATUS_TAGA3D_EKHTIARI'), (4, 'STATUS_ESTIKALA'), (5, 'STATUS_3DAM_ELIAGA_ELTIBIA'), (6, 'STATUS_ELFASL'), (7, 'STATUS_ENTIHA2_2L3AGD'), (8, 'STATUS_SHAGL_MANSAB_DASTORY'), (9, 'STATUS_ELWAFAH'), (10, 'STATUS_FOGDAN_ELJENSIA_ELSODANIA')], default=1, verbose_name='status'),
        ),
    ]
