# Generated by Django 5.0.2 on 2024-08-12 09:16

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0057_employeebasic_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikalWazifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hr.hikalwazifi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employeebasic',
            name='hikal_wazifi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.hikalwazifi', verbose_name='hikal_wazifi'),
        ),
    ]
