# Generated by Django 5.0.2 on 2024-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0058_hikalwazifi_employeebasic_hikal_wazifi'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikalwazifi',
            name='elmostoa_eltanzimi',
            field=models.IntegerField(choices=[(1, 'ELMOSTOA_ELTANZIMI_MODIR_3AM'), (2, 'ELMOSTOA_ELTANZIMI_MOSA3ID_MODIR_3AM'), (3, 'ELMOSTOA_ELTANZIMI_2DARA_3AMA'), (4, 'ELMOSTOA_ELTANZIMI_2DARA_FAR3IA'), (5, 'ELMOSTOA_ELTANZIMI_GISIM'), (6, 'ELMOSTOA_ELTANZIMI_WI7DA')], default=6, verbose_name='elmostoa_eltanzimi'),
        ),
    ]
