# Generated by Django 5.0.2 on 2024-08-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0059_hikalwazifi_elmostoa_eltanzimi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hikalwazifi',
            options={'verbose_name': 'HikalWazifi', 'verbose_name_plural': 'HikalWazifi'},
        ),
        migrations.RemoveIndex(
            model_name='employeebasic',
            name='hr_employee_edara_3_455ab2_idx',
        ),
        migrations.RenameField(
            model_name='employeebasic',
            old_name='edara_3ama',
            new_name='edara_3ama_tmp',
        ),
        migrations.RenameField(
            model_name='employeebasic',
            old_name='edara_far3ia',
            new_name='edara_far3ia_tmp',
        ),
        migrations.RenameField(
            model_name='employeebasic',
            old_name='gisim',
            new_name='gisim_tmp',
        ),
        migrations.RenameField(
            model_name='employeebasic',
            old_name='wi7da',
            new_name='wi7da_tmp',
        ),
    ]
