# Generated by Django 5.0.2 on 2024-08-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0060_alter_hikalwazifi_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebasic',
            name='gisim_tmp',
        ),
        migrations.RemoveField(
            model_name='employeebasic',
            name='wi7da_tmp',
        ),
    ]
