# Generated by Django 5.0.2 on 2024-08-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0061_remove_employeebasic_gisim_tmp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikalwazifi',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
