# Generated by Django 5.0.2 on 2024-08-13 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0062_alter_hikalwazifi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='edarafar3ia',
            name='hikal_wazifi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.hikalwazifi', verbose_name='hikal_wazifi'),
        ),
    ]
