# Generated by Django 5.0.2 on 2024-08-13 06:52

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0063_edarafar3ia_hikal_wazifi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edarafar3ia',
            name='hikal_wazifi',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.hikalwazifi', verbose_name='hikal_wazifi'),
        ),
        migrations.AlterField(
            model_name='employeebasic',
            name='hikal_wazifi',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.hikalwazifi', verbose_name='hikal_wazifi'),
        ),
    ]
