# Generated by Django 5.0.2 on 2024-08-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0064_alter_edarafar3ia_hikal_wazifi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebasic',
            name='edara_3ama_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.edara3ama', verbose_name='edara_3ama'),
        ),
        migrations.AlterField(
            model_name='employeebasic',
            name='edara_far3ia_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.edarafar3ia', verbose_name='edara_far3ia'),
        ),
    ]
