# Generated by Django 5.0.2 on 2024-08-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0065_alter_employeebasic_edara_3ama_tmp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldetail',
            name='tarikh_milad',
            field=models.DateField(blank=True, null=True, verbose_name='tarikh_milad'),
        ),
        migrations.AddField(
            model_name='payrollmaster',
            name='m3ash_age',
            field=models.FloatField(default=0, verbose_name='m3ash_age'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='code',
            field=models.CharField(choices=[('zaka_kafaf', 'SETTINGS_ZAKAT_KAFAF'), ('zaka_nisab', 'SETTINGS_ZAKAT_NISAB'), ('gasima', 'SETTINGS_GASIMA'), ('atfal', 'SETTINGS_ATFAL'), ('damga', 'SETTINGS_DAMGA'), ('sandog', 'SETTINGS_SANDOG'), ('aadoa', 'SETTINGS_AADOA'), ('daribat_2lmokafa', 'SETTINGS_DARIBAT_2LMOKAFA'), ('enable_kahraba', 'SETTINGS_ENABLE_SANDOG_KAHRABA'), ('enable_algoat', 'SETTINGS_ENABLE_YOUM_ALGOAT_ALMOSALAHA'), ('m2moria_rate', 'SETTINGS_M2MORIA_RATE'), ('e3asha_rate', 'SETTINGS_E3ASHA_RATE'), ('kharj_elsharika', 'SETTINGS_KHARJ_ELSHARIKA'), ('omer_2lma3ash', 'SETTINGS_OMER_2LMA3ASH'), ('moahil_thanoi', 'المؤهل دون الجامعي'), ('moahil_deplom_tegani', 'المؤهل دبلوم تقني'), ('moahil_deplom_waseet', 'المؤهل دبلوم وسيط'), ('moahil_baklarios', 'المؤهل بكلاريوس عام'), ('moahil_baklarios_sharaf', 'المؤهل بكلاريوس شرف'), ('moahil_daplom_3ali', 'المؤهل دبلوم عالي'), ('moahil_majstear', 'المؤهل ماجستير'), ('moahil_dectora', 'المؤهل دكتورة'), ('mosama_modir_2l3am', 'استحقاق مباشرة المدير العام'), ('mosama_mosa3deen', 'استحقاق مباشرة مساعدي المدير العام'), ('mosama_modra2_3ameen', 'استحقاق مباشرة مدراء الادارات العامة'), ('mosama_modra2_far3ia', 'استحقاق مباشرة مدراء الادارات الفرعية'), ('mosama_ro2sa2_2gsam', 'استحقاق مباشرة رؤساء الاقسام'), ('mosama_mozafeen', 'استحقاق مباشرة الموظفين'), ('mosama_3mal_sageen', 'استحقاق مباشرة العمال والسائقين')], max_length=30, verbose_name='code'),
        ),
    ]
