# Generated by Django 5.0.2 on 2024-08-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0066_payrolldetail_tarikh_milad_payrollmaster_m3ash_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalafiat',
            name='no3_2lsalafia',
            field=models.IntegerField(choices=[(1, 'NO3_2LSALAFIA_SHARIKA'), (2, 'NO3_2LSALAFIA_SANDOG')], default=1, verbose_name='no3_2lsalafia'),
        ),
    ]
