# Generated by Django 5.0.2 on 2024-08-15 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0068_payrolldetail_salafiat_sandog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeesalafiat',
            name='unique_salafiat_employee_year_month',
        ),
        migrations.AddConstraint(
            model_name='employeesalafiat',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'month', 'no3_2lsalafia'), name='unique_salafiat_employee_year_month'),
        ),
    ]
