# Generated by Django 5.0.2 on 2024-08-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0070_alter_payrolldetail_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrolldetail',
            old_name='khasm_elsandog_min_elomoratab',
            new_name='khasm_salafiat_elsandog_min_elomoratab',
        ),
    ]
