# Generated by Django 5.0.2 on 2024-08-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0071_rename_khasm_elsandog_min_elomoratab_payrolldetail_khasm_salafiat_elsandog_min_elomoratab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrolldetail',
            name='khasm_salafiat_elsandog_min_elomoratab',
        ),
        migrations.AddField(
            model_name='payrollmaster',
            name='khasm_salafiat_elsandog_min_elomoratab',
            field=models.BooleanField(default=False, verbose_name='khasm_elsandog_min_elomoratab'),
        ),
    ]
