# Generated by Django 5.0.2 on 2024-08-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0072_remove_payrolldetail_khasm_salafiat_elsandog_min_elomoratab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldetail',
            name='alawa_sanawia',
            field=models.IntegerField(blank=True, choices=[(1, 'ALAWAT_AWALA'), (2, 'ALAWAT_TANIA'), (3, 'ALAWAT_TALTA'), (4, 'ALAWAT_RAB3A'), (5, 'ALAWAT_KHAMSA'), (7, 'ALAWAT_TA3AKOD')], null=True, verbose_name='alawa_sanawia'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='draja_wazifia',
            field=models.IntegerField(blank=True, choices=[(-3, 'DRAJAT_TALTA_KHASA'), (-2, 'DRAJAT_TANIA_KHASA'), (-1, 'DRAJAT_AWLA_KHASA'), (1, 'DRAJAT_AWLA'), (2, 'DRAJAT_TANIA'), (3, 'DRAJAT_TALTA'), (4, 'DRAJAT_RAB3A'), (5, 'DRAJAT_KHAMSA'), (7, 'DRAJAT_SAB3A'), (8, 'DRAJAT_TAMNA'), (9, 'DRAJAT_TAS3A'), (10, 'DRAJAT_3ASHRA'), (12, 'DRAJAT_ATNASHAR'), (15, 'DRAJAT_KHAMSTASHR'), (17, 'DRAJAT_TA3AKOD')], null=True, verbose_name='draja_wazifia'),
        ),
    ]
