# Generated by Django 5.0.2 on 2024-09-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0073_payrolldetail_alawa_sanawia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalafiat',
            name='no3_2lsalafia',
            field=models.IntegerField(choices=[(1, 'NO3_2LSALAFIA_SHARIKA'), (2, 'NO3_2LSALAFIA_SANDOG')], default=2, verbose_name='no3_2lsalafia'),
        ),
    ]
