# Generated by Django 5.0.2 on 2024-09-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0074_alter_employeesalafiat_no3_2lsalafia'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldetail',
            name='account_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='account_no'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='bank',
            field=models.CharField(blank=True, choices=[('bok', 'BANK_KHARTOUM'), ('onb', 'BANK_OMDURMAN')], max_length=10, null=True, verbose_name='bank'),
        ),
    ]
