# Generated by Django 5.0.2 on 2024-09-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0075_payrolldetail_account_no_payrolldetail_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldetail',
            name='salafiat_3la_2lmokaf2',
            field=models.FloatField(default=0, verbose_name='salafiat_3la_2lmokaf2'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='salafiat_3la_2lmoratab',
            field=models.FloatField(default=0, verbose_name='salafiat_3la_2lmoratab'),
        ),
        migrations.AlterField(
            model_name='employeesalafiat',
            name='no3_2lsalafia',
            field=models.IntegerField(choices=[(1, 'NO3_2LSALAFIA_SHARIKA'), (2, 'NO3_2LSALAFIA_SANDOG'), (3, 'NO3_2LSALAFIA_3LA_2LMORATAB'), (4, 'NO3_2LSALAFIA_3LA_2LMOKAF2')], default=2, verbose_name='no3_2lsalafia'),
        ),
    ]
