# Generated by Django 5.0.2 on 2024-09-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0076_payrolldetail_salafiat_3la_2lmokaf2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeesalafiat',
            options={'ordering': ['year', 'month'], 'verbose_name': 'Salafiat', 'verbose_name_plural': 'Salafiat'},
        ),
    ]
