# Generated by Django 5.0.2 on 2024-09-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0077_alter_employeesalafiat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeesalafiat',
            options={'ordering': ['year', 'month', 'no3_2lsalafia'], 'verbose_name': 'Salafiat', 'verbose_name_plural': 'Salafiat'},
        ),
    ]
