# Generated by Django 5.0.2 on 2024-10-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0078_alter_employeesalafiat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebasic',
            name='no3_2lertibat',
            field=models.CharField(choices=[('ta3een', 'NO3_2LERTIBAT_TA3EEN'), ('nagl', 'NO3_2LERTIBAT_NAGL'), ('2ntedab', 'NO3_2LERTIBAT_2NTEDAB'), ('takleef', 'NO3_2LERTIBAT_TAKLEEF'), ('2l7ag', 'NO3_2LERTIBAT_2L7ag'), ('ta3agod_mosimi', 'NO3_2LERTIBAT_TA3AGOD'), ('mashro3', 'NO3_2LERTIBAT_MASHRO3')], max_length=15, verbose_name='no3_2lertibat'),
        ),
    ]
