# Generated by Django 5.0.2 on 2024-10-23 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0079_alter_employeebasic_no3_2lertibat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebasic',
            name='no3_2lertibat',
            field=models.CharField(choices=[('ta3een', 'NO3_2LERTIBAT_TA3EEN'), ('nagl', 'NO3_2LERTIBAT_NAGL'), ('2ntedab', 'NO3_2LERTIBAT_2NTEDAB'), ('takleef', 'NO3_2LERTIBAT_TAKLEEF'), ('2l7ag', 'NO3_2LERTIBAT_2L7ag'), ('ta3agod_mosimi', 'NO3_2LERTIBAT_TA3AGOD'), ('ta3agod', 'NO3_2LERTIBAT_TA3AGOD_MOSIMI'), ('mashro3', 'NO3_2LERTIBAT_MASHRO3')], max_length=15, verbose_name='no3_2lertibat'),
        ),
        migrations.CreateModel(
            name='EmployeeWi7datMosa3da',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('has_diff', models.BooleanField(default=False, verbose_name='has_diff')),
                ('payroll_2ljiha_2l2om', models.FloatField(verbose_name='payroll_2ljiha_2l2om')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wi7dat_mosa3da', to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': '2lwi7dat 2lmosa3da',
                'verbose_name_plural': '2lwi7dat 2lmosa3da',
            },
        ),
    ]
