# Generated by Django 5.0.2 on 2024-10-23 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0080_alter_employeebasic_no3_2lertibat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollDetailWi7datMosa3ida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salafiat', models.FloatField(default=0, verbose_name='salafiat')),
                ('jazaat', models.FloatField(default=0, verbose_name='jazaat')),
                ('damga', models.FloatField(default=0, verbose_name='damga')),
                ('sandog', models.FloatField(default=0, verbose_name='sandog')),
                ('sandog_kahraba', models.FloatField(default=0, verbose_name='sandog_kahraba')),
                ('tarikh_milad', models.DateField(blank=True, null=True, verbose_name='tarikh_milad')),
                ('salafiat_sandog', models.FloatField(default=0, verbose_name='salafiat_sandog')),
                ('salafiat_3la_2lmoratab', models.FloatField(default=0, verbose_name='salafiat_3la_2lmoratab')),
                ('salafiat_3la_2lmokaf2', models.FloatField(default=0, verbose_name='salafiat_3la_2lmokaf2')),
                ('draja_wazifia', models.IntegerField(blank=True, choices=[(-3, 'DRAJAT_TALTA_KHASA'), (-2, 'DRAJAT_TANIA_KHASA'), (-1, 'DRAJAT_AWLA_KHASA'), (1, 'DRAJAT_AWLA'), (2, 'DRAJAT_TANIA'), (3, 'DRAJAT_TALTA'), (4, 'DRAJAT_RAB3A'), (5, 'DRAJAT_KHAMSA'), (7, 'DRAJAT_SAB3A'), (8, 'DRAJAT_TAMNA'), (9, 'DRAJAT_TAS3A'), (10, 'DRAJAT_3ASHRA'), (12, 'DRAJAT_ATNASHAR'), (15, 'DRAJAT_KHAMSTASHR'), (17, 'DRAJAT_TA3AKOD')], null=True, verbose_name='draja_wazifia')),
                ('alawa_sanawia', models.IntegerField(blank=True, choices=[(1, 'ALAWAT_AWALA'), (2, 'ALAWAT_TANIA'), (3, 'ALAWAT_TALTA'), (4, 'ALAWAT_RAB3A'), (5, 'ALAWAT_KHAMSA'), (7, 'ALAWAT_TA3AKOD')], null=True, verbose_name='alawa_sanawia')),
                ('bank', models.CharField(blank=True, choices=[('bok', 'BANK_KHARTOUM'), ('onb', 'BANK_OMDURMAN')], max_length=10, null=True, verbose_name='bank')),
                ('account_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='account_no')),
                ('payroll_2ljiha_2l2om', models.FloatField(default=0, verbose_name='payroll_2ljiha_2l2om')),
                ('payroll_2lsharika', models.FloatField(default=0, verbose_name='payroll_2lsharika')),
                ('has_diff', models.BooleanField(default=False, verbose_name='has_diff')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('payroll_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.payrollmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
