# Generated by Django 5.0.2 on 2024-10-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0081_payrolldetailwi7datmosa3ida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrolldetail',
            options={'verbose_name': 'Payroll detail', 'verbose_name_plural': 'Payroll details'},
        ),
        migrations.AlterModelOptions(
            name='payrolldetailwi7datmosa3ida',
            options={'ordering': ['employee__code']},
        ),
        migrations.RemoveConstraint(
            model_name='payrolldetail',
            name='unique_employee_payroll',
        ),
        migrations.AddConstraint(
            model_name='payrolldetailwi7datmosa3ida',
            constraint=models.UniqueConstraint(fields=('payroll_master', 'employee'), name='unique_employee_payroll'),
        ),
    ]
