# Generated by Django 5.0.2 on 2024-10-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0083_alter_payrolldetail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrolldetailwi7datmosa3ida',
            options={'ordering': ['employee__code'], 'verbose_name': 'Payroll detail (wi7dat mosa3da)', 'verbose_name_plural': 'Payroll details (wi7dat mosa3da)'},
        ),
        migrations.AddField(
            model_name='payrolldetailwi7datmosa3ida',
            name='abtdai',
            field=models.FloatField(default=0, verbose_name='abtdai'),
        ),
        migrations.AddField(
            model_name='payrolldetailwi7datmosa3ida',
            name='galaa_m3isha',
            field=models.FloatField(default=0, verbose_name='galaa_m3isha'),
        ),
        migrations.AddField(
            model_name='payrolldetailwi7datmosa3ida',
            name='ma3adin',
            field=models.FloatField(default=0, verbose_name='ma3adin'),
        ),
        migrations.AddField(
            model_name='payrolldetailwi7datmosa3ida',
            name='shakhsia',
            field=models.FloatField(default=0, verbose_name='shakhsia'),
        ),
        migrations.AddConstraint(
            model_name='payrolldetailwi7datmosa3ida',
            constraint=models.UniqueConstraint(fields=('payroll_master', 'employee'), name='unique_employee_payroll_wi7dat_mosa3da'),
        ),
    ]
