# Generated by Django 5.0.2 on 2024-10-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0084_alter_payrolldetailwi7datmosa3ida_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollDetailTa3agodMosimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abtdai', models.FloatField(default=0, verbose_name='abtdai')),
                ('galaa_m3isha', models.FloatField(default=0, verbose_name='galaa_m3isha')),
                ('shakhsia', models.FloatField(default=0, verbose_name='shakhsia')),
                ('ma3adin', models.FloatField(default=0, verbose_name='ma3adin')),
                ('salafiat', models.FloatField(default=0, verbose_name='salafiat')),
                ('jazaat', models.FloatField(default=0, verbose_name='jazaat')),
                ('damga', models.FloatField(default=0, verbose_name='damga')),
                ('sandog', models.FloatField(default=0, verbose_name='sandog')),
                ('sandog_kahraba', models.FloatField(default=0, verbose_name='sandog_kahraba')),
                ('tarikh_milad', models.DateField(blank=True, null=True, verbose_name='tarikh_milad')),
                ('salafiat_sandog', models.FloatField(default=0, verbose_name='salafiat_sandog')),
                ('salafiat_3la_2lmoratab', models.FloatField(default=0, verbose_name='salafiat_3la_2lmoratab')),
                ('salafiat_3la_2lmokaf2', models.FloatField(default=0, verbose_name='salafiat_3la_2lmokaf2')),
                ('draja_wazifia', models.IntegerField(blank=True, choices=[(-3, 'DRAJAT_TALTA_KHASA'), (-2, 'DRAJAT_TANIA_KHASA'), (-1, 'DRAJAT_AWLA_KHASA'), (1, 'DRAJAT_AWLA'), (2, 'DRAJAT_TANIA'), (3, 'DRAJAT_TALTA'), (4, 'DRAJAT_RAB3A'), (5, 'DRAJAT_KHAMSA'), (7, 'DRAJAT_SAB3A'), (8, 'DRAJAT_TAMNA'), (9, 'DRAJAT_TAS3A'), (10, 'DRAJAT_3ASHRA'), (12, 'DRAJAT_ATNASHAR'), (15, 'DRAJAT_KHAMSTASHR'), (17, 'DRAJAT_TA3AKOD')], null=True, verbose_name='draja_wazifia')),
                ('alawa_sanawia', models.IntegerField(blank=True, choices=[(1, 'ALAWAT_AWALA'), (2, 'ALAWAT_TANIA'), (3, 'ALAWAT_TALTA'), (4, 'ALAWAT_RAB3A'), (5, 'ALAWAT_KHAMSA'), (7, 'ALAWAT_TA3AKOD')], null=True, verbose_name='alawa_sanawia')),
                ('bank', models.CharField(blank=True, choices=[('bok', 'BANK_KHARTOUM'), ('onb', 'BANK_OMDURMAN')], max_length=10, null=True, verbose_name='bank')),
                ('account_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='account_no')),
                ('payroll_ajmali', models.FloatField(default=0, verbose_name='payroll_ajmali')),
                ('payroll_mokaf2', models.FloatField(default=0, verbose_name='payroll_mokaf2')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('payroll_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.payrollmaster')),
            ],
            options={
                'verbose_name': 'Payroll detail (ta3agod mosimi)',
                'verbose_name_plural': 'Payroll details (ta3agod mosimi)',
                'ordering': ['employee__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrolldetailta3agodmosimi',
            constraint=models.UniqueConstraint(fields=('payroll_master', 'employee'), name='unique_employee_payroll_ta3agod_mosimi'),
        ),
    ]
