# Generated by Django 5.0.2 on 2024-10-26 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0087_alter_settings_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebasic',
            name='no3_2lertibat',
            field=models.CharField(choices=[('ta3een', 'NO3_2LERTIBAT_TA3EEN'), ('nagl', 'NO3_2LERTIBAT_NAGL'), ('2ntedab', 'NO3_2LERTIBAT_2NTEDAB'), ('takleef', 'NO3_2LERTIBAT_TAKLEEF'), ('2l7ag', 'NO3_2LERTIBAT_2L7ag'), ('ta3agod_mosimi', 'NO3_2LERTIBAT_TA3AGOD'), ('ta3agod', 'NO3_2LERTIBAT_TA3AGOD_MOSIMI'), ('mashro3', 'NO3_2LERTIBAT_MASHRO3'), ('majlis_el2dara', 'NO3_2LERTIBAT_MAJLIS_EL2DARA')], max_length=15, verbose_name='no3_2lertibat'),
        ),
        migrations.CreateModel(
            name='EmployeeMajlisEl2dara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('position', models.IntegerField(choices=[(1, 'POSITION_R2IS_2LMAJLIS'), (2, 'POSITION_MODIR_3AM'), (3, 'POSITION_3ODO')], verbose_name='position')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='majlis_el2dara', to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'majlis el2dara',
                'verbose_name_plural': 'majlis el2dara',
            },
        ),
        migrations.CreateModel(
            name='PayrollDetailMajlisEl2dara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salafiat', models.FloatField(default=0, verbose_name='salafiat')),
                ('jazaat', models.FloatField(default=0, verbose_name='jazaat')),
                ('damga', models.FloatField(default=0, verbose_name='damga')),
                ('sandog', models.FloatField(default=0, verbose_name='sandog')),
                ('sandog_kahraba', models.FloatField(default=0, verbose_name='sandog_kahraba')),
                ('tarikh_milad', models.DateField(blank=True, null=True, verbose_name='tarikh_milad')),
                ('salafiat_sandog', models.FloatField(default=0, verbose_name='salafiat_sandog')),
                ('salafiat_3la_2lmoratab', models.FloatField(default=0, verbose_name='salafiat_3la_2lmoratab')),
                ('salafiat_3la_2lmokaf2', models.FloatField(default=0, verbose_name='salafiat_3la_2lmokaf2')),
                ('draja_wazifia', models.IntegerField(blank=True, choices=[(-3, 'DRAJAT_TALTA_KHASA'), (-2, 'DRAJAT_TANIA_KHASA'), (-1, 'DRAJAT_AWLA_KHASA'), (1, 'DRAJAT_AWLA'), (2, 'DRAJAT_TANIA'), (3, 'DRAJAT_TALTA'), (4, 'DRAJAT_RAB3A'), (5, 'DRAJAT_KHAMSA'), (7, 'DRAJAT_SAB3A'), (8, 'DRAJAT_TAMNA'), (9, 'DRAJAT_TAS3A'), (10, 'DRAJAT_3ASHRA'), (12, 'DRAJAT_ATNASHAR'), (15, 'DRAJAT_KHAMSTASHR'), (17, 'DRAJAT_TA3AKOD')], null=True, verbose_name='draja_wazifia')),
                ('alawa_sanawia', models.IntegerField(blank=True, choices=[(1, 'ALAWAT_AWALA'), (2, 'ALAWAT_TANIA'), (3, 'ALAWAT_TALTA'), (4, 'ALAWAT_RAB3A'), (5, 'ALAWAT_KHAMSA'), (7, 'ALAWAT_TA3AKOD')], null=True, verbose_name='alawa_sanawia')),
                ('bank', models.CharField(blank=True, choices=[('bok', 'BANK_KHARTOUM'), ('onb', 'BANK_OMDURMAN')], max_length=10, null=True, verbose_name='bank')),
                ('account_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='account_no')),
                ('payroll_mokaf2', models.FloatField(default=0, verbose_name='payroll_mokaf2')),
                ('payroll_asasi', models.FloatField(default=0, verbose_name='payroll_asasi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('payroll_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.payrollmaster')),
            ],
            options={
                'verbose_name': 'Payroll detail (majlis el2dara)',
                'verbose_name_plural': 'Payroll details (majlis el2dara)',
                'ordering': ['employee__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrolldetailmajlisel2dara',
            constraint=models.UniqueConstraint(fields=('payroll_master', 'employee'), name='unique_employee_payroll_majlis_el2dara'),
        ),
    ]
