# Generated by Django 5.0.2 on 2024-10-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0088_alter_employeebasic_no3_2lertibat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemajlisel2dara',
            name='position',
            field=models.IntegerField(choices=[(1, 'POSITION_R2IS_2LMAJLIS'), (2, 'POSITION_MODIR_3AM'), (3, 'POSITION_3ODO')], default=3, verbose_name='position'),
        ),
    ]
