# Generated by Django 5.0.2 on 2024-10-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0090_alter_settings_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldetailmajlisel2dara',
            name='atfal',
            field=models.FloatField(default=0, verbose_name='atfal'),
        ),
        migrations.AddField(
            model_name='payrolldetailmajlisel2dara',
            name='gasima',
            field=models.FloatField(default=0, verbose_name='gasima'),
        ),
        migrations.AddField(
            model_name='payrolldetailmajlisel2dara',
            name='moahil',
            field=models.FloatField(default=0, verbose_name='moahil'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='code',
            field=models.CharField(choices=[('zaka_kafaf', 'SETTINGS_ZAKAT_KAFAF'), ('zaka_nisab', 'SETTINGS_ZAKAT_NISAB'), ('gasima', 'SETTINGS_GASIMA'), ('atfal', 'SETTINGS_ATFAL'), ('damga', 'SETTINGS_DAMGA'), ('sandog', 'SETTINGS_SANDOG'), ('aadoa', 'SETTINGS_AADOA'), ('daribat_2lmokafa', 'SETTINGS_DARIBAT_2LMOKAFA'), ('enable_kahraba', 'SETTINGS_ENABLE_SANDOG_KAHRABA'), ('enable_algoat', 'SETTINGS_ENABLE_YOUM_ALGOAT_ALMOSALAHA'), ('m2moria_rate', 'SETTINGS_M2MORIA_RATE'), ('e3asha_rate', 'SETTINGS_E3ASHA_RATE'), ('kharj_elsharika', 'SETTINGS_KHARJ_ELSHARIKA'), ('omer_2lma3ash', 'SETTINGS_OMER_2LMA3ASH'), ('khasm_elsandog_min_elomoratab', 'SETTINGS_KHASM_ELSANDOG_MIN_ELOMORATAB'), ('ta3agod_mosimi_mozaf', 'SETTINGS_TA3AGODMOSIMI_MOZAF'), ('ta3agod_mosimi_3amil', 'SETTINGS_TA3AGODMOSIMI_3AMIL'), ('ta3agod_mosimi_mokaf2', 'SETTINGS_TA3AGODMOSIMI_MOKAF2'), ('majlis_el2dara_r2is', 'SETTINGS_MAJLIS_EL2DARA_R2IS_2LMAJLIS'), ('majlis_el2dara_3odo', 'SETTINGS_MAJLIS_EL2DARA_3ODO'), ('modir_3am_asai', 'SETTINGS_MODIR_3AM_ASAI'), ('moahil_thanoi', 'المؤهل دون الجامعي'), ('moahil_deplom_tegani', 'المؤهل دبلوم تقني'), ('moahil_deplom_waseet', 'المؤهل دبلوم وسيط'), ('moahil_baklarios', 'المؤهل بكلاريوس عام'), ('moahil_baklarios_sharaf', 'المؤهل بكلاريوس شرف'), ('moahil_daplom_3ali', 'المؤهل دبلوم عالي'), ('moahil_majstear', 'المؤهل ماجستير'), ('moahil_dectora', 'المؤهل دكتورة'), ('mosama_modir_2l3am', 'استحقاق مباشرة المدير العام'), ('mosama_mosa3deen', 'استحقاق مباشرة مساعدي المدير العام'), ('mosama_modra2_3ameen', 'استحقاق مباشرة مدراء الادارات العامة'), ('mosama_modra2_far3ia', 'استحقاق مباشرة مدراء الادارات الفرعية'), ('mosama_ro2sa2_2gsam', 'استحقاق مباشرة رؤساء الاقسام'), ('mosama_mozafeen', 'استحقاق مباشرة الموظفين'), ('mosama_3mal_sageen', 'استحقاق مباشرة العمال والسائقين')], max_length=30, verbose_name='code'),
        ),
    ]
