# Generated by Django 5.1 on 2024-11-04 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0091_payrolldetailmajlisel2dara_atfal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeem2moriamonthly',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='employeem2moriamonthly',
            name='payroll_master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.payrollmaster'),
            preserve_default=False,
        ),
    ]
