# Generated by Django 5.1 on 2024-11-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0092_remove_employeem2moriamonthly_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeem2moriamonthly',
            name='unique_m2moriaemployee_year_month',
        ),
        migrations.RemoveIndex(
            model_name='employeem2moriamonthly',
            name='hr_employee_year_919a3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeem2moriamonthly',
            name='hr_employee_employe_86deeb_idx',
        ),
        migrations.RemoveField(
            model_name='employeem2moriamonthly',
            name='month',
        ),
        migrations.RemoveField(
            model_name='employeem2moriamonthly',
            name='year',
        ),
    ]
