# Generated by Django 5.1 on 2024-11-04 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0093_remove_employeem2moriamonthly_unique_m2moriaemployee_year_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeem2moriamonthly',
            name='m2moria_master',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='hr.employeem2moria'),
            preserve_default=False,
        ),
    ]
