# Generated by Django 5.1 on 2024-11-14 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0094_employeem2moriamonthly_m2moria_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeem2moriamonthly',
            options={'verbose_name': 'M2moria detail', 'verbose_name_plural': 'M2moria details'},
        ),
        migrations.CreateModel(
            name='PayrollTasoia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_abtdai', models.FloatField(default=0, verbose_name='abtdai')),
                ('total_galaa_m3isha', models.FloatField(default=0, verbose_name='galaa_m3isha')),
                ('total_tabi3at_3mal', models.FloatField(default=0, verbose_name='tabi3at_3mal')),
                ('total_tamtheel', models.FloatField(default=0, verbose_name='tamtheel')),
                ('total_mihna', models.FloatField(default=0, verbose_name='mihna')),
                ('total_ma3adin', models.FloatField(default=0, verbose_name='ma3adin')),
                ('total_aadoa', models.FloatField(default=0, verbose_name='aadoa')),
                ('total_ajtima3ia', models.FloatField(default=0, verbose_name='ajtima3ia')),
                ('total_moahil', models.FloatField(default=0, verbose_name='moahil')),
                ('total_shakhsia', models.FloatField(default=0, verbose_name='shakhsia')),
                ('total_makhatir', models.FloatField(default=0, verbose_name='makhatir')),
                ('total_salafiat', models.FloatField(default=0, verbose_name='salafiat')),
                ('total_dariba', models.FloatField(default=0, verbose_name='dariba')),
                ('total_damga', models.FloatField(default=0, verbose_name='damga')),
                ('total_m3ash', models.FloatField(default=0, verbose_name='m3ash')),
                ('total_tameen_ajtima3i', models.FloatField(default=0, verbose_name='tameen_ajtima3i')),
                ('total_sandog', models.FloatField(default=0, verbose_name='sandog')),
                ('total_zakat', models.FloatField(default=0, verbose_name='zakat')),
                ('total_youm_algoat_almosalaha', models.FloatField(default=0, verbose_name='youm_algoat_almosalaha')),
                ('total_jazaat', models.FloatField(default=0, verbose_name='jazaat')),
                ('total_salafiat_sandog', models.FloatField(default=0, verbose_name='salafiat_sandog')),
                ('payroll_master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.payrollmaster')),
            ],
            options={
                'verbose_name': 'Payroll tasoia',
                'verbose_name_plural': 'Payroll tasoia',
            },
        ),
    ]
