# Generated by Django 5.1 on 2024-11-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0095_alter_employeem2moriamonthly_options_payrolltasoia'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolltasoia',
            name='total_safi_alisti7gag',
            field=models.FloatField(default=0, verbose_name='total_safi_alisti7gag'),
        ),
    ]
