# Generated by Django 5.0.2 on 2024-12-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0097_employeetelegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetelegram',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='user_id'),
            preserve_default=False,
        ),
    ]
