# Generated by Django 5.0.2 on 2024-12-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0098_employeetelegram_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetelegram',
            name='user_id',
            field=models.IntegerField(max_length=12, verbose_name='user_id'),
        ),
    ]
