# Generated by Django 5.0.2 on 2024-12-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0100_alter_employeetelegram_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetelegram',
            name='phone',
            field=models.CharField(max_length=30, unique=True, verbose_name='phone'),
        ),
    ]
