# Generated by Django 5.0.2 on 2024-12-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0101_alter_employeetelegram_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetelegram',
            name='user_id',
            field=models.FloatField(unique=True, verbose_name='user_id'),
        ),
    ]
