# Generated by Django 5.0.2 on 2024-12-25 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0103_employeetelegramregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetelegramregistration',
            name='name',
            field=models.CharField(default='', max_length=150, validators=[django.core.validators.MinLengthValidator(12, '2dkhil al2sm roba3i')], verbose_name='employee_name'),
            preserve_default=False,
        ),
    ]
