# Generated by Django 5.0.2 on 2024-12-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0104_employeetelegramregistration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetelegramregistration',
            name='name',
            field=models.CharField(max_length=150, verbose_name='employee_name'),
        ),
    ]
