# Generated by Django 5.0.2 on 2024-12-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0105_alter_employeetelegramregistration_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetelegramregistration',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeetelegramregistration',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeetelegramregistration',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='EmployeeTelegram',
        ),
        migrations.DeleteModel(
            name='EmployeeTelegramRegistration',
        ),
    ]
