# Generated by Django 5.0.2 on 2025-01-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0108_alter_settings_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebasic',
            name='status',
            field=models.IntegerField(choices=[(1, 'STATUS_ACTIVE'), (2, 'STATUS_MA3ASH'), (3, 'STATUS_TAGA3D_EKHTIARI'), (4, 'STATUS_ESTIKALA'), (5, 'STATUS_3DAM_ELIAGA_ELTIBIA'), (6, 'STATUS_ELFASL'), (7, 'STATUS_ENTIHA2_2L3AGD'), (8, 'STATUS_SHAGL_MANSAB_DASTORY'), (9, 'STATUS_ELWAFAH'), (10, 'STATUS_FOGDAN_ELJENSIA_ELSODANIA'), (11, 'STATUS_ENHA2_ENTIDAB'), (12, 'STATUS_NAGL'), (13, 'STATUS_2L7AG'), (14, 'STATUS_EJAZA_MIN_GAIR_MORATAB'), (15, 'STATUS_EIGAF_MO2KAT')], default=1, verbose_name='status'),
        ),
    ]
