# Generated by Django 5.0.2 on 2025-01-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0109_alter_employeebasic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebasic',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='email'),
        ),
    ]
