# Generated by Django 5.0.2 on 2025-01-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0110_employeebasic_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefamily',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
