# Generated by Django 5.0.2 on 2025-01-22 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0111_alter_employeefamily_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeebasic',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_employee_code'),
        ),
    ]
