# Generated by Django 5.1.7 on 2025-04-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0112_employeebasic_unique_employee_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeebankaccount',
            name='unique_bank_account',
        ),
    ]
