# Generated by Django 5.1.7 on 2025-04-28 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0113_remove_employeebankaccount_unique_bank_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeebankaccount',
            constraint=models.UniqueConstraint(fields=('bank', 'account_no'), name='unique_bank_account'),
        ),
    ]
