# Generated by Django 5.0.2 on 2025-06-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0116_alter_settings_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldetail',
            name='mokaf2at_2da2',
            field=models.FloatField(default=0, verbose_name='mokaf2at_2da2'),
        ),
    ]
