# Generated by Django 5.0.2 on 2025-06-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0117_payrolldetail_mokaf2at_2da2'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolltasoia',
            name='total_mokaf2at_2da2',
            field=models.FloatField(default=0, verbose_name='aadoa'),
        ),
    ]
