# Generated by Django 5.0.2 on 2025-07-09 07:02

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0118_payrolltasoia_total_mokaf2at_2da2'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikalwazifi',
            name='edara_3ama',
            field=mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.hikalwazifi', verbose_name='edara_3ama'),
        ),
        migrations.AddField(
            model_name='hikalwazifi',
            name='edara_far3ia',
            field=mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.hikalwazifi', verbose_name='edara_far3ia'),
        ),
        migrations.AddField(
            model_name='hikalwazifi',
            name='gisim',
            field=mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.hikalwazifi', verbose_name='gasima'),
        ),
    ]
