# Generated by Django 5.0.2 on 2025-07-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0119_hikalwazifi_edara_3ama_hikalwazifi_edara_far3ia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebasic',
            name='edara_3ama_tmp',
        ),
        migrations.RemoveField(
            model_name='employeebasic',
            name='edara_far3ia_tmp',
        ),
    ]
