# Generated by Django 5.0.2 on 2025-07-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0120_remove_employeebasic_edara_3ama_tmp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebasic',
            name='no3_2lertibat',
            field=models.CharField(choices=[('ta3een', 'NO3_2LERTIBAT_TA3EEN'), ('nagl', 'NO3_2LERTIBAT_NAGL'), ('2ntedab', 'NO3_2LERTIBAT_2NTEDAB'), ('takleef', 'NO3_2LERTIBAT_TAKLEEF'), ('2l7ag', 'NO3_2LERTIBAT_2L7ag'), ('ta3agod', 'NO3_2LERTIBAT_TA3AGOD'), ('ta3agod_mosimi', 'NO3_2LERTIBAT_TA3AGOD_MOSIMI'), ('mashro3', 'NO3_2LERTIBAT_MASHRO3'), ('majlis_el2dara', 'NO3_2LERTIBAT_MAJLIS_EL2DARA')], max_length=15, verbose_name='no3_2lertibat'),
        ),
    ]
