# Generated by Django 5.0.2 on 2025-09-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0121_alter_employeebasic_no3_2lertibat'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldetail',
            name='mokaf2at_2da2_fi_mokaf2',
            field=models.BooleanField(default=True, verbose_name='حساب بدل المكافئة في كشف المكافئة'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='code',
            field=models.CharField(choices=[('zaka_kafaf', 'SETTINGS_ZAKAT_KAFAF'), ('zaka_nisab', 'SETTINGS_ZAKAT_NISAB'), ('gasima', 'SETTINGS_GASIMA'), ('atfal', 'SETTINGS_ATFAL'), ('damga', 'SETTINGS_DAMGA'), ('sandog', 'SETTINGS_SANDOG'), ('daribat_2lmokafa', 'SETTINGS_DARIBAT_2LMOKAFA'), ('enable_kahraba', 'SETTINGS_ENABLE_SANDOG_KAHRABA'), ('enable_algoat', 'SETTINGS_ENABLE_YOUM_ALGOAT_ALMOSALAHA'), ('m2moria_rate', 'SETTINGS_M2MORIA_RATE'), ('e3asha_rate', 'SETTINGS_E3ASHA_RATE'), ('kharj_elsharika', 'SETTINGS_KHARJ_ELSHARIKA'), ('omer_2lma3ash', 'SETTINGS_OMER_2LMA3ASH'), ('khasm_elsandog_min_elomoratab', 'SETTINGS_KHASM_ELSANDOG_MIN_ELOMORATAB'), ('ta3agod_mosimi_mozaf', 'SETTINGS_TA3AGODMOSIMI_MOZAF'), ('ta3agod_mosimi_3amil', 'SETTINGS_TA3AGODMOSIMI_3AMIL'), ('ta3agod_mosimi_mokaf2', 'SETTINGS_TA3AGODMOSIMI_MOKAF2'), ('majlis_el2dara_r2is', 'SETTINGS_MAJLIS_EL2DARA_R2IS_2LMAJLIS'), ('majlis_el2dara_3odo', 'SETTINGS_MAJLIS_EL2DARA_3ODO'), ('modir_3am_asai', 'SETTINGS_MODIR_3AM_ASAI'), ('mokaf2t_ada2_fi_mokaf2', 'حساب مكافئة الاداء في المرتب'), ('moahil_thanoi', 'المؤهل دون الجامعي'), ('moahil_deplom_tegani', 'المؤهل دبلوم تقني'), ('moahil_deplom_waseet', 'المؤهل دبلوم وسيط'), ('moahil_baklarios', 'المؤهل بكلاريوس عام'), ('moahil_baklarios_sharaf', 'المؤهل بكلاريوس شرف'), ('moahil_daplom_3ali', 'المؤهل دبلوم عالي'), ('moahil_majstear', 'المؤهل ماجستير'), ('moahil_dectora', 'المؤهل دكتورة'), ('mosama_modir_2l3am', 'استحقاق مباشرة المدير العام'), ('mosama_mosa3deen', 'استحقاق مباشرة مساعدي المدير العام'), ('mosama_modra2_3ameen', 'استحقاق مباشرة مدراء الادارات العامة'), ('mosama_modra2_far3ia', 'استحقاق مباشرة مدراء الادارات الفرعية'), ('mosama_ro2sa2_2gsam', 'استحقاق مباشرة رؤساء الاقسام'), ('mosama_mozafeen', 'استحقاق مباشرة الموظفين'), ('mosama_3mal_sageen', 'استحقاق مباشرة العمال والسائقين'), ('aadoa_daraja_-3', 'بدل عدوى الثالثة الخاصة'), ('mokaf2t_ada2_daraja_-3', 'مكافئة اداء الثالثة الخاصة'), ('aadoa_daraja_-2', 'بدل عدوى الثانية الخاصة'), ('mokaf2t_ada2_daraja_-2', 'مكافئة اداء الثانية الخاصة'), ('aadoa_daraja_-1', 'بدل عدوى الاولى الخاصة'), ('mokaf2t_ada2_daraja_-1', 'مكافئة اداء الاولى الخاصة'), ('aadoa_daraja_1', 'بدل عدوى الاولى'), ('mokaf2t_ada2_daraja_1', 'مكافئة اداء الاولى'), ('aadoa_daraja_2', 'بدل عدوى الثانية'), ('mokaf2t_ada2_daraja_2', 'مكافئة اداء الثانية'), ('aadoa_daraja_3', 'بدل عدوى الثالثة'), ('mokaf2t_ada2_daraja_3', 'مكافئة اداء الثالثة'), ('aadoa_daraja_4', 'بدل عدوى الرابعة'), ('mokaf2t_ada2_daraja_4', 'مكافئة اداء الرابعة'), ('aadoa_daraja_5', 'بدل عدوى الخامسة'), ('mokaf2t_ada2_daraja_5', 'مكافئة اداء الخامسة'), ('aadoa_daraja_7', 'بدل عدوى السابعة'), ('mokaf2t_ada2_daraja_7', 'مكافئة اداء السابعة'), ('aadoa_daraja_8', 'بدل عدوى الثامنة'), ('mokaf2t_ada2_daraja_8', 'مكافئة اداء الثامنة'), ('aadoa_daraja_9', 'بدل عدوى التاسعة'), ('mokaf2t_ada2_daraja_9', 'مكافئة اداء التاسعة'), ('aadoa_daraja_10', 'بدل عدوى العاشرة'), ('mokaf2t_ada2_daraja_10', 'مكافئة اداء العاشرة'), ('aadoa_daraja_12', 'بدل عدوى الثانية عشرة'), ('mokaf2t_ada2_daraja_12', 'مكافئة اداء الثانية عشرة'), ('aadoa_daraja_15', 'بدل عدوى الخامسة عشرة'), ('mokaf2t_ada2_daraja_15', 'مكافئة اداء الخامسة عشرة'), ('aadoa_daraja_17', 'بدل عدوى تعاقد'), ('mokaf2t_ada2_daraja_17', 'مكافئة اداء تعاقد')], max_length=30, verbose_name='code'),
        ),
    ]
