# Generated by Django 5.2.7 on 2025-11-02 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0122_payrolldetail_mokaf2at_2da2_fi_mokaf2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalafiatMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('no3_2lsalafia', models.IntegerField(choices=[(1, 'NO3_2LSALAFIA_SHARIKA'), (2, 'NO3_2LSALAFIA_SANDOG'), (3, 'NO3_2LSALAFIA_3LA_2LMORATAB'), (4, 'NO3_2LSALAFIA_3LA_2LMOKAF2')], default=2, verbose_name='no3_2lsalafia')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employeesalafiat',
            name='salafiat_master',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.employeesalafiatmaster', verbose_name='employee_name'),
        ),
    ]
