# Generated by Django 5.2.7 on 2025-11-02 14:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0123_employeesalafiatmaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalafiatSandog',
            fields=[
            ],
            options={
                'verbose_name': 'سلفية صندوق',
                'verbose_name_plural': 'سلفيات الصندوق',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.employeesalafiat',),
        ),
        migrations.AlterModelOptions(
            name='employeesalafiat',
            options={'ordering': ['year', 'month', 'no3_2lsalafia'], 'verbose_name': 'تفاصيل سلفية', 'verbose_name_plural': 'تفاصيل السلفيات'},
        ),
        migrations.AlterModelOptions(
            name='employeesalafiatmaster',
            options={'verbose_name': 'سجل سلفية', 'verbose_name_plural': 'سجل السلفيات'},
        ),
        migrations.AddField(
            model_name='employeesalafiatmaster',
            name='no_month',
            field=models.IntegerField(default=1, verbose_name='عدد الشهور'),
        ),
        migrations.AddField(
            model_name='employeesalafiatmaster',
            name='start_month',
            field=models.IntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], default=11, verbose_name='تاريخ البداية - الشهر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeesalafiatmaster',
            name='start_year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(limit_value=2015), django.core.validators.MaxValueValidator(limit_value=2100)], verbose_name='تاريخ البداية - السنة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeesalafiat',
            name='salafiat_master',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.employeesalafiatmaster', verbose_name='مرجع السلفية'),
        ),
    ]
