# Generated by Django 5.2.7 on 2025-11-20 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0124_employeesalafiatsandog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salary', models.FloatField(default=0, verbose_name='اجمالي المرتب')),
                ('net_salary', models.FloatField(default=0, verbose_name='صافي الإستحقاق')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('payroll_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.payrollmaster')),
            ],
        ),
    ]
