# Generated by Django 5.2.7 on 2025-11-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0125_payrollsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsummary',
            name='mokaf2',
            field=models.FloatField(default=0, verbose_name='المكافئة'),
        ),
    ]
