# Generated by Django 5.2.7 on 2025-12-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0126_payrollsummary_mokaf2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikalwazifi',
            name='elmostoa_eltanzimi',
            field=models.IntegerField(choices=[(1, 'ELMOSTOA_ELTANZIMI_MODIR_3AM'), (2, 'ELMOSTOA_ELTANZIMI_MOSA3ID_MODIR_3AM'), (3, 'ELMOSTOA_ELTANZIMI_2DARA_3AMA'), (4, 'ELMOSTOA_ELTANZIMI_2DARA_FAR3IA'), (5, 'ELMOSTOA_ELTANZIMI_GISIM'), (6, 'ELMOSTOA_ELTANZIMI_WI7DA'), (7, 'ELMOSTOA_ELTANZIMI_MAKTAB_WILA2I')], default=6, verbose_name='elmostoa_eltanzimi'),
        ),
    ]
