# Generated by Django 5.2.7 on 2025-12-17 05:57

import django.db.models.deletion
import treewidget.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0127_alter_hikalwazifi_elmostoa_eltanzimi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edarafar3ia',
            name='hikal_wazifi',
            field=treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.hikalwazifi', verbose_name='hikal_wazifi'),
        ),
        migrations.AlterField(
            model_name='employeebasic',
            name='hikal_wazifi',
            field=treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.hikalwazifi', verbose_name='hikal_wazifi'),
        ),
        migrations.AlterField(
            model_name='hikalwazifi',
            name='edara_3ama',
            field=treewidget.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.hikalwazifi', verbose_name='edara_3ama'),
        ),
        migrations.AlterField(
            model_name='hikalwazifi',
            name='edara_far3ia',
            field=treewidget.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.hikalwazifi', verbose_name='edara_far3ia'),
        ),
        migrations.AlterField(
            model_name='hikalwazifi',
            name='gisim',
            field=treewidget.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.hikalwazifi', verbose_name='gasima'),
        ),
        migrations.AlterField(
            model_name='hikalwazifi',
            name='parent',
            field=treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hr.hikalwazifi'),
        ),
    ]
