# Generated by Django 5.2.7 on 2025-12-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0128_alter_edarafar3ia_hikal_wazifi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsummary',
            name='salary_mokaf2',
            field=models.FloatField(default=0, verbose_name='مكافئة اداء'),
        ),
    ]
