# Generated by Django 5.2.7 on 2026-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0130_payrolldetail_calculate_mokaf2t_ada2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldetail',
            name='mokaf2at_majlis',
            field=models.FloatField(default=0, verbose_name='مكافئة اداء مجلس الوزراء'),
        ),
    ]
