# Generated by Django 5.2.7 on 2026-02-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0131_payrolldetail_mokaf2at_majlis'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebankaccount',
            name='account_type',
            field=models.CharField(max_length=5, null=True, verbose_name='account_type'),
        ),
        migrations.AddField(
            model_name='employeebankaccount',
            name='branch_code',
            field=models.CharField(max_length=5, null=True, verbose_name='branch_code'),
        ),
    ]
