# Generated by Django 5.2.7 on 2026-02-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0132_employeebankaccount_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebankaccount',
            name='account_type',
            field=models.CharField(default='', max_length=5, null=True, verbose_name='نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='employeebankaccount',
            name='branch_code',
            field=models.CharField(default='', max_length=5, null=True, verbose_name='كود الفرع'),
        ),
    ]
