# Generated by Django 5.2.7 on 2026-02-12 09:47

import django.db.models.deletion
import hr.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0135_alter_employeebankaccount_account_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebasic',
            name='no3_2lertibat',
            field=models.CharField(choices=[('ta3een', 'NO3_2LERTIBAT_TA3EEN'), ('nagl', 'NO3_2LERTIBAT_NAGL'), ('nagl_niha2i', 'نقل نهائي'), ('2ntedab', 'NO3_2LERTIBAT_2NTEDAB'), ('takleef', 'NO3_2LERTIBAT_TAKLEEF'), ('2l7ag', 'NO3_2LERTIBAT_2L7ag'), ('ta3agod', 'NO3_2LERTIBAT_TA3AGOD'), ('ta3agod_mosimi', 'NO3_2LERTIBAT_TA3AGOD_MOSIMI'), ('mashro3', 'NO3_2LERTIBAT_MASHRO3'), ('majlis_el2dara', 'NO3_2LERTIBAT_MAJLIS_EL2DARA')], max_length=15, verbose_name='no3_2lertibat'),
        ),
        migrations.CreateModel(
            name='EmployeeArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('document_type', models.CharField(choices=[('contract', 'عقد'), ('certificate', 'شهادة'), ('decision', 'قرار'), ('letter', 'خطاب'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المستند')),
                ('document_date', models.DateField(verbose_name='تاريخ المستند')),
                ('attachment', models.FileField(upload_to=hr.models.attachement_path, verbose_name='المرفق')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'ارشيف رقمي',
                'verbose_name_plural': 'الارشيف الرقمي',
            },
        ),
        migrations.CreateModel(
            name='EmployeeKhibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('jiha', models.CharField(max_length=150, verbose_name='الجهة')),
                ('mosama_wazifi', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('start_dt', models.DateField(verbose_name='تاريخ البداية')),
                ('end_dt', models.DateField(verbose_name='تاريخ النهاية')),
                ('no3_khibra', models.CharField(choices=[('mutabaqa', 'مطابقة'), ('mushtabaha', 'مشتبهة')], max_length=20, verbose_name='نوع الخبرة')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'خبرة العامل',
                'verbose_name_plural': 'خبرات العاملين',
            },
        ),
        migrations.CreateModel(
            name='EmployeeNo32lertibat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('no3_2lertibat', models.CharField(choices=[('ta3een', 'NO3_2LERTIBAT_TA3EEN'), ('nagl', 'NO3_2LERTIBAT_NAGL'), ('nagl_niha2i', 'نقل نهائي'), ('2ntedab', 'NO3_2LERTIBAT_2NTEDAB'), ('takleef', 'NO3_2LERTIBAT_TAKLEEF'), ('2l7ag', 'NO3_2LERTIBAT_2L7ag'), ('ta3agod', 'NO3_2LERTIBAT_TA3AGOD'), ('ta3agod_mosimi', 'NO3_2LERTIBAT_TA3AGOD_MOSIMI'), ('mashro3', 'NO3_2LERTIBAT_MASHRO3'), ('majlis_el2dara', 'NO3_2LERTIBAT_MAJLIS_EL2DARA')], max_length=15, verbose_name='no3_2lertibat')),
                ('tarikh_start_dt', models.DateField(verbose_name='تاريخ البداية')),
                ('tarikh_end_dt', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'نوع الإرتباط',
                'verbose_name_plural': 'أنواع الإرتباط',
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('status', models.IntegerField(choices=[(1, 'STATUS_ACTIVE'), (2, 'STATUS_MA3ASH'), (3, 'STATUS_TAGA3D_EKHTIARI'), (4, 'STATUS_ESTIKALA'), (5, 'STATUS_3DAM_ELIAGA_ELTIBIA'), (6, 'STATUS_ELFASL'), (7, 'STATUS_ENTIHA2_2L3AGD'), (8, 'STATUS_SHAGL_MANSAB_DASTORY'), (9, 'STATUS_ELWAFAH'), (10, 'STATUS_FOGDAN_ELJENSIA_ELSODANIA'), (11, 'STATUS_ENHA2_ENTIDAB'), (12, 'STATUS_NAGL'), (13, 'STATUS_2L7AG'), (14, 'STATUS_EJAZA_MIN_GAIR_MORATAB'), (15, 'STATUS_EIGAF_MO2KAT')], default=1, verbose_name='status')),
                ('tarikh_dt', models.DateField(verbose_name='التاريخ')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'حالة الموظف',
                'verbose_name_plural': 'حالة الموظفين',
            },
        ),
    ]
