# Generated by Django 5.2.7 on 2026-02-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0136_alter_employeebasic_no3_2lertibat_employeearchive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebasic',
            name='no3_2lertibat',
            field=models.CharField(blank=True, choices=[('ta3een', 'NO3_2LERTIBAT_TA3EEN'), ('nagl', 'NO3_2LERTIBAT_NAGL'), ('nagl_niha2i', 'نقل نهائي'), ('2ntedab', 'NO3_2LERTIBAT_2NTEDAB'), ('takleef', 'NO3_2LERTIBAT_TAKLEEF'), ('2l7ag', 'NO3_2LERTIBAT_2L7ag'), ('ta3agod', 'NO3_2LERTIBAT_TA3AGOD'), ('ta3agod_mosimi', 'NO3_2LERTIBAT_TA3AGOD_MOSIMI'), ('mashro3', 'NO3_2LERTIBAT_MASHRO3'), ('majlis_el2dara', 'NO3_2LERTIBAT_MAJLIS_EL2DARA')], max_length=15, null=True, verbose_name='no3_2lertibat'),
        ),
        migrations.AlterField(
            model_name='employeebasic',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'STATUS_ACTIVE'), (2, 'STATUS_MA3ASH'), (3, 'STATUS_TAGA3D_EKHTIARI'), (4, 'STATUS_ESTIKALA'), (5, 'STATUS_3DAM_ELIAGA_ELTIBIA'), (6, 'STATUS_ELFASL'), (7, 'STATUS_ENTIHA2_2L3AGD'), (8, 'STATUS_SHAGL_MANSAB_DASTORY'), (9, 'STATUS_ELWAFAH'), (10, 'STATUS_FOGDAN_ELJENSIA_ELSODANIA'), (11, 'STATUS_ENHA2_ENTIDAB'), (12, 'STATUS_NAGL'), (13, 'STATUS_2L7AG'), (14, 'STATUS_EJAZA_MIN_GAIR_MORATAB'), (15, 'STATUS_EIGAF_MO2KAT')], default=1, null=True, verbose_name='status'),
        ),
    ]
