# Generated by Django 5.0.2 on 2024-05-06 21:30

import help_request.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprecord',
            name='issue_app',
            field=models.CharField(max_length=20, verbose_name='app name'),
        ),
        migrations.AlterField(
            model_name='helprecord',
            name='issue_img',
            field=models.ImageField(upload_to=help_request.models.HelpRecord.attachement_path, verbose_name='capture'),
        ),
    ]
