# Generated by Django 5.0.2 on 2024-05-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_request', '0002_alter_helprecord_issue_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprecord',
            name='issue_url',
            field=models.CharField(default='/', max_length=200, verbose_name='page url'),
            preserve_default=False,
        ),
    ]
