# Generated by Django 5.0.2 on 2024-06-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_request', '0003_helprecord_issue_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helprecord',
            options={'ordering': ['-id'], 'verbose_name': 'help request', 'verbose_name_plural': 'help requests'},
        ),
        migrations.AlterField(
            model_name='helprecord',
            name='issue_url',
            field=models.URLField(verbose_name='page url'),
        ),
    ]
