# Generated by Django 5.0.2 on 2024-06-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_request', '0005_helprecord_issue_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprecord',
            name='issue_txt',
            field=models.TextField(max_length=200, verbose_name='describe issue'),
        ),
    ]
