# Generated by Django 5.1 on 2024-11-18 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMokhalafat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('code', models.IntegerField(verbose_name='code')),
                ('date', models.DateField(verbose_name='date')),
                ('aism_almukhalafa', models.CharField(max_length=150, verbose_name='aism_almukhalafa')),
                ('wasf_almukhalafa', models.CharField(max_length=255, verbose_name='wasf_almukhalafa')),
                ('tahlil_almukhalafa', models.CharField(max_length=150, verbose_name='tahlil_almukhalafa')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppMokhalafatProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mokhalafat.appmokhalafat')),
            ],
        ),
        migrations.CreateModel(
            name='AppMokhalafatRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('jihat_altanfidh', models.CharField(max_length=100, verbose_name='jihat_altanfidh')),
                ('from_date', models.DateField(verbose_name='from_date')),
                ('to_date', models.DateField(verbose_name='to_date')),
                ('comments', models.CharField(max_length=255, verbose_name='wasf_almukhalafa')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mokhalafat.appmokhalafat')),
            ],
        ),
    ]
