# Generated by Django 5.1 on 2024-11-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mokhalafat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmokhalafat',
            options={'verbose_name': 'AppMokhalafat', 'verbose_name_plural': 'AppMokhalafat'},
        ),
        migrations.AlterModelOptions(
            name='appmokhalafatprocedure',
            options={'verbose_name': 'AppMokhalafatProcedure', 'verbose_name_plural': 'AppMokhalafatProcedure'},
        ),
        migrations.AlterModelOptions(
            name='appmokhalafatrecommendation',
            options={'verbose_name': 'AppMokhalafatRecommendation', 'verbose_name_plural': 'AppMokhalafatRecommendation'},
        ),
        migrations.AlterField(
            model_name='appmokhalafatrecommendation',
            name='comments',
            field=models.CharField(max_length=255, verbose_name='comments'),
        ),
    ]
