# Generated by Django 5.1 on 2024-11-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mokhalafat', '0002_alter_appmokhalafat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmokhalafatprocedure',
            name='name',
            field=models.CharField(max_length=150, verbose_name='procedure_name'),
        ),
        migrations.AlterField(
            model_name='appmokhalafatrecommendation',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='appmokhalafatrecommendation',
            name='name',
            field=models.CharField(max_length=150, verbose_name='recommendation_name'),
        ),
    ]
