# Generated by Django 5.1 on 2024-11-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mokhalafat', '0003_alter_appmokhalafatprocedure_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmokhalafat',
            name='wasf_almukhalafa',
            field=models.CharField(max_length=1000, verbose_name='wasf_almukhalafa'),
        ),
    ]
