# Generated by Django 5.2.7 on 2026-06-14 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0139_lkpstate_code'),
        ('mokhalafat', '0004_alter_appmokhalafat_wasf_almukhalafa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppChemicalMaterialsViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(verbose_name='الزمن')),
                ('city_or_village', models.CharField(max_length=150, verbose_name='المدينة أو القرية')),
                ('neighborhood', models.CharField(max_length=150, verbose_name='الحي')),
                ('house', models.CharField(max_length=150, verbose_name='المنزل')),
                ('location_details', models.TextField(max_length=1000, verbose_name='احداثيات الموقع بالتفصيل')),
                ('incident_type', models.CharField(choices=[('inspection_tour', 'جولة تفتيش'), ('incoming_report', 'بلاغ وارد'), ('field_work', 'عمل ميداني')], max_length=50, verbose_name='تفاصيل الواقعة')),
                ('officer_name', models.CharField(max_length=200, verbose_name='الاسم (القائم بالضبط)')),
                ('officer_job', models.CharField(max_length=150, verbose_name='الوظيفة (القائم بالضبط)')),
                ('officer_org', models.CharField(max_length=150, verbose_name='الجهة (القائم بالضبط)')),
                ('is_safely_stored', models.CharField(choices=[('yes', 'نعم'), ('no', 'لا')], max_length=5, verbose_name='هل المواد محفوظة بطريقة آمنة؟')),
                ('ventilation', models.CharField(choices=[('good', 'جيدة'), ('weak', 'ضعيفة'), ('none', 'معدومة')], max_length=10, verbose_name='وجود تهوية')),
                ('has_warning_labels', models.CharField(choices=[('yes', 'نعم'), ('no', 'لا')], max_length=5, verbose_name='وجود ملصقات تحذيرية')),
                ('near_heat_or_flame', models.CharField(choices=[('yes', 'نعم'), ('no', 'لا')], max_length=5, verbose_name='قرب المواد من مصادر حرارة أو لهب')),
                ('public_health_risk', models.CharField(choices=[('high', 'عالي'), ('medium', 'متوسط'), ('low', 'منخفض')], max_length=10, verbose_name='خطر على الصحة العامة')),
                ('fire_explosion_risk', models.CharField(choices=[('high', 'عالي'), ('medium', 'متوسط'), ('low', 'منخفض')], max_length=10, verbose_name='خطر حريق أو انفجار')),
                ('environmental_risk', models.CharField(choices=[('high', 'عالي'), ('medium', 'متوسط'), ('low', 'منخفض')], max_length=10, verbose_name='خطر تلوث بيئي')),
                ('proc_secure_site', models.BooleanField(default=False, verbose_name='تأمين الموقع وإبعاد السكان بشريط عاكس او غيره')),
                ('proc_notify_authorities', models.BooleanField(default=False, verbose_name='إبلاغ الجهات المختصة (الشرطة / المجلس الأعلى للبيئة / نيابة التعدين)')),
                ('proc_prevent_handling', models.BooleanField(default=False, verbose_name='منع استخدام أو تداول المواد ووضعها تحت سيطرة شرطة التعدين')),
                ('proc_notify_violations', models.BooleanField(default=False, verbose_name='إبلاغ إدارة المخالفات')),
                ('proc_educate_owner', models.BooleanField(default=False, verbose_name='توعية صاحب الموقع بخطورة المواد')),
                ('owner_statements', models.TextField(blank=True, null=True, verbose_name='أقوال صاحب الموقع')),
                ('officer_signature_name', models.CharField(max_length=200, verbose_name='توقيع القائم بالضبط (الاسم)')),
                ('owner_signature_name', models.CharField(max_length=200, verbose_name='توقيع صاحب الموقع (الاسم)')),
                ('site_photos', models.FileField(blank=True, null=True, upload_to='mokhalafat/chemical_violations/site_photos/', verbose_name='صور للموقع')),
                ('material_photos', models.FileField(blank=True, null=True, upload_to='mokhalafat/chemical_violations/material_photos/', verbose_name='صور للمواد')),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='mokhalafat/chemical_violations/docs/', verbose_name='مستندات (إن وجدت)')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='الولاية')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'مخالفة المواد الكيميائية',
                'verbose_name_plural': 'مخالفات المواد الكيميائية',
            },
        ),
        migrations.CreateModel(
            name='AppChemicalMaterialsViolationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200, verbose_name='اسم المادة')),
                ('quantity', models.CharField(max_length=100, verbose_name='الكمية')),
                ('condition', models.CharField(max_length=100, verbose_name='الحالة')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mokhalafat.appchemicalmaterialsviolation', verbose_name='المخالفة')),
            ],
            options={
                'verbose_name': 'مادة مضبوطة',
                'verbose_name_plural': 'المواد المضبوطة',
            },
        ),
        migrations.CreateModel(
            name='AppChemicalMaterialsViolationWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشاهد')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='mokhalafat.appchemicalmaterialsviolation', verbose_name='المخالفة')),
            ],
            options={
                'verbose_name': 'شاهد',
                'verbose_name_plural': 'الشهود',
            },
        ),
    ]
