# Generated by Django 5.2.7 on 2026-06-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mokhalafat', '0005_appchemicalmaterialsviolation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appchemicalmaterialsviolation',
            name='material_photos',
        ),
        migrations.RemoveField(
            model_name='appchemicalmaterialsviolation',
            name='site_photos',
        ),
        migrations.RemoveField(
            model_name='appchemicalmaterialsviolation',
            name='supporting_documents',
        ),
        migrations.CreateModel(
            name='AppChemicalMaterialsViolationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('site_photo', 'صورة الموقع'), ('material_photo', 'صورة للمواد المضبوطة'), ('other_doc', 'أي مستندات أخرى')], max_length=50, verbose_name='نوع المرفق')),
                ('file', models.FileField(upload_to='mokhalafat/chemical_violations/attachments/', verbose_name='الملف المرفق')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mokhalafat.appchemicalmaterialsviolation', verbose_name='المخالفة')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
            },
        ),
    ]
