# Generated by Django 5.2.7 on 2026-06-14 13:56

from django.db import migrations
from django.contrib.auth.management import create_permissions
from django.apps import apps as global_apps

def create_chemical_violation_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Force Django to create permissions for 'mokhalafat'
    try:
        app_config = global_apps.get_app_config('mokhalafat')
        create_permissions(app_config, verbosity=0)
    except Exception:
        pass
    
    group_name = 'chemical_violations_users'
    group, created = Group.objects.get_or_create(name=group_name)
    
    models = [
        'appchemicalmaterialsviolation',
        'appchemicalmaterialsviolationitem',
        'appchemicalmaterialsviolationwitness',
        'appchemicalmaterialsviolationattachment',
    ]
    
    permissions_to_add = []
    for model_name in models:
        try:
            ct = ContentType.objects.get(app_label='mokhalafat', model=model_name)
            for action in ['view', 'add', 'change']:
                codename = f'{action}_{model_name}'
                try:
                    perm = Permission.objects.get(content_type=ct, codename=codename)
                    permissions_to_add.append(perm)
                except Permission.DoesNotExist:
                    pass
        except ContentType.DoesNotExist:
            pass
                
    if permissions_to_add:
        group.permissions.set(permissions_to_add)


def remove_chemical_violation_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='chemical_violations_users').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mokhalafat', '0006_remove_appchemicalmaterialsviolation_material_photos_and_more'),
    ]

    operations = [
        migrations.RunPython(create_chemical_violation_group, remove_chemical_violation_group),
    ]
