# Generated by Django 5.2.7 on 2026-07-20 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0139_lkpstate_code'),
        ('mokhalafat', '0007_auto_20260614_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='appchemicalmaterialsviolation',
            name='record_state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_smrc'), (3, 'state_approved'), (8, 'state_canceled')], default=1, verbose_name='record_state'),
        ),
        migrations.AddField(
            model_name='appchemicalmaterialsviolation',
            name='source_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemical_violations', to='company_profile.lkpstate', verbose_name='ولاية المصدر'),
        ),
        migrations.AlterField(
            model_name='appchemicalmaterialsviolation',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemical_violations_incident_state', to='company_profile.lkpstate', verbose_name='الولاية'),
        ),
    ]
