# Generated by Django 5.2.7 on 2026-07-20 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0139_lkpstate_code'),
        ('mokhalafat', '0009_create_kimyaeya_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalViolationStateRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='الولاية')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='chemical_violation_representative', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ممثل ولاية - مخالفات كيميائية',
                'verbose_name_plural': 'ممثلو الولايات - مخالفات كيميائية',
            },
        ),
    ]
