# Generated by Django 5.2.7 on 2026-07-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mokhalafat', '0010_add_chemical_violation_state_representative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appchemicalmaterialsviolation',
            name='state',
        ),
    ]
