# Generated by Django 5.1 on 2024-12-11 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0084_alter_appborrowmaterial_company_from_str'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldTravelTraditionalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gold_travel_traditional', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'gold_travel_user',
                'verbose_name_plural': 'gold_travel_users',
            },
        ),
        migrations.CreateModel(
            name='LkpJihatAlaisdar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
            ],
            options={
                'verbose_name': 'jihat_alaisdar',
                'verbose_name_plural': 'jihat_alaisdar',
            },
        ),
        migrations.CreateModel(
            name='LkpSoag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
            ],
            options={
                'verbose_name': 'Soag',
                'verbose_name_plural': 'Soag',
            },
        ),
        migrations.CreateModel(
            name='GoldTravelTraditionalUserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel_traditional.goldtraveltraditionaluser')),
                ('soug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel_traditional.lkpsoag', verbose_name='Soag')),
            ],
            options={
                'verbose_name': 'gold_travel_user_detail',
                'verbose_name_plural': 'gold_travel_user_details',
            },
        ),
        migrations.CreateModel(
            name='AppMoveGoldTraditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('issue_date', models.DateField(verbose_name='issue_date')),
                ('muharir_alaistimara', models.CharField(max_length=150, verbose_name='muharir_alaistimara')),
                ('almustafid_name', models.CharField(max_length=150, verbose_name='almustafid_name')),
                ('almustafid_phone', models.CharField(max_length=30, verbose_name='almustafid_phone')),
                ('gold_weight_in_gram', models.FloatField(verbose_name='gold_weight_in_gram')),
                ('almushtari_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='almushtari_name')),
                ('tarikh_akhar_tajdid', models.DateField(blank=True, null=True, verbose_name='tarikh_akhar_tajdid')),
                ('state', models.IntegerField(choices=[(1, 'state_new'), (2, 'state_sold'), (3, 'state_expired'), (4, 'state_renew')], default=1, verbose_name='record_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('jihat_alaisdar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel_traditional.lkpjihatalaisdar', verbose_name='jihat_alaisdar')),
                ('wijhat_altarhil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel_traditional.lkpsoag', verbose_name='wijhat altarhil')),
            ],
            options={
                'verbose_name': 'Move Gold',
                'verbose_name_plural': 'Move Gold',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['code', 'almustafid_phone'], name='gold_travel_code_119fc8_idx')],
            },
        ),
    ]
