# Generated by Django 5.1 on 2024-12-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmovegoldtraditional',
            options={'ordering': ['-id'], 'verbose_name': 'Move Gold Traditional', 'verbose_name_plural': 'Move Gold Traditional'},
        ),
    ]
