# Generated by Django 5.1.4 on 2024-12-15 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0002_alter_appmovegoldtraditional_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmovegoldtraditional',
            name='tarikh_akhar_tajdid',
        ),
        migrations.AddField(
            model_name='appmovegoldtraditional',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='gold_travel_traditional.appmovegoldtraditional', verbose_name='parent'),
        ),
    ]
