# Generated by Django 5.1.4 on 2024-12-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0003_remove_appmovegoldtraditional_tarikh_akhar_tajdid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_new'), (2, 'state_sold'), (3, 'state_expired'), (4, 'state_renew'), (5, 'state_cancled')], default=1, verbose_name='record_state'),
        ),
    ]
