# Generated by Django 5.1.4 on 2024-12-16 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0004_alter_appmovegoldtraditional_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldtraveltraditionaluserdetail',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_travel_traditional.goldtraveltraditionaluser'),
        ),
    ]
