# Generated by Django 5.1.7 on 2025-04-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0005_alter_goldtraveltraditionaluserdetail_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmovegoldtraditional',
            name='attachement_file',
            field=models.ImageField(blank=True, null=True, upload_to='gold_travel_traditional/', verbose_name='attachement_file'),
        ),
    ]
