# Generated by Django 5.2.7 on 2026-04-26 08:02

import django.db.models.deletion
import gold_travel_traditional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0006_appmovegoldtraditional_attachement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='attachement_file',
            field=models.FileField(blank=True, null=True, upload_to=gold_travel_traditional.models.AppMoveGoldTraditional.attachement_path, verbose_name='attachement_file'),
        ),
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='jihat_alaisdar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel_traditional.lkpsoag', verbose_name='jihat_alaisdar'),
        ),
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='wijhat_altarhil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel_traditional.lkpjihatalaisdar', verbose_name='wijhat altarhil'),
        ),
        migrations.CreateModel(
            name='AppMoveGoldTraditionalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alloy_weight_gram', models.FloatField(verbose_name='وزن السبيكة بالجرام')),
                ('alloy_shape', models.IntegerField(choices=[(1, 'دائري'), (2, 'مستطيل')], verbose_name='شكل السبيكة')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='gold_travel_traditional.appmovegoldtraditional', verbose_name='master')),
            ],
            options={
                'verbose_name': 'تفاصيل السبيكة',
                'verbose_name_plural': 'تفاصيل السبائك',
            },
        ),
    ]
