# Generated by Django 5.2.7 on 2026-04-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0009_remove_gold_weight_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmovegoldtraditional',
            name='almustafid_identity',
            field=models.CharField(default='', max_length=50, verbose_name='almustafid_identity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appmovegoldtraditional',
            name='almustafid_identity_type',
            field=models.IntegerField(choices=[(1, 'identity_passport'), (2, 'identity_personal'), (3, 'identity_national_id'), (4, 'identity_driving_license')], default=1, verbose_name='almustafid_identity_type'),
        ),
    ]
