# Generated by Django 5.2.7 on 2026-04-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0010_appmovegoldtraditional_almustafid_identity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='almustafid_identity',
            field=models.CharField(max_length=50, verbose_name='رقم الإثبات'),
        ),
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='almustafid_identity_type',
            field=models.IntegerField(choices=[(1, 'identity_passport'), (2, 'identity_personal'), (3, 'identity_national_id'), (4, 'identity_driving_license')], default=1, verbose_name='نوع الإثبات'),
        ),
    ]
