# Generated by Django 5.2.7 on 2026-04-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0010_alter_appmovegoldtraditional_code_unique'),
        ('gold_travel_traditional', '0011_alter_appmovegoldtraditional_almustafid_identity_and_more'),
    ]

    operations = [
    ]
