# Generated by Django 5.2.7 on 2026-04-26 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0012_merge_20260426_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='jihat_alaisdar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel_traditional.lkpjihatalaisdar', verbose_name='jihat_alaisdar'),
        ),
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='wijhat_altarhil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel_traditional.lkpsoag', verbose_name='wijhat altarhil'),
        ),
    ]
