# Generated by Django 5.2.7 on 2026-04-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0138_alter_apphseaccidentreport_options'),
        ('gold_travel_traditional', '0013_alter_appmovegoldtraditional_jihat_alaisdar_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LkpSoag',
            new_name='LkpJihatAltarhil',
        ),
    ]
