# Generated by Django 5.2.7 on 2026-04-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0014_rename_lkpsoag_lkpjihataltarhil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lkpjihataltarhil',
            options={'verbose_name': 'جهة الوصول', 'verbose_name_plural': 'جهات الوصول'},
        ),
        migrations.RemoveField(
            model_name='appmovegoldtraditional',
            name='muharir_alaistimara',
        ),
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='jihat_alaisdar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel_traditional.lkpjihatalaisdar', verbose_name='جهة الإصدار'),
        ),
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='wijhat_altarhil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel_traditional.lkpjihataltarhil', verbose_name='جهة الوصول'),
        ),
    ]
