# Generated by Django 5.2.7 on 2026-04-26 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0015_alter_lkpjihataltarhil_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldTravelTraditionalUserJihatAlaisdar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jihat_alaisdar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel_traditional.lkpjihatalaisdar', verbose_name='جهة الإصدار')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_travel_traditional.goldtraveltraditionaluser')),
            ],
            options={
                'verbose_name': 'جهة الإصدار المعتمدة للمستخدم',
                'verbose_name_plural': 'جهات الإصدار المعتمدة للمستخدمين',
            },
        ),
        migrations.CreateModel(
            name='GoldTravelTraditionalUserJihatTarhil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_travel_traditional.goldtraveltraditionaluser')),
                ('wijhat_altarhil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel_traditional.lkpjihataltarhil', verbose_name='جهة الوصول')),
            ],
            options={
                'verbose_name': 'جهة الوصول المعتمدة للمستخدم',
                'verbose_name_plural': 'جهات الوصول المعتمدة للمستخدمين',
            },
        ),
        migrations.DeleteModel(
            name='GoldTravelTraditionalUserDetail',
        ),
    ]
