# Generated by Django 5.2.7 on 2026-04-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0016_goldtraveltraditionaluserjihatalaisdar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_new'), (2, 'state_sold'), (3, 'state_expired'), (4, 'state_renew'), (5, 'state_cancled'), (6, 'state_arrived')], default=1, verbose_name='record_state'),
        ),
    ]
