# Generated by Django 5.2.7 on 2026-04-27 13:59

import gold_travel_traditional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0018_alter_appmovegoldtraditional_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmovegoldtraditional',
            name='almustafid_identity_attachement',
            field=models.FileField(blank=True, null=True, upload_to=gold_travel_traditional.models.AppMoveGoldTraditional.attachement_path, verbose_name='مرفق الإثبات'),
        ),
    ]
