# Generated by Django 5.2.7 on 2026-06-30 14:03

import gold_travel_traditional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0019_appmovegoldtraditional_almustafid_identity_attachement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='almustafid_identity_attachement',
            field=models.FileField(default='', upload_to=gold_travel_traditional.models.AppMoveGoldTraditional.attachement_path, verbose_name='مرفق الإثبات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='attachement_file',
            field=models.FileField(default='', upload_to=gold_travel_traditional.models.AppMoveGoldTraditional.attachement_path, verbose_name='attachement_file'),
            preserve_default=False,
        ),
    ]
