# Generated by Django 5.2.7 on 2026-06-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0020_alter_appmovegoldtraditional_almustafid_identity_attachement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmovegoldtraditional',
            name='renew_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='renew_date'),
        ),
    ]
