# Generated by Django 5.2.7 on 2026-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0021_appmovegoldtraditional_renew_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldtraveltraditionaluser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'جهة الإصدار'), (2, 'جهة الوصول'), (3, 'كلاهما')], default=1, verbose_name='user_type'),
        ),
    ]
