# Generated by Django 5.2.7 on 2026-07-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0022_goldtraveltraditionaluser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldtraveltraditionaluser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'جهة الإصدار'), (2, 'جهة الوصول'), (3, 'كلاهما'), (4, 'مدير الولاية')], default=1, verbose_name='user_type'),
        ),
    ]
