# Generated by Django 5.2.7 on 2026-07-02 12:51

import gold_travel_traditional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0024_alter_goldtraveltraditionaluser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='attachement_file',
            field=models.FileField(upload_to=gold_travel_traditional.models.AppMoveGoldTraditional.attachement_path, verbose_name='صورة الذهب المرحل'),
        ),
    ]
