# Generated by Django 5.2.7 on 2026-07-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0025_alter_appmovegoldtraditional_attachement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegoldtraditionaldetail',
            name='alloy_shape',
            field=models.IntegerField(choices=[(1, 'دائري'), (2, 'مستطيل'), (3, 'أخرى')], verbose_name='شكل السبيكة'),
        ),
    ]
