# Generated by Django 5.2.7 on 2026-07-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0026_alter_appmovegoldtraditionaldetail_alloy_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmovegoldtraditional',
            name='melt_workshop',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ورشة الصهر'),
        ),
        migrations.AddField(
            model_name='appmovegoldtraditional',
            name='standardization_lab',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='مختبر المعايرة'),
        ),
    ]
