# Generated by Django 5.2.7 on 2026-07-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0027_appmovegoldtraditional_melt_workshop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmovegoldtraditional',
            name='melt_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الصهر'),
        ),
        migrations.AlterField(
            model_name='goldtraveltraditionaluser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'جهة الإصدار'), (2, 'جهة الوصول'), (3, 'جهة الإصدار والوصول'), (4, 'مدير الولاية'), (5, 'مشاهد الولاية')], default=1, verbose_name='user_type'),
        ),
    ]
