# Generated by Django 5.2.7 on 2026-07-02 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0139_lkpstate_code'),
        ('gold_travel_traditional', '0028_appmovegoldtraditional_melt_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeltBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('melt_date', models.DateField(verbose_name='تاريخ الصهر')),
                ('melt_workshop', models.CharField(max_length=150, verbose_name='ورشة الصهر')),
                ('standardization_lab', models.CharField(max_length=150, verbose_name='مختبر المعايرة')),
                ('state', models.IntegerField(choices=[(1, 'قيد الصهر'), (2, 'مكتمل')], default=1, verbose_name='state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'دفعة الصهر',
                'verbose_name_plural': 'دفعات الصهر',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='appmovegoldtraditional',
            name='melt_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='gold_travel_traditional.meltbatch', verbose_name='دفعة الصهر'),
        ),
    ]
