# Generated by Django 5.2.7 on 2026-07-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0139_lkpstate_code'),
        ('gold_travel_traditional', '0029_meltbatch_appmovegoldtraditional_melt_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meltbatch',
            name='source_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='source_state'),
        ),
    ]
