# Generated by Django 5.2.7 on 2026-07-02 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0139_lkpstate_code'),
        ('gold_travel_traditional', '0030_alter_meltbatch_source_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meltbatch',
            name='source_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='meltbatch',
            name='state',
            field=models.IntegerField(choices=[(1, 'قيد الصهر'), (2, 'مكتمل')], default=1, verbose_name='record_state'),
        ),
    ]
