# Generated by Django 5.2.7 on 2026-07-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0032_sale_appmovegoldtraditional_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meltbatch',
            options={'ordering': ['-id'], 'verbose_name': 'استمارة تسييح ومعاييرة', 'verbose_name_plural': 'استمارات تسييح ومعاييرة'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-id'], 'verbose_name': 'استمارة بيع', 'verbose_name_plural': 'استمارات البيع'},
        ),
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_new'), (3, 'state_expired'), (4, 'state_renew'), (5, 'state_cancled'), (6, 'وصل للوجهة')], default=1, verbose_name='record_state'),
        ),
    ]
