# Generated by Django 5.2.7 on 2026-07-02 20:38

import gold_travel_traditional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0033_alter_meltbatch_options_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='almustafid_identity_attachement',
            field=models.ImageField(upload_to=gold_travel_traditional.models.AppMoveGoldTraditional.attachement_path, verbose_name='مرفق الإثبات'),
        ),
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='attachement_file',
            field=models.ImageField(upload_to=gold_travel_traditional.models.AppMoveGoldTraditional.attachement_path, verbose_name='صورة الذهب المرحل'),
        ),
    ]
