# Generated by Django 5.2.7 on 2026-07-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0034_alter_appmovegoldtraditional_almustafid_identity_attachement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldtraveltraditionaluserjihattarhil',
            name='can_arrive',
            field=models.BooleanField(default=True, verbose_name='يمكنه التوصيل'),
        ),
    ]
