# Generated by Django 5.2.7 on 2026-07-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0035_goldtraveltraditionaluserjihattarhil_can_arrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='state',
            field=models.IntegerField(choices=[(1, 'قيد البيع'), (2, 'مكتمل')], default=1, verbose_name='record_state'),
        ),
    ]
