# Generated by Django 5.2.7 on 2026-07-05 14:09

import django.db.models.deletion
import gold_travel_traditional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0037_storage_appmovegoldtraditional_storage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['-id'], 'verbose_name': 'شهادة تخزين', 'verbose_name_plural': 'شهادات التخزين'},
        ),
        migrations.AddField(
            model_name='appmovegoldtraditional',
            name='arrival_attachement',
            field=models.ImageField(blank=True, null=True, upload_to=gold_travel_traditional.models.AppMoveGoldTraditional.attachement_path, verbose_name='مرفق الاستمارة'),
        ),
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='gold_travel_traditional.storage', verbose_name='شهادة تخزين'),
        ),
    ]
