# Generated by Django 5.2.7 on 2026-07-05 14:12

import gold_travel_traditional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0038_alter_storage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='arrival_attachement',
            field=models.ImageField(blank=True, help_text='ارفاق استمارة  الترحيل', null=True, upload_to=gold_travel_traditional.models.AppMoveGoldTraditional.attachement_path, verbose_name='مرفق الاستمارة'),
        ),
    ]
