# Generated by Django 5.2.7 on 2026-07-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0039_alter_appmovegoldtraditional_arrival_attachement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='melt_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='gold_travel_traditional.meltbatch', verbose_name='استمارة تسييح ومعايرة'),
        ),
    ]
