# Generated by Django 5.2.7 on 2026-07-06 16:56

import gold_travel_traditional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0040_alter_appmovegoldtraditional_melt_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmovegoldtraditional',
            name='almustafid_photo',
            field=models.ImageField(blank=True, null=True, upload_to=gold_travel_traditional.models.AppMoveGoldTraditional.attachement_path, verbose_name='صورة المستفيد'),
        ),
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='almustafid_identity',
            field=models.CharField(max_length=50, verbose_name='الرقم الوطني'),
        ),
    ]
