# Generated by Django 5.2.7 on 2026-07-08 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0139_lkpstate_code'),
        ('gold_travel_traditional', '0041_appmovegoldtraditional_almustafid_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldTravelTraditionalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_days', models.IntegerField(default=3, verbose_name='مدة الصلاحية بالأيام')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gold_travel_config', to='company_profile.lkpstate', verbose_name='الولاية')),
            ],
            options={
                'verbose_name': 'إعدادات الولاية',
                'verbose_name_plural': 'إعدادات الولايات',
            },
        ),
    ]
