# Generated by Django 5.2.7 on 2026-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0042_goldtraveltraditionalstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmovegoldtraditional',
            name='expiry_days',
            field=models.IntegerField(default=3, verbose_name='مدة الصلاحية بالأيام'),
        ),
    ]
