# Generated by Django 5.2.7 on 2026-07-09 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0139_lkpstate_code'),
        ('gold_travel', '0044_lkpowner_authorized_person_name_and_more'),
        ('gold_travel_traditional', '0043_appmovegoldtraditional_expiry_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='buyer',
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_exporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gold_travel.lkpowner', verbose_name='مصدر'),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_type',
            field=models.CharField(choices=[('exporter', 'مصدر'), ('saig', 'صائغ')], default='exporter', max_length=10, verbose_name='نوع المشتري'),
        ),
        migrations.CreateModel(
            name='LkpSaig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='code')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
            ],
            options={
                'verbose_name': 'صائغ',
                'verbose_name_plural': 'صائغ',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_saig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gold_travel_traditional.lkpsaig', verbose_name='صائغ'),
        ),
    ]
