# Generated by Django 5.2.7 on 2026-07-09 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0044_lkpowner_authorized_person_name_and_more'),
        ('gold_travel_traditional', '0044_remove_sale_buyer_sale_buyer_exporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='buyer_exporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gold_travel.lkpowner', verbose_name='مصدر'),
        ),
    ]
