# Generated by Django 5.2.7 on 2026-07-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0045_alter_sale_buyer_exporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmovegoldtraditional',
            name='renew_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='تاريخ التجديد'),
        ),
    ]
