# Generated by Django 5.2.7 on 2026-07-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0046_alter_appmovegoldtraditional_renew_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='note',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ملاحظات'),
        ),
    ]
