# Generated by Django 5.2.7 on 2026-07-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0051_meltbatch_sale_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meltbatchdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
