# Generated by Django 5.2.7 on 2026-07-22 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0139_lkpstate_code'),
        ('gold_travel', '0044_lkpowner_authorized_person_name_and_more'),
        ('gold_travel_traditional', '0052_alter_meltbatchdetail_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appmovegoldtraditional',
            index=models.Index(fields=['state', 'issue_date'], name='gold_travel_state_c49d44_idx'),
        ),
        migrations.AddIndex(
            model_name='appmovegoldtraditional',
            index=models.Index(fields=['source_state', 'state'], name='gold_travel_source__5f1269_idx'),
        ),
        migrations.AddIndex(
            model_name='appmovegoldtraditional',
            index=models.Index(fields=['jihat_alaisdar', 'state'], name='gold_travel_jihat_a_396e01_idx'),
        ),
        migrations.AddIndex(
            model_name='appmovegoldtraditional',
            index=models.Index(fields=['wijhat_altarhil', 'state'], name='gold_travel_wijhat__36c3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='meltbatch',
            index=models.Index(fields=['source_state', 'state'], name='gold_travel_source__28e81c_idx'),
        ),
        migrations.AddIndex(
            model_name='meltbatch',
            index=models.Index(fields=['melt_date'], name='gold_travel_melt_da_289504_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['source_state', 'state'], name='gold_travel_source__278a73_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='gold_travel_sale_da_66e94d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['buyer_type'], name='gold_travel_buyer_t_df5346_idx'),
        ),
        migrations.AddIndex(
            model_name='storage',
            index=models.Index(fields=['source_state', 'state'], name='gold_travel_source__d4d1cc_idx'),
        ),
        migrations.AddIndex(
            model_name='storage',
            index=models.Index(fields=['storage_date'], name='gold_travel_storage_bb7886_idx'),
        ),
    ]
