# Generated by Django 5.2.7 on 2026-08-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0053_appmovegoldtraditional_gold_travel_state_c49d44_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jihat_alaisdar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_travel_traditional.lkpjihatalaisdar', verbose_name='جهة الإصدار')),
                ('wijhat_altarhil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_travel_traditional.lkpjihataltarhil', verbose_name='جهة الوصول')),
            ],
            options={
                'verbose_name': 'مسار الترحيل',
                'verbose_name_plural': 'مسارات الترحيل',
                'unique_together': {('jihat_alaisdar', 'wijhat_altarhil')},
            },
        ),
    ]
