# Generated by Django 5.0.2 on 2025-03-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0116_appfuelpermissiondetail_fuel_actual_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('date', models.DateField(verbose_name='date')),
                ('state', models.IntegerField(choices=[(1, 'TRADITIONAL_STATE_DRAFT'), (2, 'TRADITIONAL_STATE_CONFIRMED2'), (4, 'TRADITIONAL_STATE_APPROVED')], default=1, verbose_name='record_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Daily Report',
                'verbose_name_plural': 'Daily Reports',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LkpSoag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traditional_state', to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Soag',
                'verbose_name_plural': 'Soag',
            },
        ),
        migrations.CreateModel(
            name='DailyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('hajr_type', models.IntegerField(choices=[(1, 'hajr_type_toahin'), (2, 'hajr_type_bolimal')], default=1, verbose_name='hajr_type')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.dailyreport', verbose_name='daily_report')),
                ('soag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpsoag', verbose_name='soag')),
            ],
            options={
                'verbose_name': 'Daily Income',
                'verbose_name_plural': 'Daily Incomes',
            },
        ),
        migrations.CreateModel(
            name='TahsilForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('form_count', models.IntegerField(verbose_name='form_count')),
                ('gold_in_gram', models.FloatField(verbose_name='gold_in_gram')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.dailyreport', verbose_name='daily_report')),
                ('soag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpsoag', verbose_name='soag')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Tahsil Form',
                'verbose_name_plural': 'Tahsil Forms',
            },
        ),
        migrations.CreateModel(
            name='WardHajr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('hajr_type', models.IntegerField(choices=[(1, 'hajr_type_toahin'), (2, 'hajr_type_bolimal')], default=1, verbose_name='hajr_type')),
                ('hajr_count', models.IntegerField(verbose_name='hajr_count')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.dailyreport', verbose_name='daily_report')),
                ('soag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpsoag', verbose_name='soag')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Ward Hajr',
                'verbose_name_plural': 'Ward Hajrs',
            },
        ),
    ]
