# Generated by Django 5.0.2 on 2025-03-17 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0116_appfuelpermissiondetail_fuel_actual_qty'),
        ('traditional_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpsoag',
            name='locality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='company_profile.lkpstate', verbose_name='state'),
            preserve_default=False,
        ),
    ]
