# Generated by Django 5.0.2 on 2025-03-17 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0003_alter_lkpsoag_locality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldMor7ala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('weight_in_gram', models.FloatField(verbose_name='weight_in_gram')),
                ('owner_name', models.CharField(max_length=100, verbose_name='owner_name')),
                ('destination', models.CharField(max_length=100, verbose_name='destination')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.dailyreport', verbose_name='daily_report')),
                ('soag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpsoag', verbose_name='soag')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Gold Mor7ala',
                'verbose_name_plural': 'Gold Mor7alas',
            },
        ),
        migrations.CreateModel(
            name='KartaMor7ala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('galabat_count', models.IntegerField(verbose_name='galabat_count')),
                ('destination', models.CharField(max_length=100, verbose_name='destination')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.dailyreport', verbose_name='daily_report')),
                ('soag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpsoag', verbose_name='soag')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Karta Mor7ala',
                'verbose_name_plural': 'Karta Mor7alas',
            },
        ),
    ]
