# Generated by Django 5.0.2 on 2025-03-17 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0004_goldmor7ala_kartamor7ala'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LkpMojam3atTawa7in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('owner_name', models.CharField(max_length=100, verbose_name='owner_name')),
                ('toa7in_type', models.IntegerField(choices=[(1, 'toahin_type_jaf'), (2, 'toahin_type_ratib')], default=1, verbose_name='toa7in_type')),
                ('toa7in_count', models.IntegerField(verbose_name='toa7in_count')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='traditional/mojam3at_tawa7in/', verbose_name='attachment')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('soag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpsoag', verbose_name='soag')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Mojam3at Tawa7in',
                'verbose_name_plural': 'Mojam3at Tawa7in',
            },
        ),
        migrations.CreateModel(
            name='LkpSaig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='traditional/saig/', verbose_name='attachment')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('soag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpsoag', verbose_name='soag')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Saig',
                'verbose_name_plural': 'Saga',
            },
        ),
    ]
