# Generated by Django 5.0.2 on 2025-03-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0005_lkpmojam3attawa7in_lkpsaig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lkpmojam3attawa7in',
            name='toa7in_count',
        ),
        migrations.RemoveField(
            model_name='lkpmojam3attawa7in',
            name='toa7in_type',
        ),
        migrations.AddField(
            model_name='lkpmojam3attawa7in',
            name='toa7in_jafa_count',
            field=models.IntegerField(default=0, verbose_name='toa7in_jafa_count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkpmojam3attawa7in',
            name='toa7in_ratiba_count',
            field=models.IntegerField(default=0, verbose_name='toa7in_ratiba_count'),
            preserve_default=False,
        ),
    ]
