# Generated by Django 5.0.2 on 2025-03-17 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0116_appfuelpermissiondetail_fuel_actual_qty'),
        ('traditional_app', '0006_remove_lkpmojam3attawa7in_toa7in_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lkpmojam3attawa7in',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='lkpsaig',
            name='attachment',
        ),
        migrations.AddField(
            model_name='lkpmojam3attawa7in',
            name='pid_attachment',
            field=models.FileField(blank=True, null=True, upload_to='traditional/mojam3at_tawa7in/', verbose_name='pid_attachment'),
        ),
        migrations.AddField(
            model_name='lkpsaig',
            name='pid_attachment',
            field=models.FileField(blank=True, null=True, upload_to='traditional/saig/', verbose_name='pid_attachment'),
        ),
        migrations.AlterField(
            model_name='lkpsaig',
            name='name',
            field=models.CharField(max_length=100, verbose_name='owner_name'),
        ),
        migrations.CreateModel(
            name='Lkp2bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='owner_name')),
                ('cordinates', models.TextField(max_length=256, verbose_name='cordinates')),
                ('pid_attachment', models.FileField(blank=True, null=True, upload_to='traditional/2bar/', verbose_name='pid_attachment')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkplocality', verbose_name='locality')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': '2bar_khtot_2ntaj',
                'verbose_name_plural': '2bar_khtot_2ntaj',
            },
        ),
        migrations.CreateModel(
            name='Lkp2jhizatBahth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='owner_name')),
                ('pid_attachment', models.FileField(blank=True, null=True, upload_to='traditional/2jhizat_bahth/', verbose_name='pid_attachment')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkplocality', verbose_name='locality')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': '2jhizat Bahth',
                'verbose_name_plural': '2jhizat Bahth',
            },
        ),
        migrations.CreateModel(
            name='Lkp7ofrKabira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='owner_name')),
                ('cordinates', models.TextField(max_length=256, verbose_name='cordinates')),
                ('status', models.IntegerField(choices=[(1, 'state_active'), (2, 'state_inactive')], default=1, verbose_name='status')),
                ('pid_attachment', models.FileField(blank=True, null=True, upload_to='traditional/7ofr_kabira/', verbose_name='pid_attachment')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkplocality', verbose_name='locality')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': '7ofr Kabira',
                'verbose_name_plural': '7ofr Kabira',
            },
        ),
        migrations.CreateModel(
            name='LkpGrabeel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='owner_name')),
                ('type', models.IntegerField(choices=[(1, 'type_big'), (2, 'type_small')], default=1, verbose_name='type')),
                ('pid_attachment', models.FileField(blank=True, null=True, upload_to='traditional/grabeel/', verbose_name='pid_attachment')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkplocality', verbose_name='locality')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Grabeel',
                'verbose_name_plural': 'Grabeel',
            },
        ),
        migrations.CreateModel(
            name='LkpKhalatat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='owner_name')),
                ('pid_attachment', models.FileField(blank=True, null=True, upload_to='traditional/khalatat/', verbose_name='pid_attachment')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkplocality', verbose_name='locality')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Khalatat',
                'verbose_name_plural': 'Khalatat',
            },
        ),
        migrations.CreateModel(
            name='LkpSmallProcessingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='owner_name')),
                ('bolimal_count', models.IntegerField(verbose_name='bolimal_count')),
                ('khalatat_count', models.IntegerField(verbose_name='khalatat_count')),
                ('kasarat_count', models.IntegerField(verbose_name='kasarat_count')),
                ('pid_attachment', models.FileField(blank=True, null=True, upload_to='traditional/small_processing_unit/', verbose_name='pid_attachment')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkplocality', verbose_name='locality')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Small Processing Unit',
                'verbose_name_plural': 'Small Processing Units',
            },
        ),
        migrations.CreateModel(
            name='LkpSosalGold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='owner_name')),
                ('pid_attachment', models.FileField(blank=True, null=True, upload_to='traditional/sosl_gold/', verbose_name='pid_attachment')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkplocality', verbose_name='locality')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Sosal Gold',
                'verbose_name_plural': 'Sosal Gold',
            },
        ),
    ]
