# Generated by Django 5.0.2 on 2025-03-17 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0116_appfuelpermissiondetail_fuel_actual_qty'),
        ('traditional_app', '0008_rename_goldmor7ala_dailygoldmor7ala_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('no3_elta3god', models.IntegerField(choices=[(1, 'employee'), (2, 't3agood'), (3, 'el7ag'), (4, 'goat_2mnia')], default=1, verbose_name='no3_elta3god')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('job', models.CharField(max_length=100, verbose_name='job')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('work_place', models.CharField(max_length=100, verbose_name='work_place')),
                ('contract_start_date', models.DateField(verbose_name='contract_start_date')),
                ('contract_end_date', models.DateField(verbose_name='contract_end_date')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.employee', verbose_name='employee')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Employee Project',
                'verbose_name_plural': 'Employee Projects',
            },
        ),
        migrations.CreateModel(
            name='RentedApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('apartment_type', models.IntegerField(choices=[(1, 'office'), (2, '2stra7a'), (3, 'sakan_modir')], default=1, verbose_name='rented_type')),
                ('monthly_rent', models.FloatField(verbose_name='monthly_rent')),
                ('contract_start_date', models.DateField(verbose_name='contract_start_date')),
                ('contract_end_date', models.DateField(verbose_name='contract_end_date')),
                ('owner_name', models.CharField(max_length=100, verbose_name='owner_name')),
                ('contract_attachment', models.FileField(blank=True, null=True, upload_to='traditional/rented_apartments/', verbose_name='contract_attachment')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Rented Apartment',
                'verbose_name_plural': 'Rented Apartments',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('vehicle_type', models.IntegerField(choices=[(1, 'car'), (2, 'motor')], default=1, verbose_name='vehicle_type')),
                ('plate_no', models.CharField(max_length=100, verbose_name='plate_no')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='RentedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('monthly_rent', models.FloatField(verbose_name='monthly_rent')),
                ('contract_start_date', models.DateField(verbose_name='contract_start_date')),
                ('contract_end_date', models.DateField(verbose_name='contract_end_date')),
                ('contract_attachment', models.FileField(blank=True, null=True, upload_to='traditional/rented_vehicles/', verbose_name='contract_attachment')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('rented_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.employee', verbose_name='rented_for')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'Rented Vehicle',
                'verbose_name_plural': 'Rented Vehicles',
            },
        ),
    ]
