# Generated by Django 5.0.2 on 2025-03-17 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0009_employee_employeeproject_rentedapartment_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailygoldmor7ala',
            options={'verbose_name': 'الذهب المنتج والمرحل', 'verbose_name_plural': 'الذهب المنتج والمرحل'},
        ),
        migrations.AlterModelOptions(
            name='dailygrabeel',
            options={'verbose_name': 'غربال', 'verbose_name_plural': 'غرابيل'},
        ),
        migrations.AlterModelOptions(
            name='dailyhofrkabira',
            options={'verbose_name': 'حفرة كبيرة', 'verbose_name_plural': 'حفر كبيرة'},
        ),
        migrations.AlterModelOptions(
            name='dailyincome',
            options={'verbose_name': 'الإيراد اليومي', 'verbose_name_plural': 'الإيراد اليومي'},
        ),
        migrations.AlterModelOptions(
            name='dailykartamor7ala',
            options={'verbose_name': 'الكرتة المرحلة', 'verbose_name_plural': 'الكرتة المرحلة من الاسواق'},
        ),
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['-date'], 'verbose_name': 'التقرير اليومي', 'verbose_name_plural': 'التقارير اليومية'},
        ),
        migrations.AlterModelOptions(
            name='dailysmallprocessingunit',
            options={'verbose_name': 'وحدة معالجة صغيرة', 'verbose_name_plural': 'وحدات المعالجة الصغيرة'},
        ),
        migrations.AlterModelOptions(
            name='dailytahsilform',
            options={'verbose_name': 'استمارة تحصيل', 'verbose_name_plural': 'استمارات التحصيل'},
        ),
        migrations.AlterModelOptions(
            name='dailywardhajr',
            options={'verbose_name': 'وارد حجر', 'verbose_name_plural': 'وارد حجر'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='employeeproject',
            options={'verbose_name': 'موظف مشروع', 'verbose_name_plural': 'موظفي المشروع'},
        ),
        migrations.AlterModelOptions(
            name='lkp2bar',
            options={'verbose_name': 'بئر/خط انتاج', 'verbose_name_plural': 'ابار/خطوط انتاج'},
        ),
        migrations.AlterModelOptions(
            name='lkp2jhizatbahth',
            options={'verbose_name': 'جهاز بحث/إستكشاف', 'verbose_name_plural': 'اجهزة بحث/استكشاف'},
        ),
        migrations.AlterModelOptions(
            name='lkp7ofrkabira',
            options={'verbose_name': 'حفرة كبيرة', 'verbose_name_plural': 'حفر كبيرة'},
        ),
        migrations.AlterModelOptions(
            name='lkpgrabeel',
            options={'verbose_name': 'غربال', 'verbose_name_plural': 'غرابيل'},
        ),
        migrations.AlterModelOptions(
            name='lkpkhalatat',
            options={'verbose_name': 'خلاط', 'verbose_name_plural': 'خلاطات'},
        ),
        migrations.AlterModelOptions(
            name='lkpmojam3attawa7in',
            options={'verbose_name': 'مجمع طواحين', 'verbose_name_plural': 'مجمعات طواحين'},
        ),
        migrations.AlterModelOptions(
            name='lkpsaig',
            options={'verbose_name': 'صائغ', 'verbose_name_plural': 'صاغة'},
        ),
        migrations.AlterModelOptions(
            name='lkpsmallprocessingunit',
            options={'verbose_name': 'وحدة معالجة صغيرة', 'verbose_name_plural': 'وحدات المعالجة الصغيرة'},
        ),
        migrations.AlterModelOptions(
            name='lkpsoag',
            options={'verbose_name': 'سوق', 'verbose_name_plural': 'أسواق'},
        ),
        migrations.AlterModelOptions(
            name='lkpsosalgold',
            options={'verbose_name': 'ذهب صوصال', 'verbose_name_plural': 'ذهب صوصال'},
        ),
        migrations.AlterModelOptions(
            name='rentedapartment',
            options={'verbose_name': 'عقار مستأجر', 'verbose_name_plural': 'عقارات مستأجرة'},
        ),
        migrations.AlterModelOptions(
            name='rentedvehicle',
            options={'verbose_name': 'متحرك مستأجرة', 'verbose_name_plural': 'متحركات مستأجرة'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'المركبة', 'verbose_name_plural': 'المركبات'},
        ),
        migrations.AlterField(
            model_name='dailygoldmor7ala',
            name='soag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpsoag', verbose_name='السوق'),
        ),
        migrations.AlterField(
            model_name='dailygoldmor7ala',
            name='weight_in_gram',
            field=models.FloatField(verbose_name='الوزن بالجرام'),
        ),
        migrations.AlterField(
            model_name='dailygrabeel',
            name='grabeel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpgrabeel', verbose_name='غربال'),
        ),
        migrations.AlterField(
            model_name='dailygrabeel',
            name='weight_in_gram',
            field=models.FloatField(verbose_name='الوزن بالجرام'),
        ),
        migrations.AlterField(
            model_name='dailyhofrkabira',
            name='hofr_kabira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkp7ofrkabira', verbose_name='حفرة كبيرة'),
        ),
        migrations.AlterField(
            model_name='dailyhofrkabira',
            name='weight_in_gram',
            field=models.FloatField(verbose_name='الوزن بالجرام'),
        ),
        migrations.AlterField(
            model_name='dailyincome',
            name='hajr_type',
            field=models.IntegerField(choices=[(1, 'طواحين'), (2, 'بوليمل')], default=1, verbose_name='نوع الحجر'),
        ),
        migrations.AlterField(
            model_name='dailyincome',
            name='soag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpsoag', verbose_name='السوق'),
        ),
        migrations.AlterField(
            model_name='dailykartamor7ala',
            name='galabat_count',
            field=models.IntegerField(verbose_name='عدد القلابات'),
        ),
        migrations.AlterField(
            model_name='dailykartamor7ala',
            name='soag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpsoag', verbose_name='السوق'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='state',
            field=models.IntegerField(choices=[(1, 'مسودة'), (2, 'تأكيد اولي'), (3, 'تأكيد نهائي'), (4, 'إعتماد')], default=1, verbose_name='record_state'),
        ),
        migrations.AlterField(
            model_name='dailysmallprocessingunit',
            name='small_processing_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpsmallprocessingunit', verbose_name='وحدة معالجة صغيرة'),
        ),
        migrations.AlterField(
            model_name='dailysmallprocessingunit',
            name='weight_in_gram',
            field=models.FloatField(verbose_name='الوزن بالجرام'),
        ),
        migrations.AlterField(
            model_name='dailytahsilform',
            name='form_count',
            field=models.IntegerField(verbose_name='عدد الإستمارات'),
        ),
        migrations.AlterField(
            model_name='dailytahsilform',
            name='gold_in_gram',
            field=models.FloatField(verbose_name='كمية الذهب بالجرام'),
        ),
        migrations.AlterField(
            model_name='dailytahsilform',
            name='soag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpsoag', verbose_name='السوق'),
        ),
        migrations.AlterField(
            model_name='dailywardhajr',
            name='hajr_count',
            field=models.IntegerField(verbose_name='عدد الجوالات'),
        ),
        migrations.AlterField(
            model_name='dailywardhajr',
            name='hajr_type',
            field=models.IntegerField(choices=[(1, 'طواحين'), (2, 'بوليمل')], default=1, verbose_name='نوع الحجر'),
        ),
        migrations.AlterField(
            model_name='dailywardhajr',
            name='soag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpsoag', verbose_name='السوق'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(max_length=100, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='no3_elta3god',
            field=models.IntegerField(choices=[(1, 'موظف'), (2, 'متعاقد'), (3, 'ملحق'), (4, 'قوات أمنية')], default=1, verbose_name='نوع التعاقد'),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='contract_end_date',
            field=models.DateField(verbose_name='تاريخ نهاية العقد'),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='contract_start_date',
            field=models.DateField(verbose_name='تاريخ بداية العقد'),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='work_place',
            field=models.CharField(max_length=100, verbose_name='موقع العمل'),
        ),
        migrations.AlterField(
            model_name='lkp2bar',
            name='cordinates',
            field=models.TextField(max_length=256, verbose_name='الإحداثيات'),
        ),
        migrations.AlterField(
            model_name='lkp2bar',
            name='pid_attachment',
            field=models.FileField(blank=True, null=True, upload_to='traditional/2bar/', verbose_name='صورة من إثبات الشخصية'),
        ),
        migrations.AlterField(
            model_name='lkp2jhizatbahth',
            name='pid_attachment',
            field=models.FileField(blank=True, null=True, upload_to='traditional/2jhizat_bahth/', verbose_name='صورة من إثبات الشخصية'),
        ),
        migrations.AlterField(
            model_name='lkp7ofrkabira',
            name='cordinates',
            field=models.TextField(max_length=256, verbose_name='الإحداثيات'),
        ),
        migrations.AlterField(
            model_name='lkp7ofrkabira',
            name='pid_attachment',
            field=models.FileField(blank=True, null=True, upload_to='traditional/7ofr_kabira/', verbose_name='صورة من إثبات الشخصية'),
        ),
        migrations.AlterField(
            model_name='lkp7ofrkabira',
            name='status',
            field=models.IntegerField(choices=[(1, 'منتجة'), (2, 'غير منتجة')], default=1, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='lkpgrabeel',
            name='pid_attachment',
            field=models.FileField(blank=True, null=True, upload_to='traditional/grabeel/', verbose_name='صورة من إثبات الشخصية'),
        ),
        migrations.AlterField(
            model_name='lkpgrabeel',
            name='type',
            field=models.IntegerField(choices=[(1, 'كبير'), (2, 'صغير')], default=1, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='lkpkhalatat',
            name='pid_attachment',
            field=models.FileField(blank=True, null=True, upload_to='traditional/khalatat/', verbose_name='صورة من إثبات الشخصية'),
        ),
        migrations.AlterField(
            model_name='lkpmojam3attawa7in',
            name='owner_name',
            field=models.CharField(max_length=100, verbose_name='اسم المالك'),
        ),
        migrations.AlterField(
            model_name='lkpmojam3attawa7in',
            name='pid_attachment',
            field=models.FileField(blank=True, null=True, upload_to='traditional/mojam3at_tawa7in/', verbose_name='صورة من إثبات الشخصية'),
        ),
        migrations.AlterField(
            model_name='lkpmojam3attawa7in',
            name='soag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpsoag', verbose_name='السوق'),
        ),
        migrations.AlterField(
            model_name='lkpmojam3attawa7in',
            name='toa7in_jafa_count',
            field=models.IntegerField(verbose_name='عدد الطواحين الجافة'),
        ),
        migrations.AlterField(
            model_name='lkpmojam3attawa7in',
            name='toa7in_ratiba_count',
            field=models.IntegerField(verbose_name='عدد الطواحين الرطبة'),
        ),
        migrations.AlterField(
            model_name='lkpsaig',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الصائغ'),
        ),
        migrations.AlterField(
            model_name='lkpsaig',
            name='pid_attachment',
            field=models.FileField(blank=True, null=True, upload_to='traditional/saig/', verbose_name='صورة من إثبات الشخصية'),
        ),
        migrations.AlterField(
            model_name='lkpsaig',
            name='soag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.lkpsoag', verbose_name='السوق'),
        ),
        migrations.AlterField(
            model_name='lkpsmallprocessingunit',
            name='bolimal_count',
            field=models.IntegerField(verbose_name='عدد طواحين البولميل'),
        ),
        migrations.AlterField(
            model_name='lkpsmallprocessingunit',
            name='kasarat_count',
            field=models.IntegerField(verbose_name='عدد الكسارات'),
        ),
        migrations.AlterField(
            model_name='lkpsmallprocessingunit',
            name='khalatat_count',
            field=models.IntegerField(verbose_name='عدد الخلاطات'),
        ),
        migrations.AlterField(
            model_name='lkpsmallprocessingunit',
            name='pid_attachment',
            field=models.FileField(blank=True, null=True, upload_to='traditional/small_processing_unit/', verbose_name='صورة من إثبات الشخصية'),
        ),
        migrations.AlterField(
            model_name='lkpsoag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='lkpsosalgold',
            name='pid_attachment',
            field=models.FileField(blank=True, null=True, upload_to='traditional/sosl_gold/', verbose_name='صورة من إثبات الشخصية'),
        ),
        migrations.AlterField(
            model_name='rentedapartment',
            name='apartment_type',
            field=models.IntegerField(choices=[(1, 'مكتب'), (2, 'إستراحة'), (3, 'سكن المدير')], default=1, verbose_name='نوع المقر'),
        ),
        migrations.AlterField(
            model_name='rentedapartment',
            name='contract_attachment',
            field=models.FileField(blank=True, null=True, upload_to='traditional/rented_apartments/', verbose_name='صورة من العقد'),
        ),
        migrations.AlterField(
            model_name='rentedapartment',
            name='contract_end_date',
            field=models.DateField(verbose_name='تاريخ نهاية العقد'),
        ),
        migrations.AlterField(
            model_name='rentedapartment',
            name='contract_start_date',
            field=models.DateField(verbose_name='تاريخ بداية العقد'),
        ),
        migrations.AlterField(
            model_name='rentedapartment',
            name='monthly_rent',
            field=models.FloatField(verbose_name='الاجار الشهري'),
        ),
        migrations.AlterField(
            model_name='rentedapartment',
            name='owner_name',
            field=models.CharField(max_length=100, verbose_name='اسم مالك العقار'),
        ),
        migrations.AlterField(
            model_name='rentedvehicle',
            name='contract_attachment',
            field=models.FileField(blank=True, null=True, upload_to='traditional/rented_vehicles/', verbose_name='صورة من العقد'),
        ),
        migrations.AlterField(
            model_name='rentedvehicle',
            name='contract_end_date',
            field=models.DateField(verbose_name='تاريخ نهاية العقد'),
        ),
        migrations.AlterField(
            model_name='rentedvehicle',
            name='contract_start_date',
            field=models.DateField(verbose_name='تاريخ بداية العقد'),
        ),
        migrations.AlterField(
            model_name='rentedvehicle',
            name='monthly_rent',
            field=models.FloatField(verbose_name='الاجار الشهري'),
        ),
        migrations.AlterField(
            model_name='rentedvehicle',
            name='rented_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.employee', verbose_name='المستفيد من الاجار'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=100, verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_no',
            field=models.CharField(max_length=100, verbose_name='رقم اللوحة'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.IntegerField(choices=[(1, 'عربة'), (2, 'موتر')], default=1, verbose_name='نوع المتحرك'),
        ),
    ]
