# Generated by Django 5.0.2 on 2025-03-17 16:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0116_appfuelpermissiondetail_fuel_actual_qty'),
        ('traditional_app', '0011_alter_rentedvehicle_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoldTravelTraditionalUser',
            new_name='TraditionalAppUser',
        ),
    ]
