# Generated by Django 5.0.2 on 2025-03-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0012_rename_goldtraveltraditionaluser_traditionalappuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traditionalappuser',
            options={'verbose_name': 'مستخدم نظام التعدين التقليدي', 'verbose_name_plural': 'مستخدمي نظام التعدين التقليدي'},
        ),
    ]
