# Generated by Django 5.1.7 on 2025-05-06 14:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0014_lkpgrindintmp_lkpproductionpathtmp_lkpproductiontmp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='adress_of',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='age_work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='amount_c_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='amount_car',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='blood',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='company_na',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='edu_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='elc_consum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='fuelconsum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='laborer_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='laborersno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='locality',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='market',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='market_cod',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='mill_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='mill_sort',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='national_n',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='point_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='point_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='previous_j',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='social_sta',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='unit_numb',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='waterconsu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lkpgrindintmp',
            name='zabuq',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductionpathtmp',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='lkpproductionpathtmp',
            name='line_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductionpathtmp',
            name='locality',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductionpathtmp',
            name='shape_leng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductionpathtmp',
            name='state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductionpathtmp',
            name='target_fro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductionpathtmp',
            name='target_to',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='adress_of',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='age_work',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='area_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='blood',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='classifica',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='company_na',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='edu_level',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='laborer_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='locality',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='locationsu',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='national_n',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='previous_j',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='processing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='social_sta',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='traditiona',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpproductiontmp',
            name='watersourc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='adress_of',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='age_work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='aveagemerc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='blood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='edu_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='grindingmi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='laborer_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='locality',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='market_cod',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='national_n',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='point_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='point_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='previous_j',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='social_sta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsaigtmp',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='adress_of_field',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='age',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='blood',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='classfy_of',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='company_na',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='date_of_po',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='edulevel',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='enter_at',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='flag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='gender',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='id_of_poc1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='job',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='market_pur',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='mother',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='national_n',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='nickname',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='number_gil',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='number_lab',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='number_mac',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='number_yea',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='owner_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='partnar_na',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='phone_no',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='place',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='place_of',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='resources_field',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='soc_status',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='state',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='techncal_a',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='units',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='upload_at',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougothertmp',
            name='zabuq',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='adress_of',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='age',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='age_work',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='blood',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='edu_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='laborer_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='locality',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='market_cod',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='national_n',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='owner',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='phone_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='point_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='point_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='previous_j',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='servicetyp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='social_sta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougservicetmp',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='accountcol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='contorol_v',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='controller',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='framingsta',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='fuel_stati',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='locality',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='market_man',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='network_so',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='processing_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='securityfo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='shape_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='shape_leng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='tailingsco',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougtmp',
            name='total_cart',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='adress_of',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='age',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='age_work',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='basinowner',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='blood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='edu_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='karta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='laborer_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='locality',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='market',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='mercury_us',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='national_n',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='point_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='point_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='previous_j',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkpsougwashingtmp',
            name='water_cons',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
