# Generated by Django 5.1.7 on 2025-05-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0016_lkplocalitytmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lkplocalitytmp',
            name='city',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lkplocalitytmp',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lkplocalitytmp',
            name='shape_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkplocalitytmp',
            name='shape_leng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lkplocalitytmp',
            name='state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
