# Generated by Django 5.1.7 on 2025-05-07 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0126_alter_tblcompanyproductionfactoryvat_options_and_more'),
        ('traditional_app', '0017_alter_lkplocalitytmp_city_alter_lkplocalitytmp_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkplocalitytmp',
            name='locality_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkplocality', verbose_name='Locality'),
        ),
        migrations.AddField(
            model_name='lkplocalitytmp',
            name='state_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='الولاية'),
        ),
    ]
