# Generated by Django 5.1.7 on 2025-05-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0018_lkplocalitytmp_locality_m_lkplocalitytmp_state_m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lkplocalitytmp',
            old_name='state',
            new_name='state_gis',
        ),
    ]
