# Generated by Django 5.1.7 on 2025-05-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0019_rename_state_lkplocalitytmp_state_gis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lkplocalitytmp',
            old_name='locality_m',
            new_name='locality',
        ),
        migrations.RenameField(
            model_name='lkplocalitytmp',
            old_name='state_m',
            new_name='state',
        ),
    ]
