# Generated by Django 5.1.7 on 2025-05-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0020_rename_locality_m_lkplocalitytmp_locality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lkplocalitytmp',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='lkplocalitytmp',
            name='state',
        ),
    ]
