# Generated by Django 5.1.7 on 2025-05-11 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0127_lkpstate_geom'),
        ('traditional_app', '0021_remove_lkplocalitytmp_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkplocalitytmp',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkplocality', verbose_name='Locality'),
        ),
        migrations.AddField(
            model_name='lkplocalitytmp',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='الولاية'),
        ),
    ]
