# Generated by Django 5.1.7 on 2025-05-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0023_remove_lkp7ofrkabira_cordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lkp2bar',
            name='cordinates',
        ),
        migrations.AddField(
            model_name='lkp2bar',
            name='cordinates_x',
            field=models.FloatField(default=0, verbose_name='الإحداثيات x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkp2bar',
            name='cordinates_y',
            field=models.FloatField(default=0, verbose_name='الإحداثيات y'),
            preserve_default=False,
        ),
    ]
