# Generated by Django 5.1.7 on 2025-05-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0024_remove_lkp2bar_cordinates_lkp2bar_cordinates_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpgrabeel',
            name='cordinates_x',
            field=models.FloatField(default=0, verbose_name='الإحداثيات x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkpgrabeel',
            name='cordinates_y',
            field=models.FloatField(default=0, verbose_name='الإحداثيات y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkpkhalatat',
            name='cordinates_x',
            field=models.FloatField(default=0, verbose_name='الإحداثيات x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkpkhalatat',
            name='cordinates_y',
            field=models.FloatField(default=0, verbose_name='الإحداثيات y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkpmojam3attawa7in',
            name='cordinates_x',
            field=models.FloatField(default=0, verbose_name='الإحداثيات x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkpmojam3attawa7in',
            name='cordinates_y',
            field=models.FloatField(default=0, verbose_name='الإحداثيات y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkpsaig',
            name='cordinates_x',
            field=models.FloatField(default=0, verbose_name='الإحداثيات x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkpsaig',
            name='cordinates_y',
            field=models.FloatField(default=0, verbose_name='الإحداثيات y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkpsmallprocessingunit',
            name='cordinates_x',
            field=models.FloatField(default=0, verbose_name='الإحداثيات x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkpsmallprocessingunit',
            name='cordinates_y',
            field=models.FloatField(default=0, verbose_name='الإحداثيات y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentedapartment',
            name='cordinates_x',
            field=models.FloatField(default=0, verbose_name='الإحداثيات x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentedapartment',
            name='cordinates_y',
            field=models.FloatField(default=0, verbose_name='الإحداثيات y'),
            preserve_default=False,
        ),
    ]
