# Generated by Django 5.1.7 on 2025-05-13 12:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0025_lkpgrabeel_cordinates_x_lkpgrabeel_cordinates_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpsoag',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
    ]
