# Generated by Django 5.1.7 on 2025-05-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0026_lkpsoag_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lkpsoag',
            name='geom',
        ),
    ]
