# Generated by Django 5.1.7 on 2025-05-13 14:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0028_remove_lkpsoag_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpsoag',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
