# Generated by Django 5.1.7 on 2025-05-14 05:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0029_lkpsoag_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkp2bar',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='lkp7ofrkabira',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='lkpgrabeel',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='lkpkhalatat',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='lkpmojam3attawa7in',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='lkpsaig',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='lkpsmallprocessingunit',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='rentedapartment',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
    ]
