# Generated by Django 5.1.7 on 2025-05-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0030_lkp2bar_geom_lkp7ofrkabira_geom_lkpgrabeel_geom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lkp2bar',
            name='cordinates_x',
        ),
        migrations.RemoveField(
            model_name='lkp2bar',
            name='cordinates_y',
        ),
        migrations.RemoveField(
            model_name='lkp7ofrkabira',
            name='cordinates_x',
        ),
        migrations.RemoveField(
            model_name='lkp7ofrkabira',
            name='cordinates_y',
        ),
        migrations.RemoveField(
            model_name='lkpgrabeel',
            name='cordinates_x',
        ),
        migrations.RemoveField(
            model_name='lkpgrabeel',
            name='cordinates_y',
        ),
        migrations.RemoveField(
            model_name='lkpkhalatat',
            name='cordinates_x',
        ),
        migrations.RemoveField(
            model_name='lkpkhalatat',
            name='cordinates_y',
        ),
        migrations.RemoveField(
            model_name='lkpsmallprocessingunit',
            name='cordinates_x',
        ),
        migrations.RemoveField(
            model_name='lkpsmallprocessingunit',
            name='cordinates_y',
        ),
        migrations.RemoveField(
            model_name='rentedapartment',
            name='cordinates_x',
        ),
        migrations.RemoveField(
            model_name='rentedapartment',
            name='cordinates_y',
        ),
    ]
