# Generated by Django 5.1.7 on 2025-05-14 05:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0031_remove_lkp2bar_cordinates_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpsosalgold',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
    ]
