# Generated by Django 5.1.7 on 2025-05-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0032_lkpsosalgold_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lkpmojam3attawa7in',
            name='cordinates_x',
        ),
        migrations.RemoveField(
            model_name='lkpmojam3attawa7in',
            name='cordinates_y',
        ),
        migrations.RemoveField(
            model_name='lkpsaig',
            name='cordinates_x',
        ),
        migrations.RemoveField(
            model_name='lkpsaig',
            name='cordinates_y',
        ),
    ]
