# Generated by Django 5.1.7 on 2025-05-15 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0033_remove_lkpmojam3attawa7in_cordinates_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'فئة الموظف',
                'verbose_name_plural': 'فئات الموظفين',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='traditional_app.employeecategory', verbose_name='فئة الموظف'),
            preserve_default=False,
        ),
    ]
