# Generated by Django 5.1.7 on 2025-05-18 14:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0034_employeecategory_employee_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=2015), django.core.validators.MaxValueValidator(limit_value=2100)], verbose_name='year')),
                ('month', models.IntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], verbose_name='month')),
                ('asasi', models.FloatField(default=0, verbose_name='galaa_m3isha')),
                ('galaa_m3isha', models.FloatField(default=0, verbose_name='galaa_m3isha')),
                ('badel_sakan', models.FloatField(default=0, verbose_name='galaa_m3isha')),
                ('badel_tar7il', models.FloatField(default=0, verbose_name='galaa_m3isha')),
                ('tabi3at_3amal', models.FloatField(default=0, verbose_name='galaa_m3isha')),
                ('badel_laban', models.FloatField(default=0, verbose_name='galaa_m3isha')),
                ('badel_3laj', models.FloatField(default=0, verbose_name='galaa_m3isha')),
                ('damga', models.FloatField(default=0, verbose_name='galaa_m3isha')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payroll',
            },
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traditional_app.employee', verbose_name='employee_name')),
                ('payroll_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traditional_app.payrollmaster')),
            ],
            options={
                'verbose_name': 'Payroll detail',
                'verbose_name_plural': 'Payroll details',
            },
        ),
        migrations.AddIndex(
            model_name='payrollmaster',
            index=models.Index(fields=['year', 'month'], name='traditional_year_a4f267_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollmaster',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='tra_unique_payroll_year_month'),
        ),
        migrations.AddConstraint(
            model_name='payrolldetail',
            constraint=models.UniqueConstraint(fields=('payroll_master', 'employee'), name='tra_unique_employee_payroll'),
        ),
    ]
