# Generated by Django 5.1.7 on 2025-05-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0035_payrollmaster_payrolldetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollmaster',
            name='asasi',
            field=models.FloatField(default=0, verbose_name='الاساسي'),
        ),
        migrations.AlterField(
            model_name='payrollmaster',
            name='badel_3laj',
            field=models.FloatField(default=0, verbose_name='بدل علاج'),
        ),
        migrations.AlterField(
            model_name='payrollmaster',
            name='badel_laban',
            field=models.FloatField(default=0, verbose_name='بدل لبن'),
        ),
        migrations.AlterField(
            model_name='payrollmaster',
            name='badel_sakan',
            field=models.FloatField(default=0, verbose_name='بدل سكن'),
        ),
        migrations.AlterField(
            model_name='payrollmaster',
            name='badel_tar7il',
            field=models.FloatField(default=0, verbose_name='بدل ترحيل'),
        ),
        migrations.AlterField(
            model_name='payrollmaster',
            name='damga',
            field=models.FloatField(default=0, verbose_name='دمغة'),
        ),
        migrations.AlterField(
            model_name='payrollmaster',
            name='galaa_m3isha',
            field=models.FloatField(default=0, verbose_name='غلاء معيشة'),
        ),
        migrations.AlterField(
            model_name='payrollmaster',
            name='tabi3at_3amal',
            field=models.FloatField(default=0, verbose_name='طبيعة عمل'),
        ),
    ]
