# Generated by Django 5.1.7 on 2025-05-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0036_alter_payrollmaster_asasi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollmaster',
            options={'verbose_name': 'الموظفين - المرتبات', 'verbose_name_plural': 'الموظفين - المرتبات'},
        ),
    ]
