# Generated by Django 5.1.7 on 2025-05-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0037_alter_payrollmaster_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywardhajr',
            name='hajr_count',
            field=models.FloatField(verbose_name='عدد الجوالات'),
        ),
    ]
