# Generated by Django 5.2.1 on 2025-09-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0038_alter_dailywardhajr_hajr_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentedapartment',
            name='geom',
        ),
        migrations.AddField(
            model_name='rentedapartment',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentedapartment',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
