# Generated by Django 5.2.7 on 2025-11-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0040_remove_lkp2bar_geom_remove_lkp7ofrkabira_geom_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LkpGrindinTmp',
        ),
        migrations.RemoveField(
            model_name='lkplocalitytmp',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='lkplocalitytmp',
            name='state',
        ),
        migrations.DeleteModel(
            name='LkpProductionPathTmp',
        ),
        migrations.DeleteModel(
            name='LkpProductionTmp',
        ),
        migrations.DeleteModel(
            name='LkpSaigTmp',
        ),
        migrations.DeleteModel(
            name='LkpSougOtherTmp',
        ),
        migrations.DeleteModel(
            name='LkpSougServiceTmp',
        ),
        migrations.DeleteModel(
            name='LkpSougTmp',
        ),
        migrations.DeleteModel(
            name='LkpSougWashingTmp',
        ),
        migrations.DeleteModel(
            name='LkpLocalityTmp',
        ),
    ]
