# Generated by Django 5.2.12 on 2026-04-05 05:37

from django.db import migrations


def setup_group_perms(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    group, created = Group.objects.get_or_create(name='traditional_hr')
    group.permissions.clear()
    
    ct_objs = ContentType.objects.filter(app_label='traditional_app')
    full_access_models = ['employee', 'employeecategory', 'employeeproject', 'payrollmaster', 'payrolldetail']
    
    for ct in ct_objs:
        model_name = ct.model
        perms = ['add', 'change', 'delete', 'view'] if model_name in full_access_models else []
        for action in perms:
            p = Permission.objects.filter(content_type=ct, codename=f"{action}_{model_name}").first()
            if p: group.permissions.add(p)
            
    # Restrict modify perms from other groups
    for g in Group.objects.exclude(name='traditional_hr'):
        for model_name in full_access_models:
            ct = ContentType.objects.filter(app_label='traditional_app', model=model_name).first()
            if not ct: continue
            for action in ['add', 'change', 'delete']:
                p = Permission.objects.filter(content_type=ct, codename=f"{action}_{model_name}").first()
                if p: g.permissions.remove(p)

class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0041_delete_lkpgrindintmp_remove_lkplocalitytmp_locality_and_more'),
    ]

    operations = [
        migrations.RunPython(setup_group_perms, reverse_code=migrations.RunPython.noop),
    ]
