# Generated by Django 5.2.12 on 2026-04-05 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0042_auto_20260405_0737'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('qualification', models.IntegerField(choices=[(1, 'ثانوي'), (2, 'دبلوم تقني'), (3, 'دبلوم وسيط'), (4, 'بكلاريوس'), (5, 'دبلوم عالي'), (6, 'بكلاريوس شرف'), (7, 'ماجستير'), (8, 'دكتوراه')], verbose_name='المؤهل')),
                ('university', models.CharField(max_length=100, verbose_name='الجامعة')),
                ('specialization', models.CharField(max_length=100, verbose_name='التخصص')),
                ('graduation_date', models.DateField(verbose_name='تاريخ التخرج')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='traditional/academic_qualifications/', verbose_name='إرفاق الشهادة')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_qualifications', to='traditional_app.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'المؤهل الأكاديمي',
                'verbose_name_plural': 'المؤهلات الأكاديمية',
            },
        ),
    ]
