# Generated by Django 5.2.12 on 2026-04-08 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0043_academicqualification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeJobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('hire_date', models.DateField(verbose_name='تاريخ التعيين')),
                ('association_type', models.IntegerField(choices=[(1, 'الهيكل'), (2, 'تعاقد'), (3, 'الحاق'), (4, 'قوات امنية')], default=1, verbose_name='نوع الارتباط')),
                ('secondment_or_security_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الالحاق/القوات الامنية')),
                ('secondment_or_security_entity', models.CharField(blank=True, max_length=255, null=True, verbose_name='جهة الالحاق/القوات الامنية')),
                ('contract_extension_date', models.DateField(blank=True, null=True, verbose_name='تاريخ تمديد العقد')),
                ('job_title', models.CharField(max_length=255, verbose_name='المسمي الوظيفي')),
                ('status', models.IntegerField(choices=[(1, 'نشط'), (2, 'انهاء عقد'), (3, 'استقالة'), (4, 'وفاة'), (5, 'فصل من الخدمة'), (6, 'انهاء اللحاق')], default=1, verbose_name='الحالة')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_data', to='traditional_app.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'البيانات الوظيفية',
                'verbose_name_plural': 'البيانات الوظيفية',
            },
        ),
        migrations.DeleteModel(
            name='EmployeeProject',
        ),
    ]
