# Generated by Django 5.2.12 on 2026-04-08 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0044_employeejobdata_delete_employeeproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeejobdata',
            name='status',
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'ذكر'), (2, 'أنثى')], null=True, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='التلفون'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.CreateModel(
            name='EmployeeBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('bank_name', models.CharField(max_length=255, verbose_name='البنك')),
                ('bank_code', models.CharField(max_length=50, verbose_name='كود البنك')),
                ('account_type', models.IntegerField(choices=[(1, 'توفير'), (2, 'ادخار')], default=1, verbose_name='نوع الحساب')),
                ('account_number', models.CharField(max_length=100, verbose_name='رقم الحساب')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='traditional_app.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'الحسابات البنكية',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('document_type', models.IntegerField(choices=[(1, 'عقد'), (2, 'شهادة'), (3, 'قرار'), (4, 'خطاب'), (5, 'أخرى')], default=5, verbose_name='نوع المستند')),
                ('document_date', models.DateField(verbose_name='التاريخ')),
                ('attachment', models.FileField(upload_to='traditional/employee/documents/', verbose_name='المرفق')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='الملاحظة')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='traditional_app.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'الأرشيف الرقمي',
                'ordering': ['-document_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('leave_type', models.CharField(max_length=100, verbose_name='نوع الإجازة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='traditional/employee/leaves/', verbose_name='المرفق')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_assignments', to='traditional_app.employee', verbose_name='الموظف المكلف')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='traditional_app.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'إجازة',
                'verbose_name_plural': 'الإجازات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('penalty_type', models.IntegerField(choices=[(1, 'لفت نظر'), (2, 'انذار'), (3, 'استيضاح')], default=1, verbose_name='نوع الجزاء')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='النسخة')),
                ('month', models.IntegerField(blank=True, choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'ابريل'), (5, 'مايو'), (6, 'يونيو'), (7, 'يوليو'), (8, 'اغسطس'), (9, 'سبتمبر'), (10, 'اكتوبر'), (11, 'نوفمبر'), (12, 'ديسمبر')], null=True, verbose_name='الشهر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='البيان')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='traditional/employee/penalties/', verbose_name='المرفق')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='traditional_app.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'جزاء',
                'verbose_name_plural': 'الجزاءات',
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('status', models.IntegerField(choices=[(1, 'نشط'), (2, 'انهاء عقد'), (3, 'استقالة'), (4, 'وفاة'), (5, 'فصل من الخدمة'), (6, 'انهاء اللحاق')], default=1, verbose_name='الحالة')),
                ('status_date', models.DateField(verbose_name='التاريخ')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='traditional_app.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'حالة الموظف',
                'verbose_name_plural': 'حالات الموظف',
                'ordering': ['-status_date'],
            },
        ),
    ]
