# Generated by Django 5.2.8 on 2026-04-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0045_remove_employeejobdata_status_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='no3_elta3god',
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_certificate_attachment',
            field=models.FileField(blank=True, null=True, upload_to='traditional/employee/birth_certificates/', verbose_name='مرفق شهادة الميلاد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_attachment',
            field=models.FileField(blank=True, null=True, upload_to='traditional/employee/id_attachments/', verbose_name='مرفق إثبات الهوية'),
        ),
        migrations.AlterField(
            model_name='employeejobdata',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المسمي الوظيفي'),
        ),
    ]
