# Generated by Django 5.2.12 on 2026-04-08 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0046_remove_employee_job_remove_employee_no3_elta3god_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('asasi', models.FloatField(default=0, verbose_name='الاساسي')),
                ('galaa_m3isha', models.FloatField(default=0, verbose_name='غلاء معيشة')),
                ('badel_sakan', models.FloatField(default=0, verbose_name='بدل سكن')),
                ('badel_tar7il', models.FloatField(default=0, verbose_name='بدل ترحيل')),
                ('tabi3at_3amal', models.FloatField(default=0, verbose_name='طبيعة عمل')),
                ('badel_laban', models.FloatField(default=0, verbose_name='بدل لبن')),
                ('badel_3laj', models.FloatField(default=0, verbose_name='بدل علاج')),
                ('damga', models.FloatField(default=1, verbose_name='دمغة')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='traditional_app.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'تفاصيل المرتب',
                'verbose_name_plural': 'تفاصيل المرتب',
            },
        ),
    ]
