# Generated by Django 5.2.12 on 2026-04-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0047_employeesalary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSalary',
        ),
    ]
