# Generated by Django 5.2.7 on 2026-04-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0049_assign_hr_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejobdata',
            name='association_type',
            field=models.IntegerField(choices=[(1, 'الهيكل'), (2, 'تعاقد'), (3, 'الحاق'), (4, 'قوات امنية'), (5, 'ملحق علي الرئاسة')], default=1, verbose_name='نوع الارتباط'),
        ),
    ]
