# Generated by Django 5.2.7 on 2026-04-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0050_alter_employeejobdata_association_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='state_serial_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='الرقم المتسلسل بالولاية'),
        ),
    ]
