# Generated by Django 5.2.7 on 2026-04-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_app', '0051_employee_state_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='state_serial_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الوظيفي'),
        ),
    ]
