# Generated by Django 5.2.7 on 2026-07-18 06:10

from django.db import migrations


CHILD_TABLES = [
    'traditional_app_lkpmojam3attawa7in',
    'traditional_app_lkpsaig',
    'traditional_app_dailywardhajr',
    'traditional_app_dailyincome',
    'traditional_app_dailytahsilform',
    'traditional_app_dailykartamor7ala',
    'traditional_app_dailygoldmor7ala',
    'traditional_app_dailygrabeel',
]

OLD_TABLE = 'traditional_app_lkpsoag'


def _get_fk_constraint_name(cursor, table, column, ref_table):
    cursor.execute("""
        SELECT con.conname
        FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        JOIN pg_attribute att ON att.attrelid = rel.oid AND att.attnum = ANY(con.conkey)
        JOIN pg_class ref_rel ON ref_rel.oid = con.confrelid
        WHERE rel.relname = %s
          AND att.attname = %s
          AND ref_rel.relname = %s
          AND con.contype = 'f'
    """, [table, column, ref_table])
    row = cursor.fetchone()
    return row[0] if row else None


def drop_fks_and_table(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for table in CHILD_TABLES:
            name = _get_fk_constraint_name(cursor, table, 'soag_id', OLD_TABLE)
            if name:
                cursor.execute(
                    f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS "{name}" CASCADE'
                )
        cursor.execute(f'DROP TABLE IF EXISTS "{OLD_TABLE}" CASCADE')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel_traditional', '0052_alter_meltbatchdetail_id'),
        ('traditional_app', '0053_assign_academicqualification_to_state_hr'),
    ]

    operations = [
        migrations.RunPython(drop_fks_and_table, noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='LkpSoag'),
                migrations.CreateModel(
                    name='LkpSoag',
                    fields=[],
                    options={
                        'verbose_name': 'سوق',
                        'verbose_name_plural': 'أسواق',
                        'proxy': True,
                        'indexes': [],
                        'constraints': [],
                    },
                    bases=('gold_travel_traditional.lkpjihatalaisdar',),
                ),
            ],
        ),
    ]
