# Generated by Django 5.2.7 on 2026-02-18 13:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'سوق',
                'verbose_name_plural': 'الأسواق',
            },
        ),
        migrations.CreateModel(
            name='CollectionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_receipt_number', message='رقم الإيصال يجب أن يتكون من 10 أرقام بالضبط.', regex='^\\d{10}$')])),
                ('miner_name', models.CharField(max_length=255)),
                ('sacks_count', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'مسودة'), ('Waiting Approval', 'بانتظار الموافقة'), ('Pending Payment', 'بانتظار الدفع'), ('Paid', 'تم الدفع'), ('Cancelled', 'ملغي')], default='Draft', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_collections', to=settings.AUTH_USER_MODEL)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='form15_tra.market')),
            ],
            options={
                'verbose_name': 'إيصال تحصيل',
                'verbose_name_plural': 'إيصالات التحصيل',
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
                ('collection_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to='form15_tra.collectionform')),
            ],
            options={
                'verbose_name': 'سجل واجهة البرمجة',
                'verbose_name_plural': 'سجلات واجهة البرمجة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_collector', models.BooleanField(default=False, help_text='يسمح للمستخدم بإنشاء وتأكيد إيصالات التحصيل.')),
                ('is_senior_collector', models.BooleanField(default=False, help_text='يسمح للمستخدم بإلغاء إيصالات التحصيل.')),
                ('is_observer', models.BooleanField(default=False, help_text='يسمح للمستخدم بإنشاء إيصالات مسودة فقط.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to='form15_tra.market')),
            ],
            options={
                'verbose_name': 'تكليف متحصل',
                'verbose_name_plural': 'تكليف المتحصلين',
            },
        ),
    ]
