# Generated by Django 5.2.7 on 2026-04-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form15_tra', '0006_collectionform_created_by_collectionform_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionform',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
