# Generated by Django 5.2.7 on 2026-04-08 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form15_tra', '0007_collectionform_phone'),
    ]

    def _delete_existing_collectionforms(apps, schema_editor) -> None:
        CollectionForm = apps.get_model("form15_tra", "CollectionForm")
        CollectionForm.objects.all().delete()

    operations = [
        migrations.RunPython(_delete_existing_collectionforms, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='collectionform',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون 10 أرقام بالضبط.', regex='^\\d{10}$')]),
        ),
    ]
