# Generated by Django 5.2.7 on 2026-04-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form15_tra', '0008_alter_collectionform_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionform',
            name='rrn_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
