# Generated by Django 5.2.7 on 2026-04-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form15_tra', '0009_collectionform_rrn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorassignment',
            name='esali_password_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='collectorassignment',
            name='esali_service_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='collectorassignment',
            name='esali_username',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
