# Generated by Django 5.2.7 on 2026-04-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form15_tra', '0010_collectorassignment_esali_password_enc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorassignment',
            name='is_collector',
            field=models.BooleanField(default=False, help_text='يسمح للمستخدم بإنشاء وتأكيد إيصالات التحصيل.', verbose_name='متحصل'),
        ),
        migrations.AlterField(
            model_name='collectorassignment',
            name='is_observer',
            field=models.BooleanField(default=False, help_text='يسمح للمستخدم بإنشاء إيصالات مسودة فقط.', verbose_name='مراقب'),
        ),
        migrations.AlterField(
            model_name='collectorassignment',
            name='is_senior_collector',
            field=models.BooleanField(default=False, help_text='يسمح للمستخدم بإلغاء إيصالات التحصيل.', verbose_name='كبير متحصل'),
        ),
    ]
