# Generated by Django 5.2.7 on 2026-04-09 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0138_alter_apphseaccidentreport_options'),
        ('form15_tra', '0011_alter_collectorassignment_is_collector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='الولاية'),
        ),
    ]
