# Generated by Django 5.2.7 on 2026-04-09 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form15_tra', '0012_market_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collectionform',
            index=models.Index(fields=['receipt_number'], name='idx_collection_receipt_number'),
        ),
        migrations.AddIndex(
            model_name='collectionform',
            index=models.Index(fields=['rrn_number'], name='idx_collection_rrn_number'),
        ),
        migrations.AddIndex(
            model_name='collectionform',
            index=models.Index(fields=['miner_name'], name='idx_collection_miner_name'),
        ),
    ]
