# Generated by Django 5.2.7 on 2026-04-13 10:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form15_tra', '0015_collectionform_invoice_generated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='collection_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to='form15_tra.collectionform', verbose_name='إيصال التحصيل'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='request_data',
            field=models.JSONField(blank=True, null=True, verbose_name='بيانات الطلب'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='response_data',
            field=models.JSONField(blank=True, null=True, verbose_name='بيانات الرد'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الإلغاء'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_collections', to=settings.AUTH_USER_MODEL, verbose_name='تم الإلغاء بواسطة'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='المتحصل'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المنشئ'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='invoice_generated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ إنشاء الفاتورة'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='invoice_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='form15_tra.market', verbose_name='السوق'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='miner_name',
            field=models.CharField(max_length=255, verbose_name='اسم العميل / المعدن'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='pending_payment_check_now',
            field=models.BooleanField(db_index=True, default=False, help_text='Set when a user opens this collection in Pending Payment; cleared when the sync worker consumes it.', verbose_name='التحقق من الدفع الآن'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون 10 أرقام بالضبط.', regex='^\\d{10}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='رقم الإيصال'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='rrn_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='رقم التحويل'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='sacks_count',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='عدد الجوالات'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='status',
            field=models.CharField(choices=[('Draft', 'مسودة'), ('Collector Confirmation', 'بانتظار تأكيد المتحصل'), ('Invoice Requested', 'تم طلب الفاتورة'), ('Invoice Queued', 'تمت جدولة الفاتورة'), ('Pending Payment', 'بانتظار الدفع'), ('Paid', 'تم الدفع'), ('Cancelled', 'ملغي')], default='Draft', max_length=30, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ الإجمالي'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المحدث'),
        ),
        migrations.AlterField(
            model_name='collectorassignment',
            name='esali_password_enc',
            field=models.TextField(blank=True, default='', verbose_name='كلمة المرور المشفرة لمستخدم ايصالي'),
        ),
        migrations.AlterField(
            model_name='collectorassignment',
            name='esali_service_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='رقم الخدمة'),
        ),
        migrations.AlterField(
            model_name='collectorassignment',
            name='esali_username',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='مستخدم ايصالي'),
        ),
        migrations.AlterField(
            model_name='collectorassignment',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to='form15_tra.market', verbose_name='السوق'),
        ),
        migrations.AlterField(
            model_name='collectorassignment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='market',
            name='location',
            field=models.CharField(max_length=255, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='market',
            name='market_name',
            field=models.CharField(max_length=255, verbose_name='اسم السوق'),
        ),
    ]
