# Generated by Django 5.2.7 on 2026-04-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form15_tra', '0016_alter_apilog_action_alter_apilog_collection_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorAssignmentCollector',
            fields=[
            ],
            options={
                'verbose_name': 'متحصل',
                'verbose_name_plural': 'المتحصلين',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form15_tra.collectorassignment',),
        ),
        migrations.CreateModel(
            name='CollectorAssignmentObserver',
            fields=[
            ],
            options={
                'verbose_name': 'مراقب',
                'verbose_name_plural': 'المراقبين',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form15_tra.collectorassignment',),
        ),
        migrations.CreateModel(
            name='CollectorAssignmentSeniorCollector',
            fields=[
            ],
            options={
                'verbose_name': 'كبير متحصل',
                'verbose_name_plural': 'كبار المتحصلين',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form15_tra.collectorassignment',),
        ),
    ]
