# Generated by Django 5.2.7 on 2026-04-14 12:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form15_tra', '0019_alter_apilog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionform',
            name='arrival_source',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='جهة القدوم'),
        ),
        migrations.AddField(
            model_name='collectionform',
            name='vehicle_plate',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='لوحة العربة'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='sacks_count',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='عدد الجوالات'),
        ),
    ]
