# Generated by Django 5.0.1 on 2024-02-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lang',
            field=models.CharField(choices=[('AR', 'English')], default='AR', max_length=2),
        ),
    ]
