# Generated by Django 5.0.1 on 2024-02-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lang',
            field=models.CharField(choices=[('ar', 'English')], default='ar', max_length=2),
        ),
    ]
