# Generated by Django 5.1.7 on 2025-04-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usable_password',
            field=models.BooleanField(default=True),
        ),
    ]
