# Generated by Django 5.0.2 on 2025-01-07 10:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=255)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'goal_type_main'), (2, 'goal_type_sub')])),
                ('outcome', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='planning.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=2015), django.core.validators.MaxValueValidator(limit_value=2100)])),
                ('name', models.CharField(max_length=255)),
                ('responsible', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planning.goal')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')])),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duration', to='planning.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=100)])),
                ('problems', models.TextField(blank=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='planning.task')),
            ],
        ),
    ]
