# Generated by Django 5.0.2 on 2025-01-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='kpi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='planning.goal'),
        ),
    ]
