# Generated by Django 5.0.2 on 2025-01-07 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_goal_kpi_alter_goal_outcome_alter_goal_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskduration',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration', to='planning.task'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='planning.task'),
        ),
    ]
