# Generated by Django 5.0.2 on 2025-01-07 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_alter_taskduration_task_alter_taskexecution_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecution',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='planning.task'),
        ),
    ]
