# Generated by Django 5.0.2 on 2025-01-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_alter_taskexecution_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cost',
        ),
    ]
