# Generated by Django 5.0.2 on 2025-01-07 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_remove_task_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='type',
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='planning.goal', verbose_name='parent_goal'),
        ),
    ]
