# Generated by Django 5.0.2 on 2025-01-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_remove_goal_type_alter_goal_name_alter_goal_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='responsible',
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='kpi',
            field=models.TextField(blank=True, null=True, verbose_name='kpi'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='outcome',
            field=models.TextField(blank=True, null=True, verbose_name='outcome'),
        ),
    ]
