# Generated by Django 5.0.2 on 2025-01-07 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_alter_department_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='responsible',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='planning.department'),
            preserve_default=False,
        ),
    ]
