# Generated by Django 5.0.2 on 2025-01-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_goal_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='code',
            field=models.CharField(default=' ', max_length=10, verbose_name='code'),
            preserve_default=False,
        ),
    ]
