# Generated by Django 5.0.2 on 2025-01-07 12:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_goal_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['code'], 'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskduration',
            options={'verbose_name': 'TaskDuration', 'verbose_name_plural': 'TaskDurations'},
        ),
        migrations.AlterModelOptions(
            name='taskexecution',
            options={'verbose_name': 'TaskExecution', 'verbose_name_plural': 'TaskExecutions'},
        ),
        migrations.AlterField(
            model_name='goal',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='planning.department', verbose_name='responsible'),
        ),
        migrations.AlterField(
            model_name='task',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planning.goal', verbose_name='goal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=2015), django.core.validators.MaxValueValidator(limit_value=2100)], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='taskduration',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='taskduration',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration', to='planning.task', verbose_name='task'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='percentage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='percentage'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='problems',
            field=models.TextField(blank=True, verbose_name='problems'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='planning.task', verbose_name='task'),
        ),
    ]
