# Generated by Django 5.0.2 on 2025-01-08 07:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_alter_department_options_alter_goal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_confirmed'), (3, 'state_expired')], default=1, verbose_name='record_state'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='updated_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_department', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
