# Generated by Django 5.0.2 on 2025-01-08 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_taskexecution_created_at_taskexecution_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='planning_department', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
