# Generated by Django 5.0.2 on 2025-01-08 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_alter_department_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], default=1, verbose_name='month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='year',
            field=models.PositiveIntegerField(default=2025, validators=[django.core.validators.MinValueValidator(limit_value=2015), django.core.validators.MaxValueValidator(limit_value=2100)], verbose_name='year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='percentage'),
        ),
    ]
