# Generated by Django 5.0.2 on 2025-01-08 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0016_alter_department_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='responsible',
        ),
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='planning.department', verbose_name='responsible'),
            preserve_default=False,
        ),
    ]
