# Generated by Django 5.0.2 on 2025-01-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0017_remove_goal_responsible_task_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='code',
            field=models.IntegerField(verbose_name='code'),
        ),
    ]
