# Generated by Django 5.0.2 on 2025-01-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0018_alter_goal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='code',
            field=models.CharField(max_length=10, verbose_name='code'),
        ),
    ]
