# Generated by Django 5.0.2 on 2025-01-09 11:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0019_alter_goal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskexecution',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='month',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='year',
        ),
        migrations.CreateModel(
            name='MonthelyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=2015), django.core.validators.MaxValueValidator(limit_value=2100)], verbose_name='year')),
                ('month', models.PositiveIntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], verbose_name='month')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_tasks', to='planning.monthelyreport', verbose_name='report'),
        ),
        migrations.CreateModel(
            name='TaskAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=255, verbose_name='view_name')),
                ('percent_calculation_method', models.CharField(max_length=255, verbose_name='percent_calculation_method')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation', to='planning.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
