# Generated by Django 5.0.2 on 2025-01-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0020_remove_taskexecution_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskautomation',
            options={'verbose_name': 'TaskAutomation', 'verbose_name_plural': 'TaskAutomations'},
        ),
        migrations.AlterField(
            model_name='taskautomation',
            name='percent_calculation_method',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='percent_calculation_method'),
        ),
    ]
