# Generated by Django 5.0.2 on 2025-01-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0021_alter_taskautomation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskautomation',
            name='percent_calculation_method',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='percent_calculation_method'),
        ),
    ]
