# Generated by Django 5.0.2 on 2025-01-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0022_alter_taskautomation_percent_calculation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskautomation',
            name='view',
            field=models.CharField(help_text='admin inline view', max_length=255, verbose_name='view_name'),
        ),
    ]
