# Generated by Django 5.0.2 on 2025-01-09 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0024_companyproductiontask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskautomation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation', to='planning.task', verbose_name='task'),
        ),
    ]
