# Generated by Django 5.0.2 on 2025-01-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0025_alter_taskautomation_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskautomation',
            name='type',
            field=models.IntegerField(choices=[(1, 'type_manual'), (2, 'type_auto')], default=1, verbose_name='type'),
        ),
    ]
