# Generated by Django 5.0.2 on 2025-01-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0026_taskautomation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskautomation',
            name='view',
            field=models.CharField(blank=True, default='', help_text='admin inline view', max_length=255, null=True, verbose_name='view_name'),
        ),
    ]
