# Generated by Django 5.0.2 on 2025-01-13 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0084_alter_appborrowmaterial_company_from_str'),
        ('planning', '0031_traditionaltahsiltask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othermineralstask',
            name='mineral',
        ),
        migrations.AddField(
            model_name='othermineralstask',
            name='mineral',
            field=models.ForeignKey(default=1, help_text='in ton', on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpmineral', verbose_name='mineral'),
            preserve_default=False,
        ),
    ]
