# Generated by Django 5.0.2 on 2025-01-13 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0033_othermineralstask_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfotask',
            options={'verbose_name': 'CompanyInfoTask', 'verbose_name_plural': 'CompanyInfoTasks'},
        ),
        migrations.AlterModelOptions(
            name='companylicenseinfotask',
            options={'verbose_name': 'CompanyLicenseInfoTask', 'verbose_name_plural': 'CompanyLicenseInfoTasks'},
        ),
        migrations.AlterModelOptions(
            name='companyproductiontask',
            options={'verbose_name': 'CompanyProductionTask', 'verbose_name_plural': 'CompanyProductionTasks'},
        ),
        migrations.AlterModelOptions(
            name='exportgoldcompanytask',
            options={'verbose_name': 'ExportGoldCompanyTask', 'verbose_name_plural': 'ExportGoldCompanyTasks'},
        ),
        migrations.AlterModelOptions(
            name='exportgoldtraditionaltask',
            options={'verbose_name': 'ExportGoldTraditionalTask', 'verbose_name_plural': 'ExportGoldTraditionalTasks'},
        ),
        migrations.AlterModelOptions(
            name='othermineralstask',
            options={'verbose_name': 'OtherMineralsTask', 'verbose_name_plural': 'OtherMineralsTasks'},
        ),
        migrations.AlterModelOptions(
            name='traditionalproductiontask',
            options={'verbose_name': 'TraditionalProductionTask', 'verbose_name_plural': 'TraditionalProductionTasks'},
        ),
        migrations.AlterModelOptions(
            name='traditionalstatetask',
            options={'verbose_name': 'TraditionalStateTask', 'verbose_name_plural': 'TraditionalStateTasks'},
        ),
        migrations.AlterModelOptions(
            name='traditionaltahsiltask',
            options={'verbose_name': 'TraditionalTahsilTask', 'verbose_name_plural': 'TraditionalTahsilTasks'},
        ),
        migrations.AlterField(
            model_name='traditionalstatetask',
            name='abar_khtot_intag',
            field=models.IntegerField(verbose_name='no_abar_khtot_intag'),
        ),
        migrations.AlterField(
            model_name='traditionalstatetask',
            name='ajhizat_bahth',
            field=models.IntegerField(verbose_name='no_ajhizat_bahth'),
        ),
        migrations.AlterField(
            model_name='traditionalstatetask',
            name='grabeel',
            field=models.IntegerField(verbose_name='no_grabeel'),
        ),
        migrations.AlterField(
            model_name='traditionalstatetask',
            name='hofra_kabira',
            field=models.IntegerField(verbose_name='no_hofra_kabira'),
        ),
        migrations.AlterField(
            model_name='traditionalstatetask',
            name='mo3dinin_sosal',
            field=models.IntegerField(verbose_name='no_mo3dinin_sosal'),
        ),
        migrations.AlterField(
            model_name='traditionalstatetask',
            name='soug',
            field=models.IntegerField(verbose_name='no_soug'),
        ),
        migrations.AlterField(
            model_name='traditionalstatetask',
            name='toahin_jafa',
            field=models.IntegerField(verbose_name='no_toahin_jafa'),
        ),
        migrations.AlterField(
            model_name='traditionalstatetask',
            name='toahin_ratiba',
            field=models.IntegerField(verbose_name='no_toahin_ratiba'),
        ),
        migrations.CreateModel(
            name='TraditionalTahsilByBandTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.IntegerField(choices=[(1, 'band_1'), (2, 'band_2'), (3, 'band_3'), (4, 'band_4'), (5, 'band_5'), (6, 'band_6'), (7, 'band_7'), (8, 'band_8'), (9, 'band_9'), (10, 'band_10'), (11, 'band_11'), (12, 'band_12'), (13, 'band_13'), (14, 'band_14'), (15, 'band_15'), (16, 'band_16')], verbose_name='band')),
                ('total_money', models.FloatField(verbose_name='total_money')),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.taskexecution', verbose_name='task_execution')),
            ],
            options={
                'verbose_name': 'TraditionalTahsilTask',
                'verbose_name_plural': 'TraditionalTahsilTasks',
            },
        ),
    ]
