# Generated by Django 5.0.2 on 2025-01-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0084_alter_appborrowmaterial_company_from_str'),
        ('planning', '0035_alter_traditionaltahsilbybandtask_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMokhalafatTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_mokhalafat', models.IntegerField(verbose_name='no_mokhalafat')),
                ('no_mokhalafat_fixed', models.IntegerField(verbose_name='no_mokhalafat_fixed')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.taskexecution', verbose_name='task_execution')),
            ],
            options={
                'verbose_name': 'CompanyMokhalafatTask',
                'verbose_name_plural': 'CompanyMokhalafatTasks',
            },
        ),
        migrations.CreateModel(
            name='CompanySalamaMatlobatTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nashat', models.IntegerField(choices=[(1, 'nashat_1'), (2, 'nashat_2'), (3, 'nashat_3'), (4, 'nashat_4'), (5, 'nashat_5'), (6, 'nashat_6')], verbose_name='nashat')),
                ('percent', models.FloatField(verbose_name='percent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.taskexecution', verbose_name='task_execution')),
            ],
            options={
                'verbose_name': 'CompanySalamaMatlobatTask',
                'verbose_name_plural': 'CompanySalamaMatlobatTasks',
            },
        ),
        migrations.CreateModel(
            name='CompanyWafiatTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_wafiat', models.IntegerField(verbose_name='no_wafiat')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.taskexecution', verbose_name='task_execution')),
            ],
            options={
                'verbose_name': 'CompanyWafiatTask',
                'verbose_name_plural': 'CompanyWafiatTasks',
            },
        ),
        migrations.CreateModel(
            name='Traditional7oadthTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_wafiat', models.IntegerField(verbose_name='no_wafiat')),
                ('no_7oadith', models.IntegerField(verbose_name='no_7oadith')),
                ('no_e9abat', models.IntegerField(verbose_name='no_e9abat')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.taskexecution', verbose_name='task_execution')),
            ],
            options={
                'verbose_name': 'Traditional7oadthTask',
                'verbose_name_plural': 'Traditional7oadthTasks',
            },
        ),
        migrations.CreateModel(
            name='TraditionalSalamaMatlobatTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taswir_asag', models.FloatField(verbose_name='taswir_asag')),
                ('trhil_karta', models.FloatField(verbose_name='trhil_karta')),
                ('slamat_manajim', models.FloatField(verbose_name='slamat_manajim')),
                ('no_3iadat', models.FloatField(verbose_name='no_3iadat')),
                ('no_is3af', models.FloatField(verbose_name='no_is3af')),
                ('t3mol_zi2bag', models.FloatField(verbose_name='t3mol_zi2bag')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.taskexecution', verbose_name='task_execution')),
            ],
            options={
                'verbose_name': 'TraditionalSalamaMatlobatTask',
                'verbose_name_plural': 'TraditionalSalamaMatlobatTasks',
            },
        ),
        migrations.CreateModel(
            name='TraditionalSalamaRagabaTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m2moriat_taftishia', models.FloatField(verbose_name='m2moriat_taftishia')),
                ('lig2at_2rshadia', models.FloatField(verbose_name='lig2at_2rshadia')),
                ('taslim_tgarir', models.FloatField(verbose_name='taslim_tgarir')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.taskexecution', verbose_name='task_execution')),
            ],
            options={
                'verbose_name': 'TraditionalSalamaRagabaTask',
                'verbose_name_plural': 'TraditionalSalamaRagabaTasks',
            },
        ),
    ]
