# Generated by Django 5.0.2 on 2025-01-13 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0084_alter_appborrowmaterial_company_from_str'),
        ('planning', '0036_companymokhalafattask_companysalamamatlobattask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company7oadithTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_7oadith', models.IntegerField(verbose_name='no_7oadith')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.taskexecution', verbose_name='task_execution')),
            ],
            options={
                'verbose_name': 'Company7oadithTask',
                'verbose_name_plural': 'Company7oadithTasks',
            },
        ),
        migrations.DeleteModel(
            name='CompanyWafiatTask',
        ),
    ]
