# Generated by Django 5.0.2 on 2025-01-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0037_company7oadithtask_delete_companywafiattask'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproductiontask',
            name='planed_weight',
            field=models.FloatField(default=0, verbose_name='planed_weight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='othermineralstask',
            name='planed_weight',
            field=models.FloatField(default=0, verbose_name='planed_weight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traditionalproductiontask',
            name='planed_weight',
            field=models.FloatField(default=0, verbose_name='planed_weight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traditionaltahsilbybandtask',
            name='planed_money',
            field=models.FloatField(default=0, verbose_name='planed_money'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traditionaltahsilbyjihatask',
            name='planed_money',
            field=models.FloatField(default=0, verbose_name='planed_money'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traditionaltahsiltask',
            name='planed_money',
            field=models.FloatField(default=0, verbose_name='planed_money'),
            preserve_default=False,
        ),
    ]
