# Generated by Django 5.0.2 on 2025-01-16 07:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0084_alter_appborrowmaterial_company_from_str'),
        ('planning', '0038_companyproductiontask_planed_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyproductiontask',
            name='planed_weight',
        ),
        migrations.RemoveField(
            model_name='othermineralstask',
            name='planed_weight',
        ),
        migrations.RemoveField(
            model_name='traditionalproductiontask',
            name='planed_weight',
        ),
        migrations.RemoveField(
            model_name='traditionaltahsilbybandtask',
            name='planed_money',
        ),
        migrations.RemoveField(
            model_name='traditionaltahsiltask',
            name='planed_money',
        ),
        migrations.CreateModel(
            name='YearlyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=2015), django.core.validators.MaxValueValidator(limit_value=2100)], verbose_name='year')),
                ('state', models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_confirmed')], default=1, verbose_name='record_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TraditionaTahsilYearlyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], verbose_name='month')),
                ('planed_money', models.FloatField(verbose_name='planed_money')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.yearlyplanning', verbose_name='plan')),
            ],
        ),
        migrations.CreateModel(
            name='TraditionaTahsilByJihaYearlyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], verbose_name='month')),
                ('jiha', models.IntegerField(choices=[(1, 'jiha_1'), (2, 'jiha_2'), (3, 'jiha_3'), (4, 'jiha_4'), (5, 'jiha_5')], verbose_name='jiha')),
                ('planed_money', models.FloatField(verbose_name='planed_money')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.yearlyplanning', verbose_name='plan')),
            ],
        ),
        migrations.CreateModel(
            name='TraditionaTahsilByBandYearlyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], verbose_name='month')),
                ('band', models.IntegerField(choices=[(1, 'band_1'), (2, 'band_2'), (3, 'band_3'), (4, 'band_4'), (5, 'band_5'), (6, 'band_6'), (7, 'band_7'), (8, 'band_8'), (9, 'band_9'), (10, 'band_10'), (11, 'band_11'), (12, 'band_12'), (13, 'band_13'), (14, 'band_14'), (15, 'band_15'), (16, 'band_16')], verbose_name='band')),
                ('planed_money', models.FloatField(verbose_name='planed_money')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.yearlyplanning', verbose_name='plan')),
            ],
        ),
        migrations.CreateModel(
            name='TraditionaProductionYearlyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], verbose_name='month')),
                ('planed_weight', models.FloatField(verbose_name='planed_weight')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.yearlyplanning', verbose_name='plan')),
            ],
        ),
        migrations.CreateModel(
            name='OtherMineralsProductionYearlyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], verbose_name='month')),
                ('planed_weight', models.FloatField(verbose_name='planed_weight')),
                ('mineral', models.ForeignKey(help_text='in ton', on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpmineral', verbose_name='mineral')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.yearlyplanning', verbose_name='plan')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProductionYearlyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(choices=[(1, 'MONTH_JAN'), (2, 'MONTH_FEB'), (3, 'MONTH_MAR'), (4, 'MONTH_APR'), (5, 'MONTH_MAY'), (6, 'MONTH_JUN'), (7, 'MONTH_JLY'), (8, 'MONTH_AUG'), (9, 'MONTH_SEP'), (10, 'MONTH_OCT'), (11, 'MONTH_NOV'), (12, 'MONTH_DEC')], verbose_name='month')),
                ('planed_weight', models.FloatField(verbose_name='planed_weight')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.yearlyplanning', verbose_name='plan')),
            ],
        ),
    ]
