# Generated by Django 5.0.2 on 2025-01-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0084_alter_appborrowmaterial_company_from_str'),
        ('planning', '0039_remove_companyproductiontask_planed_weight_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TraditionaProductionYearlyPlanning',
            new_name='CompanyProductionMonthlyPlanning',
        ),
        migrations.RenameModel(
            old_name='OtherMineralsProductionYearlyPlanning',
            new_name='OtherMineralsProductionMonthlyPlanning',
        ),
        migrations.RenameModel(
            old_name='CompanyProductionYearlyPlanning',
            new_name='TraditionaProductionMonthlyPlanning',
        ),
        migrations.RenameModel(
            old_name='TraditionaTahsilByBandYearlyPlanning',
            new_name='TraditionaTahsilByBandMonthlyPlanning',
        ),
        migrations.RenameModel(
            old_name='TraditionaTahsilByJihaYearlyPlanning',
            new_name='TraditionaTahsilByJihaMonthlyPlanning',
        ),
        migrations.RenameModel(
            old_name='TraditionaTahsilYearlyPlanning',
            new_name='TraditionaTahsilMonthlyPlanning',
        ),
    ]
