# Generated by Django 5.0.2 on 2025-01-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0040_rename_traditionaproductionyearlyplanning_companyproductionmonthlyplanning_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyproductionmonthlyplanning',
            options={'verbose_name': 'CompanyProductionMonthlyPlanning', 'verbose_name_plural': 'CompanyProductionMonthlyPlanning'},
        ),
        migrations.AlterModelOptions(
            name='othermineralsproductionmonthlyplanning',
            options={'verbose_name': 'OtherMineralsProductionMonthlyPlanning', 'verbose_name_plural': 'OtherMineralsProductionMonthlyPlanning'},
        ),
        migrations.AlterModelOptions(
            name='traditionaproductionmonthlyplanning',
            options={'verbose_name': 'TraditionaProductionMonthlyPlanning', 'verbose_name_plural': 'TraditionaProductionMonthlyPlanning'},
        ),
        migrations.AlterModelOptions(
            name='traditionatahsilbybandmonthlyplanning',
            options={'verbose_name': 'TraditionaTahsilByBandMonthlyPlanning', 'verbose_name_plural': 'TraditionaTahsilByBandMonthlyPlanning'},
        ),
        migrations.AlterModelOptions(
            name='traditionatahsilbyjihamonthlyplanning',
            options={'verbose_name': 'TraditionaTahsilByJihaMonthlyPlanning', 'verbose_name_plural': 'TraditionaTahsilByJihaMonthlyPlanning'},
        ),
        migrations.AlterModelOptions(
            name='traditionatahsilmonthlyplanning',
            options={'verbose_name': 'TraditionaTahsilMonthlyPlanning', 'verbose_name_plural': 'TraditionaTahsilMonthlyPlanning'},
        ),
        migrations.AlterModelOptions(
            name='yearlyplanning',
            options={'verbose_name': 'YearlyPlanning', 'verbose_name_plural': 'YearlyPlanning'},
        ),
        migrations.RemoveField(
            model_name='exportgoldcompanytask',
            name='no_alloy',
        ),
        migrations.RemoveField(
            model_name='exportgoldtraditionaltask',
            name='total_dollar',
        ),
    ]
