# Generated by Django 5.0.2 on 2025-01-16 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0041_alter_companyproductionmonthlyplanning_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportGoldCompanyMonthlyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_total_weight', models.FloatField(verbose_name='raw_total_weight')),
                ('net_total_weight', models.FloatField(verbose_name='net_total_weight')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.yearlyplanning', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'ExportGoldCompanyMonthlyPlanning',
                'verbose_name_plural': 'ExportGoldCompanyMonthlyPlanning',
            },
        ),
        migrations.CreateModel(
            name='ExportGoldTraditionalMonthlyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_total_weight', models.FloatField(verbose_name='raw_total_weight')),
                ('net_total_weight', models.FloatField(verbose_name='net_total_weight')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.yearlyplanning', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'ExportGoldTraditionalMonthlyPlanning',
                'verbose_name_plural': 'ExportGoldTraditionalMonthlyPlanning',
            },
        ),
    ]
