# Generated by Django 5.0.2 on 2025-02-17 09:14

import django.db.models.deletion
import planning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0044_gmtask_mas2oliamojtama3iatask_mediadiscoverytask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorationMapTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new_map', models.BooleanField(verbose_name='is_new_map_exists')),
                ('map', models.ImageField(upload_to=planning.models.ExplorationMapTask.attachement_path, verbose_name='exploration_map')),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.taskexecution', verbose_name='task_execution')),
            ],
            options={
                'verbose_name': 'ExplorationMapTask',
                'verbose_name_plural': 'ExplorationMapTasks',
            },
        ),
    ]
