# Generated by Django 5.0.2 on 2025-02-17 09:17

import planning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0045_explorationmaptask'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorationmaptask',
            name='map_description',
            field=models.TextField(blank=True, null=True, verbose_name='map_description'),
        ),
        migrations.AlterField(
            model_name='explorationmaptask',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to=planning.models.ExplorationMapTask.attachement_path, verbose_name='exploration_map'),
        ),
    ]
