# Generated by Django 5.0.2 on 2025-02-18 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0046_explorationmaptask_map_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanoniaTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'ganonia_task_1'), (2, 'ganonia_task_2'), (3, 'ganonia_task_3'), (4, 'ganonia_task_4'), (5, 'ganonia_task_5'), (6, 'ganonia_task_6'), (7, 'ganonia_task_7')], verbose_name='type')),
                ('count', models.IntegerField(verbose_name='count')),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.taskexecution', verbose_name='task_execution')),
            ],
            options={
                'verbose_name': 'GanoniaTask',
                'verbose_name_plural': 'GanoniaTasks',
            },
        ),
    ]
