# Generated by Django 5.0.2 on 2025-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0047_ganoniatask'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportgoldtraditionaltask',
            name='total_hasila_dollar',
            field=models.FloatField(default=0, verbose_name='total_hasila_dollar'),
            preserve_default=False,
        ),
    ]
