# Generated by Django 5.0.2 on 2025-03-13 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0116_appfuelpermissiondetail_fuel_actual_qty'),
        ('planning', '0048_exportgoldtraditionaltask_total_hasila_dollar'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportgoldtraditionaltask',
            name='no_alloy',
            field=models.IntegerField(default=0, verbose_name='no_alloy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportgoldtraditionaltask',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state'),
            preserve_default=False,
        ),
    ]
