# Generated by Django 5.2.12 on 2026-03-14 12:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0138_alter_apphseaccidentreport_options'),
        ('planning', '0049_exportgoldtraditionaltask_no_alloy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExportGoldCompanyMonthlyPlanning',
            new_name='ExportGoldCompanyQuarterlyPlanning',
        ),
        migrations.RenameModel(
            old_name='ExportGoldTraditionalMonthlyPlanning',
            new_name='ExportGoldTraditionalQuarterlyPlanning',
        ),
        migrations.RemoveField(
            model_name='monthelyreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='monthelyreport',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='othermineralsproductionmonthlyplanning',
            name='mineral',
        ),
        migrations.RemoveField(
            model_name='othermineralsproductionmonthlyplanning',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='traditionaproductionmonthlyplanning',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='traditionatahsilbybandmonthlyplanning',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='traditionatahsilbyjihamonthlyplanning',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='traditionatahsilmonthlyplanning',
            name='plan',
        ),
        migrations.AlterModelOptions(
            name='exportgoldcompanyquarterlyplanning',
            options={'verbose_name': 'ExportGoldCompanyQuarterlyPlanning', 'verbose_name_plural': 'ExportGoldCompanyQuarterlyPlanning'},
        ),
        migrations.AlterModelOptions(
            name='exportgoldtraditionalquarterlyplanning',
            options={'verbose_name': 'ExportGoldTraditionalQuarterlyPlanning', 'verbose_name_plural': 'ExportGoldTraditionalQuarterlyPlanning'},
        ),
        migrations.RemoveField(
            model_name='taskduration',
            name='month',
        ),
        migrations.AddField(
            model_name='taskduration',
            name='quarter',
            field=models.PositiveIntegerField(choices=[(1, 'QUARTER_Q1'), (2, 'QUARTER_Q2'), (3, 'QUARTER_Q3'), (4, 'QUARTER_Q4')], default=1, verbose_name='quarter'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CompanyProductionQuarterlyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveIntegerField(choices=[(1, 'QUARTER_Q1'), (2, 'QUARTER_Q2'), (3, 'QUARTER_Q3'), (4, 'QUARTER_Q4')], verbose_name='quarter')),
                ('planed_weight', models.FloatField(verbose_name='planed_weight')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.yearlyplanning', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'CompanyProductionQuarterlyPlanning',
                'verbose_name_plural': 'CompanyProductionQuarterlyPlanning',
            },
        ),
        migrations.CreateModel(
            name='OtherMineralsProductionQuarterlyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveIntegerField(choices=[(1, 'QUARTER_Q1'), (2, 'QUARTER_Q2'), (3, 'QUARTER_Q3'), (4, 'QUARTER_Q4')], verbose_name='quarter')),
                ('planed_weight', models.FloatField(verbose_name='planed_weight')),
                ('mineral', models.ForeignKey(help_text='in ton', on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpmineral', verbose_name='mineral')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.yearlyplanning', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'OtherMineralsProductionQuarterlyPlanning',
                'verbose_name_plural': 'OtherMineralsProductionQuarterlyPlanning',
            },
        ),
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=2015), django.core.validators.MaxValueValidator(limit_value=2100)], verbose_name='year')),
                ('quarter', models.PositiveIntegerField(choices=[(1, 'QUARTER_Q1'), (2, 'QUARTER_Q2'), (3, 'QUARTER_Q3'), (4, 'QUARTER_Q4')], verbose_name='quarter')),
                ('state', models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_confirmed')], default=1, verbose_name='record_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_tasks', to='planning.quarterlyreport', verbose_name='report'),
        ),
        migrations.CreateModel(
            name='TraditionaProductionQuarterlyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveIntegerField(choices=[(1, 'QUARTER_Q1'), (2, 'QUARTER_Q2'), (3, 'QUARTER_Q3'), (4, 'QUARTER_Q4')], verbose_name='quarter')),
                ('planed_weight', models.FloatField(verbose_name='planed_weight')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.yearlyplanning', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'TraditionaProductionQuarterlyPlanning',
                'verbose_name_plural': 'TraditionaProductionQuarterlyPlanning',
            },
        ),
        migrations.CreateModel(
            name='TraditionaTahsilByBandQuarterlyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveIntegerField(choices=[(1, 'QUARTER_Q1'), (2, 'QUARTER_Q2'), (3, 'QUARTER_Q3'), (4, 'QUARTER_Q4')], verbose_name='quarter')),
                ('band', models.IntegerField(choices=[(1, 'band_1'), (2, 'band_2'), (3, 'band_3'), (4, 'band_4'), (5, 'band_5'), (6, 'band_6'), (7, 'band_7'), (8, 'band_8'), (9, 'band_9'), (10, 'band_10'), (11, 'band_11'), (12, 'band_12'), (13, 'band_13'), (14, 'band_14'), (15, 'band_15'), (16, 'band_16')], verbose_name='band')),
                ('planed_money', models.FloatField(verbose_name='planed_money')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.yearlyplanning', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'TraditionaTahsilByBandQuarterlyPlanning',
                'verbose_name_plural': 'TraditionaTahsilByBandQuarterlyPlanning',
            },
        ),
        migrations.CreateModel(
            name='TraditionaTahsilByJihaQuarterlyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveIntegerField(choices=[(1, 'QUARTER_Q1'), (2, 'QUARTER_Q2'), (3, 'QUARTER_Q3'), (4, 'QUARTER_Q4')], verbose_name='quarter')),
                ('jiha', models.IntegerField(choices=[(1, 'jiha_1'), (2, 'jiha_2'), (3, 'jiha_3'), (4, 'jiha_4'), (5, 'jiha_5')], verbose_name='jiha')),
                ('planed_money', models.FloatField(verbose_name='planed_money')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.yearlyplanning', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'TraditionaTahsilByJihaQuarterlyPlanning',
                'verbose_name_plural': 'TraditionaTahsilByJihaQuarterlyPlanning',
            },
        ),
        migrations.CreateModel(
            name='TraditionaTahsilQuarterlyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveIntegerField(choices=[(1, 'QUARTER_Q1'), (2, 'QUARTER_Q2'), (3, 'QUARTER_Q3'), (4, 'QUARTER_Q4')], verbose_name='quarter')),
                ('planed_money', models.FloatField(verbose_name='planed_money')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.yearlyplanning', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'TraditionaTahsilQuarterlyPlanning',
                'verbose_name_plural': 'TraditionaTahsilQuarterlyPlanning',
            },
        ),
        migrations.DeleteModel(
            name='CompanyProductionMonthlyPlanning',
        ),
        migrations.DeleteModel(
            name='OtherMineralsProductionMonthlyPlanning',
        ),
        migrations.DeleteModel(
            name='TraditionaProductionMonthlyPlanning',
        ),
        migrations.DeleteModel(
            name='TraditionaTahsilByBandMonthlyPlanning',
        ),
        migrations.DeleteModel(
            name='TraditionaTahsilByJihaMonthlyPlanning',
        ),
        migrations.DeleteModel(
            name='TraditionaTahsilMonthlyPlanning',
        ),
        migrations.DeleteModel(
            name='MonthelyReport',
        ),
    ]
