# Generated by Django 5.2.7 on 2026-04-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0050_rename_exportgoldcompanymonthlyplanning_exportgoldcompanyquarterlyplanning_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quarterlyreport',
            options={'verbose_name': 'QuarterlyReport', 'verbose_name_plural': 'QuarterlyReports'},
        ),
        migrations.AlterField(
            model_name='companyproductionquarterlyplanning',
            name='quarter',
            field=models.PositiveIntegerField(choices=[(1, 'الربع الأول'), (2, 'الربع الثاني'), (3, 'الربع الثالث'), (4, 'الربع الرابع')], verbose_name='quarter'),
        ),
        migrations.AlterField(
            model_name='othermineralsproductionquarterlyplanning',
            name='quarter',
            field=models.PositiveIntegerField(choices=[(1, 'الربع الأول'), (2, 'الربع الثاني'), (3, 'الربع الثالث'), (4, 'الربع الرابع')], verbose_name='quarter'),
        ),
        migrations.AlterField(
            model_name='quarterlyreport',
            name='quarter',
            field=models.PositiveIntegerField(choices=[(1, 'الربع الأول'), (2, 'الربع الثاني'), (3, 'الربع الثالث'), (4, 'الربع الرابع')], verbose_name='quarter'),
        ),
        migrations.AlterField(
            model_name='taskduration',
            name='quarter',
            field=models.PositiveIntegerField(choices=[(1, 'الربع الأول'), (2, 'الربع الثاني'), (3, 'الربع الثالث'), (4, 'الربع الرابع')], verbose_name='quarter'),
        ),
        migrations.AlterField(
            model_name='traditionaproductionquarterlyplanning',
            name='quarter',
            field=models.PositiveIntegerField(choices=[(1, 'الربع الأول'), (2, 'الربع الثاني'), (3, 'الربع الثالث'), (4, 'الربع الرابع')], verbose_name='quarter'),
        ),
        migrations.AlterField(
            model_name='traditionatahsilbybandquarterlyplanning',
            name='quarter',
            field=models.PositiveIntegerField(choices=[(1, 'الربع الأول'), (2, 'الربع الثاني'), (3, 'الربع الثالث'), (4, 'الربع الرابع')], verbose_name='quarter'),
        ),
        migrations.AlterField(
            model_name='traditionatahsilbyjihaquarterlyplanning',
            name='quarter',
            field=models.PositiveIntegerField(choices=[(1, 'الربع الأول'), (2, 'الربع الثاني'), (3, 'الربع الثالث'), (4, 'الربع الرابع')], verbose_name='quarter'),
        ),
        migrations.AlterField(
            model_name='traditionatahsilquarterlyplanning',
            name='quarter',
            field=models.PositiveIntegerField(choices=[(1, 'الربع الأول'), (2, 'الربع الثاني'), (3, 'الربع الثالث'), (4, 'الربع الرابع')], verbose_name='quarter'),
        ),
    ]
