# Generated by Django 5.0.2 on 2025-07-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlicensetype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='driverlicensetype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='driverlicensetype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='driverlicensetype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='vehiclecertificatetype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehiclecertificatetype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehiclecertificatetype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vehiclecertificatetype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='vehiclefueltype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehiclefueltype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehiclefueltype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vehiclefueltype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='vehiclemake',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehiclemake',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehiclemake',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vehiclemake',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='vehiclestatus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehiclestatus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehiclestatus',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vehiclestatus',
            name='updated_by',
        ),
    ]
