# Generated by Django 5.0.2 on 2025-07-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_remove_driverlicensetype_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='assigned_vehicle',
        ),
    ]
