# Generated by Django 5.0.2 on 2025-07-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_remove_driver_assigned_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleassignment',
            options={'verbose_name': 'الجهة/الموظف المخصصة له', 'verbose_name_plural': 'الجهات/الموظفين المخصص لهم'},
        ),
    ]
