# Generated by Django 5.0.2 on 2025-07-14 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_vehicleassignment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleassignment',
            options={'verbose_name': 'الجهة او الموظف المخصصة له', 'verbose_name_plural': 'الجهات او الموظفين المخصص لهم'},
        ),
        migrations.AlterField(
            model_name='vehicleassignment',
            name='assign_to',
            field=models.CharField(max_length=100, verbose_name='اسم الموظف او الجهة المخصص لها'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehiclemake', verbose_name='الشركة المصنعة'),
        ),
    ]
