# Generated by Django 5.0.2 on 2025-07-15 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_vehiclegpsdevice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclegpsdevice',
            options={'verbose_name': 'جهاز تتبع مركبة', 'verbose_name_plural': 'اجهزة تتبع المركبات'},
        ),
        migrations.AlterField(
            model_name='vehiclegpsdevice',
            name='gps',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fleet.tcdevices', verbose_name='جهاز التتبع'),
        ),
        migrations.AlterField(
            model_name='vehiclegpsdevice',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehicle', verbose_name='المركبة'),
        ),
    ]
