# Generated by Django 5.0.2 on 2025-07-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_alter_vehiclegpsdevice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclegpsdevice',
            name='gps',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.tcdevices', verbose_name='جهاز التتبع'),
        ),
        migrations.AlterField(
            model_name='vehiclegpsdevice',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle', verbose_name='المركبة'),
        ),
    ]
