# Generated by Django 5.0.2 on 2025-07-15 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_alter_vehiclegpsdevice_gps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclegpsdevice',
            name='gps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.tcdevices', verbose_name='جهاز التتبع'),
        ),
    ]
