# Generated by Django 5.0.2 on 2025-07-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_mission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleassignment',
            options={'verbose_name': 'تخصيص مركبة', 'verbose_name_plural': 'تخصيص المركبات'},
        ),
    ]
