# Generated by Django 5.0.2 on 2025-07-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_alter_vehicleassignment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'المأمورية', 'verbose_name_plural': 'المأموريات'},
        ),
    ]
