# Generated by Django 5.0.2 on 2025-07-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_alter_mission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'السائق', 'verbose_name_plural': 'قائمة السائقين'},
        ),
        migrations.AlterModelOptions(
            name='driverlicensetype',
            options={'verbose_name': 'نوع الرخصة', 'verbose_name_plural': 'قائمة انواع الرخص'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'المأمورية', 'verbose_name_plural': 'إدارة المأموريات'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'المركبة', 'verbose_name_plural': 'إدارة المركبات'},
        ),
        migrations.AlterModelOptions(
            name='vehicleassignment',
            options={'verbose_name': 'تخصيص مركبة', 'verbose_name_plural': 'إدارة تخصيص المركبات'},
        ),
        migrations.AlterModelOptions(
            name='vehiclecertificate',
            options={'verbose_name': 'شهادة المركبة', 'verbose_name_plural': 'قائمة شهادات المركبات'},
        ),
        migrations.AlterModelOptions(
            name='vehiclecertificatetype',
            options={'verbose_name': 'نوع شهادة مركبة', 'verbose_name_plural': 'قائمة انواع شهادات المركبات'},
        ),
        migrations.AlterModelOptions(
            name='vehicledriver',
            options={'verbose_name': 'سائق مركبة', 'verbose_name_plural': 'سائقي المركبات'},
        ),
        migrations.AlterModelOptions(
            name='vehiclefueltype',
            options={'verbose_name': 'نوع الوقود', 'verbose_name_plural': 'قائمة انواع الوقود'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemake',
            options={'verbose_name': 'الشركة المصنعة', 'verbose_name_plural': 'قائمة الشركات المصنعة'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'verbose_name': 'موديل المركبة', 'verbose_name_plural': 'قائمة موديلات المركبات'},
        ),
        migrations.AlterModelOptions(
            name='vehiclestatus',
            options={'verbose_name': 'حالة المركبة', 'verbose_name_plural': 'قائمة حالات المركبات'},
        ),
    ]
