# Generated by Django 5.0.2 on 2025-07-16 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_alter_driver_options_alter_driverlicensetype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='start_date',
        ),
        migrations.AddField(
            model_name='mission',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البدء الفعلي'),
        ),
        migrations.AddField(
            model_name='mission',
            name='no_of_days',
            field=models.IntegerField(default=0, verbose_name='عدد الأيام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='planned_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ البدء المخطط'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='تاريخ الانتهاء'),
        ),
    ]
