# Generated by Django 5.0.2 on 2025-07-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_remove_mission_start_date_mission_actual_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='end_date',
        ),
        migrations.AddField(
            model_name='mission',
            name='actual_end_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='تاريخ الانتهاء الفعلي'),
        ),
        migrations.AddField(
            model_name='mission',
            name='planned_end_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='تاريخ الانتهاء المخطط'),
        ),
    ]
