# Generated by Django 5.0.2 on 2025-07-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_remove_mission_end_date_mission_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclegpsdevice',
            name='gps',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.tcdevices', verbose_name='جهاز التتبع'),
        ),
    ]
