# Generated by Django 5.0.2 on 2025-07-16 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_alter_vehiclegpsdevice_gps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclegpsdevice',
            name='gps',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.tcdevices', verbose_name='جهاز التتبع'),
        ),
    ]
