# Generated by Django 5.0.2 on 2025-07-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0019_alter_vehiclegpsdevice_gps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcdevices',
            options={'managed': False, 'verbose_name': 'جهاز تتبع', 'verbose_name_plural': 'قائمة اجهزة التتبع'},
        ),
    ]
