# Generated by Django 5.0.2 on 2025-07-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0020_alter_tcdevices_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='book_value',
            field=models.CharField(default=0, max_length=100, verbose_name='القيمة التقديرية'),
        ),
    ]
