# Generated by Django 5.0.2 on 2025-07-17 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_vehicle_book_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=100, verbose_name='رقم الهاتف')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'مقدم الخدمة',
                'verbose_name_plural': 'قائمة مقدمي الخدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('periodic', models.BooleanField(default=False, verbose_name='خدمة دورية؟')),
            ],
            options={
                'verbose_name': 'نوع الصيانة',
                'verbose_name_plural': 'قائمة انواع الصيانة',
            },
        ),
        migrations.CreateModel(
            name='VehicleSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('service_date', models.DateField(verbose_name='تاريخ الصيانة')),
                ('next_service_due', models.DateField(blank=True, help_text='في حال الصيانة/الخدمة الدورية', null=True, verbose_name='تاريخ الصيانة التالية')),
                ('odometer_km', models.FloatField(verbose_name='قراءة عداد المسافة (كم)')),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة (جنيه)')),
                ('downtime_hrs', models.FloatField(blank=True, null=True, verbose_name='وقت التوقف (ساعات)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.serviceprovider', verbose_name='مقدم الصيانة')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.servicetype', verbose_name='نوع الصيانة')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'صيانة المركبة',
                'verbose_name_plural': 'إدارة صيانة المركبات',
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenancePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة (جنيه)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehiclemaintenance', verbose_name='صيانة')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehicle', verbose_name='المركبة')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehiclesparepart')),
            ],
            options={
                'verbose_name': 'اسبير مركبة',
                'verbose_name_plural': 'اسبيرات المركبات',
            },
        ),
    ]
