# Generated by Django 5.0.2 on 2025-07-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0022_serviceprovider_servicetype_vehiclesparepart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemaintenancepart',
            name='vehicle',
        ),
    ]
