# Generated by Django 5.0.2 on 2025-07-17 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0023_remove_vehiclemaintenancepart_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaintenancepart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehiclesparepart', verbose_name='الاسبير'),
        ),
    ]
