# Generated by Django 5.0.2 on 2025-07-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0024_alter_vehiclemaintenancepart_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaintenancepart',
            name='part',
            field=models.CharField(max_length=100, verbose_name='الاسبير'),
        ),
        migrations.DeleteModel(
            name='VehicleSparePart',
        ),
    ]
