# Generated by Django 5.0.2 on 2025-07-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0025_alter_vehiclemaintenancepart_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='no_of_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الأيام'),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='next_service_due',
            field=models.DateField(blank=True, editable=False, help_text='في حال الصيانة/الخدمة الدورية', null=True, verbose_name='تاريخ الصيانة التالية'),
        ),
    ]
