# Generated by Django 5.0.2 on 2025-07-17 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0026_servicetype_no_of_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.serviceprovider', verbose_name='مقدم الخدمة'),
        ),
    ]
