# Generated by Django 5.0.2 on 2025-07-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0027_alter_vehiclemaintenance_service_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemaintenance',
            old_name='service_cost',
            new_name='service_total_cost',
        ),
    ]
