# Generated by Django 5.0.2 on 2025-07-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0028_rename_service_cost_vehiclemaintenance_service_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='service_total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة الكلية (جنيه)'),
        ),
    ]
