# Generated by Django 5.0.2 on 2025-07-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0029_alter_vehiclemaintenance_service_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='book_value',
            field=models.FloatField(default=0, verbose_name='القيمة التقديرية'),
        ),
    ]
