# Generated by Django 5.2.7 on 2026-05-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0030_alter_vehicle_book_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='extended_actual_end_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='تاريخ الانتهاء الفعلي بعد التمديد'),
        ),
        migrations.AddField(
            model_name='mission',
            name='extended_planned_end_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='تاريخ الانتهاء المخطط بعد التمديد'),
        ),
        migrations.AddField(
            model_name='mission',
            name='extension_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد أيام التمديد'),
        ),
        migrations.AddField(
            model_name='mission',
            name='is_extended',
            field=models.BooleanField(default=False, verbose_name='تمديد المأمورية؟'),
        ),
    ]
