# Generated by Django 5.2.7 on 2026-05-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0031_mission_extended_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleassignment',
            name='status',
            field=models.CharField(choices=[('allocation', 'تخصيص'), ('missions', 'ماموريات'), ('transport', 'تراحيل'), ('state_office', 'مكتب ولائي')], default='allocation', max_length=20, verbose_name='الحالة'),
        ),
    ]
