# Generated by Django 5.2.7 on 2026-05-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0032_vehicleassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleassignment',
            name='status',
            field=models.CharField(choices=[('allocation', 'تخصيص'), ('missions', 'ماموريات'), ('transport', 'تراحيل'), ('administrative', 'ادارية'), ('state_office', 'مكتب ولائي')], default='allocation', max_length=20, verbose_name='الحالة'),
        ),
    ]
