# Generated by Django 5.2.7 on 2026-05-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0034_alter_mission_driver_alter_mission_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionvehicle',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='missionvehicle',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='missionvehicle',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.vehicledriver', verbose_name='المركبة والسائق'),
        ),
    ]
