# Generated by Django 5.2.7 on 2026-05-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0035_remove_missionvehicle_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='no_of_vehicles',
            field=models.IntegerField(default=1, verbose_name='عدد المركبات'),
        ),
    ]
