# Generated by Django 5.2.7 on 2026-07-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0036_mission_no_of_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mission_attachments/', verbose_name='الملف')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_attachments', to='fleet.mission', verbose_name='المأمورية')),
            ],
            options={
                'verbose_name': 'مرفق المأمورية',
                'verbose_name_plural': 'مرفقات المأمورية',
            },
        ),
    ]
