# Generated by Django 5.2.7 on 2026-07-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0037_add_mission_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='termination_date',
            field=models.DateField(blank=True, help_text='في حال قطع المأمورية قبل موعدها، يصبح هذا التاريخ هو تاريخ الانتهاء الفعلي وتُعتبر المأمورية منتهية', null=True, verbose_name='تاريخ قطع المأمورية'),
        ),
    ]
