# Generated by Django 5.2.7 on 2026-08-24 06:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0038_add_mission_termination_date'),
        ('hr', '0137_alter_employeebasic_no3_2lertibat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelMonthlyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(help_text='مثال: كشف الوقود الشهري - أغسطس 2026', max_length=200, verbose_name='عنوان الكشف')),
                ('month', models.IntegerField(default=8, verbose_name='الشهر')),
                ('year', models.IntegerField(default=2026, verbose_name='السنة')),
                ('statement_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الكشف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'كشف وقود شهري',
                'verbose_name_plural': 'كشوفات الوقود الشهرية',
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelDistributionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('is_external', models.BooleanField(default=False, verbose_name='مستفيد غير مدرج / خارجي')),
                ('beneficiary_name', models.CharField(max_length=150, verbose_name='اسم المستفيد')),
                ('employee_code_or_card', models.CharField(blank=True, max_length=50, null=True, verbose_name='كود الموظف / رقم البطاقة')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='البريد الإلكتروني')),
                ('department', models.CharField(blank=True, max_length=150, null=True, verbose_name='الإدارة')),
                ('job_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='الوظيفة')),
                ('petrol_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حصة البنزين (لتر)')),
                ('diesel_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حصة الجازولين (لتر)')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ (جنيه)')),
                ('notes_signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='التوقيع / ملاحظات')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_distributions', to='hr.employeebasic', verbose_name='الموظف بالموارد البشرية')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fleet.fuelmonthlystatement', verbose_name='كشف الوقود')),
            ],
            options={
                'verbose_name': 'بند كشف الوقود',
                'verbose_name_plural': 'بنود كشف الوقود',
                'ordering': ['id'],
            },
        ),
    ]
