# Generated by Django 5.2.7 on 2026-08-24 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0039_fuelmonthlystatement_fueldistributionitem'),
        ('hr', '0137_alter_employeebasic_no3_2lertibat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelBeneficiarySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('is_external', models.BooleanField(default=False, verbose_name='مستفيد غير مدرج / خارجي')),
                ('beneficiary_name', models.CharField(max_length=150, verbose_name='اسم المستفيد')),
                ('employee_code_or_card', models.CharField(blank=True, max_length=50, null=True, verbose_name='كود الموظف / رقم البطاقة')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='البريد الإلكتروني')),
                ('department', models.CharField(blank=True, max_length=150, null=True, verbose_name='الإدارة')),
                ('job_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='الوظيفة')),
                ('default_petrol_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حصة البنزين الافتراضية (لتر)')),
                ('default_diesel_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حصة الجازولين الافتراضية (لتر)')),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ الافتراضي (جنيه)')),
                ('is_active_for_fuel', models.BooleanField(default=True, verbose_name='مفعل للحصول على الوقود شهرياً')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_settings', to='hr.employeebasic', verbose_name='الموظف بالموارد البشرية')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'إعداد مستفيد الوقود',
                'verbose_name_plural': 'إعدادات مستفيدي الوقود',
                'ordering': ['id'],
            },
        ),
    ]
