# Generated by Django 5.2.7 on 2026-08-24 07:15 (modified to use RenameField to preserve existing data)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0040_fuelbeneficiarysetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelbeneficiarysetting',
            old_name='employee_code_or_card',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='fueldistributionitem',
            old_name='employee_code_or_card',
            new_name='card_number',
        ),
    ]
