# Generated by Django 5.2.7 on 2026-08-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0041_rename_employee_code_to_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelmonthlystatement',
            name='diesel_price_per_liter',
            field=models.DecimalField(decimal_places=2, default=0, help_text='سعر لتر الجازولين بالجنيه السوداني - يُستخدم لحساب المبلغ عند توليد بنود الكشف', max_digits=10, verbose_name='سعر لتر الجازولين (جنيه)'),
        ),
        migrations.AddField(
            model_name='fuelmonthlystatement',
            name='petrol_price_per_liter',
            field=models.DecimalField(decimal_places=2, default=0, help_text='سعر لتر البنزين بالجنيه السوداني - يُستخدم لحساب المبلغ عند توليد بنود الكشف', max_digits=10, verbose_name='سعر لتر البنزين (جنيه)'),
        ),
        migrations.AlterField(
            model_name='fuelbeneficiarysetting',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم بطاقة الوقود'),
        ),
        migrations.AlterField(
            model_name='fueldistributionitem',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم بطاقة الوقود'),
        ),
    ]
