# Generated by Django 5.2.7 on 2026-08-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0042_add_fuel_prices_to_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueldistributionitem',
            name='diesel_liters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حصة الجازولين (جالون)'),
        ),
        migrations.AlterField(
            model_name='fueldistributionitem',
            name='petrol_liters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حصة البنزين (جالون)'),
        ),
        migrations.AlterField(
            model_name='fuelmonthlystatement',
            name='diesel_price_per_liter',
            field=models.DecimalField(decimal_places=4, default=0, help_text='', max_digits=10, verbose_name='سعر لتر الجازولين (جنيه)'),
        ),
        migrations.AlterField(
            model_name='fuelmonthlystatement',
            name='petrol_price_per_liter',
            field=models.DecimalField(decimal_places=4, default=0, help_text='', max_digits=10, verbose_name='سعر لتر البنزين (جنيه)'),
        ),
    ]
