# Generated by Django 5.2.7 on 2026-08-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0043_update_price_decimal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelmonthlystatement',
            name='diesel_price_per_liter',
            field=models.DecimalField(decimal_places=4, help_text='', default=0, max_digits=10, verbose_name='سعر لتر الجازولين (جنيه)'),
        ),
        migrations.AlterField(
            model_name='fuelmonthlystatement',
            name='petrol_price_per_liter',
            field=models.DecimalField(decimal_places=4, help_text='', default=0, max_digits=10, verbose_name='سعر لتر البنزين (جنيه)'),
        ),
    ]
