# Generated by Django 5.2.7 on 2026-08-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0044_alter_fuelmonthlystatement_diesel_price_per_liter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelbeneficiarysetting',
            name='default_amount',
        ),
        migrations.AlterField(
            model_name='fuelmonthlystatement',
            name='diesel_price_per_liter',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='سعر لتر الجازولين (جنيه)'),
        ),
        migrations.AlterField(
            model_name='fuelmonthlystatement',
            name='petrol_price_per_liter',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='سعر لتر البنزين (جنيه)'),
        ),
        migrations.AlterField(
            model_name='fuelmonthlystatement',
            name='title',
            field=models.CharField(help_text='', max_length=200, verbose_name='عنوان الكشف'),
        ),
    ]
