# Generated by Django 5.2.7 on 2026-09-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0046_setup_fleet_group_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelmonthlystatement',
            name='title',
            field=models.CharField(help_text='', max_length=200, verbose_name='عنوان الكشف'),
        ),
    ]
