# Generated by Django 5.2.7 on 2026-09-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0049_alter_fuelmonthlystatement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelmonthlystatement',
            name='title',
            field=models.CharField(help_text='', max_length=200, verbose_name='عنوان الكشف'),
        ),
    ]
