# Generated by Django 5.2.7 on 2025-11-08 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BPMNNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bpmn_id', models.CharField(help_text='ID from BPMN XML', max_length=200)),
                ('node_type', models.CharField(choices=[('start_event', 'Start Event'), ('end_event', 'End Event'), ('intermediate_event', 'Intermediate Event'), ('user_task', 'User Task'), ('service_task', 'Service Task'), ('script_task', 'Script Task'), ('send_task', 'Send Task'), ('receive_task', 'Receive Task'), ('exclusive_gateway', 'Exclusive Gateway'), ('parallel_gateway', 'Parallel Gateway'), ('inclusive_gateway', 'Inclusive Gateway')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('assignee_expression', models.CharField(blank=True, help_text="Expression to determine assignee (e.g., '${department.manager}')", max_length=500)),
                ('candidate_groups', models.JSONField(blank=True, default=list, help_text='List of group names that can claim this task')),
                ('form_key', models.CharField(blank=True, help_text='Reference to Django form class', max_length=200)),
                ('implementation', models.CharField(blank=True, help_text='Python function path for service tasks', max_length=500)),
                ('default_flow', models.CharField(blank=True, help_text='BPMN ID of default sequence flow', max_length=200, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BPMN Node',
                'verbose_name_plural': 'BPMN Nodes',
            },
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('variables', models.JSONField(default=dict, help_text='Process-level variables')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_processes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Process Instance',
                'verbose_name_plural': 'Process Instances',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn_workflow.bpmnnode')),
                ('parent_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tokens', to='bpmn_workflow.token')),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='bpmn_workflow.processinstance')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('ready', 'Ready'), ('reserved', 'Reserved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('candidate_users', models.ManyToManyField(blank=True, related_name='candidate_tasks', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bpmn_workflow.bpmnnode')),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='bpmn_workflow.processinstance')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn_workflow.token')),
            ],
            options={
                'verbose_name': 'Task Instance',
                'verbose_name_plural': 'Task Instances',
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text='Unique identifier for this workflow', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('bpmn_xml', models.TextField(help_text='Original BPMN 2.0 XML content')),
                ('bpmn_process_id', models.CharField(help_text='Process ID from BPMN file', max_length=200)),
                ('handler_class', models.CharField(blank=True, help_text="Python path to handler class (e.g., 'bpmn_workflow.handlers.MyHandler')", max_length=500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow Definition',
                'verbose_name_plural': 'Workflow Definitions',
                'ordering': ['-version'],
                'unique_together': {('key', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SequenceFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bpmn_id', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('condition_expression', models.TextField(blank=True, help_text='Python expression for flow condition')),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_flows', to='bpmn_workflow.bpmnnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_flows', to='bpmn_workflow.bpmnnode')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='bpmn_workflow.workflowdefinition')),
            ],
            options={
                'verbose_name': 'Sequence Flow',
                'verbose_name_plural': 'Sequence Flows',
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='processinstance',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bpmn_workflow.workflowdefinition'),
        ),
        migrations.AddField(
            model_name='bpmnnode',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='bpmn_workflow.workflowdefinition'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('process_started', 'Process Started'), ('process_completed', 'Process Completed'), ('process_terminated', 'Process Terminated'), ('process_suspended', 'Process Suspended'), ('process_resumed', 'Process Resumed'), ('task_created', 'Task Created'), ('task_assigned', 'Task Assigned'), ('task_started', 'Task Started'), ('task_completed', 'Task Completed'), ('task_failed', 'Task Failed'), ('gateway_evaluated', 'Gateway Evaluated'), ('token_moved', 'Token Moved'), ('variable_set', 'Variable Set')], max_length=30)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bpmn_workflow.bpmnnode')),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='bpmn_workflow.processinstance')),
                ('task_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpmn_workflow.taskinstance')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['process_instance', '-timestamp'], name='bpmn_workfl_process_2de328_idx'), models.Index(fields=['event_type', '-timestamp'], name='bpmn_workfl_event_t_3f7be7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['process_instance', 'is_active'], name='bpmn_workfl_process_f5e453_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['assignee', 'status'], name='bpmn_workfl_assigne_f1957d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['process_instance', 'status'], name='bpmn_workfl_process_aa24bc_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['-created_at'], name='bpmn_workfl_created_a4d9e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sequenceflow',
            unique_together={('workflow', 'bpmn_id')},
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='bpmn_workfl_content_119019_idx'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['status'], name='bpmn_workfl_status_9554e5_idx'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['-started_at'], name='bpmn_workfl_started_5f7ea7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bpmnnode',
            unique_together={('workflow', 'bpmn_id')},
        ),
    ]
