# Generated by Django 5.2.7 on 2025-11-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn_workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequenceflow',
            name='condition_expression',
            field=models.TextField(blank=True, help_text='Python expression for flow condition', null=True),
        ),
    ]
