# Generated by Django 5.2.7 on 2025-11-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn_workflow', '0002_alter_sequenceflow_condition_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmnnode',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
