# Generated by Django 5.2.7 on 2025-11-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn_workflow', '0003_bpmnnode_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bpmnnode',
            old_name='is_approved',
            new_name='final_approval',
        ),
    ]
