# Generated by Django 5.2.7 on 2025-11-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn_workflow', '0004_rename_is_approved_bpmnnode_final_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpmnnode',
            name='final_approval',
        ),
    ]
