# Generated by Django 5.2.7 on 2025-11-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn_workflow', '0005_remove_bpmnnode_final_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('process_started', 'بدأت العملية'), ('process_completed', 'إكتملت العملية'), ('process_terminated', 'Process Terminated'), ('process_suspended', 'تم تجميد العملية'), ('process_resumed', 'تم فك تجميد العملية'), ('task_created', 'تم انشاء مهمة'), ('task_assigned', 'تم اسناد مهمة'), ('task_started', 'بدأت المهمة'), ('task_completed', 'إكتملت المهمة'), ('task_failed', 'فشلت المهمة'), ('gateway_evaluated', 'Gateway Evaluated'), ('token_moved', 'Token Moved'), ('variable_set', 'Variable Set')], max_length=30),
        ),
    ]
