# Generated by Django 5.2.7 on 2026-02-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn_workflow', '0006_alter_activitylog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('error', 'Error'), ('waiting', 'Waiting')], default='active', max_length=20),
        ),
    ]
