# Generated by Django 6.0.3 on 2026-04-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn_workflow', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='status',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
