# Generated by Django 5.1.7 on 2025-05-12 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khatabat',
            fields=[
                ('letter_number', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='رقم الخطاب')),
                ('subject', models.TextField(verbose_name='موضوع الخطاب')),
            ],
        ),
        migrations.CreateModel(
            name='HarkatKhatabat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(max_length=100, verbose_name='نوع الحركة')),
                ('source_entity', models.CharField(max_length=255, verbose_name='جهة الخطاب')),
                ('receive_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='الإدراج')),
                ('letter_image', models.ImageField(blank=True, null=True, upload_to='khatabat/', verbose_name='صورة الخطاب')),
                ('forwarded_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='الجهة المحول لها')),
                ('forward_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التحويل')),
                ('receiver_signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='توقيع المستلم')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('followup_image', models.ImageField(blank=True, null=True, upload_to='mutabaah/', verbose_name='صورة نتيجة المتابعة')),
                ('followup_result', models.CharField(blank=True, max_length=255, null=True, verbose_name='نتيجة المتابعة')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khatabat.khatabat', verbose_name='رقم الخطاب')),
            ],
        ),
    ]
