# Generated by Django 5.1.7 on 2025-05-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0002_alter_harkatkhatabat_letter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harkatkhatabat',
            options={'verbose_name': 'حركة خطاب', 'verbose_name_plural': 'حركة الخطابات'},
        ),
        migrations.AlterModelOptions(
            name='khatabat',
            options={'verbose_name': 'الخطاب', 'verbose_name_plural': 'الخطابات'},
        ),
    ]
