# Generated by Django 5.1.7 on 2025-05-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0003_alter_harkatkhatabat_options_alter_khatabat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khatabat',
            options={'ordering': ['-letter_number'], 'verbose_name': 'الخطاب', 'verbose_name_plural': 'الخطابات'},
        ),
    ]
