# Generated by Django 5.1.7 on 2025-05-12 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0006_alter_harkatkhatabat_movement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harkatkhatabat',
            name='receive_date',
        ),
        migrations.AddField(
            model_name='harkatkhatabat',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='harkatkhatabat',
            name='movement_type',
            field=models.IntegerField(choices=[(1, 'وارد'), (2, 'صادر')], verbose_name='نوع الحركة'),
        ),
    ]
