# Generated by Django 5.1.7 on 2025-05-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0009_alter_harkatkhatabat_followup_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harkatkhatabat',
            name='receiver_signature',
            field=models.BooleanField(default=False, verbose_name='توقيع المستلم'),
        ),
    ]
