# Generated by Django 5.1.7 on 2025-05-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0010_alter_harkatkhatabat_receiver_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harkatkhatabat',
            name='procedure',
            field=models.IntegerField(choices=[(1, 'الاجرأء'), (2, 'توصية'), (3, 'للإجراء'), (4, 'للتشاور'), (5, 'للإفادة'), (6, 'تصدق'), (7, 'للإطلاع والإحاطة'), (8, 'للعمل بموجبه'), (9, 'للإحاطة واجراء اللازم'), (10, 'للإطلاع وابداء الرأي')], verbose_name='الإجراء'),
        ),
    ]
