# Generated by Django 5.1.7 on 2025-05-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0011_alter_harkatkhatabat_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harkatkhatabat',
            name='procedure',
            field=models.IntegerField(choices=[(1, 'توصية'), (2, 'للإجراء'), (3, 'للتشاور'), (4, 'للإفادة'), (5, 'تصدق'), (6, 'للإطلاع والإحاطة'), (7, 'للعمل بموجبه'), (8, 'للإحاطة واجراء اللازم'), (9, 'للإطلاع وابداء الرأي')], verbose_name='الإجراء'),
        ),
    ]
