# Generated by Django 5.1.7 on 2025-05-12 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0012_alter_harkatkhatabat_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaktabTanfizi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='المكتب التنفيذي')),
            ],
            options={
                'verbose_name': 'المكتب التنفيذي',
                'verbose_name_plural': 'المكاتب التنفيذية',
            },
        ),
        migrations.RemoveField(
            model_name='harkatkhatabat',
            name='receiver_signature',
        ),
        migrations.AddField(
            model_name='harkatkhatabat',
            name='destination_entity',
            field=models.CharField(default=1, max_length=255, verbose_name='جهة الخطاب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='khatabat',
            name='maktab_tanfizi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='khatabat.maktabtanfizi', verbose_name='المكتب التنفيذي'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MaktabTanfiziJiha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='جهة الخطاب')),
                ('maktab_tanfizi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khatabat.maktabtanfizi', verbose_name='المكتب التنفيذي')),
            ],
            options={
                'verbose_name': 'جهة الخطاب',
                'verbose_name_plural': 'جهات الخطاب',
            },
        ),
        migrations.AlterField(
            model_name='harkatkhatabat',
            name='forwarded_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forwarded_to', to='khatabat.maktabtanfizijiha', verbose_name='الجهة المحول لها'),
        ),
        migrations.AlterField(
            model_name='harkatkhatabat',
            name='source_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_entities', to='khatabat.maktabtanfizijiha', verbose_name='جهة الخطاب'),
        ),
    ]
