# Generated by Django 5.1.7 on 2025-05-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0014_khatabat_created_at_khatabat_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harkatkhatabat',
            name='destination_entity',
        ),
    ]
