# Generated by Django 5.1.7 on 2025-05-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0016_maktabtanfizi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='harkatkhatabat',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='harkatkhatabat',
            name='letter_attachment',
            field=models.FileField(blank=True, null=True, upload_to='khatabat/', verbose_name='صورة الخطاب'),
        ),
    ]
