# Generated by Django 5.2.7 on 2025-11-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0017_harkatkhatabat_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harkatkhatabat',
            name='procedure',
            field=models.IntegerField(choices=[(1, 'توصية'), (2, 'للإجراء'), (3, 'للتشاور'), (4, 'للإفادة'), (5, 'تصدق'), (6, 'للإطلاع والإحاطة'), (7, 'للعمل بموجبه'), (8, 'للإحاطة واجراء اللازم'), (9, 'للإطلاع وابداء الرأي'), (10, 'للحفظ')], verbose_name='الإجراء'),
        ),
    ]
