# Generated by Django 5.2.7 on 2025-11-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0018_alter_harkatkhatabat_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='maktabtanfizi',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='الرمز'),
        ),
    ]
