# Generated by Django 5.2.7 on 2025-11-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0019_maktabtanfizi_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harkatkhatabat',
            name='forwarded_to',
        ),
        migrations.AddField(
            model_name='harkatkhatabat',
            name='forwarded_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='forwarded_to', to='khatabat.maktabtanfizijiha', verbose_name='الجهة المحول لها'),
        ),
    ]
