# Generated by Django 5.2.7 on 2025-11-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0020_remove_harkatkhatabat_forwarded_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harkatkhatabat',
            name='forwarded_to',
            field=models.ManyToManyField(related_name='forwarded_to', to='khatabat.maktabtanfizijiha', verbose_name='الجهة المحول لها'),
        ),
    ]
