# Generated by Django 5.2.7 on 2025-12-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0021_alter_harkatkhatabat_forwarded_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarkatKhatabatInbox',
            fields=[
            ],
            options={
                'verbose_name': 'حركة خطاب وارد',
                'verbose_name_plural': 'حركة الخطابات الواردة',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('khatabat.harkatkhatabat',),
        ),
        migrations.CreateModel(
            name='HarkatKhatabatOutbox',
            fields=[
            ],
            options={
                'verbose_name': 'حركة خطاب صادر',
                'verbose_name_plural': 'حركة الخطابات الصادرة',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('khatabat.harkatkhatabat',),
        ),
    ]
