# Generated by Django 5.2.7 on 2025-12-02 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0023_alter_harkatkhatabat_procedure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maktabtanfizi',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maktab_tanfizi_manager', to=settings.AUTH_USER_MODEL, verbose_name='مدير'),
        ),
    ]
