# Generated by Django 5.2.7 on 2025-12-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0024_maktabtanfizi_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khatabat',
            options={'ordering': ['-created_at'], 'verbose_name': 'الخطاب', 'verbose_name_plural': 'الخطابات'},
        ),
    ]
