# Generated by Django 5.2.7 on 2025-12-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0025_alter_khatabat_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harkatkhatabat',
            name='followup_attachment',
        ),
        migrations.RemoveField(
            model_name='harkatkhatabat',
            name='followup_result',
        ),
        migrations.CreateModel(
            name='Motab3atKhatabat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('note', models.CharField(verbose_name='الإجراء')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='mutabaah/', verbose_name='صورة نتيجة المتابعة')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khatabat.khatabat', verbose_name='رقم الخطاب')),
            ],
            options={
                'verbose_name': 'متابعة خطاب',
                'verbose_name_plural': 'متابعة الخطابات',
            },
        ),
    ]
