# Generated by Django 5.2.7 on 2025-12-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0026_remove_harkatkhatabat_followup_attachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motab3atkhatabat',
            old_name='note',
            new_name='action',
        ),
    ]
