# Generated by Django 5.2.7 on 2025-12-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0027_rename_note_motab3atkhatabat_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='khatabat',
            name='has_motab3at',
            field=models.BooleanField(default=False, verbose_name='يوجد متابعة؟'),
        ),
    ]
