# Generated by Django 5.2.7 on 2025-12-02 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0028_khatabat_has_motab3at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maktabtanfizi',
            name='follow_up',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maktab_tanfizi_follow_up', to=settings.AUTH_USER_MODEL, verbose_name='موظف متابعة'),
        ),
        migrations.RemoveField(
            model_name='maktabtanfizi',
            name='manager',
        ),
        migrations.AddField(
            model_name='maktabtanfizi',
            name='manager',
            field=models.ManyToManyField(null=True, related_name='maktab_tanfizi_manager', to=settings.AUTH_USER_MODEL, verbose_name='مدير'),
        ),
    ]
