# Generated by Django 5.2.7 on 2025-12-02 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0029_maktabtanfizi_follow_up_remove_maktabtanfizi_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maktabtanfizi',
            name='manager',
            field=models.ManyToManyField(related_name='maktab_tanfizi_manager', to=settings.AUTH_USER_MODEL, verbose_name='مدير'),
        ),
    ]
