# Generated by Django 5.2.7 on 2025-12-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0030_alter_maktabtanfizi_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='motab3atkhatabat',
            name='done',
            field=models.BooleanField(default=False, verbose_name='هل إكتملت المهمة؟'),
        ),
    ]
