# Generated by Django 5.2.7 on 2025-12-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0031_motab3atkhatabat_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='motab3atkhatabat',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
    ]
