# Generated by Django 5.2.7 on 2025-12-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0032_motab3atkhatabat_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harkatkhatabat',
            name='letter_attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='khatabat/', verbose_name='صورة الخطاب'),
        ),
        migrations.AlterField(
            model_name='motab3atkhatabat',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='mutabaah/', verbose_name='صورة نتيجة المتابعة'),
        ),
    ]
