# Generated by Django 5.2.7 on 2025-12-14 08:45

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0033_alter_harkatkhatabat_letter_attachment_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='khatabat',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
