# Generated by Django 5.2.7 on 2025-12-14 09:00

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0035_khatabattaggedletter_alter_khatabat_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khatabat',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='khatabat.KhatabatTaggedLetter', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
