# Generated by Django 5.2.7 on 2025-12-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0036_alter_khatabat_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='maktabtanfizijiha',
            name='kharijia',
            field=models.BooleanField(default=False, verbose_name='جهة خارجية؟'),
        ),
    ]
