# Generated by Django 5.2.7 on 2025-12-24 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatabat', '0037_maktabtanfizijiha_kharijia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maktabtanfizi',
            name='follow_up',
        ),
        migrations.RemoveField(
            model_name='maktabtanfizi',
            name='user',
        ),
        migrations.AddField(
            model_name='maktabtanfizi',
            name='follow_up',
            field=models.ManyToManyField(null=True, related_name='maktab_tanfizi_follow_up', to=settings.AUTH_USER_MODEL, verbose_name='موظف متابعة'),
        ),
        migrations.AddField(
            model_name='maktabtanfizi',
            name='user',
            field=models.ManyToManyField(related_name='maktab_tanfizi_user', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
