# Generated by Django 5.0.1 on 2024-02-04 19:44

import company_profile.models
import django.db.models.deletion
# import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LkpCompanyProductionFactoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Factory Type',
                'verbose_name_plural': 'Factory Types',
            },
        ),
        migrations.CreateModel(
            name='LkpCompanyProductionLicenseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'License Status',
                'verbose_name_plural': 'License Status',
            },
        ),
        migrations.CreateModel(
            name='LkpCompanyProductionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Company Status',
                'verbose_name_plural': 'Company Status',
            },
        ),
        migrations.CreateModel(
            name='LkpNationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationalities',
            },
        ),
        migrations.CreateModel(
            name='LkpState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='AppBorrowMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('state', models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=50, verbose_name='application_state')),
                ('notify', models.BooleanField(default=False, editable=False, verbose_name='notify_user')),
                ('borrow_date', models.DateField(verbose_name='borrow_date')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application: BorrowMaterials',
                'verbose_name_plural': 'Application: BorrowMaterials',
            },
        ),
        migrations.CreateModel(
            name='AppBorrowMaterialDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200, verbose_name='borrow_material')),
                ('quantity', models.IntegerField(verbose_name='borrow_quantity')),
                ('borrow_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.appborrowmaterial')),
            ],
            options={
                'verbose_name': 'AppBorrowMaterialDetail',
                'verbose_name_plural': 'AppBorrowMaterialDetail',
            },
        ),
        migrations.CreateModel(
            name='LkpLocality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
            ],
            options={
                'verbose_name': 'Locality',
                'verbose_name_plural': 'Localities',
            },
        ),
        migrations.CreateModel(
            name='TblCompanyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name_ar')),
                ('name_en', models.CharField(max_length=200, verbose_name='name_en')),
                ('location', models.TextField(max_length=256, verbose_name='location')),
                ('cordinates', models.TextField(max_length=256, verbose_name='cordinates')),
                ('address', models.TextField(max_length=256, verbose_name='address')),
                ('website', models.URLField(verbose_name='website')),
                ('manager_name', models.CharField(max_length=200, verbose_name='manager_name')),
                ('manager_phone', models.CharField(max_length=20, verbose_name='manager_phone')),
                ('rep_name', models.CharField(max_length=200, verbose_name='Representative name')),
                ('rep_phone', models.CharField(max_length=20, verbose_name='Representative phone')),
                ('email', models.EmailField(max_length=100, verbose_name='Official email')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkplocality', verbose_name='locality')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpnationality', verbose_name='nationality')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpcompanyproductionstatus', verbose_name='status')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Production Company',
                'verbose_name_plural': 'Production Companies',
            },
        ),
        migrations.CreateModel(
            name='AppForignerMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('state', models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=50, verbose_name='application_state')),
                ('notify', models.BooleanField(default=False, editable=False, verbose_name='notify_user')),
                ('route_from', models.CharField(max_length=200, verbose_name='route_from')),
                ('route_to', models.CharField(max_length=200, verbose_name='route_to')),
                ('period_from', models.DateField(verbose_name='period_from')),
                ('period_to', models.DateField(verbose_name='period_to')),
                ('address_in_sudan', models.TextField(max_length=256, verbose_name='address_in_sudan')),
                ('passport_no', models.CharField(max_length=20, verbose_name='passport_no')),
                ('passport_expiry_date', models.DateField(verbose_name='passport_expiry_date')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpnationality', verbose_name='nationality')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Application: Forigner movement ',
                'verbose_name_plural': 'Application: Forigner movement',
            },
        ),
        migrations.AddField(
            model_name='appborrowmaterial',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_to', to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='appborrowmaterial',
            name='company_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_from', to='company_profile.tblcompanyproduction', verbose_name='company_borrow_from'),
        ),
        migrations.CreateModel(
            name='TblCompanyProductionFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('capacity', models.FloatField(verbose_name='Capacity (Tones per day)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('factory_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpcompanyproductionfactorytype', verbose_name='factory_type')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Production Company Factory',
                'verbose_name_plural': 'Production Company Factories',
            },
        ),
        migrations.CreateModel(
            name='TblCompanyProductionLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('date', models.DateField(verbose_name='Sign date')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('sheet_no', models.CharField(max_length=10, verbose_name='sheet_no')),
                ('cordinates', models.TextField(max_length=256, verbose_name='cordinates')),
                ('area', models.FloatField(verbose_name='Area in Kilometers')),
                ('reserve', models.FloatField(verbose_name='Reserve in Tones')),
                ('gov_rep', models.CharField(max_length=200, verbose_name='Goverment representative')),
                ('rep_percent', models.FloatField(verbose_name='Representative percentage(%)')),
                ('com_percent', models.FloatField(verbose_name='Company percentage(%)')),
                ('royalty', models.FloatField(verbose_name='royalty')),
                ('zakat', models.FloatField(verbose_name='zakat')),
                ('annual_rent', models.FloatField(verbose_name='company')),
                ('contract_file', models.FileField(upload_to=company_profile.models.company_contract_path, verbose_name='contract_file')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('contract_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpcompanyproductionlicensestatus', verbose_name='contract_status')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Production Company License',
                'verbose_name_plural': 'Production Company Licenses',
            },
        ),
        migrations.CreateModel(
            name='TblCompanyProductionUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pro_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production Company User',
                'verbose_name_plural': 'Production Company Users',
            },
        ),
    ]
