# Generated by Django 5.0.1 on 2024-02-04 20:01

import company_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appforignermovement',
            name='cv_file',
            field=models.FileField(default=(), upload_to=company_profile.models.company_contract_path, verbose_name='cv_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appforignermovement',
            name='experiance_certificates_file',
            field=models.FileField(default=(), upload_to=company_profile.models.company_contract_path, verbose_name='experiance_certificates_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appforignermovement',
            name='official_letter_file',
            field=models.FileField(default=(), upload_to=company_profile.models.company_contract_path, verbose_name='official_letter_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appforignermovement',
            name='passport_copy_file',
            field=models.FileField(default=(), upload_to=company_profile.models.company_contract_path, verbose_name='passport_copy_file'),
            preserve_default=False,
        ),
    ]
