# Generated by Django 5.0.1 on 2024-02-04 20:24

import company_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0002_appforignermovement_cv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appborrowmaterial',
            name='borrow_from_approval_file',
            field=models.FileField(default=('1\n',), upload_to=company_profile.models.company_applications_path, verbose_name='borrow_from_approval_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appborrowmaterial',
            name='borrow_materials_list_file',
            field=models.FileField(default=('1\n',), upload_to=company_profile.models.company_applications_path, verbose_name='borrow_materials_list_file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appforignermovement',
            name='cv_file',
            field=models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='cv_file'),
        ),
        migrations.AlterField(
            model_name='appforignermovement',
            name='experiance_certificates_file',
            field=models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='experiance_certificates_file'),
        ),
        migrations.AlterField(
            model_name='appforignermovement',
            name='official_letter_file',
            field=models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='official_letter_file'),
        ),
        migrations.AlterField(
            model_name='appforignermovement',
            name='passport_copy_file',
            field=models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='passport_copy_file'),
        ),
    ]
