# Generated by Django 5.0.1 on 2024-02-06 22:38

import company_profile.models
import django.db.models.deletion
# # import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0005_insert_data_for_first_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appborrowmaterial',
            options={'ordering': ['-id'], 'verbose_name': 'Application: BorrowMaterials', 'verbose_name_plural': 'Application: BorrowMaterials'},
        ),
        migrations.AlterModelOptions(
            name='appforignermovement',
            options={'ordering': ['-id'], 'verbose_name': 'Application: Forigner movement ', 'verbose_name_plural': 'Application: Forigner movement'},
        ),
        migrations.CreateModel(
            name='AppWorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('state', models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=50, verbose_name='application_state')),
                ('notify', models.BooleanField(default=False, editable=False, verbose_name='notify_user')),
                ('plan_from', models.DateField(verbose_name='plan_from')),
                ('plan_to', models.DateField(verbose_name='plan_to')),
                ('official_letter_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='official_letter_file')),
                ('work_plan_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='work_plan_file')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application: Work Plan',
                'verbose_name_plural': 'Application: Work Plan',
                'ordering': ['-id'],
            },
        ),
    ]
