# Generated by Django 5.0.1 on 2024-02-07 00:50

import company_profile.models
import django.db.models.deletion
# import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0007_apptechnicalfinancialreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptechnicalfinancialreport',
            name='report_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('financial', 'Financial')], max_length=15, verbose_name='report_type'),
        ),
        migrations.CreateModel(
            name='AppChangeCompanyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('state', models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=50, verbose_name='application_state')),
                ('notify', models.BooleanField(default=False, editable=False, verbose_name='notify_user')),
                ('new_name', models.CharField(max_length=200, verbose_name='new_name')),
                ('cause_for_change', models.TextField(max_length=256, verbose_name='cause_for_change')),
                ('tasis_certificate_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='tasis_certificate_file')),
                ('tasis_contract_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='tasis_contract_file')),
                ('sh7_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='sh7_file')),
                ('lahat_tasis_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='lahat_tasis_file')),
                ('name_change_alert_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='name_change_alert_file')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application: Company Name Change',
                'verbose_name_plural': 'Application: Company Name Changes',
                'ordering': ['-id'],
            },
        ),
    ]
