# Generated by Django 5.0.1 on 2024-02-07 01:10

import company_profile.models
import django.db.models.deletion
# import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0008_alter_apptechnicalfinancialreport_report_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appchangecompanyname',
            name='cause_for_change',
            field=models.TextField(max_length=1000, verbose_name='cause_for_change'),
        ),
        migrations.CreateModel(
            name='AppExplorationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('state', models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=50, verbose_name='application_state')),
                ('notify', models.BooleanField(default=False, editable=False, verbose_name='notify_user')),
                ('expo_from', models.DateField(verbose_name='expo_from')),
                ('expo_to', models.DateField(verbose_name='expo_to')),
                ('expo_cause_for_timing', models.TextField(max_length=1000, verbose_name='expo_cause_for_timing')),
                ('expo_cause_for_change_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='expo_cause_for_change_file')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application: Exploration Time',
                'verbose_name_plural': 'Application: Exploration Time',
                'ordering': ['-id'],
            },
        ),
    ]
