# Generated by Django 5.0.1 on 2024-02-07 06:59

import company_profile.models
import django.core.validators
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0010_alter_appexplorationtime_options_appaddarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRemoveArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('state', django_fsm.FSMField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=50, verbose_name='application_state')),
                ('notify', models.BooleanField(default=False, editable=False, verbose_name='notify_user')),
                ('remove_type', models.CharField(choices=[('first', 'first'), ('second', 'second'), ('exceptional', 'exceptional')], max_length=15, verbose_name='remove_type')),
                ('area_in_km2', models.IntegerField(verbose_name='area_in_km2')),
                ('area_percent_from_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='area_percent_from_total')),
                ('geo_coordinator_for_removed_area_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='geo_coordinator_for_removed_area_file')),
                ('geo_coordinator_for_remain_area_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='geo_coordinator_for_remain_area_file')),
                ('map_for_clarification_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='map_for_clarification_file')),
                ('technical_report_for_removed_area_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='technical_report_for_removed_area_file')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application: Remove Area',
                'verbose_name_plural': 'Application: Remove Area',
                'ordering': ['-id'],
            },
        ),
    ]
