# Generated by Django 5.0.1 on 2024-02-07 04:37

import company_profile.models
import django.db.models.deletion
# # import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0019_appchangeworkprocedure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppExportGold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('state', models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=50, verbose_name='application_state')),
                ('notify', models.BooleanField(default=False, editable=False, verbose_name='notify_user')),
                ('total_in_gram', models.FloatField(verbose_name='total_in_gram')),
                ('net_in_gram', models.FloatField(verbose_name='net_in_gram')),
                ('zakat_in_gram', models.FloatField(verbose_name='zakat_in_gram')),
                ('awaad_jalila_in_gram', models.FloatField(verbose_name='awaad_jalila_in_gram')),
                ('arbah_amal_in_gram', models.FloatField(verbose_name='arbah_amal_in_gram')),
                ('sold_for_bank_of_sudan_in_gram', models.FloatField(verbose_name='sold_for_bank_of_sudan_in_gram')),
                ('amount_to_export_in_gram', models.FloatField(verbose_name='amount_to_export_in_gram')),
                ('remain_in_gram', models.FloatField(verbose_name='remain_in_gram')),
                ('f1', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f1')),
                ('f2', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f2')),
                ('f3', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f3')),
                ('f4', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f4')),
                ('f5', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f5')),
                ('f6', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f6')),
                ('f7', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f7')),
                ('f8', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f8')),
                ('f9', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f9')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application: Export Gold',
                'verbose_name_plural': 'Application: Export Gold',
                'ordering': ['-id'],
            },
        ),
    ]
