# Generated by Django 5.0.1 on 2024-02-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0020_appexportgold'),
    ]

    operations = [
        migrations.CreateModel(
            name='LkpMineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Mineral',
                'verbose_name_plural': 'Minerals',
            },
        ),
    ]
