# Generated by Django 5.0.1 on 2024-02-07 05:01

import company_profile.models
import django.db.models.deletion
# import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0021_lkpmineral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppExportGoldRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('state', models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=50, verbose_name='application_state')),
                ('notify', models.BooleanField(default=False, editable=False, verbose_name='notify_user')),
                ('license_type', models.CharField(max_length=50, verbose_name='license_type')),
                ('amount_in_gram', models.FloatField(verbose_name='amount_in_gram')),
                ('sale_price', models.FloatField(verbose_name='sale_price')),
                ('export_country', models.CharField(max_length=50, verbose_name='export_country')),
                ('export_city', models.CharField(max_length=50, verbose_name='export_city')),
                ('export_address', models.TextField(max_length=200, verbose_name='export_address')),
                ('f11', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f11')),
                ('f12', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f12')),
                ('f13', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f13')),
                ('f14', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f14')),
                ('f15', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f15')),
                ('f16', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f16')),
                ('f17', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f17')),
                ('f18', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f18')),
                ('f19', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='f19')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('mineral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpmineral', verbose_name='mineral')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application: Export Gold Raw',
                'verbose_name_plural': 'Application: Export Gold Raw',
                'ordering': ['-id'],
            },
        ),
    ]
