# Generated by Django 5.0.1 on 2024-02-07 08:02

import company_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0023_appsendsamplesforanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsendsamplesforanalysis',
            name='last_analysis_report_file',
            field=models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='last_analysis_report_file'),
        ),
    ]
