# Generated by Django 5.0.1 on 2024-02-07 08:24

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0024_alter_appsendsamplesforanalysis_last_analysis_report_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSendSamplesForAnalysisDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('state', django_fsm.FSMField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=50, verbose_name='application_state')),
                ('notify', models.BooleanField(default=False, editable=False, verbose_name='notify_user')),
                ('sample_type', models.CharField(max_length=100, verbose_name='sample_type')),
                ('sample_weight', models.FloatField(verbose_name='sample_weight')),
                ('sample_packing_type', models.CharField(max_length=100, verbose_name='sample_packing_type')),
                ('sample_analysis_type', models.CharField(max_length=100, verbose_name='sample_analysis_type')),
                ('sample_analysis_cause', models.TextField(max_length=256, verbose_name='sample_analysis_cause')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('sample_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.appsendsamplesforanalysis', verbose_name='sample_master')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
