# Generated by Django 5.0.1 on 2024-02-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0025_appsendsamplesforanalysisdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsendsamplesforanalysisdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appsendsamplesforanalysisdetail',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appsendsamplesforanalysisdetail',
            name='notify',
        ),
        migrations.RemoveField(
            model_name='appsendsamplesforanalysisdetail',
            name='state',
        ),
        migrations.RemoveField(
            model_name='appsendsamplesforanalysisdetail',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='appsendsamplesforanalysisdetail',
            name='updated_by',
        ),
    ]
