# Generated by Django 5.0.1 on 2024-02-06 22:15

import company_profile.models
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0026_remove_appsendsamplesforanalysisdetail_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LkpForeignerProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Foreigner Procedure Type',
                'verbose_name_plural': 'Foreigner Procedure Types',
            },
        ),
        migrations.AlterModelOptions(
            name='appsendsamplesforanalysisdetail',
            options={'verbose_name': 'Send Samples For Analysis Detail', 'verbose_name_plural': 'Send Samples For Analysis Detail'},
        ),
        migrations.CreateModel(
            name='AppForeignerProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('state', django_fsm.FSMField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=50, verbose_name='application_state')),
                ('notify', models.BooleanField(default=False, editable=False, verbose_name='notify_user')),
                ('procedure_from', models.DateField(verbose_name='procedure_from')),
                ('procedure_to', models.DateField(verbose_name='procedure_to')),
                ('procedure_cause', models.TextField(max_length=1000, verbose_name='procedure_cause')),
                ('official_letter_file', models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='official_letter_file')),
                ('passport_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='passport_file')),
                ('cv_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='cv_file')),
                ('experience_certificates_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='experience_certificates_file')),
                ('eqama_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='eqama_file')),
                ('dawa_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='dawa_file')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('procedure_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpforeignerproceduretype', verbose_name='procedure_type')),
            ],
            options={
                'verbose_name': 'Application: Send samples for analysis',
                'verbose_name_plural': 'Application: Send samples for analysis',
                'ordering': ['-id'],
            },
        ),
    ]
