# Generated by Django 5.0.1 on 2024-02-06 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0027_lkpforeignerproceduretype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppForeignerProcedureDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100, verbose_name='employee_name')),
                ('employee_address', models.TextField(max_length=200, verbose_name='employee_address')),
                ('procedure_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.appforeignerprocedure', verbose_name='procedure_master')),
            ],
            options={
                'verbose_name': 'Foreigner Procedure Detail',
                'verbose_name_plural': 'Foreigner Procedure Detail',
            },
        ),
    ]
