# Generated by Django 5.0.1 on 2024-02-06 22:36

import company_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0029_alter_appforeignerprocedure_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appforeignerprocedure',
            name='dawa_file',
            field=models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='dawa_file'),
        ),
        migrations.AlterField(
            model_name='appforeignerprocedure',
            name='eqama_file',
            field=models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='eqama_file'),
        ),
    ]
