# Generated by Django 5.0.1 on 2024-02-06 23:06

import company_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0030_alter_appforeignerprocedure_dawa_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appforeignerprocedure',
            name='official_letter_file',
            field=models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='official_letter_file'),
        ),
    ]
