# Generated by Django 5.0.1 on 2024-02-06 22:40

import company_profile.models
import django.db.models.deletion
# import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0031_alter_appforeignerprocedure_official_letter_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAifaaJomrki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('state', models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=50, verbose_name='application_state')),
                ('notify', models.BooleanField(default=False, editable=False, verbose_name='notify_user')),
                ('approved_requirements_list_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='approved_requirements_list_file')),
                ('approval_from_finance_ministry_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='approval_from_finance_ministry_file')),
                ('final_voucher_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='final_voucher_file')),
                ('shipping_policy_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='shipping_policy_file')),
                ('check_certificate_file', models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='check_certificate_file')),
                ('origin_certificate_file', models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='origin_certificate_file')),
                ('packing_certificate_file', models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='packing_certificate_file')),
                ('specifications_file', models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='specifications_file')),
                ('taba_file', models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='taba_file')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpcompanyproductionlicensestatus', verbose_name='license_type')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application: Aifaa Jomrki',
                'verbose_name_plural': 'Application: Aifaa Jomrki',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AppAifaaJomrkiDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200, verbose_name='material_name')),
                ('aifaa_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.appaifaajomrki', verbose_name='aifaa_master')),
            ],
            options={
                'verbose_name': 'Aifaa Jomrki Detail',
                'verbose_name_plural': 'Aifaa Jomrki Details',
            },
        ),
    ]
