# Generated by Django 5.0.1 on 2024-02-06 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0032_appaifaajomrki_appaifaajomrkidetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appaifaajomrki',
            name='license_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproductionlicense', verbose_name='license_type'),
        ),
    ]
