# Generated by Django 5.0.1 on 2024-02-06 23:09

import company_profile.models
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0033_alter_appaifaajomrki_license_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppReexportEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('state', django_fsm.FSMField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=50, verbose_name='application_state')),
                ('notify', models.BooleanField(default=False, editable=False, verbose_name='notify_user')),
                ('cause_for_equipments', models.TextField(max_length=1000, verbose_name='procedure_cause')),
                ('shipping_policy_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='shipping_policy_file')),
                ('voucher_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='voucher_file')),
                ('specifications_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='specifications_file')),
                ('momentary_approval_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='momentary_approval_file')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application: Reexport Equipments',
                'verbose_name_plural': 'Application: Reexport Equipments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AppReexportEquipmentsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='material_name')),
                ('serial_id', models.CharField(max_length=50, verbose_name='serial_id')),
                ('policy_no', models.CharField(max_length=50, verbose_name='policy_no')),
                ('voucher_no', models.CharField(max_length=50, verbose_name='voucher_no')),
                ('insurance_no', models.CharField(max_length=50, verbose_name='insurance_no')),
                ('check_certificate_no', models.CharField(max_length=50, verbose_name='check_certificate_no')),
                ('reexport_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.appreexportequipments', verbose_name='aifaa_master')),
            ],
            options={
                'verbose_name': 'Reexport Equipments Detail',
                'verbose_name_plural': 'Reexport Equipments Details',
            },
        ),
    ]
