# Generated by Django 5.0.1 on 2024-02-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0034_appreexportequipments_appreexportequipmentsdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreexportequipments',
            name='cause_for_equipments',
            field=models.TextField(max_length=1000, verbose_name='cause_for_equipments'),
        ),
        migrations.AlterField(
            model_name='appreexportequipmentsdetail',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
