# Generated by Django 5.0.1 on 2024-02-06 22:35

import company_profile.models
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0035_alter_appreexportequipments_cause_for_equipments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRequirementsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('state', django_fsm.FSMField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=50, verbose_name='application_state')),
                ('notify', models.BooleanField(default=False, editable=False, verbose_name='notify_user')),
                ('approved_work_plan_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='approved_work_plan_file')),
                ('initial_voucher_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='initial_voucher_file')),
                ('specifications_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='specifications_file')),
                ('mshobat_jamarik_file', models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='mshobat_jamarik_file')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application: Requirements List',
                'verbose_name_plural': 'Application: Requirements List',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AppRequirementsListChemicalEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='item')),
                ('description', models.TextField(max_length=256, verbose_name='cause_for_equipments')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('requirements_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apprequirementslist', verbose_name='requirements_master')),
            ],
            options={
                'verbose_name': 'Application: Requirements List - Chemical Equipments',
                'verbose_name_plural': 'Application: Requirements List - Chemical Equipments',
            },
        ),
        migrations.CreateModel(
            name='AppRequirementsListChemicalLabEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='item')),
                ('description', models.TextField(max_length=256, verbose_name='cause_for_equipments')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('requirements_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apprequirementslist', verbose_name='requirements_master')),
            ],
            options={
                'verbose_name': 'Application: Requirements List - Chemical Lab Equipments',
                'verbose_name_plural': 'Application: Requirements List - Chemical Lab Equipments',
            },
        ),
        migrations.CreateModel(
            name='AppRequirementsListElectricityEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='item')),
                ('description', models.TextField(max_length=256, verbose_name='cause_for_equipments')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('requirements_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apprequirementslist', verbose_name='requirements_master')),
            ],
            options={
                'verbose_name': 'Application: Requirements List - Electricity Equipments',
                'verbose_name_plural': 'Application: Requirements List - Electricity Equipments',
            },
        ),
        migrations.CreateModel(
            name='AppRequirementsListFactoryEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='item')),
                ('description', models.TextField(max_length=256, verbose_name='cause_for_equipments')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('requirements_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apprequirementslist', verbose_name='requirements_master')),
            ],
            options={
                'verbose_name': 'Application: Requirements List - Factory Equipments',
                'verbose_name_plural': 'Application: Requirements List - Factory Equipments',
            },
        ),
        migrations.CreateModel(
            name='AppRequirementsListMangamEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='item')),
                ('description', models.TextField(max_length=256, verbose_name='cause_for_equipments')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('requirements_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apprequirementslist', verbose_name='requirements_master')),
            ],
            options={
                'verbose_name': 'Application: Requirements List - Mangam Equipments',
                'verbose_name_plural': 'Application: Requirements List - Mangam Equipments',
            },
        ),
        migrations.CreateModel(
            name='AppRequirementsListMotafjeratEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='item')),
                ('description', models.TextField(max_length=256, verbose_name='cause_for_equipments')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('requirements_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apprequirementslist', verbose_name='requirements_master')),
            ],
            options={
                'verbose_name': 'Application: Requirements List - Motafjerat Equipments',
                'verbose_name_plural': 'Application: Requirements List - Motafjerat Equipments',
            },
        ),
        migrations.CreateModel(
            name='AppRequirementsListVehiclesEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='item')),
                ('description', models.TextField(max_length=256, verbose_name='cause_for_equipments')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('requirements_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apprequirementslist', verbose_name='requirements_master')),
            ],
            options={
                'verbose_name': 'Application: Requirements List - Vehicles Equipments',
                'verbose_name_plural': 'Application: Requirements List - Vehicles Equipments',
            },
        ),
    ]
