# Generated by Django 5.0.1 on 2024-02-06 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0037_alter_apprequirementslistchemicalequipments_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appremovearea',
            name='area_percent_from_total',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='area_percent_from_total'),
        ),
    ]
