# Generated by Django 5.0.2 on 2024-03-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0038_alter_appremovearea_area_percent_from_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanyproduction',
            name='company_type',
            field=models.CharField(choices=[('entaj', 'entaj'), ('mokhalfat', 'mokhalfat'), ('emtiaz', 'emtiaz'), ('sageer', 'sageer')], default='entaj', max_length=15, verbose_name='company_type'),
            preserve_default=False,
        ),
    ]
