# Generated by Django 5.0.2 on 2024-03-12 08:34

import company_profile.models
import django.db.models.deletion
# import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0039_tblcompanyproduction_company_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVisibityStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('state', models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=50, verbose_name='application_state')),
                ('notify', models.BooleanField(default=False, editable=False, verbose_name='notify_user')),
                ('study_area', models.CharField(max_length=100, verbose_name='study_area')),
                ('study_type', models.CharField(max_length=100, verbose_name='study_type')),
                ('study_comment', models.TextField(max_length=1000, verbose_name='study_comment')),
                ('attachement_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='attachement_file')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproductionlicense', verbose_name='license_type')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application: Visibity Study',
                'verbose_name_plural': 'Application: Visibity Study',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AppVisibityStudyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_point_id', models.IntegerField(verbose_name='study_point_id')),
                ('study_point_long', models.DecimalField(decimal_places=12, max_digits=20, verbose_name='study_point_long')),
                ('study_point_lat', models.DecimalField(decimal_places=12, max_digits=20, verbose_name='study_point_lat')),
                ('study_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.appvisibitystudy')),
            ],
            options={
                'verbose_name': 'Visibity Study Detail',
                'verbose_name_plural': 'Visibity Study Details',
            },
        ),
    ]
