# Generated by Django 5.0.2 on 2024-03-14 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0042_appfuelpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcompanyproduction',
            name='cordinates',
        ),
        migrations.RemoveField(
            model_name='tblcompanyproduction',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='tblcompanyproduction',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tblcompanyproduction',
            name='state',
        ),
        migrations.AddField(
            model_name='tblcompanyproductionlicense',
            name='locality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkplocality', verbose_name='locality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcompanyproductionlicense',
            name='location',
            field=models.TextField(default=1, max_length=256, verbose_name='location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcompanyproductionlicense',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state'),
            preserve_default=False,
        ),
    ]
