# Generated by Django 5.0.2 on 2024-03-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0043_remove_tblcompanyproduction_cordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='location',
            field=models.CharField(max_length=100, verbose_name='location'),
        ),
    ]
