# Generated by Django 5.0.2 on 2024-03-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0044_alter_tblcompanyproductionlicense_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='com_percent',
            field=models.FloatField(blank=True, verbose_name='Company percentage(%)'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='gov_rep',
            field=models.CharField(blank=True, max_length=200, verbose_name='Goverment representative'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='rep_percent',
            field=models.FloatField(blank=True, verbose_name='Representative percentage(%)'),
        ),
    ]
