# Generated by Django 5.0.2 on 2024-03-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0045_alter_tblcompanyproductionlicense_com_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='annual_rent',
            field=models.FloatField(verbose_name='annual_rent'),
        ),
    ]
