# Generated by Django 5.0.2 on 2024-03-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0048_alter_tblcompanyproductionlicense_com_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='com_percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Company percentage(%)'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='gov_rep',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='Goverment representative'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='rep_percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Representative percentage(%)'),
        ),
    ]
