# Generated by Django 5.0.2 on 2024-03-17 22:06

import company_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0049_alter_tblcompanyproductionlicense_com_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanyproductionlicense',
            name='license_no',
            field=models.CharField(default='-', max_length=20, verbose_name='License no'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appborrowmaterial',
            name='borrow_materials_list_file',
            field=models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='borrow_materials_list_file'),
        ),
    ]
