# Generated by Django 5.0.2 on 2024-03-19 09:56

import company_profile.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0050_tblcompanyproductionlicense_license_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appexportgold',
            name='f2',
        ),
        migrations.RemoveField(
            model_name='appreexportequipments',
            name='momentary_approval_file',
        ),
        migrations.AddField(
            model_name='appexplosivepermission',
            name='attachement_file2',
            field=models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='explosive_amount_file'),
        ),
        migrations.AddField(
            model_name='appexplosivepermission',
            name='attachement_file3',
            field=models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='explosive_last_approved_request_file'),
        ),
        migrations.AddField(
            model_name='applocalpurchase',
            name='attachement_file2',
            field=models.FileField(default='', upload_to=company_profile.models.company_applications_path, verbose_name='local_purchase_invoice_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apptnazolshraka',
            name='agreement_file',
            field=models.FileField(default='', upload_to=company_profile.models.company_applications_path, verbose_name='agreement_file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appcyanidecertificate',
            name='attachement_file',
            field=models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='cyanide_request_file'),
        ),
        migrations.AlterField(
            model_name='appexplosivepermission',
            name='attachement_file',
            field=models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='explosive_request_file'),
        ),
        migrations.AlterField(
            model_name='appexportgold',
            name='arbah_amal_in_gram',
            field=models.FloatField(blank=True, default=0, verbose_name='arbah_amal_in_gram'),
        ),
        migrations.AlterField(
            model_name='appexportgold',
            name='f5',
            field=models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='f5'),
        ),
        migrations.AlterField(
            model_name='appimportpermission',
            name='attachement_file',
            field=models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='import_permission_materials_list_file'),
        ),
        migrations.AlterField(
            model_name='applocalpurchase',
            name='attachement_file',
            field=models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='local_request_file'),
        ),
        migrations.AlterField(
            model_name='apprestartactivity',
            name='attachement_file',
            field=models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='restart_activity_reason_file'),
        ),
        migrations.AlterField(
            model_name='apptamdeed',
            name='tnazol_file',
            field=models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='tnazol_file'),
        ),
        migrations.CreateModel(
            name='AppFuelPermissionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type_name', models.CharField(max_length=20, verbose_name='fuel_type_name')),
                ('fuel_qty', models.FloatField(verbose_name='fuel_qty')),
                ('fuel_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.appfuelpermission')),
            ],
            options={
                'verbose_name': 'Fuel Permission Detail',
                'verbose_name_plural': 'Fuel Permission Details',
            },
        ),
        migrations.CreateModel(
            name='AppImportPermissionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_material_name', models.CharField(max_length=100, verbose_name='import_material_name')),
                ('import_qty', models.FloatField(verbose_name='import_qty')),
                ('import_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.appimportpermission')),
            ],
            options={
                'verbose_name': 'Import Permission Detail',
                'verbose_name_plural': 'Import Permission Details',
            },
        ),
    ]
