# Generated by Django 5.0.2 on 2024-03-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0052_alter_appfuelpermission_attachement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appvisibitystudydetail',
            name='study_point_lat',
            field=models.FloatField(verbose_name='study_point_lat'),
        ),
        migrations.AlterField(
            model_name='appvisibitystudydetail',
            name='study_point_long',
            field=models.FloatField(verbose_name='study_point_long'),
        ),
    ]
