# Generated by Django 5.0.2 on 2024-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0054_appworkplan_plan_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appaddarea',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appaifaajomrki',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appborrowmaterial',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appchangecompanyname',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appchangeworkprocedure',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appcyanidecertificate',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appexplorationtime',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appexplosivepermission',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appexportgold',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appexportgoldraw',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appforeignerprocedure',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appforignermovement',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appfuelpermission',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='apphseaccidentreport',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='apphseperformancereport',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appimportpermission',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='applocalpurchase',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appmda',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appreexportequipments',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appremovearea',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='apprenewalcontract',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='apprequirementslist',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='apprestartactivity',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appsendsamplesforanalysis',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='apptaaweed',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='apptajeeltnazol',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='apptajmeed',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='apptakhali',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='apptamdeed',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='apptechnicalfinancialreport',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='apptemporaryexemption',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='apptnazolshraka',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appvisibitystudy',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
        migrations.AddField(
            model_name='appworkplan',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='reject_comments'),
        ),
    ]
