# Generated by Django 5.0.2 on 2024-03-20 21:20

import company_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0056_appwhomconcern'),
    ]

    operations = [
        migrations.AddField(
            model_name='appwhomconcern',
            name='whom_attachement_file',
            field=models.FileField(default='', upload_to=company_profile.models.company_applications_path, verbose_name='whom_attachement_file'),
            preserve_default=False,
        ),
    ]
