# Generated by Django 5.0.2 on 2024-03-20 21:26

import company_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0057_appwhomconcern_whom_attachement_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appwhomconcern',
            options={'ordering': ['-id'], 'verbose_name': 'Application: Whom may concern request', 'verbose_name_plural': 'Application: Whom may concern requests'},
        ),
        migrations.AlterField(
            model_name='appwhomconcern',
            name='whom_attachement_file',
            field=models.FileField(blank=True, upload_to=company_profile.models.company_applications_path, verbose_name='whom_attachement_file'),
        ),
    ]
