# Generated by Django 5.0.2 on 2024-03-20 21:38

import company_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0058_alter_appwhomconcern_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appwhomconcern',
            name='whom_attachement_file',
            field=models.FileField(blank=True, null=True, upload_to=company_profile.models.company_applications_path, verbose_name='whom_attachement_file'),
        ),
    ]
