# Generated by Django 5.0.2 on 2024-03-22 11:17

import company_profile.models
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0059_alter_appwhomconcern_whom_attachement_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppGoldProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('reject_comments', models.TextField(blank=True, max_length=256, verbose_name='reject_comments')),
                ('state', django_fsm.FSMField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=50, verbose_name='application_state')),
                ('notify', models.BooleanField(default=False, editable=False, verbose_name='notify_user')),
                ('form_no', models.CharField(max_length=20, verbose_name='form_no')),
                ('attachement_file', models.FileField(upload_to=company_profile.models.company_applications_path, verbose_name='gold_production_form_file')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application: Gold Production',
                'verbose_name_plural': 'Application: Gold Production',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AppGoldProductionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melt_dt', models.DateTimeField(verbose_name='melt_dt')),
                ('melt_bar_no', models.CharField(max_length=30, verbose_name='melt_bar_no')),
                ('melt_bar_weight', models.FloatField(verbose_name='melt_bar_weight')),
                ('melt_jaf', models.FloatField(verbose_name='melt_jaf')),
                ('melt_khabath', models.FloatField(verbose_name='melt_khabath')),
                ('melt_added_gold', models.FloatField(verbose_name='melt_added_gold')),
                ('melt_remaind', models.FloatField(verbose_name='melt_remaind')),
                ('melt_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.appgoldproduction')),
            ],
            options={
                'verbose_name': 'Gold Production Detail',
                'verbose_name_plural': 'Gold Production Details',
            },
        ),
    ]
