# Generated by Django 5.0.2 on 2024-03-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0061_alter_appgoldproductiondetail_melt_added_gold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appgoldproductiondetail',
            name='melt_added_gold',
            field=models.FloatField(blank=True, null=True, verbose_name='melt_added_gold'),
        ),
        migrations.AlterField(
            model_name='appgoldproductiondetail',
            name='melt_remaind',
            field=models.FloatField(blank=True, null=True, verbose_name='melt_remaind'),
        ),
    ]
