# Generated by Django 5.0.2 on 2024-04-22 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0062_alter_appgoldproductiondetail_melt_added_gold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanyproductionlicense',
            name='mineral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpmineral', verbose_name='mineral'),
            preserve_default=False,
        ),
    ]
