# Generated by Django 5.0.2 on 2024-05-02 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0063_tblcompanyproductionlicense_mineral'),
    ]

    operations = [
        migrations.CreateModel(
            name='LkpAccidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Accident Type',
                'verbose_name_plural': 'Accident Types',
            },
        ),
        migrations.AddField(
            model_name='apphseaccidentreport',
            name='accident_class',
            field=models.CharField(choices=[('minor', 'minor'), ('moderate', 'moderate'), ('major', 'major')], default='minor', max_length=10, verbose_name='accident_class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apphseaccidentreport',
            name='accident_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='accident_dt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apphseaccidentreport',
            name='accident_place',
            field=models.CharField(default='factory', max_length=100, verbose_name='accident_place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apphseaccidentreport',
            name='accident_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpaccidenttype', verbose_name='accident_type'),
            preserve_default=False,
        ),
    ]
