# Generated by Django 5.0.2 on 2024-05-05 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0064_lkpaccidenttype_apphseaccidentreport_accident_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appaddarea',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appaddarea',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appaddarea',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appaifaajomrki',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appaifaajomrki',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appaifaajomrki',
            name='license_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproductionlicense', verbose_name='license_type'),
        ),
        migrations.AlterField(
            model_name='appaifaajomrki',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appaifaajomrkidetail',
            name='aifaa_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.appaifaajomrki', verbose_name='aifaa_master'),
        ),
        migrations.AlterField(
            model_name='appborrowmaterial',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_to', to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appborrowmaterial',
            name='company_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_from', to='company_profile.tblcompanyproduction', verbose_name='company_borrow_from'),
        ),
        migrations.AlterField(
            model_name='appborrowmaterial',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appborrowmaterial',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appborrowmaterialdetail',
            name='borrow_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.appborrowmaterial'),
        ),
        migrations.AlterField(
            model_name='appchangecompanyname',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appchangecompanyname',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appchangecompanyname',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appchangeworkprocedure',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appchangeworkprocedure',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appchangeworkprocedure',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appcyanidecertificate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appcyanidecertificate',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appcyanidecertificate',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appexplorationtime',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appexplorationtime',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appexplorationtime',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appexplosivepermission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appexplosivepermission',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appexplosivepermission',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appexportgold',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appexportgold',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appexportgold',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appexportgoldraw',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appexportgoldraw',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appexportgoldraw',
            name='mineral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.lkpmineral', verbose_name='mineral'),
        ),
        migrations.AlterField(
            model_name='appexportgoldraw',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appforeignerprocedure',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appforeignerprocedure',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appforeignerprocedure',
            name='procedure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.lkpforeignerproceduretype', verbose_name='procedure_type'),
        ),
        migrations.AlterField(
            model_name='appforeignerprocedure',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appforeignerproceduredetail',
            name='procedure_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.appforeignerprocedure', verbose_name='procedure_master'),
        ),
        migrations.AlterField(
            model_name='appforignermovement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appforignermovement',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appforignermovement',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.lkpnationality', verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='appforignermovement',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appfuelpermission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appfuelpermission',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appfuelpermission',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appfuelpermissiondetail',
            name='fuel_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.appfuelpermission'),
        ),
        migrations.AlterField(
            model_name='appgoldproduction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appgoldproduction',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appgoldproduction',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appgoldproductiondetail',
            name='melt_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.appgoldproduction'),
        ),
        migrations.AlterField(
            model_name='apphseaccidentreport',
            name='accident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.lkpaccidenttype', verbose_name='accident_type'),
        ),
        migrations.AlterField(
            model_name='apphseaccidentreport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='apphseaccidentreport',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='apphseaccidentreport',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereport',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereport',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appimportpermission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appimportpermission',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appimportpermission',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appimportpermissiondetail',
            name='import_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.appimportpermission'),
        ),
        migrations.AlterField(
            model_name='applocalpurchase',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='applocalpurchase',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='applocalpurchase',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appmda',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appmda',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appmda',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appreexportequipments',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appreexportequipments',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appreexportequipments',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appreexportequipmentsdetail',
            name='reexport_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.appreexportequipments', verbose_name='aifaa_master'),
        ),
        migrations.AlterField(
            model_name='appremovearea',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appremovearea',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appremovearea',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='apprenewalcontract',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='apprenewalcontract',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='apprenewalcontract',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='apprequirementslist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='apprequirementslist',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='apprequirementslist',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='apprequirementslistchemicalequipments',
            name='requirements_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.apprequirementslist', verbose_name='requirements_master'),
        ),
        migrations.AlterField(
            model_name='apprequirementslistchemicallabequipments',
            name='requirements_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.apprequirementslist', verbose_name='requirements_master'),
        ),
        migrations.AlterField(
            model_name='apprequirementslistelectricityequipments',
            name='requirements_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.apprequirementslist', verbose_name='requirements_master'),
        ),
        migrations.AlterField(
            model_name='apprequirementslistfactoryequipments',
            name='requirements_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.apprequirementslist', verbose_name='requirements_master'),
        ),
        migrations.AlterField(
            model_name='apprequirementslistmangamequipments',
            name='requirements_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.apprequirementslist', verbose_name='requirements_master'),
        ),
        migrations.AlterField(
            model_name='apprequirementslistmotafjeratequipments',
            name='requirements_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.apprequirementslist', verbose_name='requirements_master'),
        ),
        migrations.AlterField(
            model_name='apprequirementslistvehiclesequipments',
            name='requirements_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.apprequirementslist', verbose_name='requirements_master'),
        ),
        migrations.AlterField(
            model_name='apprestartactivity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='apprestartactivity',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='apprestartactivity',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appsendsamplesforanalysis',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appsendsamplesforanalysis',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appsendsamplesforanalysis',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appsendsamplesforanalysisdetail',
            name='sample_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.appsendsamplesforanalysis', verbose_name='sample_master'),
        ),
        migrations.AlterField(
            model_name='apptaaweed',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='apptaaweed',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='apptaaweed',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='apptajeeltnazol',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='apptajeeltnazol',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='apptajeeltnazol',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='apptajmeed',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='apptajmeed',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='apptajmeed',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='apptakhali',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='apptakhali',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='apptakhali',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='apptamdeed',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='apptamdeed',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='apptamdeed',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='apptechnicalfinancialreport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='apptechnicalfinancialreport',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='apptechnicalfinancialreport',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='apptemporaryexemption',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='apptemporaryexemption',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='apptemporaryexemption',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='apptnazolshraka',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='apptnazolshraka',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='apptnazolshraka',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appvisibitystudy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appvisibitystudy',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appvisibitystudy',
            name='license_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproductionlicense', verbose_name='license_type'),
        ),
        migrations.AlterField(
            model_name='appvisibitystudy',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appvisibitystudydetail',
            name='study_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.appvisibitystudy'),
        ),
        migrations.AlterField(
            model_name='appwhomconcern',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appwhomconcern',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appwhomconcern',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='appworkplan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='appworkplan',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='appworkplan',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='lkplocality',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.lkpstate', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproduction',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproduction',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.lkpnationality', verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproduction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.lkpcompanyproductionstatus', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproduction',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionfactory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionfactory',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionfactory',
            name='factory_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.lkpcompanyproductionfactorytype', verbose_name='factory_type'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionfactory',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='contract_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.lkpcompanyproductionlicensestatus', verbose_name='contract_status'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.lkplocality', verbose_name='locality'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='mineral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.lkpmineral', verbose_name='mineral'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.lkpstate', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionuserrole',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionuserrole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
