# Generated by Django 5.0.2 on 2024-05-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0066_alter_appaddarea_company_alter_appaddarea_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanyproduction',
            name='manager_phone',
            field=models.CharField(max_length=50, verbose_name='manager_phone'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproduction',
            name='rep_phone',
            field=models.CharField(max_length=50, verbose_name='Representative phone'),
        ),
    ]
