# Generated by Django 5.0.2 on 2024-06-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0068_remove_tblcompanyproduction_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcompanyproductionlicense',
            name='mineral',
        ),
        migrations.AddField(
            model_name='tblcompanyproductionlicense',
            name='mineral',
            field=models.ManyToManyField(to='company_profile.lkpmineral', verbose_name='mineral'),
        ),
    ]
