# Generated by Django 5.0.2 on 2024-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0069_remove_tblcompanyproductionlicense_mineral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanyproduction',
            name='nationality',
            field=models.ManyToManyField(default=1, to='company_profile.lkpnationality', verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='annual_rent',
            field=models.FloatField(default=0, verbose_name='annual_rent'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Area in Kilometers'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='mineral',
            field=models.ManyToManyField(default=1, to='company_profile.lkpmineral', verbose_name='mineral'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='reserve',
            field=models.FloatField(blank=True, null=True, verbose_name='Reserve in Tones'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='royalty',
            field=models.FloatField(default=0, verbose_name='royalty'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='sheet_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sheet_no'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='zakat',
            field=models.FloatField(default=0, verbose_name='zakat'),
        ),
    ]
