# Generated by Django 5.0.2 on 2024-08-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0070_alter_tblcompanyproduction_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='gov_rep',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Goverment representative'),
        ),
    ]
