# Generated by Django 5.0.2 on 2024-08-22 14:24

import company_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0071_alter_tblcompanyproductionlicense_gov_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanyproduction',
            name='address',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproduction',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Official email'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproduction',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to=company_profile.models.company_contract_path, verbose_name='contract_file'),
        ),
    ]
