# Generated by Django 5.0.2 on 2024-08-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0072_alter_tblcompanyproduction_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanyproduction',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Official email'),
        ),
    ]
