# Generated by Django 5.0.2 on 2024-08-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0073_alter_tblcompanyproduction_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanyproduction',
            name='nationality',
            field=models.ManyToManyField(default=[1], to='company_profile.lkpnationality', verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='mineral',
            field=models.ManyToManyField(default=[1], to='company_profile.lkpmineral', verbose_name='mineral'),
        ),
    ]
