# Generated by Django 5.0.2 on 2024-09-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0076_alter_tblcompanyproduction_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanyproduction',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='code'),
        ),
    ]
