# Generated by Django 5.0.2 on 2024-09-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0077_tblcompanyproduction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanyproductionlicense',
            name='license_count',
            field=models.IntegerField(default=1, verbose_name='License count'),
        ),
    ]
