# Generated by Django 5.0.2 on 2024-10-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0079_alter_tblcompanyproductionlicense_sheet_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanyproductionlicense',
            name='area_initial',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Initial area in Kilometers'),
        ),
    ]
