# Generated by Django 5.1 on 2024-11-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0081_alter_tblcompanyproduction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanyproductionlicense',
            name='license_type',
            field=models.IntegerField(blank=True, choices=[(1, 'license_type_2tifagia'), (2, 'license_type_3agd'), (3, 'license_type_rokh9a')], null=True, verbose_name='license_type'),
        ),
    ]
