# Generated by Django 5.1 on 2024-12-08 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0082_tblcompanyproductionlicense_license_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appborrowmaterial',
            name='company_from_str',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='company_borrow_from_str'),
        ),
        migrations.AlterField(
            model_name='appborrowmaterial',
            name='company_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borrow_from', to='company_profile.tblcompanyproduction', verbose_name='company_borrow_from'),
        ),
    ]
