# Generated by Django 5.1 on 2024-12-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0083_appborrowmaterial_company_from_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appborrowmaterial',
            name='company_from_str',
            field=models.CharField(default='-', max_length=200, verbose_name='company_borrow_from_str'),
        ),
    ]
