# Generated by Django 5.0.2 on 2025-01-19 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0084_alter_appborrowmaterial_company_from_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHSEPerformanceReportManPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(choices=[(1, 'man_power_total'), (2, 'man_power_work_hours')], verbose_name='man_power')),
                ('no_gov', models.PositiveIntegerField(verbose_name='no_gov')),
                ('no_staff', models.PositiveIntegerField(verbose_name='no_staff')),
                ('no_contractor', models.PositiveIntegerField(verbose_name='no_contractor')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE Man power',
                'verbose_name_plural': 'HSE Man power',
            },
        ),
    ]
