# Generated by Django 5.0.2 on 2025-01-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0085_apphseperformancereportmanpower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apphseperformancereport',
            name='attachement_file',
        ),
    ]
