# Generated by Django 5.0.2 on 2025-01-19 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0086_remove_apphseperformancereport_attachement_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHSEPerformanceReportFireFighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(choices=[(1, 'fire_fighting_1'), (2, 'fire_fighting_2')], verbose_name='fire_fighting_type')),
                ('count', models.PositiveIntegerField(verbose_name='no_gov')),
                ('exam_dt', models.DateField(verbose_name='exam_dt')),
                ('situation', models.PositiveIntegerField(choices=[(1, 'situation_ok'), (2, 'situation_bad')], verbose_name='situation')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE fire fighting',
                'verbose_name_plural': 'HSE fire fighting',
            },
        ),
    ]
