# Generated by Django 5.0.2 on 2025-01-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0087_apphseperformancereportfirefighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='apphseperformancereportfirefighting',
            name='factor',
            field=models.PositiveIntegerField(choices=[(1, 'fire_fighting_1'), (2, 'fire_fighting_2')], default=1, verbose_name='fire_fighting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apphseperformancereportfirefighting',
            name='count',
            field=models.PositiveIntegerField(verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereportfirefighting',
            name='size',
            field=models.PositiveIntegerField(verbose_name='size'),
        ),
    ]
