# Generated by Django 5.0.2 on 2025-01-19 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0088_apphseperformancereportfirefighting_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHSEPerformanceReportWorkEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(choices=[(1, 'work_environment_factor1'), (2, 'work_environment_factor2'), (3, 'work_environment_factor3'), (4, 'work_environment_factor4'), (5, 'work_environment_factor5'), (6, 'work_environment_factor6'), (7, 'work_environment_factor7'), (8, 'work_environment_factor8')], verbose_name='work_environment')),
                ('offices', models.PositiveIntegerField(choices=[(1, 'ranking_excellent'), (2, 'ranking_very_good'), (3, 'ranking_good'), (4, 'ranking_bad')], default=4, verbose_name='offices')),
                ('camp', models.PositiveIntegerField(choices=[(1, 'ranking_excellent'), (2, 'ranking_very_good'), (3, 'ranking_good'), (4, 'ranking_bad')], default=4, verbose_name='camp')),
                ('kitchen_dining', models.PositiveIntegerField(choices=[(1, 'ranking_excellent'), (2, 'ranking_very_good'), (3, 'ranking_good'), (4, 'ranking_bad')], default=4, verbose_name='kitchen_dining')),
                ('factory', models.PositiveIntegerField(choices=[(1, 'ranking_excellent'), (2, 'ranking_very_good'), (3, 'ranking_good'), (4, 'ranking_bad')], default=4, verbose_name='factory')),
                ('stores', models.PositiveIntegerField(choices=[(1, 'ranking_excellent'), (2, 'ranking_very_good'), (3, 'ranking_good'), (4, 'ranking_bad')], default=4, verbose_name='Stores')),
                ('lab', models.PositiveIntegerField(choices=[(1, 'ranking_excellent'), (2, 'ranking_very_good'), (3, 'ranking_good'), (4, 'ranking_bad')], default=4, verbose_name='lab')),
                ('mines', models.PositiveIntegerField(choices=[(1, 'ranking_excellent'), (2, 'ranking_very_good'), (3, 'ranking_good'), (4, 'ranking_bad')], default=4, verbose_name='mines')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE work environment',
                'verbose_name_plural': 'HSE work environment',
            },
        ),
    ]
