# Generated by Django 5.0.2 on 2025-01-19 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0090_apphseperformancereportproactiveindicators'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHSEPerformanceReportActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(choices=[(1, 'ACTIVITIES_type1'), (2, 'ACTIVITIES_type2'), (3, 'ACTIVITIES_type3'), (4, 'ACTIVITIES_type4'), (5, 'ACTIVITIES_type5'), (6, 'ACTIVITIES_type6'), (7, 'ACTIVITIES_type7'), (8, 'ACTIVITIES_type8'), (9, 'ACTIVITIES_type9'), (10, 'ACTIVITIES_type10'), (11, 'ACTIVITIES_type11')], verbose_name='proactive_indicators')),
                ('no_staff', models.PositiveIntegerField(verbose_name='no_staff')),
                ('no_contractor', models.PositiveIntegerField(verbose_name='no_contractor')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE activities',
                'verbose_name_plural': 'HSE activities',
            },
        ),
    ]
