# Generated by Django 5.0.2 on 2025-01-20 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0091_apphseperformancereportactivities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphseperformancereportactivities',
            name='factor',
            field=models.PositiveIntegerField(choices=[(1, 'ACTIVITIES_type1'), (2, 'ACTIVITIES_type2'), (3, 'ACTIVITIES_type3'), (4, 'ACTIVITIES_type4'), (5, 'ACTIVITIES_type5'), (6, 'ACTIVITIES_type6'), (7, 'ACTIVITIES_type7'), (8, 'ACTIVITIES_type8'), (9, 'ACTIVITIES_type9'), (10, 'ACTIVITIES_type10'), (11, 'ACTIVITIES_type11')], verbose_name='hse_activities'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereportfirefighting',
            name='factor',
            field=models.PositiveIntegerField(choices=[(1, 'fire_fighting_1'), (2, 'fire_fighting_2')], verbose_name='hse_fire_fighting'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereportmanpower',
            name='factor',
            field=models.PositiveIntegerField(choices=[(1, 'man_power_total'), (2, 'man_power_work_hours')], verbose_name='hse_man_power'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereportproactiveindicators',
            name='factor',
            field=models.PositiveIntegerField(choices=[(1, 'proactive_indicators_type1'), (2, 'proactive_indicators_type2'), (3, 'proactive_indicators_type3'), (4, 'proactive_indicators_type4')], verbose_name='hse_proactive_indicators'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereportworkenvironment',
            name='factor',
            field=models.PositiveIntegerField(choices=[(1, 'work_environment_factor1'), (2, 'work_environment_factor2'), (3, 'work_environment_factor3'), (4, 'work_environment_factor4'), (5, 'work_environment_factor5'), (6, 'work_environment_factor6'), (7, 'work_environment_factor7'), (8, 'work_environment_factor8')], verbose_name='hse_work_environment'),
        ),
        migrations.CreateModel(
            name='AppHSEPerformanceReportChemicalUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(choices=[(1, 'CHEMICAL_USED1'), (2, 'CHEMICAL_USED2'), (3, 'CHEMICAL_USED3'), (4, 'CHEMICAL_USED4'), (5, 'CHEMICAL_USED5'), (6, 'CHEMICAL_USED6')], verbose_name='hse_chemical_used')),
                ('qty_used', models.PositiveIntegerField(verbose_name='qty_used')),
                ('qty_in_store', models.PositiveIntegerField(verbose_name='qty_in_store')),
                ('expire_dt', models.DateField(verbose_name='expire_dt')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE CHEMICAL USED',
                'verbose_name_plural': 'HSE CHEMICAL USED',
            },
        ),
        migrations.CreateModel(
            name='AppHSEPerformanceReportOilUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(choices=[(1, 'OIL_USED1'), (2, 'OIL_USED2'), (3, 'OIL_USED3'), (4, 'OIL_USED4')], verbose_name='hse_oil_used')),
                ('qty_used', models.FloatField(verbose_name='qty_used')),
                ('disposal_method', models.CharField(verbose_name='disposal_method')),
                ('storage_method', models.CharField(verbose_name='storage_method')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE OIL USED',
                'verbose_name_plural': 'HSE OIL USED',
            },
        ),
        migrations.CreateModel(
            name='AppHSEPerformanceReportWasteDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(choices=[(1, 'WASTE_DISPOSAL1'), (2, 'WASTE_DISPOSAL2'), (3, 'WASTE_DISPOSAL3'), (4, 'WASTE_DISPOSAL4'), (5, 'WASTE_DISPOSAL5'), (6, 'WASTE_DISPOSAL6'), (7, 'WASTE_DISPOSAL7'), (8, 'WASTE_DISPOSAL8'), (9, 'WASTE_DISPOSAL9'), (10, 'WASTE_DISPOSAL10'), (11, 'WASTE_DISPOSAL11'), (12, 'WASTE_DISPOSAL12'), (13, 'WASTE_DISPOSAL13'), (14, 'WASTE_DISPOSAL14')], verbose_name='hse_WASTE_DISPOSAL')),
                ('qty_used', models.FloatField(verbose_name='qty_used')),
                ('disposal_method', models.CharField(verbose_name='disposal_method')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE WASTE DISPOSAL',
                'verbose_name_plural': 'HSE WASTE DISPOSAL',
            },
        ),
        migrations.CreateModel(
            name='AppHSEPerformanceReportWaterUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(choices=[(1, 'WATER_USED1'), (2, 'WATER_USED2'), (3, 'WATER_USED3'), (4, 'WATER_USED4')], verbose_name='hse_water_used')),
                ('qty_used', models.FloatField(verbose_name='qty_used')),
                ('source_of_water', models.CharField(verbose_name='source_of_water')),
                ('storage_method', models.CharField(verbose_name='storage_method')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE WATER USED',
                'verbose_name_plural': 'HSE WATER USED',
            },
        ),
    ]
