# Generated by Django 5.0.2 on 2025-01-20 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0092_alter_apphseperformancereportactivities_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHSEPerformanceReportCatering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_served_type', models.CharField(max_length=100, verbose_name='meal_served')),
                ('food_sources', models.CharField(max_length=100, verbose_name='food_sources')),
                ('food_transportation', models.CharField(max_length=100, verbose_name='food_transportation')),
                ('food_storage', models.TextField(verbose_name='food_storage')),
                ('kitchen_cleaning', models.TextField(verbose_name='kitchen_cleaning')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE Catering',
                'verbose_name_plural': 'HSE Catering',
            },
        ),
        migrations.CreateModel(
            name='AppHSEPerformanceReportDiseasesForWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_dt', models.DateField(verbose_name='disease_dt')),
                ('disease_type', models.CharField(max_length=100, verbose_name='disease_type')),
                ('no_patients', models.PositiveIntegerField(verbose_name='no_patients')),
                ('patients_career', models.CharField(max_length=100, verbose_name='patients_career')),
                ('patients_worksite', models.CharField(max_length=100, verbose_name='patients_worksite')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE Diseases For Workers',
                'verbose_name_plural': 'HSE Diseases For Workers',
            },
        ),
        migrations.CreateModel(
            name='AppHSEPerformanceReportStatisticalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(choices=[(1, ' STATISTICAL_DATA1'), (2, ' STATISTICAL_DATA2'), (3, ' STATISTICAL_DATA3'), (4, ' STATISTICAL_DATA4')], verbose_name='hse_statistical_data')),
                ('no_staff', models.PositiveIntegerField(verbose_name='no_staff')),
                ('no_contractor', models.PositiveIntegerField(verbose_name='no_contractor')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE STATISTICAL DATA',
                'verbose_name_plural': 'HSE STATISTICAL DATA',
            },
        ),
        migrations.CreateModel(
            name='AppHSEPerformanceReportTherapeuticUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_manager', models.CharField(max_length=100, verbose_name='unit_manager')),
                ('unit_phone', models.CharField(max_length=100, verbose_name='unit_phone')),
                ('unit_qualification', models.PositiveIntegerField(choices=[(1, 'QUALIFICATION1'), (2, 'QUALIFICATION2')], verbose_name='unit_qualification')),
                ('aid_qty_used', models.PositiveIntegerField(verbose_name='aid_qty_used')),
                ('ambulance_used', models.PositiveIntegerField(choices=[(1, 'YES'), (2, 'NO')], verbose_name='ambulance_used')),
                ('periodic_medical_examination', models.PositiveIntegerField(choices=[(1, 'YES'), (2, 'NO')], verbose_name='periodic_medical_examination')),
                ('primary_medical_examination', models.PositiveIntegerField(choices=[(1, 'YES'), (2, 'NO')], verbose_name='primary_medical_examination')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE Therapeutic unit',
                'verbose_name_plural': 'HSE Therapeutic unit',
            },
        ),
    ]
