# Generated by Django 5.0.2 on 2025-01-20 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0093_apphseperformancereportcatering_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHSEPerformanceReportBillsOfQuantities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(choices=[(1, 'BILLS_OF_QUANTITIES1'), (2, 'BILLS_OF_QUANTITIES2'), (3, 'BILLS_OF_QUANTITIES3'), (4, 'BILLS_OF_QUANTITIES4'), (5, 'BILLS_OF_QUANTITIES5'), (6, 'BILLS_OF_QUANTITIES6'), (7, 'BILLS_OF_QUANTITIES7'), (8, 'BILLS_OF_QUANTITIES8'), (9, 'BILLS_OF_QUANTITIES9'), (10, 'BILLS_OF_QUANTITIES10')], verbose_name='hse_explosives_used')),
                ('qty_used', models.PositiveIntegerField(verbose_name='qty_used')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE BILLS OF QUANTITIES',
                'verbose_name_plural': 'HSE BILLS OF QUANTITIES',
            },
        ),
        migrations.CreateModel(
            name='AppHSEPerformanceReportExplosivesUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(choices=[(1, 'EXPLOSIVES_USED1'), (2, 'EXPLOSIVES_USED2'), (3, 'EXPLOSIVES_USED3'), (4, 'EXPLOSIVES_USED4'), (5, 'EXPLOSIVES_USED5'), (6, 'EXPLOSIVES_USED6'), (7, 'EXPLOSIVES_USED7'), (8, 'EXPLOSIVES_USED8'), (9, 'EXPLOSIVES_USED9')], verbose_name='hse_explosives_used')),
                ('qty_used', models.PositiveIntegerField(verbose_name='qty_used')),
                ('qty_remain', models.PositiveIntegerField(verbose_name='qty_remain')),
                ('expire_dt', models.DateField(verbose_name='expire_dt')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE EXPLOSIVES USED',
                'verbose_name_plural': 'HSE EXPLOSIVES USED',
            },
        ),
    ]
