# Generated by Django 5.0.2 on 2025-01-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0094_apphseperformancereportbillsofquantities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphseperformancereportbillsofquantities',
            name='factor',
            field=models.PositiveIntegerField(choices=[(1, 'BILLS_OF_QUANTITIES1'), (2, 'BILLS_OF_QUANTITIES2'), (3, 'BILLS_OF_QUANTITIES3'), (4, 'BILLS_OF_QUANTITIES4'), (5, 'BILLS_OF_QUANTITIES5'), (6, 'BILLS_OF_QUANTITIES6'), (7, 'BILLS_OF_QUANTITIES7'), (8, 'BILLS_OF_QUANTITIES8'), (9, 'BILLS_OF_QUANTITIES9')], verbose_name='hse_explosives_used'),
        ),
    ]
