# Generated by Django 5.0.2 on 2025-01-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0095_alter_apphseperformancereportbillsofquantities_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appborrowmaterial',
            name='borrow_date',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='borrow_date'),
        ),
        migrations.AlterField(
            model_name='appexplorationtime',
            name='expo_from',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='expo_from'),
        ),
        migrations.AlterField(
            model_name='appexplorationtime',
            name='expo_to',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='expo_to'),
        ),
        migrations.AlterField(
            model_name='appforeignerprocedure',
            name='procedure_from',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='procedure_from'),
        ),
        migrations.AlterField(
            model_name='appforeignerprocedure',
            name='procedure_to',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='procedure_to'),
        ),
        migrations.AlterField(
            model_name='appforignermovement',
            name='passport_expiry_date',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='passport_expiry_date'),
        ),
        migrations.AlterField(
            model_name='appforignermovement',
            name='period_from',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='period_from'),
        ),
        migrations.AlterField(
            model_name='appforignermovement',
            name='period_to',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='period_to'),
        ),
        migrations.AlterField(
            model_name='appgoldproductiondetail',
            name='melt_dt',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='melt_dt'),
        ),
        migrations.AlterField(
            model_name='apphseaccidentreport',
            name='accident_dt',
            field=models.DateTimeField(help_text='Ex: 2025-01-01', verbose_name='accident_dt'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereportchemicalused',
            name='expire_dt',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='expire_dt'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereportdiseasesforworkers',
            name='disease_dt',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='disease_dt'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereportexplosivesused',
            name='expire_dt',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='expire_dt'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereportfirefighting',
            name='exam_dt',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='exam_dt'),
        ),
        migrations.AlterField(
            model_name='appmda',
            name='mda_from',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='mda_from'),
        ),
        migrations.AlterField(
            model_name='appmda',
            name='mda_to',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='mda_to'),
        ),
        migrations.AlterField(
            model_name='apptaaweed',
            name='taaweed_from',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='taaweed_from'),
        ),
        migrations.AlterField(
            model_name='apptaaweed',
            name='taaweed_to',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='taaweed_to'),
        ),
        migrations.AlterField(
            model_name='apptajmeed',
            name='tajmeed_from',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='tajmeed_from'),
        ),
        migrations.AlterField(
            model_name='apptajmeed',
            name='tajmeed_to',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='tajmeed_to'),
        ),
        migrations.AlterField(
            model_name='apptakhali',
            name='technical_presentation_date',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='technical_presentation_date'),
        ),
        migrations.AlterField(
            model_name='apptamdeed',
            name='tamdeed_from',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='tamdeed_from'),
        ),
        migrations.AlterField(
            model_name='apptamdeed',
            name='tamdeed_to',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='tamdeed_to'),
        ),
        migrations.AlterField(
            model_name='apptechnicalfinancialreport',
            name='report_from',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='report_from'),
        ),
        migrations.AlterField(
            model_name='appworkplan',
            name='plan_from',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='plan_from'),
        ),
        migrations.AlterField(
            model_name='appworkplan',
            name='plan_to',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='plan_to'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='date',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='Sign date'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='end_date',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='start_date',
            field=models.DateField(help_text='Ex: 2025-01-01', verbose_name='start_date'),
        ),
    ]
