# Generated by Django 5.0.2 on 2025-01-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0098_apphseperformancereport_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apphseperformancereportproactiveindicators',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereportfirefighting',
            name='factor',
            field=models.PositiveIntegerField(choices=[(1, 'fire_fighting_1'), (2, 'fire_fighting_2'), (3, 'fire_fighting_3'), (4, 'fire_fighting_4'), (5, 'fire_fighting_5')], verbose_name='hse_fire_fighting'),
        ),
    ]
