# Generated by Django 5.0.2 on 2025-01-21 12:09

import company_profile.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0099_apphseperformancereportproactiveindicators_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apphseperformancereportproactiveindicators',
            name='no_gov',
        ),
        migrations.AddField(
            model_name='apphseperformancereportproactiveindicators',
            name='action',
            field=models.CharField(default='', max_length=100, verbose_name='action'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apphseperformancereportoilused',
            name='factor',
            field=models.PositiveIntegerField(choices=[(1, 'OIL_USED1'), (2, 'OIL_USED2'), (3, 'OIL_USED3')], verbose_name='hse_oil_used'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereporttherapeuticunit',
            name='ambulance_used',
            field=models.PositiveIntegerField(choices=[(1, 'AMBULANCE_USED1'), (2, 'AMBULANCE_USED2'), (3, 'AMBULANCE_USED3')], verbose_name='ambulance_used'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereportwastedisposal',
            name='factor',
            field=models.PositiveIntegerField(choices=[(1, 'WASTE_DISPOSAL1'), (2, 'WASTE_DISPOSAL2'), (3, 'WASTE_DISPOSAL3'), (4, 'WASTE_DISPOSAL4'), (5, 'WASTE_DISPOSAL5'), (6, 'WASTE_DISPOSAL6'), (7, 'WASTE_DISPOSAL7'), (8, 'WASTE_DISPOSAL8'), (9, 'WASTE_DISPOSAL9'), (10, 'WASTE_DISPOSAL10'), (11, 'WASTE_DISPOSAL11'), (12, 'WASTE_DISPOSAL12'), (13, 'WASTE_DISPOSAL13'), (14, 'WASTE_DISPOSAL14'), (15, 'WASTE_DISPOSAL15')], verbose_name='hse_WASTE_DISPOSAL'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereportworkenvironment',
            name='mines',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'ranking_excellent'), (2, 'ranking_very_good'), (3, 'ranking_good'), (4, 'ranking_bad')], default=4, null=True, verbose_name='mines'),
        ),
        migrations.CreateModel(
            name='AppHSEPerformanceReportPhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('photo', models.ImageField(upload_to=company_profile.models.company_applications_path, verbose_name='photo')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE Catering',
                'verbose_name_plural': 'HSE Catering',
            },
        ),
    ]
