# Generated by Django 5.0.2 on 2025-01-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0100_remove_apphseperformancereportproactiveindicators_no_gov_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apphseperformancereportphotoalbum',
            options={'verbose_name': 'HSE PHOTO ALBUM', 'verbose_name_plural': 'HSE PHOTO ALBUM'},
        ),
    ]
