# Generated by Django 5.0.2 on 2025-01-21 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0101_alter_apphseperformancereportphotoalbum_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHSEPerformanceReportCyanideTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_method', models.PositiveIntegerField(choices=[(1, 'STORAGE_METHOD1'), (2, 'STORAGE_METHOD2')], verbose_name='storage_method')),
                ('handling_method', models.PositiveIntegerField(choices=[(1, 'HANDLING_METHOD1'), (2, 'HANDLING_METHOD2'), (3, 'HANDLING_METHOD3')], verbose_name='handling_method')),
                ('hcn_detector', models.PositiveIntegerField(choices=[(1, 'YES'), (2, 'NO')], verbose_name='hcn_detector')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE CYANIDE TABLE',
                'verbose_name_plural': 'HSE CYANIDE TABLE',
            },
        ),
    ]
