# Generated by Django 5.0.2 on 2025-01-21 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0102_apphseperformancereportcyanidetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphseperformancereportbillsofquantities',
            name='factor',
            field=models.PositiveIntegerField(choices=[(1, 'BILLS_OF_QUANTITIES1'), (2, 'BILLS_OF_QUANTITIES2'), (3, 'BILLS_OF_QUANTITIES3'), (4, 'BILLS_OF_QUANTITIES4'), (5, 'BILLS_OF_QUANTITIES5'), (6, 'BILLS_OF_QUANTITIES6'), (7, 'BILLS_OF_QUANTITIES7'), (8, 'BILLS_OF_QUANTITIES8'), (9, 'BILLS_OF_QUANTITIES9')], verbose_name='hse_bills_of_quantities'),
        ),
        migrations.CreateModel(
            name='AppHSEPerformanceReportCadastralOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(choices=[(1, 'CADASTRAL_SPECIFICATION1'), (2, 'CADASTRAL_SPECIFICATION2'), (3, 'CADASTRAL_SPECIFICATION3'), (4, 'CADASTRAL_SPECIFICATION4'), (5, 'CADASTRAL_SPECIFICATION5'), (6, 'CADASTRAL_SPECIFICATION6'), (7, 'CADASTRAL_SPECIFICATION7'), (8, 'CADASTRAL_SPECIFICATION8'), (9, 'CADASTRAL_SPECIFICATION9')], verbose_name='Specification')),
                ('value', models.CharField(max_length=100, verbose_name='value')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE cadastral operations',
                'verbose_name_plural': 'HSE cadastral operations',
            },
        ),
        migrations.CreateModel(
            name='AppHSEPerformanceReportCyanideCNStorageSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(choices=[(1, 'SPECIFICATION1'), (2, 'SPECIFICATION2'), (3, 'SPECIFICATION3'), (4, 'SPECIFICATION4')], verbose_name='Specification')),
                ('choice', models.PositiveIntegerField(choices=[(1, 'YES'), (2, 'NO')], verbose_name='is_exists')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE CYANIDE CN Storage Specification',
                'verbose_name_plural': 'HSE CYANIDE CN Storage Specification',
            },
        ),
        migrations.CreateModel(
            name='AppHSEPerformanceReportExplosivesUsedSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(choices=[(1, 'EXP_SPECIFICATION1'), (2, 'EXP_SPECIFICATION2'), (3, 'EXP_SPECIFICATION3'), (4, 'EXP_SPECIFICATION4'), (5, 'EXP_SPECIFICATION5')], verbose_name='Specification')),
                ('choice', models.PositiveIntegerField(choices=[(1, 'YES'), (2, 'NO')], verbose_name='is_exists')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE Explosive Storage Specification',
                'verbose_name_plural': 'HSE Explosive Storage Specification',
            },
        ),
    ]
