# Generated by Django 5.0.2 on 2025-01-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0103_alter_apphseperformancereportbillsofquantities_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHSEPerformanceReportCadastralOperations2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(choices=[(1, 'CADASTRAL2_SPECIFICATION1'), (2, 'CADASTRAL2_SPECIFICATION2'), (3, 'CADASTRAL2_SPECIFICATION3'), (4, 'CADASTRAL2_SPECIFICATION4'), (5, 'CADASTRAL2_SPECIFICATION5'), (6, 'CADASTRAL2_SPECIFICATION6'), (7, 'CADASTRAL2_SPECIFICATION7')], verbose_name='Specification')),
                ('observation', models.CharField(max_length=100, verbose_name='observation')),
                ('result', models.CharField(max_length=100, verbose_name='result')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE cadastral operations2',
                'verbose_name_plural': 'HSE cadastral operations2',
            },
        ),
    ]
