# Generated by Django 5.0.2 on 2025-01-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0104_apphseperformancereportcadastraloperations2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppHSEPerformanceReportCadastralOperations2',
            new_name='AppHSEPerformanceReportCadastralOperationsTwo',
        ),
    ]
