# Generated by Django 5.0.2 on 2025-01-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0105_rename_apphseperformancereportcadastraloperations2_apphseperformancereportcadastraloperationstwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphseperformancereportworkenvironment',
            name='mines',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'ranking_excellent'), (2, 'ranking_very_good'), (3, 'ranking_good'), (4, 'ranking_bad')], null=True, verbose_name='mines'),
        ),
    ]
