# Generated by Django 5.0.2 on 2025-01-21 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0106_alter_apphseperformancereportworkenvironment_mines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphseperformancereportchemicalused',
            name='factor',
            field=models.PositiveIntegerField(choices=[(1, 'CHEMICAL_USED1'), (2, 'CHEMICAL_USED2'), (3, 'CHEMICAL_USED3'), (4, 'CHEMICAL_USED4'), (5, 'CHEMICAL_USED5')], verbose_name='hse_chemical_used'),
        ),
        migrations.CreateModel(
            name='AppHSEPerformanceReportOtherChemicalUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='hse_chemical_used')),
                ('qty_used', models.PositiveIntegerField(verbose_name='qty_used')),
                ('qty_in_store', models.PositiveIntegerField(verbose_name='qty_in_store')),
                ('expire_dt', models.DateField(help_text='Ex: 2025-01-31', verbose_name='expire_dt')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.apphseperformancereport')),
            ],
            options={
                'verbose_name': 'HSE OTHER CHEMICAL USED',
                'verbose_name_plural': 'HSE OTHER CHEMICAL USED',
            },
        ),
    ]
