# Generated by Django 5.0.2 on 2025-01-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0107_alter_apphseperformancereportchemicalused_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphseperformancereportotherchemicalused',
            name='expire_dt',
            field=models.DateField(blank=True, help_text='Ex: 2025-01-31', null=True, verbose_name='expire_dt'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereportotherchemicalused',
            name='qty_in_store',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='qty_in_store'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereportotherchemicalused',
            name='qty_used',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='qty_used'),
        ),
    ]
