# Generated by Django 5.0.2 on 2025-01-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0110_apprequirementslist_other_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphseperformancereportbillsofquantities',
            name='factor',
            field=models.PositiveIntegerField(choices=[(1, 'BILLS_OF_QUANTITIES1'), (2, 'BILLS_OF_QUANTITIES2'), (3, 'BILLS_OF_QUANTITIES3'), (4, 'BILLS_OF_QUANTITIES4'), (5, 'BILLS_OF_QUANTITIES5'), (6, 'BILLS_OF_QUANTITIES6'), (7, 'BILLS_OF_QUANTITIES7'), (8, 'BILLS_OF_QUANTITIES8'), (9, 'BILLS_OF_QUANTITIES9'), (10, 'BILLS_OF_QUANTITIES10')], verbose_name='hse_bills_of_quantities'),
        ),
    ]
