# Generated by Django 5.0.2 on 2025-01-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0112_apphseperformancereport_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphseperformancereport',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
