# Generated by Django 5.0.2 on 2025-02-02 06:26

import company_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0113_alter_apphseperformancereport_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='apphseperformancereport',
            name='album',
            field=models.FileField(blank=True, null=True, upload_to=company_profile.models.company_applications_path, verbose_name='album'),
        ),
        migrations.DeleteModel(
            name='AppHSEPerformanceReportPhotoAlbum',
        ),
    ]
