# Generated by Django 5.0.2 on 2025-02-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0114_apphseperformancereport_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphseperformancereportchemicalused',
            name='expire_dt',
            field=models.DateField(blank=True, default='', help_text='Ex: 2025-01-31', null=True, verbose_name='expire_dt'),
        ),
    ]
