# Generated by Django 5.0.2 on 2025-03-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0115_alter_apphseperformancereportchemicalused_expire_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='appfuelpermissiondetail',
            name='fuel_actual_qty',
            field=models.FloatField(blank=True, null=True, verbose_name='fuel_actual_qty'),
        ),
    ]
