# Generated by Django 5.1.7 on 2025-03-24 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0116_appfuelpermissiondetail_fuel_actual_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='LkpSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.AddField(
            model_name='lkpstate',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpsector', verbose_name='sector'),
        ),
    ]
