# Generated by Django 5.1.7 on 2025-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0117_lkpsector_lkpstate_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptechnicalfinancialreport',
            name='report_comments',
            field=models.TextField(max_length=256, verbose_name='Covering letter'),
        ),
    ]
