# Generated by Django 5.1.7 on 2025-04-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0118_alter_apptechnicalfinancialreport_report_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpstate',
            name='x',
            field=models.IntegerField(default=0, verbose_name='x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkpstate',
            name='y',
            field=models.IntegerField(default=0, verbose_name='y'),
            preserve_default=False,
        ),
    ]
