# Generated by Django 5.1.7 on 2025-04-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0119_lkpstate_x_lkpstate_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lkpstate',
            name='x',
            field=models.FloatField(verbose_name='x'),
        ),
        migrations.AlterField(
            model_name='lkpstate',
            name='y',
            field=models.FloatField(verbose_name='y'),
        ),
    ]
