# Generated by Django 5.1.7 on 2025-05-06 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0120_alter_lkpstate_x_alter_lkpstate_y'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcompanyproductionfactory',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='tblcompanyproductionfactory',
            name='factory_type',
        ),
        migrations.AddField(
            model_name='tblcompanyproductionfactory',
            name='cil_capacity',
            field=models.FloatField(default=0, verbose_name='CIL Capacity (Tones per day)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcompanyproductionfactory',
            name='cil_exists',
            field=models.BooleanField(default=0, verbose_name='is cil exists'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcompanyproductionfactory',
            name='heap_capacity',
            field=models.FloatField(default=0, verbose_name='Heap Capacity (Tones per day)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcompanyproductionfactory',
            name='heap_exists',
            field=models.BooleanField(default=0, verbose_name='is heap exists'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblcompanyproductionfactory',
            name='vat_exists',
            field=models.BooleanField(default=0, verbose_name='is vat exists'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TblCompanyProductionFactoryVAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('no_sink', models.IntegerField(verbose_name='no_sink')),
                ('sink_capacity', models.FloatField(verbose_name='Sink Capacity (Tones per day)')),
                ('avg_capacity_dimension', models.CharField(max_length=100, verbose_name='name')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproductionfactory', verbose_name='company')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Production Company Factory VAT',
                'verbose_name_plural': 'Production Company Factories VAT',
            },
        ),
    ]
