# Generated by Django 5.1.7 on 2025-05-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0121_remove_tblcompanyproductionfactory_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcompanyproductionfactory',
            name='vat_exists',
        ),
    ]
