# Generated by Django 5.1.7 on 2025-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0122_remove_tblcompanyproductionfactory_vat_exists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanyproductionfactory',
            name='cil_capacity',
            field=models.FloatField(default=0, verbose_name='CIL Capacity (Tones per day)'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionfactory',
            name='heap_capacity',
            field=models.FloatField(default=0, verbose_name='Heap Capacity (Tones per day)'),
        ),
    ]
