# Generated by Django 5.1.7 on 2025-05-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0123_alter_tblcompanyproductionfactory_cil_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcompanyproductionfactoryvat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tblcompanyproductionfactoryvat',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tblcompanyproductionfactoryvat',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tblcompanyproductionfactoryvat',
            name='updated_by',
        ),
    ]
