# Generated by Django 5.1.7 on 2025-05-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0124_remove_tblcompanyproductionfactoryvat_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanyproductionfactoryvat',
            name='avg_capacity_dimension',
            field=models.CharField(max_length=100, verbose_name='متوسط ابعاد الحوض'),
        ),
    ]
