# Generated by Django 5.1.7 on 2025-05-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0125_alter_tblcompanyproductionfactoryvat_avg_capacity_dimension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcompanyproductionfactoryvat',
            options={'verbose_name': 'حوض', 'verbose_name_plural': 'احواض'},
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionfactory',
            name='cil_capacity',
            field=models.FloatField(default=0, verbose_name='السعة التشغيلية بالطن/يوم'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionfactory',
            name='cil_exists',
            field=models.BooleanField(verbose_name='CIL?'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionfactory',
            name='heap_capacity',
            field=models.FloatField(default=0, verbose_name='السعة التشغيلية بالطن/يوم'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionfactory',
            name='heap_exists',
            field=models.BooleanField(verbose_name='Heap?'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionfactoryvat',
            name='no_sink',
            field=models.IntegerField(verbose_name='عدد الأحواض'),
        ),
        migrations.AlterField(
            model_name='tblcompanyproductionfactoryvat',
            name='sink_capacity',
            field=models.FloatField(verbose_name='سعة الحوض'),
        ),
    ]
