# Generated by Django 5.1.7 on 2025-05-09 14:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0126_alter_tblcompanyproductionfactoryvat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpstate',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
