# Generated by Django 5.1.7 on 2025-05-20 08:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0127_lkpstate_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanyproductionlicense',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
