# Generated by Django 5.2.1 on 2025-08-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0130_appaddarea_recommendation_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appaddarea',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appaddarea',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appaifaajomrki',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appaifaajomrki',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appborrowmaterial',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appborrowmaterial',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appchangecompanyname',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appchangecompanyname',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appchangeworkprocedure',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appchangeworkprocedure',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appcyanidecertificate',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appcyanidecertificate',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appexplorationtime',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appexplorationtime',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appexplosivepermission',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appexplosivepermission',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appexportgold',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appexportgold',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appexportgoldraw',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appexportgoldraw',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appforeignerprocedure',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appforeignerprocedure',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appforignermovement',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appforignermovement',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appfuelpermission',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appfuelpermission',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appgoldproduction',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appgoldproduction',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='apphseaccidentreport',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='apphseaccidentreport',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereport',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='apphseperformancereport',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appimportpermission',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appimportpermission',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='applocalpurchase',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='applocalpurchase',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appmda',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appmda',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appreexportequipments',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appreexportequipments',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appremovearea',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appremovearea',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='apprenewalcontract',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='apprenewalcontract',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='apprequirementslist',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='apprequirementslist',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='apprestartactivity',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='apprestartactivity',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appsendsamplesforanalysis',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appsendsamplesforanalysis',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='apptaaweed',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='apptaaweed',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='apptajeeltnazol',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='apptajeeltnazol',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='apptajmeed',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='apptajmeed',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='apptakhali',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='apptakhali',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='apptamdeed',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='apptamdeed',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='apptechnicalfinancialreport',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='apptechnicalfinancialreport',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='apptemporaryexemption',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='apptemporaryexemption',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='apptnazolshraka',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='apptnazolshraka',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appvisibitystudy',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appvisibitystudy',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appwhomconcern',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appwhomconcern',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
        migrations.AlterField(
            model_name='appworkplan',
            name='reject_comments',
            field=models.TextField(blank=True, max_length=256, verbose_name='سبب الرفض/المراجعة'),
        ),
        migrations.AlterField(
            model_name='appworkplan',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted state'), ('accepted', 'Accepted state'), ('review_accept', 'Review acceptance state'), ('approved', 'Approved state'), ('rejected', 'Rejected state')], default='submitted', max_length=20, verbose_name='application_state'),
        ),
    ]
