# Generated by Django 5.2.7 on 2025-10-21 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0131_alter_appaddarea_reject_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appfuelpermission',
            name='license_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproductionlicense', verbose_name='license_type'),
        ),
    ]
