# Generated by Django 5.2.7 on 2025-12-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0132_appfuelpermission_license_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanyproductionlicense',
            name='fuel_route',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='خط سير الوقود'),
        ),
    ]
