# Generated by Django 5.2.7 on 2025-12-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0133_tblcompanyproductionlicense_fuel_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanyproductionlicense',
            name='fuel_route',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='خط سير الوقود'),
        ),
    ]
