# Generated by Django 5.2.7 on 2026-02-18 10:41

import company_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0134_alter_tblcompanyproductionlicense_fuel_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphseaccidentreport',
            name='attachement_file',
            field=models.FileField(blank=True, null=True, upload_to=company_profile.models.company_applications_path, verbose_name='attachement_file'),
        ),
    ]
