# Generated by Django 5.2.7 on 2026-02-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0135_alter_apphseaccidentreport_attachement_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='apphseaccidentreport',
            name='accident_category',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Occupational Health'), (2, 'Safety'), (3, 'Environment')], null=True, verbose_name='فئة الحادث Incident Category'),
        ),
    ]
