# Generated by Django 5.2.7 on 2026-02-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0136_apphseaccidentreport_accident_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apphseaccidentreport',
            options={'ordering': ['-id'], 'verbose_name': 'تقرير التبليغ عن حادث', 'verbose_name_plural': 'تقرير التبليغ عن حوادث'},
        ),
    ]
