# Generated by Django 5.2.7 on 2026-03-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0137_alter_apphseaccidentreport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apphseaccidentreport',
            options={'ordering': ['-id'], 'verbose_name': 'طلب التبليغ عن حادث', 'verbose_name_plural': 'طلب التبليغ عن حوادث'},
        ),
    ]
