# Generated by Django 5.2.7 on 2026-04-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0138_alter_apphseaccidentreport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpstate',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='كود'),
        ),
    ]
