# Generated by Django 5.2.7 on 2026-08-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0139_lkpstate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appforignermovement',
            name='security_comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='تعليق أفراد الأمن'),
        ),
    ]
