# Generated by Django 5.2.7 on 2026-09-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0140_security_comment_foreigner_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='appforeignerprocedure',
            name='security_comment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='security_comment'),
        ),
    ]
