# Generated by Django 5.0.2 on 2025-03-23 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0116_appfuelpermissiondetail_fuel_actual_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppWorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plan', to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application: Work Plan',
                'verbose_name_plural': 'Application: Work Plan',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('brief', models.TextField(verbose_name='Brief about what has been done')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('work_plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='company_profile_exploration.appworkplan', verbose_name='work_plan')),
            ],
            options={
                'verbose_name': 'Brief',
                'verbose_name_plural': 'Briefs',
            },
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('longitude', models.FloatField(verbose_name='Longitude/Easting')),
                ('latitude', models.FloatField(verbose_name='Latitude/Northing')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_exploration.appworkplan', verbose_name='work_plan')),
            ],
            options={
                'verbose_name': 'Coordinate',
                'verbose_name_plural': 'Coordinates',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('equipment_machine', models.CharField(max_length=100, verbose_name='Equipment/Machine')),
                ('item', models.CharField(max_length=100, verbose_name='Item')),
                ('unit_cost', models.FloatField(verbose_name='Unit cost')),
                ('total_cost', models.FloatField(verbose_name='Total cost')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_exploration.appworkplan', verbose_name='work_plan')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='LkpPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
            },
        ),
        migrations.CreateModel(
            name='LogisticsAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('activity_item', models.CharField(max_length=100, verbose_name='Activity/Item')),
                ('count', models.IntegerField(verbose_name='count')),
                ('unit_cost', models.FloatField(verbose_name='Unit cost')),
                ('total_cost', models.FloatField(verbose_name='Total Cost')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_exploration.appworkplan', verbose_name='work_plan')),
            ],
            options={
                'verbose_name': 'Logistics Administration',
                'verbose_name_plural': 'Logistics Administrations',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('activity_item', models.CharField(max_length=100, verbose_name='Activity/Item')),
                ('total', models.FloatField(verbose_name='Total')),
                ('unit_cost', models.FloatField(verbose_name='Unit cost')),
                ('total_cost', models.FloatField(verbose_name='Total cost')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_exploration.appworkplan', verbose_name='work_plan')),
            ],
            options={
                'verbose_name': 'Other',
                'verbose_name_plural': 'Others',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('from_dt', models.DateField(verbose_name='from_dt')),
                ('to_dt', models.DateField(verbose_name='to_dt')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_exploration.lkpphase', verbose_name='phase')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_exploration.appworkplan', verbose_name='work_plan')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
            },
        ),
        migrations.CreateModel(
            name='SamplePreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('activity', models.CharField(max_length=100, verbose_name='Activity')),
                ('total', models.FloatField(verbose_name='Total')),
                ('unit_cost', models.FloatField(verbose_name='Unit cost')),
                ('total_cost', models.FloatField(verbose_name='Total cost')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_exploration.appworkplan', verbose_name='work_plan')),
            ],
            options={
                'verbose_name': 'Sample Preparation',
                'verbose_name_plural': 'Sample Preparations',
            },
        ),
        migrations.CreateModel(
            name='StaffInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('count', models.IntegerField(verbose_name='count')),
                ('salaries_month', models.FloatField(verbose_name='Salaries_month')),
                ('salaries_year', models.FloatField(verbose_name='Salaries_year')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_exploration.appworkplan', verbose_name='work_plan')),
            ],
            options={
                'verbose_name': 'Staff Information',
                'verbose_name_plural': 'Staff Informations',
            },
        ),
        migrations.CreateModel(
            name='SubsurfaceExplorationActivitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('activity', models.CharField(max_length=100, verbose_name='Activity')),
                ('total_depth_length', models.FloatField(verbose_name='Total (depth, Length)/m')),
                ('cost_per_meter', models.FloatField(verbose_name='Cost/m')),
                ('total_cost', models.FloatField(verbose_name='Total cost')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_exploration.appworkplan', verbose_name='work_plan')),
            ],
            options={
                'verbose_name': 'Subsurface Exploration Activitie',
                'verbose_name_plural': 'Subsurface Exploration Activities',
            },
        ),
        migrations.CreateModel(
            name='SurfaceExplorationActivitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('activity', models.CharField(max_length=100, verbose_name='Activity')),
                ('unit_cost', models.FloatField(verbose_name='Unit cost')),
                ('total_cost', models.FloatField(verbose_name='Total cost')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_exploration.appworkplan', verbose_name='work_plan')),
            ],
            options={
                'verbose_name': 'Surface Exploration Activitie',
                'verbose_name_plural': 'Surface Exploration Activities',
            },
        ),
        migrations.CreateModel(
            name='TargetCommodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('mineral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpmineral', verbose_name='mineral')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_exploration.appworkplan', verbose_name='work_plan')),
            ],
            options={
                'verbose_name': 'Target Commodity',
                'verbose_name_plural': 'Target Commodities',
            },
        ),
    ]
