# Generated by Django 5.0.2 on 2025-03-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_exploration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appworkplan',
            name='state',
            field=models.IntegerField(choices=[(1, 'draft'), (4, 'STATE_GM_DECISION'), (5, 'STATE_REVIEW_CONTRACT'), (6, 'STATE_REVIEW_TECHNICAL'), (7, 'STATE_REVIEW_COMPANY'), (8, 'STATE_RELEASE_CERTIFICATE')], default=1, verbose_name='record_state'),
        ),
    ]
