# Generated by Django 5.0.2 on 2025-03-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0116_appfuelpermissiondetail_fuel_actual_qty'),
        ('company_profile_exploration', '0002_appworkplan_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='targetcommodity',
            unique_together={('work_plan', 'mineral')},
        ),
    ]
