# Generated by Django 5.0.2 on 2025-03-23 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_exploration', '0004_tblcompanyexploration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appworkplan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plan', to='company_profile_exploration.tblcompanyexploration', verbose_name='company'),
        ),
    ]
