# Generated by Django 5.1.7 on 2025-03-24 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_exploration', '0006_alter_appworkplan_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('to', models.IntegerField(choices=[(1, 'Technical'), (2, 'Contract'), (3, 'Company')], verbose_name='To')),
                ('topic', models.CharField(max_length=255, verbose_name='Topic')),
                ('actions', models.TextField(verbose_name='Actions')),
                ('is_done', models.BooleanField(default=False, verbose_name='Is Done')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_exploration.appworkplan', verbose_name='work_plan')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
            },
        ),
    ]
