# Generated by Django 5.1.7 on 2025-03-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_exploration', '0007_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appworkplan',
            name='state',
            field=models.IntegerField(choices=[(1, 'draft'), (4, 'توجيه م.ا.ع'), (5, 'دراسة اولية'), (6, 'دراسة فنية'), (7, 'مراجعة الطلب بواسطة الشركة'), (8, 'تحرير شهادة القبول'), (9, 'تحرير شهادة الرفض')], default=1, verbose_name='record_state'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='to',
            field=models.IntegerField(choices=[(1, 'الادارة الفنية'), (2, 'البرامج والعقود'), (3, 'الشركة')], verbose_name='To'),
        ),
    ]
