# Generated by Django 5.1.7 on 2025-03-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_exploration', '0008_alter_appworkplan_state_alter_todo_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='appworkplan',
            name='currency',
            field=models.CharField(choices=[('sdg', 'sdg'), ('euro', 'euro'), ('dollar', 'dollar')], default='sdg', max_length=10, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='to',
            field=models.IntegerField(choices=[(1, 'الادارة الفنية المختصة'), (2, 'البرامج والعقود'), (3, 'الشركة')], verbose_name='To'),
        ),
    ]
