# Generated by Django 5.1.7 on 2025-03-26 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_exploration', '0009_appworkplan_currency_alter_todo_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('recommendation', models.TextField(verbose_name='Recommendation')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_exploration.appworkplan', verbose_name='work_plan')),
            ],
            options={
                'verbose_name': 'Contract Recommendation',
                'verbose_name_plural': 'Contract Recommendations',
            },
        ),
        migrations.CreateModel(
            name='TechnicalRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('recommendation', models.TextField(verbose_name='Recommendation')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_exploration.appworkplan', verbose_name='work_plan')),
            ],
            options={
                'verbose_name': 'Technical Recommendation',
                'verbose_name_plural': 'Technical Recommendations',
            },
        ),
    ]
