# Generated by Django 5.1.7 on 2025-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_exploration', '0010_contractrecommendation_technicalrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appworkplan',
            name='state',
            field=models.IntegerField(choices=[(1, 'draft'), (4, 'توجيه م.ا.ع'), (5, 'توصية البرامج والعقود'), (6, 'توصية الادارة الفنية المختصة'), (7, 'مراجعة الطلب بواسطة الشركة'), (8, 'تحرير شهادة القبول'), (9, 'تحرير شهادة الرفض')], default=1, verbose_name='record_state'),
        ),
    ]
