# Generated by Django 5.1.7 on 2025-03-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_exploration', '0012_alter_appworkplan_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appworkplan',
            name='state',
            field=models.IntegerField(choices=[(1, 'draft'), (4, 'مدير الإدارة العامة'), (5, 'توصية البرامج والعقود'), (6, 'توصية الادارة الفنية المختصة'), (7, 'مراجعة الطلب بواسطة الشركة'), (8, 'تحرير شهادة القبول'), (9, 'تم تحرير شهادة القبول'), (10, 'تحرير شهادة الرفض'), (11, 'تم تحرير شهادة الرفض')], default=1, verbose_name='record_state'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='to',
            field=models.IntegerField(choices=[(1, 'الشركة'), (2, 'الادارة الفنية المختصة'), (3, 'البرامج والعقود'), (4, 'المكتب التنفيذي')], verbose_name='To'),
        ),
    ]
