# Generated by Django 5.1.7 on 2025-04-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_exploration', '0013_alter_appworkplan_state_alter_todo_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='logisticsadministration',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='other',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='samplepreparation',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='subsurfaceexplorationactivitie',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='surfaceexplorationactivitie',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='equipment',
            name='count',
            field=models.IntegerField(default=0, verbose_name='count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other',
            name='count',
            field=models.IntegerField(default=0, verbose_name='count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplepreparation',
            name='count',
            field=models.IntegerField(default=0, verbose_name='count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsurfaceexplorationactivitie',
            name='count',
            field=models.FloatField(default=0, verbose_name='count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surfaceexplorationactivitie',
            name='count',
            field=models.IntegerField(default=0, verbose_name='count'),
            preserve_default=False,
        ),
    ]
