# Generated by Django 5.1.7 on 2025-04-14 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0117_lkpsector_lkpstate_sector'),
        ('company_profile_exploration', '0014_remove_equipment_total_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblLicenseExploration',
            fields=[
            ],
            options={
                'verbose_name': 'Production Company License',
                'verbose_name_plural': 'Production Company Licenses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('company_profile.tblcompanyproductionlicense',),
        ),
        migrations.AlterField(
            model_name='appworkplan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plan_company', to='company_profile_exploration.tblcompanyexploration', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='appworkplan',
            name='license',
            field=models.ForeignKey(default=160, on_delete=django.db.models.deletion.PROTECT, related_name='work_plan_license', to='company_profile_exploration.tbllicenseexploration', verbose_name='license'),
            preserve_default=False,
        ),
    ]
