# Generated by Django 5.0.2 on 2024-05-21 14:09

import django.db.models.deletion
import doc_workflow.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0067_alter_tblcompanyproduction_manager_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('company_type', models.CharField(choices=[('entaj', 'entaj'), ('mokhalfat', 'mokhalfat'), ('emtiaz', 'emtiaz'), ('sageer', 'sageer')], max_length=15, verbose_name='company_type')),
            ],
            options={
                'verbose_name': 'Action type',
                'verbose_name_plural': 'Action types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('company_type', models.CharField(choices=[('entaj', 'entaj'), ('mokhalfat', 'mokhalfat'), ('emtiaz', 'emtiaz'), ('sageer', 'sageer')], max_length=15, verbose_name='company_type')),
            ],
            options={
                'verbose_name': 'Application type',
                'verbose_name_plural': 'Application types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDepartmentProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('attachement_file', models.FileField(blank=True, upload_to=doc_workflow.models.ApplicationDepartmentProcessing.attachement_path, verbose_name='attachement_file')),
                ('action_state', models.CharField(choices=[('draft', 'draft'), ('confirm', 'confirm')], default='draft', max_length=10, verbose_name='action_state')),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_workflow.actiontype', verbose_name='action_type')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application department processing',
                'verbose_name_plural': 'Application department processing',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationExectiveProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('attachement_file', models.FileField(blank=True, upload_to=doc_workflow.models.ApplicationExectiveProcessing.attachement_path, verbose_name='attachement_file')),
                ('action_state', models.CharField(choices=[('draft', 'draft'), ('confirm', 'confirm')], default='draft', max_length=10, verbose_name='action_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('department_processing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exective_processing', to='doc_workflow.applicationdepartmentprocessing')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application executive processing',
                'verbose_name_plural': 'Application executive processing',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('attachement_file', models.FileField(blank=True, upload_to=doc_workflow.models.ApplicationRecord.attachement_path, verbose_name='attachement_file')),
                ('state', models.CharField(choices=[('draft', 'draft'), ('confirm', 'confirm')], default='draft', max_length=10, verbose_name='record_state')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('app_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_workflow.applicationtype', verbose_name='app_type')),
            ],
            options={
                'verbose_name': 'Application record',
                'verbose_name_plural': 'Application records',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='applicationdepartmentprocessing',
            name='app_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_workflow.applicationrecord'),
        ),
        migrations.AddField(
            model_name='applicationdepartmentprocessing',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_workflow.department', verbose_name='department'),
        ),
        migrations.CreateModel(
            name='ApplicationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('delivery_state', models.CharField(choices=[('draft', 'draft'), ('confirm', 'confirm')], default='draft', max_length=10, verbose_name='delivery_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('app_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_workflow.applicationrecord')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_workflow.destination', verbose_name='destination')),
            ],
            options={
                'verbose_name': 'Application delivery',
                'verbose_name_plural': 'Application delivery',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='applicationrecord',
            index=models.Index(fields=['company'], name='doc_workflo_company_f1027e_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationrecord',
            index=models.Index(fields=['app_type'], name='doc_workflo_app_typ_4edaba_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationrecord',
            index=models.Index(fields=['state'], name='doc_workflo_state_e03ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationdepartmentprocessing',
            index=models.Index(fields=['department'], name='doc_workflo_departm_53adac_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationdepartmentprocessing',
            index=models.Index(fields=['action_type'], name='doc_workflo_action__c4d907_idx'),
        ),
    ]
