# Generated by Django 5.0.2 on 2024-05-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiontype',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='applicationtype',
            name='company_type',
        ),
    ]
