# Generated by Django 5.0.2 on 2024-05-21 14:34

import doc_workflow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_workflow', '0002_remove_actiontype_company_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='attachement_file',
            field=models.FileField(upload_to=doc_workflow.models.ApplicationRecord.attachement_path, verbose_name='attachement_file'),
        ),
    ]
