# Generated by Django 5.0.2 on 2024-05-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_workflow', '0003_alter_applicationrecord_attachement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='state',
            field=models.CharField(choices=[('new', 'new'), ('processing_department', 'processing_department'), ('processing_executive', 'processing_executive'), ('delivery_ready', 'delivery_ready'), ('delivery_partial', 'delivery_partial'), ('delivery_complete', 'delivery_complete')], default='new', max_length=25, verbose_name='record_state'),
        ),
    ]
