# Generated by Django 5.0.2 on 2024-05-21 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_workflow', '0004_alter_applicationrecord_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationexectiveprocessing',
            name='action_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='doc_workflow.actiontype', verbose_name='action_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationexectiveprocessing',
            name='app_record',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='doc_workflow.applicationrecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationexectiveprocessing',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='doc_workflow.department', verbose_name='department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='state',
            field=models.CharField(choices=[('new', 'new'), ('processing_department', 'processing_department'), ('processing_executive', 'processing_executive'), ('delivery_ready', 'delivery_ready'), ('delivery_partial', 'delivery_partial'), ('delivery_complete', 'delivery_completed')], default='new', max_length=25, verbose_name='record_state'),
        ),
    ]
