# Generated by Django 5.0.2 on 2024-05-22 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_workflow', '0005_applicationexectiveprocessing_action_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='applicationdepartmentprocessing',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('action_state', 'confirm'), ('attachement_file__isnull', False)), models.Q(('action_state', 'draft'), ('attachement_file__isnull', True)), models.Q(('action_state', 'draft'), ('attachement_file__isnull', False)), _connector='OR'), name='insure_attachment_on_confirm'),
        ),
    ]
