# Generated by Django 5.0.2 on 2024-05-22 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_workflow', '0006_applicationdepartmentprocessing_insure_attachment_on_confirm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationdepartmentprocessing',
            name='insure_attachment_on_confirm',
        ),
        migrations.AddConstraint(
            model_name='applicationdepartmentprocessing',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('action_state', 'confirm'), ('attachement_file__isnull', False)), ('action_state', 'draft'), _connector='OR'), name='insure_attachment_on_confirm'),
        ),
    ]
