# Generated by Django 5.0.2 on 2024-05-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_workflow', '0009_remove_applicationdepartmentprocessing_insure_attachment_on_confirm_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationdepartmentprocessing',
            name='insure_attachment_on_confirm',
        ),
    ]
