# Generated by Django 5.0.2 on 2024-05-22 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doc_workflow', '0010_remove_applicationdepartmentprocessing_insure_attachment_on_confirm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['id'], 'verbose_name': 'destination', 'verbose_name_plural': 'destinations'},
        ),
        migrations.AddField(
            model_name='department',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
