# Generated by Django 5.2.7 on 2026-09-06 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(blank=True, help_text='مثال: سباكة، حدادة، نجارة...', max_length=100, verbose_name='التصنيف الفرعي')),
                ('name', models.CharField(max_length=150, verbose_name='اسم العطل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعّال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'تصنيف العطل',
                'verbose_name_plural': 'تصنيفات الأعطال',
                'ordering': ['unit', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ELEC', 'وحدة الكهرباء'), ('AIR_COND', 'وحدة التبريد والتكييف'), ('MECH', 'وحدة الميكانيكا'), ('CONST', 'وحدة الإنشاءات')], max_length=20, unique=True, verbose_name='رمز الوحدة')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوحدة')),
                ('group_name', models.CharField(help_text='اسم مجموعة Django المرتبطة', max_length=100, verbose_name='مجموعة المستخدمين')),
                ('icon', models.CharField(blank=True, default='🔧', max_length=50, verbose_name='أيقونة')),
            ],
            options={
                'verbose_name': 'وحدة الصيانة',
                'verbose_name_plural': 'وحدات الصيانة',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('employee_name', models.CharField(max_length=150, verbose_name='اسم الموظف')),
                ('general_dept', models.CharField(max_length=150, verbose_name='الإدارة العامة')),
                ('department', models.CharField(max_length=150, verbose_name='القسم')),
                ('location', models.CharField(max_length=250, verbose_name='موقع العطل بالضبط')),
                ('fault_description', models.TextField(blank=True, verbose_name='وصف إضافي للمشكلة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'جاري التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجل')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات المدير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='الفني المختص')),

                ('fault_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='maintenance.faultcategory', verbose_name='نوع العطل')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('assigned_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_requests', to='maintenance.maintenanceunit', verbose_name='الوحدة المختصة')),
            ],
            options={
                'verbose_name': 'طلب صيانة',
                'verbose_name_plural': 'طلبات الصيانة',
                'ordering': ['-created_at'],
                'permissions': [('can_manage_all_requests', 'يمكنه إدارة جميع الطلبات'), ('can_view_unit_requests', 'يمكنه عرض طلبات الوحدة')],
            },
        ),
        migrations.CreateModel(
            name='CompletionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_done', models.TextField(verbose_name='العمل المنجز')),
                ('root_cause', models.TextField(blank=True, verbose_name='السبب الجذري للعطل')),
                ('recommendations', models.TextField(blank=True, verbose_name='التوصيات')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنجاز')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='الفني')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_report', to='maintenance.maintenancerequest', verbose_name='طلب الصيانة')),
            ],
            options={
                'verbose_name': 'تقرير إنجاز',
                'verbose_name_plural': 'تقارير الإنجاز',
            },
        ),
        migrations.AddField(
            model_name='faultcategory',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fault_categories', to='maintenance.maintenanceunit', verbose_name='الوحدة'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('request_created', 'طلب صيانة جديد'), ('request_updated', 'تحديث طلب صيانة'), ('request_completed', 'إغلاق طلب صيانة'), ('low_stock', 'تنبيه مخزون منخفض')], max_length=30, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='نص الإشعار')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='maintenance.maintenancerequest', verbose_name='الطلب المرتبط')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, verbose_name='تعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='maintenance.maintenancerequest', verbose_name='طلب الصيانة')),
            ],
            options={
                'verbose_name': 'تقييم الخدمة',
                'verbose_name_plural': 'تقييمات الخدمة',
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='كود القطعة (SKU)')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القطعة')),
                ('description', models.TextField(blank=True, verbose_name='وصف القطعة')),
                ('unit_of_measure', models.CharField(default='قطعة', help_text='مثال: قطعة، متر، لتر، كيلو', max_length=30, verbose_name='وحدة القياس')),
                ('quantity_in_stock', models.IntegerField(default=0, verbose_name='الرصيد الحالي')),
                ('reorder_point', models.IntegerField(default=5, help_text='يُرسل تنبيه عند الوصول لهذا الحد', verbose_name='حد إعادة الطلب (حد الأمان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعّال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spare_parts', to='maintenance.maintenanceunit', verbose_name='الوحدة المختصة')),
            ],
            options={
                'verbose_name': 'قطعة غيار',
                'verbose_name_plural': 'قطع الغيار',
                'ordering': ['unit', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_at_alert', models.IntegerField(verbose_name='الرصيد وقت التنبيه')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تمت معالجته')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التنبيه')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='maintenance.sparepart', verbose_name='القطعة')),
            ],
            options={
                'verbose_name': 'تنبيه مخزون منخفض',
                'verbose_name_plural': 'تنبيهات المخزون المنخفض',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'وارد (شراء/استلام)'), ('out', 'صادر (استهلاك في صيانة)'), ('adjust', 'تعديل جرد')], max_length=10, verbose_name='نوع الحركة')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة')),
                ('maintenance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts_used', to='maintenance.maintenancerequest', verbose_name='طلب الصيانة المرتبط')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='منفذ العملية')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='maintenance.sparepart', verbose_name='القطعة')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-created_at'],
            },
        ),
    ]
