# Generated by Django 5.2.7 on 2026-09-09 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0137_alter_employeebasic_no3_2lertibat_and_more'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_all_requests', 'يمكنه إدارة جميع الطلبات'), ('can_view_unit_requests', 'يمكنه عرض طلبات الوحدة'), ('can_manage_safety_permits', 'يمكنه إدارة وتصديق تصاريح السلامة')], 'verbose_name': 'طلب صيانة', 'verbose_name_plural': 'طلبات الصيانة'},
        ),
        migrations.AddField(
            model_name='faultcategory',
            name='requires_safety_permit',
            field=models.BooleanField(default=False, verbose_name='يتطلب تصريح سلامة مهنية'),
        ),

        migrations.AddField(
            model_name='maintenancerequest',
            name='requires_safety_permit',
            field=models.BooleanField(default=False, verbose_name='يتطلب تصريح سلامة مهنية'),
        ),
        migrations.AddField(
            model_name='maintenanceunit',
            name='requires_safety_permit',
            field=models.BooleanField(default=False, verbose_name='يتطلب تصريح سلامة مهنية'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('pending_safety', 'بانتظار تصريح السلامة'), ('in_progress', 'جاري التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='maintenanceunit',
            name='code',
            field=models.CharField(choices=[('ELEC', 'وحدة الكهرباء'), ('AIR_COND', 'وحدة التبريد والتكييف'), ('MECH', 'وحدة الميكانيكا'), ('CONST', 'وحدة الإنشاءات'), ('SAFETY', 'وحدة الأعمال الخطرة والسلامة')], max_length=20, unique=True, verbose_name='رمز الوحدة'),
        ),
        migrations.CreateModel(
            name='SafetyPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_description', models.TextField(verbose_name='وصف العمل')),
                ('start_time', models.DateTimeField(verbose_name='زمن بداية العمل')),
                ('end_time', models.DateTimeField(verbose_name='زمن انتهاء العمل')),
                ('permit_duration', models.CharField(blank=True, help_text='تُحدد وتُدخل من قبل موظف قسم السلامة', max_length=100, verbose_name='مدة التصريح')),
                ('responsible_person_name', models.CharField(max_length=150, verbose_name='اسم المسؤول عن العمل')),
                ('responsible_person_job', models.CharField(max_length=150, verbose_name='الوظيفة')),
                ('hazardous_activities', models.JSONField(blank=True, default=list, verbose_name='الأنشطة الخطرة')),
                ('hazardous_activities_other', models.CharField(blank=True, max_length=250, verbose_name='أنشطة خطرة أخرى')),
                ('control_measures', models.TextField(blank=True, verbose_name='طرق التحكم والوقاية الموجودة')),
                ('site_preparations', models.JSONField(blank=True, default=list, verbose_name='تجهيزات المكان')),
                ('site_preparations_other', models.CharField(blank=True, max_length=250, verbose_name='تجهيزات مكان أخرى')),
                ('ppe_equipment', models.JSONField(blank=True, default=list, verbose_name='مهمات ومعدات الحماية الشخصية (PPE)')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_safety', 'بانتظار موافقة السلامة'), ('approved', 'معتمد من السلامة'), ('rejected', 'مرفوض'), ('closed', 'مغلق من السلامة')], default='pending_safety', max_length=20, verbose_name='حالة التصريح')),
                ('safety_notes', models.TextField(blank=True, verbose_name='توصيات وملاحظات السلامة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء التصريح')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ موافقة السلامة')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إغلاق التصريح')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_permit', to='maintenance.maintenancerequest', verbose_name='طلب الصيانة المرتبط')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_permits_responsible', to=settings.AUTH_USER_MODEL, verbose_name='الشخص المسؤول عن العمل')),
                ('safety_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_safety_permits', to=settings.AUTH_USER_MODEL, verbose_name='موظف السلامة المعتمد')),
            ],
            options={
                'verbose_name': 'تصريح سلامة مهنية',
                'verbose_name_plural': 'تصاريح السلامة المهنية',
                'ordering': ['-created_at'],
            },
        ),
    ]
