# Generated by Django 5.2.7 on 2026-09-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0137_alter_employeebasic_no3_2lertibat_and_more'),
        ('maintenance', '0002_alter_maintenancerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='hr.employeebasic', verbose_name='سجل الموظف'),
        ),
    ]
