# Generated by Django 5.2.7 on 2026-09-09 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancerequest_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='safetypermit',
            name='assigned_technicians',
            field=models.ManyToManyField(blank=True, related_name='safety_permits_assigned', to=settings.AUTH_USER_MODEL, verbose_name='الفنيون المكلفون/المشاركون بالعمل'),
        ),
    ]
