# Generated by Django 5.2.7 on 2026-09-16 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_safetypermit_assigned_technicians'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم/رقم الشقة')),
            ],
            options={
                'verbose_name': 'الشقة',
                'verbose_name_plural': 'الشقق',
                'ordering': ['floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطابق')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'الطابق',
                'verbose_name_plural': 'الطوابق',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الفني التقني')),
                ('phone', models.CharField(max_length=30, verbose_name='رقم الهاتف')),
                ('specialty', models.CharField(blank=True, max_length=150, verbose_name='التخصص/الملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'فني تقني',
                'verbose_name_plural': 'الفنيون التقنيون',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='delay_reason',
            field=models.TextField(blank=True, verbose_name='سبب التأخير'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض/الاعتذار'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='fault_description',
            field=models.TextField(verbose_name='وصف إضافي للمشكلة'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('received', 'تم الاستلام'), ('pending_safety', 'بانتظار تصريح السلامة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغى'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='maintenance.apartment', verbose_name='الشقة'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='maintenance.floor', verbose_name='الطابق'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='maintenance.floor', verbose_name='الطابق'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_technical_technicians',
            field=models.ManyToManyField(blank=True, related_name='requests', to='maintenance.technicaltechnician', verbose_name='الفنيون التقنيون المشاركون'),
        ),
    ]
