# Generated by Django 5.2.7 on 2026-09-16 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_seed_floors_apartments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicaltechnician',
            options={'ordering': ['unit', 'name'], 'verbose_name': 'فني تقني', 'verbose_name_plural': 'الفنيون التقنيون'},
        ),
        migrations.AddField(
            model_name='technicaltechnician',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_technicians', to='maintenance.maintenanceunit', verbose_name='الوحدة المختصة'),
        ),
    ]
