# Generated by Django 5.0.2 on 2024-12-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetelegram',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_accepted'), (3, 'state_rejected')], default=1, verbose_name='record_state'),
        ),
        migrations.AddField(
            model_name='employeetelegramregistration',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_accepted'), (3, 'state_rejected')], default=1, verbose_name='record_state'),
        ),
    ]
