# Generated by Django 5.0.2 on 2024-12-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bot', '0002_employeetelegram_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetelegram',
            name='state',
        ),
    ]
