# Generated by Django 5.0.2 on 2024-12-29 07:32

import django.db.models.deletion
import hr.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0106_remove_employeetelegramregistration_created_by_and_more'),
        ('hr_bot', '0003_remove_employeetelegram_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTelegramFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('relation', models.CharField(choices=[('parent', 'FAMILY_RELATION_PARENT'), ('child', 'FAMILY_RELATION_CHILD'), ('consort', 'FAMILY_RELATION_CONSORT')], max_length=10, verbose_name='relation')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('tarikh_el2dafa', models.DateField(blank=True, null=True, verbose_name='tarikh_el2dafa')),
                ('attachement_file', models.FileField(blank=True, null=True, upload_to=hr.models.attachement_path, verbose_name='attachement')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Employee Family',
                'verbose_name_plural': 'Employee Family',
            },
        ),
    ]
