# Generated by Django 5.0.2 on 2024-12-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bot', '0004_employeetelegramfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetelegramfamily',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_accepted'), (3, 'state_rejected')], default=1, verbose_name='record_state'),
        ),
    ]
