# Generated by Django 5.0.2 on 2025-01-22 06:44

import django.db.models.deletion
import hr.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0109_alter_employeebasic_status'),
        ('hr_bot', '0005_employeetelegramfamily_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTelegramMoahil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('moahil', models.CharField(choices=[('thanoi', 'MOAHIL_THANOI'), ('deplom_tegani', 'MOAHIL_DEPLOM_TEGANI'), ('deplom_waseet', 'MOAHIL_DEPLOM_WASEET'), ('baklarios', 'MOAHIL_BAKLARIOS'), ('baklarios_sharaf', 'MOAHIL_BAKLARIOS_SHARAF'), ('daplom_3ali', 'MOAHIL_DAPLOM_3ALI'), ('majstear', 'MOAHIL_MAJSTEAR'), ('dectora', 'MOAHIL_DECTORA')], max_length=20, verbose_name='moahil')),
                ('university', models.CharField(max_length=150, verbose_name='university')),
                ('takhasos', models.CharField(max_length=100, verbose_name='takhasos')),
                ('graduate_dt', models.DateField(verbose_name='graduate_dt')),
                ('tarikh_el2dafa', models.DateField(blank=True, null=True, verbose_name='tarikh_el2dafa')),
                ('attachement_file', models.FileField(blank=True, null=True, upload_to=hr.models.attachement_path, verbose_name='attachement')),
                ('state', models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_accepted'), (3, 'state_rejected')], default=1, verbose_name='record_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Employee Moahil',
                'verbose_name_plural': 'Employee Moahil',
            },
        ),
    ]
