# Generated by Django 5.0.2 on 2025-01-22 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0109_alter_employeebasic_status'),
        ('hr_bot', '0006_employeetelegrammoahil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTelegramBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('bank', models.CharField(choices=[('bok', 'BANK_KHARTOUM'), ('onb', 'BANK_OMDURMAN')], max_length=10, verbose_name='bank')),
                ('account_no', models.CharField(max_length=20, verbose_name='account_no')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('state', models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_accepted'), (3, 'state_rejected')], default=1, verbose_name='record_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
    ]
