# Generated by Django 5.0.2 on 2025-01-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0111_alter_employeefamily_name'),
        ('hr_bot', '0007_employeetelegrambankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBasicProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.employeebasic',),
        ),
    ]
