# Generated by Django 5.0.2 on 2025-01-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bot', '0008_employeebasicproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeebasicproxy',
            options={'verbose_name': 'Employee data', 'verbose_name_plural': 'Employee data'},
        ),
        migrations.AlterModelOptions(
            name='employeetelegram',
            options={'verbose_name': 'Employee Telegram', 'verbose_name_plural': 'Employee Telegram'},
        ),
        migrations.AlterModelOptions(
            name='employeetelegrambankaccount',
            options={'verbose_name': 'Bank Account Application', 'verbose_name_plural': 'Bank Account Application'},
        ),
        migrations.AlterModelOptions(
            name='employeetelegramfamily',
            options={'verbose_name': 'Employee Family Application', 'verbose_name_plural': 'Employee Family Application'},
        ),
        migrations.AlterModelOptions(
            name='employeetelegrammoahil',
            options={'verbose_name': 'Employee Moahil Application', 'verbose_name_plural': 'Employee Moahil Application'},
        ),
        migrations.AlterModelOptions(
            name='employeetelegramregistration',
            options={'verbose_name': 'Employee Registration', 'verbose_name_plural': 'Employee Registration'},
        ),
    ]
