# Generated by Django 5.0.2 on 2025-01-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0112_employeebasic_unique_employee_code'),
        ('hr_bot', '0009_alter_employeebasicproxy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBankAccountProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.employeebankaccount',),
        ),
        migrations.CreateModel(
            name='EmployeeFamilyProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.employeefamily',),
        ),
        migrations.CreateModel(
            name='EmployeeMoahilProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.employeemoahil',),
        ),
        migrations.CreateModel(
            name='JazaatProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.employeejazaat',),
        ),
        migrations.CreateModel(
            name='SalafiatProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.employeesalafiat',),
        ),
    ]
