# Generated by Django 5.1.7 on 2025-05-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bot', '0010_employeebankaccountproxy_employeefamilyproxy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeebankaccountproxy',
            options={'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
        migrations.AlterModelOptions(
            name='employeefamilyproxy',
            options={'verbose_name': 'Employee Family', 'verbose_name_plural': 'Employee Family'},
        ),
        migrations.AlterModelOptions(
            name='employeemoahilproxy',
            options={'verbose_name': 'Employee Moahil', 'verbose_name_plural': 'Employee Moahil'},
        ),
        migrations.AlterModelOptions(
            name='jazaatproxy',
            options={'verbose_name': 'Jazaat', 'verbose_name_plural': 'Jazaat'},
        ),
        migrations.AlterModelOptions(
            name='salafiatproxy',
            options={'verbose_name': 'Salafiat', 'verbose_name_plural': 'Salafiat'},
        ),
    ]
