# Generated by Django 5.1.7 on 2025-05-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bot', '0011_alter_employeebankaccountproxy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.PositiveSmallIntegerField(choices=[(1, 'إضافة طفل'), (2, 'إضافة قسيمة'), (3, 'إضافة مؤهل'), (4, 'إضافة حساب بنكي')], verbose_name='الطلب')),
                ('requirement', models.TextField(verbose_name='المتطلبات')),
            ],
            options={
                'verbose_name': 'مطلوبات الاجراءات',
                'verbose_name_plural': 'مطلوبات الاجراءات',
            },
        ),
    ]
