# Generated by Django 5.1.7 on 2025-05-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bot', '0012_applicationrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrequirement',
            name='requirement',
            field=models.CharField(max_length=255, verbose_name='المتطلبات'),
        ),
    ]
