# Generated by Django 5.1.7 on 2025-05-18 09:19

import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bot', '0014_alter_employeetelegramfamily_attachement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetelegrammoahil',
            name='attachement_file',
            field=models.FileField(default='', upload_to=hr.models.attachement_path, verbose_name='attachement'),
            preserve_default=False,
        ),
    ]
