# Generated by Django 5.0.2 on 2025-07-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bot', '0015_alter_employeetelegrammoahil_attachement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetelegramfamily',
            name='tarikh_el2dafa',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ صدور الشهادة'),
        ),
    ]
