# Generated by Django 5.2.7 on 2025-11-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bot', '0016_alter_employeetelegramfamily_tarikh_el2dafa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetelegramfamily',
            name='tarikh_el2dafa',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الشهادة'),
        ),
    ]
