# Generated by Django 5.2.7 on 2026-02-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bot', '0017_alter_employeetelegramfamily_tarikh_el2dafa'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetelegrambankaccount',
            name='account_type',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='نوع الحساب'),
        ),
        migrations.AddField(
            model_name='employeetelegrambankaccount',
            name='branch_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='كود الفرع'),
        ),
    ]
