# Generated by Django 5.0.2 on 2025-08-17 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0121_alter_employeebasic_no3_2lertibat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_points', to='it.computer')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_type', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'macOS'), ('other', 'Other')], max_length=50)),
                ('applications', models.ManyToManyField(related_name='templates', to='it.application')),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='it.computertemplate'),
        ),
        migrations.CreateModel(
            name='EmployeeComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_computers', to='it.computer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkAdapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('connectivity_type', models.CharField(choices=[('wired', 'Wired'), ('wireless', 'Wireless')], max_length=20)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_adapters', to='it.computer')),
            ],
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('display', 'Display'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('printer', 'Printer'), ('other', 'Other')], max_length=20)),
                ('connectivity_type', models.CharField(choices=[('wired', 'Wired'), ('wireless', 'Wireless')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peripherals', to='it.computer')),
            ],
        ),
    ]
