# Generated by Django 5.0.2 on 2025-08-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computertemplate',
            name='os_version',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
