# Generated by Django 5.0.2 on 2025-08-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0002_computertemplate_os_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peripheral',
            name='connectivity_type',
            field=models.CharField(max_length=20),
        ),
    ]
