# Generated by Django 5.0.2 on 2025-03-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0003_rename_recommandation_itrecommendationform_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developmentrequestform',
            options={'verbose_name': 'DevelopmentRequestForm', 'verbose_name_plural': 'DevelopmentRequestForms'},
        ),
        migrations.AlterModelOptions(
            name='itrecommendationform',
            options={'verbose_name': 'ItRecommendationForm', 'verbose_name_plural': 'ItRecommendationForms'},
        ),
        migrations.AlterModelOptions(
            name='itrejectionform',
            options={'verbose_name': 'ItRejectionForm', 'verbose_name_plural': 'ItRejectionForms'},
        ),
        migrations.AlterField(
            model_name='developmentrequestform',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='developmentrequestform',
            name='department',
            field=models.CharField(max_length=255, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='developmentrequestform',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='developmentrequestform',
            name='product_description',
            field=models.TextField(verbose_name='product_description'),
        ),
        migrations.AlterField(
            model_name='developmentrequestform',
            name='requirements_description',
            field=models.TextField(verbose_name='requirements_description'),
        ),
        migrations.AlterField(
            model_name='developmentrequestform',
            name='responsible',
            field=models.CharField(max_length=255, verbose_name='responsible'),
        ),
        migrations.AlterField(
            model_name='developmentrequestform',
            name='state',
            field=models.IntegerField(choices=[(1, 'IT_STATE_DRAFT'), (2, 'IT_STATE_CONFIRMED'), (3, 'IT_STATE_APPROVED'), (4, 'IT_STATE_IT_MANAGER_STUDING_APPROVAL'), (5, 'IT_STATE_IT_MANAGER_STUDING_REJECTION'), (6, 'IT_STATE_IT_MANAGER_RECOMMENDATION'), (7, 'IT_STATE_PQI_MANAGER_CHANGE_REQUEST'), (8, 'IT_STATE_PQI_MANAGER_APPROVAL'), (9, 'IT_STATE_FINAL_REJECTION')], default=1, verbose_name='record_state'),
        ),
        migrations.AlterField(
            model_name='itrecommendationform',
            name='recommendation',
            field=models.TextField(verbose_name='recommendation'),
        ),
        migrations.AlterField(
            model_name='itrejectionform',
            name='reason',
            field=models.TextField(verbose_name='reason'),
        ),
    ]
