# Generated by Django 5.0.2 on 2025-08-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0003_alter_peripheral_connectivity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peripheral',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
