# Generated by Django 5.0.2 on 2025-03-05 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0004_alter_developmentrequestform_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('service_status', models.IntegerField(choices=[(2, 'active'), (4, 'inactive')], default=1, verbose_name='service_status')),
                ('description', models.TextField(verbose_name='description')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'IT Service',
                'verbose_name_plural': 'IT Services',
            },
        ),
        migrations.CreateModel(
            name='ITServiceModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('description', models.TextField(verbose_name='وصف التعديل')),
                ('event_type', models.CharField(choices=[('update', 'تحديث'), ('fix', 'إصلاح'), ('maintenance', 'صيانة'), ('other', 'أخرى')], default='update', max_length=20, verbose_name='نوع الحدث')),
                ('date', models.DateField(verbose_name='تاريخ التعديل')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'تعديل',
                'verbose_name_plural': 'التعديلات',
            },
        ),
        migrations.CreateModel(
            name='ITServiceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('description', models.TextField(verbose_name='description')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='it_service_operation', to='it.itservice', verbose_name='IT Service')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'IT Service Operation',
                'verbose_name_plural': 'IT Service Operations',
            },
        ),
        migrations.CreateModel(
            name='ITServiceResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('owner', models.CharField(max_length=150, verbose_name='owner')),
                ('responsible', models.CharField(max_length=150, verbose_name='responsible')),
                ('support', models.CharField(max_length=150, verbose_name='support')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='it_service_responsibility', to='it.itservice', verbose_name='IT Service')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Responsibility',
                'verbose_name_plural': 'Responsibilities',
            },
        ),
        migrations.CreateModel(
            name='ITServiceScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('description', models.TextField(verbose_name='description')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='it_service_scope', to='it.itservice', verbose_name='IT Service')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'IT Service Scope',
                'verbose_name_plural': 'IT Service Scopes',
            },
        ),
        migrations.CreateModel(
            name='ITServiceSLAAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الاتفاقية')),
                ('availability', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='مستوى التوفر')),
                ('response_time_urgent_hrs', models.PositiveIntegerField(verbose_name='زمن الاستجابة العاجلة (ساعة)')),
                ('resolution_time_critical_hrs', models.PositiveIntegerField(verbose_name='زمن حل المشكلات الحرجة (ساعات)')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='it_service_sla_aggrement', to='it.itservice', verbose_name='IT Service')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
