# Generated by Django 5.0.2 on 2025-08-17 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0004_alter_peripheral_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='it.employeecomputer')),
            ],
        ),
    ]
