# Generated by Django 5.0.2 on 2025-08-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0005_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peripheral',
            name='model',
        ),
        migrations.AddField(
            model_name='peripheral',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='connectivity_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='type',
            field=models.CharField(choices=[('display', 'External display'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('printer', 'Printer'), ('processor', 'Processor'), ('memory', 'Memory'), ('hard_drive', 'Hard drive'), ('graphics_card', 'Graphics card'), ('other', 'Other')], max_length=20),
        ),
    ]
