# Generated by Django 5.0.2 on 2025-08-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0006_remove_peripheral_model_peripheral_specifications_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkAdapter',
        ),
    ]
