# Generated by Django 5.0.2 on 2025-03-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0006_itservice_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itservice',
            name='state',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'confirmed'), (3, 'IT_STATE_APPROVED')], default=1, verbose_name='record_state'),
        ),
    ]
