# Generated by Django 5.0.2 on 2025-08-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0007_delete_networkadapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peripheral',
            name='type',
            field=models.CharField(choices=[('display', 'External display'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('printer', 'Printer'), ('processor', 'Processor'), ('memory', 'Memory'), ('hard_drive', 'Hard drive'), ('graphics_card', 'Graphics card'), ('network_adapter', 'Network adapter'), ('other', 'Other')], max_length=20),
        ),
    ]
