# Generated by Django 5.0.2 on 2025-03-05 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0007_alter_itservice_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='itservicemodification',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='it_service_modification', to='it.itservice', verbose_name='IT Service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itservice',
            name='service_status',
            field=models.IntegerField(choices=[(1, 'under_development'), (2, 'active'), (3, 'maintenance'), (4, 'inactive')], default=1, verbose_name='service_status'),
        ),
    ]
