# Generated by Django 5.0.2 on 2025-08-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0009_helprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='name',
        ),
    ]
