# Generated by Django 5.0.2 on 2025-08-19 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0121_alter_employeebasic_no3_2lertibat'),
        ('it', '0010_remove_helprequest_email_remove_helprequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='employee',
            field=models.ForeignKey(default=7841, on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name'),
            preserve_default=False,
        ),
    ]
