# Generated by Django 5.0.2 on 2025-08-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0011_helprequest_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='investigations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
