# Generated by Django 5.0.2 on 2025-08-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0012_helprequest_investigations_helprequest_root_cause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Unsolved'), (2, 'Solved')], default=1),
        ),
    ]
