# Generated by Django 5.0.2 on 2025-08-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0013_alter_helprequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='وصف المعالجة'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='category',
            field=models.CharField(choices=[('hardware', 'اجهزة وعتاد'), ('software', 'برامج'), ('network', 'شبكة'), ('other', 'اخرى')], max_length=50, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='description',
            field=models.TextField(verbose_name='وصف المشكلة'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='investigations',
            field=models.TextField(blank=True, null=True, verbose_name='التحريات'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='root_cause',
            field=models.TextField(blank=True, null=True, verbose_name='السبب الجزري للمشكلة'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'لم تتم المعالجة'), (2, 'تمت المعالجة')], default=1, verbose_name='موقف الطلب'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='الموضوع'),
        ),
    ]
