# Generated by Django 5.0.2 on 2025-08-19 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0014_helprequest_solution_alter_helprequest_category_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='helprequest',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
    ]
