# Generated by Django 5.0.2 on 2025-08-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0015_alter_helprequest_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpRequest',
        ),
    ]
