# Generated by Django 5.0.2 on 2025-08-19 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0121_alter_employeebasic_no3_2lertibat'),
        ('it', '0016_delete_helprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('hardware', 'اجهزة وعتاد'), ('software', 'برامج'), ('network', 'شبكة'), ('other', 'اخرى')], max_length=50, verbose_name='التصنيف')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('investigations', models.TextField(blank=True, null=True, verbose_name='التحريات')),
                ('root_cause', models.TextField(blank=True, null=True, verbose_name='السبب الجزري للمشكلة')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='وصف المعالجة')),
                ('status', models.IntegerField(choices=[(1, 'لم تتم المعالجة'), (2, 'تمت المعالجة')], default=1, verbose_name='موقف الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
            ],
        ),
    ]
