# Generated by Django 5.0.2 on 2025-08-19 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0017_helprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecomputer',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False),
        ),
    ]
