# Generated by Django 5.0.2 on 2025-08-19 08:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0020_alter_employeecomputer_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecomputer',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
