# Generated by Django 5.0.2 on 2025-08-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0021_alter_employeecomputer_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Computer name'),
        ),
    ]
