# Generated by Django 5.0.2 on 2025-08-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0022_alter_computer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='applications',
            field=models.ManyToManyField(related_name='computers', to='it.application'),
        ),
    ]
