# Generated by Django 5.0.2 on 2025-08-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0023_computer_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='applications',
            field=models.ManyToManyField(blank=True, null=True, related_name='computers', to='it.application', verbose_name='Other applications'),
        ),
    ]
