# Generated by Django 5.0.2 on 2025-08-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0024_alter_computer_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspoint',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
