# Generated by Django 5.0.2 on 2025-08-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0025_accesspoint_more_info_alter_accesspoint_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='computers', to='it.application', verbose_name='Other applications'),
        ),
    ]
