# Generated by Django 5.0.2 on 2025-08-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0026_alter_computer_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspoint',
            name='more_info',
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='purpose',
            field=models.TextField(blank=True, default='Internet, Local network', null=True),
        ),
    ]
