# Generated by Django 5.0.2 on 2025-08-23 14:56

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0027_remove_accesspoint_more_info_accesspoint_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoint',
            name='purpose',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200, null=True),
        ),
    ]
