# Generated by Django 5.0.2 on 2025-08-23 14:57

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0028_alter_accesspoint_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoint',
            name='purpose',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('INTERNET', 'INTERNET'), ('LOCAL NETWORK', 'LOCAL NETWORK'), ('PRINTER', 'PRINTER')], max_length=100, null=True),
        ),
    ]
