# Generated by Django 5.0.2 on 2025-02-13 07:03

import dabtiaat_altaedin.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0115_alter_apphseperformancereportchemicalused_expire_dt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDabtiaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('date', models.DateField(verbose_name='date')),
                ('gold_weight_in_gram', models.FloatField(verbose_name='gold_weight_in_gram')),
                ('gold_price', models.FloatField(verbose_name='gold_price')),
                ('state', models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_smrc'), (6, 'state_ssmo'), (8, 'state_canceled')], default=1, verbose_name='record_state')),
                ('attachement_file', models.FileField(blank=True, null=True, upload_to=dabtiaat_altaedin.models.AppDabtiaat.attachement_path, verbose_name='attachement_file')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'dabtiaat app',
                'verbose_name_plural': 'dabtiaat app',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LkpStateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='code')),
                ('next_serial_no', models.IntegerField(verbose_name='export_next_serial_no')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='state_representative', to='company_profile.lkpstate', verbose_name='state')),
            ],
            options={
                'verbose_name': 'dabtiaat state detail',
                'verbose_name_plural': 'dabtiaat state details',
            },
        ),
        migrations.CreateModel(
            name='TblStateRepresentative2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('authority', models.IntegerField(choices=[(2, 'authority_smrc'), (6, 'authority_smrc_nafiza')], default=2, verbose_name='authority')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='state_representative2', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'state representative',
                'verbose_name_plural': 'state representatives',
            },
        ),
        migrations.AddConstraint(
            model_name='tblstaterepresentative2',
            constraint=models.UniqueConstraint(fields=('state', 'authority'), name='unique_state_authority_dabtiaat'),
        ),
    ]
