# Generated by Django 5.0.2 on 2025-02-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabtiaat_altaedin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstaterepresentative2',
            name='authority',
            field=models.IntegerField(choices=[(2, 'authority_smrc')], default=2, verbose_name='authority'),
        ),
    ]
