# Generated by Django 5.0.2 on 2025-02-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dabtiaat_altaedin', '0002_alter_tblstaterepresentative2_authority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LkpStateDetails',
        ),
    ]
