# Generated by Django 5.0.2 on 2025-02-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabtiaat_altaedin', '0004_alter_appdabtiaat_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdabtiaat',
            name='report_number',
            field=models.CharField(default=0, max_length=20, verbose_name='Report number'),
            preserve_default=False,
        ),
    ]
