# Generated by Django 5.0.2 on 2025-03-05 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0115_alter_apphseperformancereportchemicalused_expire_dt'),
        ('dabtiaat_altaedin', '0005_appdabtiaat_report_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'settlement type',
                'verbose_name_plural': 'settlement types',
            },
        ),
        migrations.AddField(
            model_name='appdabtiaat',
            name='gold_caliber',
            field=models.FloatField(default=0, verbose_name='gold_caliber'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RevenueSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('state', models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_smrc')], default=1, verbose_name='record_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpstate', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('settlement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dabtiaat_altaedin.settlementtype', verbose_name='settlement_type')),
            ],
            options={
                'verbose_name': 'Revenue Settlement',
                'verbose_name_plural': 'Revenue Settlement',
                'ordering': ['-date'],
            },
        ),
    ]
