# Generated by Django 5.1.7 on 2025-04-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabtiaat_altaedin', '0006_settlementtype_appdabtiaat_gold_caliber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdabtiaat',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_smrc'), (3, 'state_approved'), (8, 'state_canceled')], default=1, verbose_name='record_state'),
        ),
    ]
