# Generated by Django 5.1.7 on 2025-04-26 12:16

import django.db.models.deletion
from django.db import migrations, models

# from ..data import load_data

# def migrate_data(apps, schema_editor):
#     load_data.migrate_master_to_details()

class Migration(migrations.Migration):

    dependencies = [
        ('dabtiaat_altaedin', '0007_alter_appdabtiaat_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDabtiaatDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_weight_in_gram', models.FloatField(verbose_name='gold_weight_in_gram')),
                ('gold_price', models.FloatField(verbose_name='gold_price')),
                ('gold_caliber', models.FloatField(verbose_name='gold_caliber')),
                ('app_dabtiaat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dabtiaat_altaedin.appdabtiaat', verbose_name='app_dabtiaat')),
            ],
        ),
        # migrations.RunPython(migrate_data),
    ]
