# Generated by Django 5.1.7 on 2025-04-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabtiaat_altaedin', '0009_remove_appdabtiaat_gold_caliber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdabtiaatdetails',
            name='alloy_id',
            field=models.CharField(default='1', max_length=20, verbose_name='alloy_id'),
        ),
    ]
