# Generated by Django 5.1.7 on 2025-04-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabtiaat_altaedin', '0010_appdabtiaatdetails_alloy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdabtiaatdetails',
            name='alloy_id',
            field=models.CharField(default='', max_length=20, verbose_name='alloy_id'),
        ),
    ]
