# Generated by Django 5.1.7 on 2025-05-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dabtiaat_altaedin', '0011_alter_appdabtiaatdetails_alloy_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appdabtiaatdetails',
            options={'verbose_name': 'تفاصيل استمارة ضبطية', 'verbose_name_plural': 'تفاصيل استمارة ضبطية'},
        ),
    ]
