# Generated by Django 5.1.7 on 2025-05-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabtiaat_altaedin', '0012_alter_appdabtiaatdetails_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdabtiaatdetails',
            name='gold_caliber',
            field=models.FloatField(default=0, verbose_name='gold_caliber'),
        ),
    ]
