# Generated by Django 5.1.7 on 2025-05-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabtiaat_altaedin', '0014_alter_appdabtiaat_report_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdabtiaatdetails',
            name='gold_caliber',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='gold_caliber'),
        ),
    ]
