# Generated by Django 5.2.1 on 2025-07-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabtiaat_altaedin', '0015_alter_appdabtiaatdetails_gold_caliber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuesettlement',
            name='state',
            field=models.IntegerField(choices=[(1, 'state_draft'), (2, 'state_smrc'), (3, 'state_approved'), (8, 'state_canceled')], default=1, verbose_name='record_state'),
        ),
    ]
