# Generated by Django 5.2.7 on 2026-07-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabtiaat_altaedin', '0016_alter_revenuesettlement_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='DabtiaatSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم البند')),
                ('key', models.CharField(blank=True, help_text='رمز للتعرف على البند بالنظام (اختياري)', max_length=50, null=True, unique=True, verbose_name='مفتاح البند')),
                ('percentage', models.FloatField(default=0.0, verbose_name='النسبة (%)')),
                ('calculation_base', models.CharField(choices=[('TOTAL', 'إجمالي قيمة المضبوطات'), ('HAFIZ', 'مبلغ الحافز')], default='TOTAL', max_length=20, verbose_name='أساس الاحتساب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'إعداد النسبة والبنود',
                'verbose_name_plural': 'إعدادات البنود والنسب',
                'ordering': ['id'],
            },
        ),
    ]
