# Generated by Django 5.2.7 on 2026-07-29 12:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabtiaat_altaedin', '0019_seed_total_koli_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDabtiaatCalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت الحساب')),
                ('total_gold_weight', models.FloatField(default=0.0, verbose_name='إجمالي وزن الذهب (جرام)')),
                ('total_gold_value', models.FloatField(default=0.0, verbose_name='إجمالي قيمة الذهب')),
                ('setting_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='مفتاح البند')),
                ('setting_name', models.CharField(max_length=100, verbose_name='اسم البند')),
                ('percentage', models.FloatField(default=0.0, verbose_name='النسبة (%)')),
                ('calculation_base', models.CharField(default='TOTAL', max_length=20, verbose_name='أساس الاحتساب')),
                ('calculated_amount', models.FloatField(default=0.0, verbose_name='المبلغ المحسوب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل وقت الحساب')),
                ('app_dabtiaat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_histories', to='dabtiaat_altaedin.appdabtiaat', verbose_name='dabtiaat app')),
            ],
            options={
                'verbose_name': 'سجل حساب الضبطية ',
                'verbose_name_plural': 'سجلات حسابات الضبطيات',
                'ordering': ['-calculation_date', 'id'],
            },
        ),
    ]
