# Generated by Django 5.2.7 on 2026-08-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dabtiaat_altaedin', '0021_migrate_existing_dabtiaat_histories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appdabtiaatcalculationhistory',
            options={'ordering': ['-calculation_date', 'id'], 'verbose_name': 'سجل حساب الضبطية', 'verbose_name_plural': 'سجلات حسابات الضبطيات'},
        ),
    ]
