# Generated by Django 5.0.2 on 2025-02-20 22:53

import django.core.validators
import django.db.models.deletion
import sswg.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gold_travel', '0038_alter_lkpstatedetails_reexport_next_serial_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('date', models.DateField(verbose_name='Form Date')),
                ('sn_no', models.CharField(max_length=15, unique=True, verbose_name='Serial Number')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'SSWG Basic Form',
                'verbose_name_plural': 'SSWG Basic Forms',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CBSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('customer_account_number', models.CharField(max_length=20, verbose_name='Customer Account Number')),
                ('commercial_bank_name', models.CharField(max_length=150, verbose_name='Commercial Bank Name')),
                ('issued_amount', models.DateField(verbose_name='Issued Amount Date')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=20, verbose_name='Payment Method')),
                ('attachment_file', models.FileField(upload_to=sswg.models.CBSData.attachment_path, verbose_name='attachment_file')),
                ('basic_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbs_data', to='sswg.basicform')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'SSWG CBS',
                'verbose_name_plural': 'SSWG CBS',
            },
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('surrogate_name', models.CharField(max_length=255, verbose_name='Surrogate Name')),
                ('surrogate_id_type', models.IntegerField(choices=[(1, 'identity_passport'), (2, 'identity_personal'), (3, 'identity_national_id'), (4, 'identity_driving_license')], verbose_name='ID Type')),
                ('surrogate_id_val', models.CharField(max_length=20, verbose_name='ID Value')),
                ('surrogate_id_phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('basic_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_details', to='sswg.basicform')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel.lkpowner', verbose_name='Company Name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'SSWG CompanyDetails',
                'verbose_name_plural': 'SSWG CompanyDetails',
            },
        ),
        migrations.CreateModel(
            name='MOCSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('contract_number', models.CharField(max_length=20, verbose_name='Contract Number')),
                ('exporters_importers_registry_number', models.CharField(max_length=20, verbose_name='Exporters/Importers Registry Number')),
                ('unit_price_in_grams', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Unit Price (grams)')),
                ('total_contract_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total Contract Value')),
                ('port_of_shipment', models.CharField(max_length=150, verbose_name='Port of Shipment')),
                ('port_of_arrival', models.CharField(max_length=150, verbose_name='Port of Arrival')),
                ('main_bank_name', models.CharField(max_length=150, verbose_name='Main Bank Name')),
                ('subsidiary_bank_name', models.CharField(max_length=150, verbose_name='Subsidiary Bank Name')),
                ('contract_expiration_date', models.DateField(verbose_name='Contract Expiration Date')),
                ('attachment_file', models.FileField(upload_to=sswg.models.MOCSData.attachment_path, verbose_name='attachment_file')),
                ('basic_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mocs_data', to='sswg.basicform')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'SSWG MOCSData',
                'verbose_name_plural': 'SSWG MOCSData',
            },
        ),
        migrations.CreateModel(
            name='SMRCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('raw_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Raw Weight')),
                ('allow_count', models.PositiveIntegerField(verbose_name='Allow Count')),
                ('smrc_file', models.FileField(upload_to=sswg.models.SMRCData.attachment_path, verbose_name='attachment_file')),
                ('basic_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smrc_data', to='sswg.basicform')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel.appmovegold', verbose_name='Move Gold')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'SSWG SMRCData',
                'verbose_name_plural': 'SSWG SMRCData',
            },
        ),
        migrations.CreateModel(
            name='SSMOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('raw_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Raw Weight')),
                ('net_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Net Weight')),
                ('allow_count', models.PositiveIntegerField(verbose_name='Allow Count')),
                ('certificate_id', models.CharField(max_length=20, verbose_name='Certificate ID')),
                ('attachment_file', models.FileField(upload_to=sswg.models.SSMOData.attachment_path, verbose_name='ssmo_file')),
                ('basic_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssmo_data', to='sswg.basicform')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'SSWG SSMOData',
                'verbose_name_plural': 'SSWG SSMOData',
            },
        ),
    ]
