# Generated by Django 5.0.2 on 2025-02-20 12:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('surrogate_name', models.CharField(max_length=255, verbose_name='Surrogate Name')),
                ('surrogate_id_type', models.IntegerField(choices=[(1, 'Passport'), (2, 'National ID'), (3, 'Driving License'), (4, 'Business Registration'), (5, 'Other')], verbose_name='ID Type')),
                ('surrogate_id_val', models.CharField(max_length=20, verbose_name='ID Value')),
                ('surrogate_id_phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
            ],
        ),
        migrations.CreateModel(
            name='SMRCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Raw Weight')),
                ('allow_count', models.PositiveIntegerField(verbose_name='Allow Count')),
            ],
        ),
        migrations.CreateModel(
            name='SSMOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Raw Weight')),
                ('net_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Net Weight')),
                ('allow_count', models.PositiveIntegerField(verbose_name='Allow Count')),
                ('certificate_id', models.CharField(max_length=20, verbose_name='Certificate ID')),
            ],
        ),
        migrations.CreateModel(
            name='BasicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Form Date')),
                ('sn_no', models.CharField(max_length=15, unique=True, verbose_name='Serial Number')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sswg.companydetails', verbose_name='Company Details')),
                ('smrc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sswg.smrcdata', verbose_name='SMRC Data')),
                ('ssmo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sswg.ssmodata', verbose_name='SSMO Data')),
            ],
            options={
                'verbose_name': 'Basic Form',
                'verbose_name_plural': 'Basic Forms',
                'ordering': ['-date'],
            },
        ),
    ]
