# Generated by Django 5.0.2 on 2025-02-20 22:55

import sswg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssmodata',
            old_name='attachment_file',
            new_name='ssmo_file',
        ),
        migrations.RemoveField(
            model_name='cbsdata',
            name='attachment_file',
        ),
        migrations.RemoveField(
            model_name='mocsdata',
            name='attachment_file',
        ),
        migrations.AddField(
            model_name='cbsdata',
            name='cbs_file',
            field=models.FileField(default='', upload_to=sswg.models.CBSData.attachment_path, verbose_name='cbs_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mocsdata',
            name='mocs_file',
            field=models.FileField(default='', upload_to=sswg.models.MOCSData.attachment_path, verbose_name='mocs_file'),
            preserve_default=False,
        ),
    ]
