# Generated by Django 5.0.2 on 2025-02-20 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicform',
            name='company',
        ),
        migrations.RemoveField(
            model_name='basicform',
            name='smrc',
        ),
        migrations.RemoveField(
            model_name='basicform',
            name='ssmo',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='basic_form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_details', to='sswg.basicform'),
        ),
        migrations.AddField(
            model_name='smrcdata',
            name='basic_form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smrc_data', to='sswg.basicform'),
        ),
        migrations.AddField(
            model_name='ssmodata',
            name='basic_form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssmo_data', to='sswg.basicform'),
        ),
    ]
