# Generated by Django 5.0.2 on 2025-02-20 13:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0002_remove_basicform_company_remove_basicform_smrc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOCSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=20, verbose_name='Contract Number')),
                ('exporters_importers_registry_number', models.CharField(max_length=20, verbose_name='Exporters/Importers Registry Number')),
                ('unit_price_in_grams', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Unit Price (grams)')),
                ('total_contract_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total Contract Value')),
                ('port_of_shipment', models.CharField(max_length=150, verbose_name='Port of Shipment')),
                ('port_of_arrival', models.CharField(max_length=150, verbose_name='Port of Arrival')),
                ('main_bank_name', models.CharField(max_length=150, verbose_name='Main Bank Name')),
                ('subsidiary_bank_name', models.CharField(max_length=150, verbose_name='Subsidiary Bank Name')),
                ('contract_expiration_date', models.DateField(verbose_name='Contract Expiration Date')),
                ('basic_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mocs_data', to='sswg.basicform')),
            ],
        ),
    ]
