# Generated by Django 5.0.2 on 2025-02-20 23:15

import sswg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0002_rename_attachment_file_ssmodata_ssmo_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocsdata',
            name='mocs_file',
        ),
        migrations.AddField(
            model_name='mocsdata',
            name='mocs1_file',
            field=models.FileField(default='', upload_to=sswg.models.MOCSData.attachment_path, verbose_name='mocs1_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mocsdata',
            name='mocs2_file',
            field=models.FileField(default='', upload_to=sswg.models.MOCSData.attachment_path, verbose_name='mocs2_file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smrcdata',
            name='smrc_file',
            field=models.FileField(upload_to=sswg.models.TransferRelocationFormData.attachment_path, verbose_name='smrc_file'),
        ),
    ]
