# Generated by Django 5.0.2 on 2025-02-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0003_mocsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_account_number', models.CharField(max_length=20, verbose_name='Customer Account Number')),
                ('commercial_bank_name', models.CharField(max_length=150, verbose_name='Commercial Bank Name')),
                ('issued_amount', models.DateField(verbose_name='Issued Amount Date')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=20, verbose_name='Payment Method')),
                ('basic_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbs_data', to='sswg.basicform')),
            ],
        ),
    ]
