# Generated by Django 5.0.2 on 2025-02-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0003_remove_mocsdata_mocs_file_mocsdata_mocs1_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbsdata',
            name='ex_form_number',
            field=models.CharField(default=1, max_length=20, verbose_name='EX-Form Number'),
            preserve_default=False,
        ),
    ]
