# Generated by Django 5.0.2 on 2025-02-20 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0038_alter_lkpstatedetails_reexport_next_serial_no_and_more'),
        ('sswg', '0004_cbsdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicform',
            options={'ordering': ['-date'], 'verbose_name': 'SSWG Basic Form', 'verbose_name_plural': 'SSWG Basic Forms'},
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel.lkpowner', verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='surrogate_id_type',
            field=models.IntegerField(choices=[(1, 'identity_passport'), (2, 'identity_personal'), (3, 'identity_national_id'), (4, 'identity_driving_license')], verbose_name='ID Type'),
        ),
    ]
