# Generated by Django 5.0.2 on 2025-02-21 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0004_cbsdata_ex_form_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbsdata',
            name='basic_form',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cbs_data', to='sswg.basicform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='basic_form',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_details', to='sswg.basicform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mocsdata',
            name='basic_form',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mocs_data', to='sswg.basicform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ssmodata',
            name='basic_form',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ssmo_data', to='sswg.basicform'),
            preserve_default=False,
        ),
    ]
