# Generated by Django 5.0.2 on 2025-02-21 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0005_alter_cbsdata_basic_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbsdata',
            name='basic_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cbs_data', to='sswg.basicform', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='basic_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_details', to='sswg.basicform', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='mocsdata',
            name='basic_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mocs_data', to='sswg.basicform', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='smrcdata',
            name='basic_form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smrc_data', to='sswg.basicform', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='ssmodata',
            name='basic_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssmo_data', to='sswg.basicform', verbose_name='SSWG Basic Form'),
        ),
    ]
