# Generated by Django 5.0.2 on 2025-02-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0005_alter_basicform_options_alter_companydetails_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smrcdata',
            name='code',
            field=models.CharField(default=1, max_length=20, verbose_name='code'),
            preserve_default=False,
        ),
    ]
