# Generated by Django 5.0.2 on 2025-02-20 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_travel', '0038_alter_lkpstatedetails_reexport_next_serial_no_and_more'),
        ('sswg', '0006_smrcdata_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smrcdata',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_travel.appmovegold', verbose_name='Move Gold'),
        ),
    ]
