# Generated by Django 5.0.2 on 2025-02-21 17:56

import django.db.models.deletion
import sswg.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0007_basicform_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbsdata',
            name='basic_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cbs_data', to='sswg.basicform', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='basic_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company_details', to='sswg.basicform', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='mocsdata',
            name='basic_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mocs_data', to='sswg.basicform', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='smrcdata',
            name='basic_form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smrc_data', to='sswg.basicform', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='ssmodata',
            name='basic_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ssmo_data', to='sswg.basicform', verbose_name='SSWG Basic Form'),
        ),
        migrations.CreateModel(
            name='MmAceptanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('mm_aceptance_file', models.FileField(upload_to=sswg.models.MmAceptanceData.attachment_path, verbose_name='Ministry of Minerals Acceptance File')),
                ('basic_form', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mm_aceptance_data', to='sswg.basicform', verbose_name='SSWG Basic Form')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'SSWG MmAceptanceData',
                'verbose_name_plural': 'SSWG MmAceptanceData',
            },
        ),
        migrations.CreateModel(
            name='SmrcNoObjectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('smrc_no_objection_file', models.FileField(upload_to=sswg.models.SmrcNoObjectionData.attachment_path, verbose_name='SMRC No Objection File')),
                ('basic_form', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='smrc_no_objection_data', to='sswg.basicform', verbose_name='SSWG Basic Form')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'SSWG SmrcNoObjectionData',
                'verbose_name_plural': 'SSWG SmrcNoObjectionData',
            },
        ),
    ]
