# Generated by Django 5.0.2 on 2025-02-20 21:26

import sswg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0008_basicform_created_at_basicform_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smrcdata',
            name='attachement_file',
            field=models.FileField(default='', upload_to=sswg.models.SMRCData.attachement_path, verbose_name='attachement_file'),
            preserve_default=False,
        ),
    ]
