# Generated by Django 5.0.2 on 2025-02-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0009_rename_smrcdata_transferrelocationformdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbsdata',
            name='issued_amount',
        ),
    ]
