# Generated by Django 5.0.2 on 2025-02-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0009_alter_smrcdata_attachement_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smrcdata',
            old_name='code',
            new_name='form',
        ),
    ]
