# Generated by Django 5.0.2 on 2025-02-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0010_remove_cbsdata_issued_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbsdata',
            name='issued_amount',
            field=models.FloatField(default=0, verbose_name='Issued Amount'),
            preserve_default=False,
        ),
    ]
