# Generated by Django 5.0.2 on 2025-02-20 22:10

import sswg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0011_alter_cbsdata_options_alter_companydetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbsdata',
            name='attachement_file',
            field=models.FileField(default='', upload_to=sswg.models.CBSData.attachement_path, verbose_name='attachement_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mocsdata',
            name='attachement_file',
            field=models.FileField(default='', upload_to=sswg.models.MOCSData.attachement_path, verbose_name='attachement_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smrcdata',
            name='attachement_file',
            field=models.FileField(default='', upload_to=sswg.models.SMRCData.attachement_path, verbose_name='attachement_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ssmodata',
            name='attachement_file',
            field=models.FileField(default='', upload_to=sswg.models.SSMOData.attachement_path, verbose_name='ssmo_file'),
            preserve_default=False,
        ),
    ]
