# Generated by Django 5.0.2 on 2025-02-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0011_cbsdata_issued_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrelocationformdata',
            name='basic_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smrc_data', to='sswg.basicform', verbose_name='SSWG Basic Form'),
        ),
    ]
