# Generated by Django 5.0.2 on 2025-02-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0012_alter_transferrelocationformdata_basic_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbsdata',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'دفع مقدم'), ('transfer', 'تحويل انصبة')], max_length=20, verbose_name='Payment Method'),
        ),
    ]
