# Generated by Django 5.1.7 on 2025-04-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0013_alter_cbsdata_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='surrogate_id_phone',
            field=models.CharField(max_length=50, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='surrogate_id_val',
            field=models.CharField(max_length=50, verbose_name='ID Value'),
        ),
    ]
