# Generated by Django 5.1.7 on 2025-05-24 08:45

import django.db.models.deletion
import sswg.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0014_alter_companydetails_surrogate_id_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocsdata',
            name='mocs2_file',
        ),
        migrations.CreateModel(
            name='COCSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('cocs_file', models.FileField(upload_to=sswg.models.COCSData.attachment_path, verbose_name='mocs2_file')),
                ('basic_form', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coc_data', to='sswg.basicform', verbose_name='SSWG Basic Form')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
