# Generated by Django 5.1.7 on 2025-05-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0015_remove_mocsdata_mocs2_file_cocsdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocsdata',
            options={'verbose_name': 'الغرفة التجارية', 'verbose_name_plural': 'الغرفة التجارية'},
        ),
        migrations.AlterField(
            model_name='basicform',
            name='state',
            field=models.IntegerField(choices=[(1, 'SSWG State 1'), (2, 'SSWG State 2'), (3, 'SSWG State 3'), (4, 'SSWG State 4'), (5, 'SSWG State 5'), (6, 'SSWG State 6'), (7, 'SSWG State 7'), (8, 'SSWG State 8'), (9, 'SSWG State 9'), (10, 'SSWG State 10'), (11, 'SSWG State 11')], default=1, verbose_name='record_state'),
        ),
    ]
