# Generated by Django 5.1.7 on 2025-05-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0016_alter_cocsdata_options_alter_basicform_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='العدد الكلي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetails',
            name='total_weight',
            field=models.FloatField(default=0, verbose_name='الوزن الكلي'),
            preserve_default=False,
        ),
    ]
