# Generated by Django 5.1.7 on 2025-05-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0017_companydetails_total_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='العدد الكلي'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='total_weight',
            field=models.FloatField(default=0, verbose_name='الوزن الكلي'),
        ),
    ]
