# Generated by Django 5.1.7 on 2025-05-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0018_alter_companydetails_total_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='عدد الاستمارات'),
        ),
    ]
