# Generated by Django 5.1.7 on 2025-05-25 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0021_alter_companydetails_basic_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssmodata',
            name='return_weight',
            field=models.FloatField(default=0, help_text='في حال التصنيع والإعادة', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='الذهب الراجع'),
        ),
    ]
