# Generated by Django 5.1.7 on 2025-05-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0022_ssmodata_return_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='عدد السبائك'),
        ),
    ]
