# Generated by Django 5.1.7 on 2025-05-26 07:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0023_alter_companydetails_total_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasicForm',
            new_name='BasicFormExport',
        ),
    ]
