# Generated by Django 5.1.7 on 2025-05-26 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0024_rename_basicform_basicformexport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicformexport',
            options={'ordering': ['-date'], 'verbose_name': 'ترحيل ذهب صادر', 'verbose_name_plural': 'رحيل ذهب صادر'},
        ),
        migrations.CreateModel(
            name='BasicFormReExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('date', models.DateField(verbose_name='Form Date')),
                ('sn_no', models.CharField(max_length=15, unique=True, verbose_name='Serial Number')),
                ('state', models.IntegerField(choices=[(1, 'SSWG State 1'), (2, 'SSWG State 2'), (3, 'SSWG State 3'), (4, 'SSWG State 4'), (5, 'SSWG State 5'), (6, 'SSWG State 6'), (7, 'SSWG State 7'), (8, 'SSWG State 8'), (9, 'SSWG State 9'), (10, 'SSWG State 10'), (11, 'SSWG State 11')], default=1, verbose_name='record_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'ترحيل ذهب صادر بغرض التصنيع وإعادة التصنيع',
                'verbose_name_plural': 'ترحيل ذهب صادر بغرض التصنيع وإعادة التصنيع',
                'ordering': ['-date'],
            },
        ),
    ]
