# Generated by Django 5.1.7 on 2025-05-26 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0025_alter_basicformexport_options_basicformreexport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbsdata',
            old_name='basic_form',
            new_name='basic_form_export',
        ),
        migrations.RenameField(
            model_name='cocsdata',
            old_name='basic_form',
            new_name='basic_form_export',
        ),
        migrations.RenameField(
            model_name='mmaceptancedata',
            old_name='basic_form',
            new_name='basic_form_export',
        ),
        migrations.RenameField(
            model_name='mocsdata',
            old_name='basic_form',
            new_name='basic_form_export',
        ),
        migrations.RenameField(
            model_name='smrcnoobjectiondata',
            old_name='basic_form',
            new_name='basic_form_export',
        ),
        migrations.RenameField(
            model_name='ssmodata',
            old_name='basic_form',
            new_name='basic_form_export',
        ),
        migrations.RenameField(
            model_name='transferrelocationformdata',
            old_name='basic_form',
            new_name='basic_form_export',
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='basic_form',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='basic_form_export',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_details', to='sswg.basicformexport', verbose_name='SSWG Basic Form'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='basic_form_reexport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_details', to='sswg.basicformreexport', verbose_name='SSWG Basic Form'),
        ),
        migrations.CreateModel(
            name='BasicFormSilver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('date', models.DateField(verbose_name='Form Date')),
                ('sn_no', models.CharField(max_length=15, unique=True, verbose_name='Serial Number')),
                ('state', models.IntegerField(choices=[(1, 'SSWG State 1'), (2, 'SSWG State 2'), (3, 'SSWG State 3'), (4, 'SSWG State 4'), (5, 'SSWG State 5'), (6, 'SSWG State 6'), (7, 'SSWG State 7'), (8, 'SSWG State 8'), (9, 'SSWG State 9'), (10, 'SSWG State 10'), (11, 'SSWG State 11')], default=1, verbose_name='record_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'ترحيل فضة صادر',
                'verbose_name_plural': 'ترحيل فضة صادر',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='companydetails',
            name='basic_form_silver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_details', to='sswg.basicformsilver', verbose_name='SSWG Basic Form'),
        ),
    ]
