# Generated by Django 5.1.7 on 2025-05-26 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0027_cbsdata_basic_form_reexport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbsdata',
            name='basic_form_reexport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cbs_data_reexport', to='sswg.basicformreexport', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='cbsdata',
            name='basic_form_silver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cbs_data_silver', to='sswg.basicformsilver', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='cocsdata',
            name='basic_form_reexport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coc_data_reexport', to='sswg.basicformreexport', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='cocsdata',
            name='basic_form_silver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coc_data_silver', to='sswg.basicformsilver', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='mmaceptancedata',
            name='basic_form_reexport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mm_aceptance_data_reexport', to='sswg.basicformreexport', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='mmaceptancedata',
            name='basic_form_silver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mm_aceptance_data_silver', to='sswg.basicformsilver', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='mocsdata',
            name='basic_form_reexport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mocs_data_reexport', to='sswg.basicformreexport', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='mocsdata',
            name='basic_form_silver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mocs_data_silver', to='sswg.basicformsilver', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='smrcnoobjectiondata',
            name='basic_form_reexport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smrc_no_objection_data_reexport', to='sswg.basicformreexport', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='smrcnoobjectiondata',
            name='basic_form_silver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smrc_no_objection_data_silver', to='sswg.basicformsilver', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='ssmodata',
            name='basic_form_reexport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ssmo_data_reexport', to='sswg.basicformreexport', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='ssmodata',
            name='basic_form_silver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ssmo_data_silver', to='sswg.basicformsilver', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='transferrelocationformdata',
            name='basic_form_reexport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smrc_data_reexport', to='sswg.basicformreexport', verbose_name='SSWG Basic Form'),
        ),
        migrations.AlterField(
            model_name='transferrelocationformdata',
            name='basic_form_silver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smrc_data_silver', to='sswg.basicformsilver', verbose_name='SSWG Basic Form'),
        ),
    ]
