# Generated by Django 5.1.7 on 2025-05-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0028_alter_cbsdata_basic_form_reexport_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicformexport',
            options={'ordering': ['-date'], 'verbose_name': 'ترحيل ذهب صادر', 'verbose_name_plural': 'ترحيل ذهب صادر'},
        ),
    ]
