# Generated by Django 5.2.1 on 2025-05-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0029_alter_basicformexport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocsdata',
            name='contract_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contract Expiration Date'),
        ),
    ]
