# Generated by Django 5.2.1 on 2025-05-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0030_alter_mocsdata_contract_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbsdata',
            name='commercial_bank_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Commercial Bank Name'),
        ),
    ]
