# Generated by Django 5.2.1 on 2025-05-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0031_alter_cbsdata_commercial_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbsdata',
            name='customer_account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Customer Account Number'),
        ),
    ]
