# Generated by Django 5.2.1 on 2025-05-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0032_alter_cbsdata_customer_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmaceptancedata',
            name='cert_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الشهادة'),
        ),
        migrations.AddField(
            model_name='smrcnoobjectiondata',
            name='cert_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الشهادة'),
        ),
    ]
