# Generated by Django 5.2.1 on 2025-05-31 15:24

import sswg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0033_mmaceptancedata_cert_no_smrcnoobjectiondata_cert_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmaceptancedata',
            name='mm_aceptance_file',
            field=models.FileField(blank=True, null=True, upload_to=sswg.models.MmAceptanceData.attachment_path, verbose_name='Ministry of Minerals Acceptance File'),
        ),
        migrations.AlterField(
            model_name='smrcnoobjectiondata',
            name='smrc_no_objection_file',
            field=models.FileField(blank=True, null=True, upload_to=sswg.models.SmrcNoObjectionData.attachment_path, verbose_name='SMRC No Objection File'),
        ),
    ]
