# Generated by Django 5.2.1 on 2025-06-01 06:39

import sswg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0034_alter_mmaceptancedata_mm_aceptance_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicformexport',
            options={'ordering': ['-sn_no', '-date'], 'verbose_name': 'ترحيل ذهب صادر', 'verbose_name_plural': 'ترحيل ذهب صادر'},
        ),
        migrations.AlterField(
            model_name='cbsdata',
            name='cbs_file',
            field=models.FileField(blank=True, null=True, upload_to=sswg.models.CBSData.attachment_path, verbose_name='cbs_file'),
        ),
        migrations.AlterField(
            model_name='mocsdata',
            name='mocs1_file',
            field=models.FileField(blank=True, null=True, upload_to=sswg.models.MOCSData.attachment_path, verbose_name='mocs1_file'),
        ),
    ]
