# Generated by Django 5.2.1 on 2025-06-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0035_alter_basicformexport_options_alter_cbsdata_cbs_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicformreexport',
            options={'ordering': ['-sn_no', '-date'], 'verbose_name': 'ترحيل ذهب صادر بغرض التصنيع وإعادة التصنيع', 'verbose_name_plural': 'ترحيل ذهب صادر بغرض التصنيع وإعادة التصنيع'},
        ),
        migrations.AlterModelOptions(
            name='basicformsilver',
            options={'ordering': ['-sn_no', '-date'], 'verbose_name': 'ترحيل فضة صادر', 'verbose_name_plural': 'ترحيل فضة صادر'},
        ),
    ]
