# Generated by Django 5.2.1 on 2025-06-01 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0036_alter_basicformreexport_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicformexport',
            options={'ordering': ['-sn_no', '-date'], 'verbose_name': 'صادر ذهب حر', 'verbose_name_plural': 'صادر ذهب حر'},
        ),
        migrations.AlterModelOptions(
            name='basicformreexport',
            options={'ordering': ['-sn_no', '-date'], 'verbose_name': 'صادر ذهب بغرض التصنيع وإعادة التصنيع', 'verbose_name_plural': 'صادر ذهب بغرض التصنيع وإعادة التصنيع'},
        ),
        migrations.AlterModelOptions(
            name='basicformsilver',
            options={'ordering': ['-sn_no', '-date'], 'verbose_name': 'صادر فضة', 'verbose_name_plural': 'صادر فضة'},
        ),
        migrations.CreateModel(
            name='BasicFormExportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('date', models.DateField(verbose_name='Form Date')),
                ('sn_no', models.CharField(max_length=15, unique=True, verbose_name='Serial Number')),
                ('state', models.IntegerField(choices=[(1, 'SSWG State 1'), (2, 'SSWG State 2'), (3, 'SSWG State 3'), (4, 'SSWG State 4'), (5, 'SSWG State 5'), (6, 'SSWG State 6'), (7, 'SSWG State 7'), (8, 'SSWG State 8'), (9, 'SSWG State 9'), (10, 'SSWG State 10'), (11, 'SSWG State 11')], default=1, verbose_name='record_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'صادر ذهب شركات امتياز',
                'verbose_name_plural': 'صادر ذهب شركات امتياز',
                'ordering': ['-sn_no', '-date'],
            },
        ),
        migrations.AddField(
            model_name='cbsdata',
            name='basic_form_export_emtiaz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cbs_data_export_emtiaz', to='sswg.basicformexportcompany', verbose_name='SSWG Basic Form'),
        ),
        migrations.AddField(
            model_name='cocsdata',
            name='basic_form_export_emtiaz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coc_data_export_emtiaz', to='sswg.basicformexportcompany', verbose_name='SSWG Basic Form'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='basic_form_export_emtiaz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_details_export_emtiaz', to='sswg.basicformexportcompany', verbose_name='SSWG Basic Form'),
        ),
        migrations.AddField(
            model_name='mmaceptancedata',
            name='basic_form_export_emtiaz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mm_aceptance_data_export_emtiaz', to='sswg.basicformexportcompany', verbose_name='SSWG Basic Form'),
        ),
        migrations.AddField(
            model_name='mocsdata',
            name='basic_form_export_emtiaz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mocs_data_export_emtiaz', to='sswg.basicformexportcompany', verbose_name='SSWG Basic Form'),
        ),
        migrations.AddField(
            model_name='smrcnoobjectiondata',
            name='basic_form_export_emtiaz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smrc_no_objection_data_export_emtiaz', to='sswg.basicformexportcompany', verbose_name='SSWG Basic Form'),
        ),
        migrations.AddField(
            model_name='ssmodata',
            name='basic_form_export_emtiaz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ssmo_data_export_emtiaz', to='sswg.basicformexportcompany', verbose_name='SSWG Basic Form'),
        ),
        migrations.AddField(
            model_name='transferrelocationformdata',
            name='basic_form_export_emtiaz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smrc_data_export_emtiaz', to='sswg.basicformexportcompany', verbose_name='SSWG Basic Form'),
        ),
    ]
