# Generated by Django 5.2.1 on 2025-06-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0039_companydetailsemtiaz_alloy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetailsemtiaz',
            name='travel_cert_no',
            field=models.CharField(default='-', max_length=50, verbose_name='رقم استمارة الترحيل'),
            preserve_default=False,
        ),
    ]
