# Generated by Django 5.2.1 on 2025-06-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswg', '0041_alter_basicformexport_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedteamdata',
            name='destination',
            field=models.CharField(max_length=150, verbose_name='وجهة الرحلة'),
        ),
    ]
