# Generated by Django 5.2.7 on 2026-07-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateField()),
                ('companyid', models.IntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('produced_gold', models.DecimalField(decimal_places=4, max_digits=18)),
                ('pure_gold', models.DecimalField(decimal_places=4, max_digits=18)),
                ('deduction_weight', models.DecimalField(decimal_places=4, max_digits=18)),
                ('net_weight', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                'db_table': 'deductions_view',
                'ordering': ['-tdate'],
                'managed': False,
            },
        ),
    ]
