# Generated by Django 5.0.2 on 2024-03-26 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0062_alter_appgoldproductiondetail_melt_added_gold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LkpItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='item_name')),
            ],
        ),
        migrations.CreateModel(
            name='TblCompanyCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('currency', models.CharField(choices=[('sdg', 'entaj'), ('euro', 'mokhalfat')], default='euro', max_length=10, verbose_name='currency')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa.lkpitem', verbose_name='item')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Financial commitment',
                'verbose_name_plural': 'Financial commitments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TblCompanyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('from_dt', models.DateField(verbose_name='from_dt')),
                ('to_dt', models.DateField(verbose_name='to_dt')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('currency', models.CharField(choices=[('sdg', 'entaj'), ('euro', 'mokhalfat')], default='euro', max_length=10, verbose_name='currency')),
                ('payment_state', models.CharField(choices=[('no', 'no_payment'), ('partial', 'partial_payment'), ('full', 'full_payment')], default='no', max_length=10, verbose_name='payment_state')),
                ('commitement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa.tblcompanycommitment', verbose_name='commitement')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Financial request',
                'verbose_name_plural': 'Financial requests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TblCompanyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('payment_dt', models.DateField(verbose_name='payment_dt')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('currency', models.CharField(choices=[('sdg', 'entaj'), ('euro', 'mokhalfat')], default='euro', max_length=10, verbose_name='currency')),
                ('excange_rate', models.FloatField(verbose_name='excange_rate')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa.tblcompanyrequest', verbose_name='commitement')),
            ],
            options={
                'verbose_name': 'Financial payment',
                'verbose_name_plural': 'Financial payments',
                'ordering': ['-id'],
            },
        ),
    ]
