# Generated by Django 5.0.2 on 2024-04-22 21:26

import django.db.models.deletion
import pa.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0063_tblcompanyproductionlicense_mineral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LkpItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='item_name')),
                ('company_type', models.CharField(choices=[('entaj', 'entaj'), ('mokhalfat', 'mokhalfat'), ('emtiaz', 'emtiaz'), ('sageer', 'sageer')], max_length=15, verbose_name='company_type')),
            ],
        ),
        migrations.CreateModel(
            name='TblCompanyCommitmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('currency', models.CharField(choices=[('sdg', 'sdg'), ('euro', 'euro')], default='euro', max_length=10, verbose_name='currency')),
                ('state', models.CharField(choices=[('draft', 'draft'), ('confirm', 'confirm')], default='draft', max_length=10, verbose_name='record_state')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Financial commitment',
                'verbose_name_plural': 'Financial commitments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TblCompanyCommitmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa.lkpitem', verbose_name='financial item')),
                ('commitment_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa.tblcompanycommitmentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TblCompanyCommitmentSchedular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('request_interval', models.CharField(choices=[('manual', 'manual'), ('year', 'yearly')], default='manual', max_length=10, verbose_name='interval')),
                ('request_next_interval_dt', models.DateField(blank=True, null=True, verbose_name='next_interval_dt')),
                ('request_auto_confirm', models.BooleanField(default=False, verbose_name='request_auto_confirm')),
                ('commitment_master', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commitment_schedular', to='pa.tblcompanycommitmentmaster')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TblCompanyPaymentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('payment_dt', models.DateField(verbose_name='payment_dt')),
                ('currency', models.CharField(choices=[('sdg', 'sdg'), ('euro', 'euro')], default='euro', max_length=10, verbose_name='currency')),
                ('exchange_rate', models.FloatField(default=1, validators=[pa.models.validate_positive], verbose_name='exchange_rate')),
                ('state', models.CharField(choices=[('draft', 'draft'), ('confirm', 'confirm')], default='draft', max_length=10, verbose_name='record_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Financial payment',
                'verbose_name_plural': 'Financial payments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TblCompanyPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa.lkpitem', verbose_name='financial item')),
                ('payment_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa.tblcompanypaymentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TblCompanyRequestMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('from_dt', models.DateField(verbose_name='from_dt')),
                ('to_dt', models.DateField(verbose_name='to_dt')),
                ('currency', models.CharField(choices=[('sdg', 'sdg'), ('euro', 'euro')], default='euro', max_length=10, verbose_name='currency')),
                ('payment_state', models.CharField(choices=[('no', 'no_payment'), ('partial', 'partial_payment'), ('full', 'full_payment')], default='no', max_length=10, verbose_name='payment_state')),
                ('state', models.CharField(choices=[('draft', 'draft'), ('confirm', 'confirm')], default='draft', max_length=10, verbose_name='record_state')),
                ('commitement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa.tblcompanycommitmentmaster', verbose_name='commitement')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Financial request',
                'verbose_name_plural': 'Financial requests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TblCompanyRequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa.lkpitem', verbose_name='financial item')),
                ('request_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa.tblcompanyrequestmaster')),
            ],
        ),
        migrations.AddField(
            model_name='tblcompanypaymentmaster',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa.tblcompanyrequestmaster', verbose_name='request'),
        ),
        migrations.AddIndex(
            model_name='tblcompanycommitmentmaster',
            index=models.Index(fields=['company'], name='pa_tblcompa_company_f1bd7e_idx'),
        ),
        migrations.AddIndex(
            model_name='tblcompanyrequestmaster',
            index=models.Index(fields=['commitement'], name='pa_tblcompa_commite_c6af7d_idx'),
        ),
        migrations.AddIndex(
            model_name='tblcompanypaymentmaster',
            index=models.Index(fields=['request'], name='pa_tblcompa_request_33fcbb_idx'),
        ),
    ]
