# Generated by Django 5.0.2 on 2024-03-27 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanycommitment',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('confirm', 'confirm')], default='draft', max_length=10, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='tblcompanypayment',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('confirm', 'confirm')], default='draft', max_length=10, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='tblcompanyrequest',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('confirm', 'confirm')], default='draft', max_length=10, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='tblcompanycommitment',
            name='currency',
            field=models.CharField(choices=[('sdg', 'sdg'), ('euro', 'euro')], default='euro', max_length=10, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='tblcompanycommitment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa.lkpitem', verbose_name='financial item'),
        ),
        migrations.AlterField(
            model_name='tblcompanypayment',
            name='currency',
            field=models.CharField(choices=[('sdg', 'sdg'), ('euro', 'euro')], default='euro', max_length=10, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='tblcompanypayment',
            name='excange_rate',
            field=models.FloatField(default=1, verbose_name='excange_rate'),
        ),
        migrations.AlterField(
            model_name='tblcompanyrequest',
            name='currency',
            field=models.CharField(choices=[('sdg', 'sdg'), ('euro', 'euro')], default='euro', max_length=10, verbose_name='currency'),
        ),
    ]
