# Generated by Django 5.0.2 on 2024-04-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblcompanycommitmentschedular',
            old_name='commitment_master',
            new_name='commitment',
        ),
    ]
