# Generated by Django 5.0.2 on 2024-04-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0002_rename_commitment_master_tblcompanycommitmentschedular_commitment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcompanycommitmentdetail',
            name='amount',
        ),
        migrations.AddField(
            model_name='lkpitem',
            name='calculation_method',
            field=models.CharField(choices=[('fixed_value', 'fixed_value'), ('area_km', 'area_km'), ('no_contracts', 'no_contracts')], default='fixed_value', max_length=20, verbose_name='calculation_method'),
        ),
        migrations.AddField(
            model_name='tblcompanycommitmentdetail',
            name='amount_factor',
            field=models.FloatField(default=1, verbose_name='amount_factor'),
            preserve_default=False,
        ),
    ]
