# Generated by Django 5.0.2 on 2024-04-23 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0003_remove_tblcompanycommitmentdetail_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tblcompanyrequestmaster',
            name='pa_tblcompa_commite_c6af7d_idx',
        ),
        migrations.RemoveField(
            model_name='tblcompanyrequestmaster',
            name='commitement',
        ),
        migrations.AddField(
            model_name='tblcompanyrequestmaster',
            name='commitment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='pa.tblcompanycommitmentmaster', verbose_name='commitment'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='tblcompanyrequestmaster',
            index=models.Index(fields=['commitment'], name='pa_tblcompa_commitm_76aa84_idx'),
        ),
    ]
