# Generated by Django 5.0.2 on 2024-03-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0003_tblcompanycommitment_request_auto_confirm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanycommitment',
            name='request_next_interval_dt',
            field=models.DateField(blank=True, null=True, verbose_name='next_interval_dt'),
        ),
    ]
