# Generated by Django 5.0.2 on 2024-03-30 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0062_alter_appgoldproductiondetail_melt_added_gold_and_more'),
        ('pa', '0004_alter_tblcompanycommitment_request_next_interval_dt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblcompanycommitment',
            unique_together={('company', 'item')},
        ),
    ]
