# Generated by Django 5.0.2 on 2024-04-23 14:12

import django.db.models.deletion
import pa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0004_remove_tblcompanyrequestmaster_pa_tblcompa_commite_c6af7d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LkpPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='payment_method_name')),
            ],
            options={
                'verbose_name': 'Payment method',
                'verbose_name_plural': 'Payment method',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='lkpitem',
            options={'ordering': ['id'], 'verbose_name': 'Financial item', 'verbose_name_plural': 'Financial items'},
        ),
        migrations.AlterModelOptions(
            name='tblcompanycommitmentschedular',
            options={'ordering': ['-id'], 'verbose_name': 'Financial commitment schedular', 'verbose_name_plural': 'Financial commitment schedulars'},
        ),
        migrations.AlterField(
            model_name='tblcompanycommitmentschedular',
            name='commitment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commitment_schedular', to='pa.tblcompanycommitmentmaster', verbose_name='commitment'),
        ),
        migrations.CreateModel(
            name='TblCompanyPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('ref_key', models.CharField(max_length=50, verbose_name='reference_key')),
                ('attachement_file', models.FileField(upload_to=pa.models.TblCompanyPaymentMethod.attachement_path, verbose_name='attachement_file')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa.lkppaymentmethod', verbose_name='Payment method')),
                ('payment_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa.tblcompanypaymentmaster')),
            ],
        ),
    ]
