# Generated by Django 5.0.2 on 2024-03-30 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0062_alter_appgoldproductiondetail_melt_added_gold_and_more'),
        ('pa', '0005_alter_tblcompanycommitment_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblcompanycommitment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tblcompanycommitment',
            constraint=models.UniqueConstraint(fields=('company', 'item'), name='unique_commitment'),
        ),
    ]
