# Generated by Django 5.0.2 on 2024-04-23 14:51

import pa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0005_lkppaymentmethod_alter_lkpitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanypaymentmaster',
            name='exchange_attachement_file',
            field=models.FileField(default='', upload_to=pa.models.TblCompanyPaymentMaster.attachement_path, verbose_name='exchange_attachement_file'),
            preserve_default=False,
        ),
    ]
