# Generated by Django 5.0.2 on 2024-04-23 14:53

import pa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0006_tblcompanypaymentmaster_exchange_attachement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanypaymentmaster',
            name='exchange_attachement_file',
            field=models.FileField(blank=True, upload_to=pa.models.TblCompanyPaymentMaster.attachement_path, verbose_name='exchange_attachement_file'),
        ),
    ]
