# Generated by Django 5.0.2 on 2024-03-30 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0062_alter_appgoldproductiondetail_melt_added_gold_and_more'),
        ('pa', '0006_alter_tblcompanycommitment_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tblcompanycommitment',
            index=models.Index(fields=['company', 'item'], name='pa_tblcompa_company_9f7b37_idx'),
        ),
        migrations.AddIndex(
            model_name='tblcompanycommitment',
            index=models.Index(fields=['company'], name='pa_tblcompa_company_fc89bf_idx'),
        ),
        migrations.AddIndex(
            model_name='tblcompanycommitment',
            index=models.Index(fields=['item'], name='pa_tblcompa_item_id_c267b1_idx'),
        ),
    ]
