# Generated by Django 5.0.2 on 2024-04-23 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0007_alter_tblcompanypaymentmaster_exchange_attachement_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblCompanyRequestReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_dt', models.DateField(verbose_name='receive_dt')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='receiver_name')),
                ('request_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pa.tblcompanyrequestmaster')),
            ],
        ),
    ]
