# Generated by Django 5.0.2 on 2024-03-30 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0007_tblcompanycommitment_pa_tblcompa_company_9f7b37_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tblcompanypayment',
            index=models.Index(fields=['request'], name='pa_tblcompa_request_beeb69_idx'),
        ),
        migrations.AddIndex(
            model_name='tblcompanyrequest',
            index=models.Index(fields=['commitement'], name='pa_tblcompa_commite_999e5f_idx'),
        ),
    ]
