# Generated by Django 5.0.2 on 2024-04-02 21:52

import pa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0008_tblcompanypayment_pa_tblcompa_request_beeb69_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcompanypayment',
            name='excange_rate',
        ),
        migrations.AddField(
            model_name='tblcompanypayment',
            name='exchange_rate',
            field=models.FloatField(default=1, validators=[pa.models.validate_positive], verbose_name='exchange_rate'),
        ),
    ]
