# Generated by Django 5.0.2 on 2024-04-24 16:27

import pa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0008_tblcompanyrequestreceive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcompanycommitmentdetail',
            options={'ordering': ['id'], 'verbose_name': 'Financial commitment detail', 'verbose_name_plural': 'Financial commitment details'},
        ),
        migrations.AddField(
            model_name='tblcompanycommitmentschedular',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('confirm', 'confirm')], default='draft', max_length=10, verbose_name='record_state'),
        ),
        migrations.AlterField(
            model_name='tblcompanypaymentmethod',
            name='attachement_file',
            field=models.FileField(blank=True, upload_to=pa.models.TblCompanyPaymentMethod.attachement_path, verbose_name='attachement_file'),
        ),
        migrations.AlterField(
            model_name='tblcompanypaymentmethod',
            name='ref_key',
            field=models.CharField(blank=True, max_length=50, verbose_name='reference_key'),
        ),
    ]
