# Generated by Django 5.0.2 on 2024-04-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0009_remove_tblcompanypayment_excange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkpitem',
            name='company_type',
            field=models.CharField(choices=[('entaj', 'entaj'), ('mokhalfat', 'mokhalfat'), ('emtiaz', 'emtiaz'), ('sageer', 'sageer')], default='emtiaz', max_length=15, verbose_name='company_type'),
            preserve_default=False,
        ),
    ]
