# Generated by Django 5.0.2 on 2024-04-30 13:19

import pa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0009_alter_tblcompanycommitmentdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanypaymentmethod',
            name='attachement_file',
            field=models.FileField(upload_to=pa.models.TblCompanyPaymentMethod.attachement_path, verbose_name='attachement_file'),
        ),
        migrations.AlterField(
            model_name='tblcompanypaymentmethod',
            name='ref_key',
            field=models.CharField(max_length=50, verbose_name='reference_key'),
        ),
    ]
