# Generated by Django 5.0.2 on 2024-04-30 20:21

import pa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0010_alter_tblcompanypaymentmethod_attachement_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanypaymentdetail',
            name='attachement_file',
            field=models.FileField(blank=True, upload_to=pa.models.TblCompanyPaymentDetail.attachement_path, verbose_name='attachement_file'),
        ),
        migrations.AddField(
            model_name='tblcompanyrequestdetail',
            name='attachement_file',
            field=models.FileField(blank=True, upload_to=pa.models.TblCompanyRequestDetail.attachement_path, verbose_name='attachement_file'),
        ),
    ]
