# Generated by Django 5.0.2 on 2024-05-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0012_alter_tblcompanycommitmentmaster_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcompanyopenningbalancedetail',
            name='amount_factor',
        ),
        migrations.AddField(
            model_name='tblcompanyopenningbalancedetail',
            name='amount',
            field=models.FloatField(default=0, verbose_name='amount'),
            preserve_default=False,
        ),
    ]
