# Generated by Django 5.0.2 on 2024-05-05 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0065_alter_appaddarea_company_alter_appaddarea_created_by_and_more'),
        ('pa', '0015_alter_tblcompanycommitmentmaster_license'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanycommitmentdetail',
            name='commitment_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa.tblcompanycommitmentmaster'),
        ),
        migrations.AlterField(
            model_name='tblcompanycommitmentdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa.lkpitem', verbose_name='financial item'),
        ),
        migrations.AlterField(
            model_name='tblcompanycommitmentmaster',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='tblcompanycommitmentmaster',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanycommitmentmaster',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproductionlicense', verbose_name='license'),
        ),
        migrations.AlterField(
            model_name='tblcompanycommitmentmaster',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanycommitmentschedular',
            name='commitment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_schedular', to='pa.tblcompanycommitmentmaster', verbose_name='commitment'),
        ),
        migrations.AlterField(
            model_name='tblcompanycommitmentschedular',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanycommitmentschedular',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanyopenningbalancedetail',
            name='commitment_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa.tblcompanyopenningbalancemaster'),
        ),
        migrations.AlterField(
            model_name='tblcompanyopenningbalancedetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa.lkpitem', verbose_name='financial item'),
        ),
        migrations.AlterField(
            model_name='tblcompanyopenningbalancemaster',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.tblcompanyproduction', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='tblcompanyopenningbalancemaster',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanyopenningbalancemaster',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanypaymentdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa.lkpitem', verbose_name='financial item'),
        ),
        migrations.AlterField(
            model_name='tblcompanypaymentdetail',
            name='payment_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa.tblcompanypaymentmaster'),
        ),
        migrations.AlterField(
            model_name='tblcompanypaymentmaster',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanypaymentmaster',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa.tblcompanyrequestmaster', verbose_name='request'),
        ),
        migrations.AlterField(
            model_name='tblcompanypaymentmaster',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanypaymentmethod',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa.lkppaymentmethod', verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='tblcompanypaymentmethod',
            name='payment_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa.tblcompanypaymentmaster'),
        ),
        migrations.AlterField(
            model_name='tblcompanyrequestdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa.lkpitem', verbose_name='financial item'),
        ),
        migrations.AlterField(
            model_name='tblcompanyrequestdetail',
            name='request_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa.tblcompanyrequestmaster'),
        ),
        migrations.AlterField(
            model_name='tblcompanyrequestmaster',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa.tblcompanycommitmentmaster', verbose_name='commitment'),
        ),
        migrations.AlterField(
            model_name='tblcompanyrequestmaster',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanyrequestmaster',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AlterField(
            model_name='tblcompanyrequestreceive',
            name='request_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa.tblcompanyrequestmaster'),
        ),
    ]
