# Generated by Django 5.0.2 on 2024-10-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0018_remove_tblcompanypaymentdetail_attachement_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanycommitmentmaster',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='note'),
        ),
    ]
