# Generated by Django 5.0.2 on 2024-10-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0019_tblcompanycommitmentmaster_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanypaymentmaster',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='note'),
        ),
    ]
