# Generated by Django 5.1 on 2024-11-26 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0020_tblcompanypaymentmaster_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompanycommitmentdetail',
            name='commitment_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa.tblcompanycommitmentmaster'),
        ),
        migrations.AlterField(
            model_name='tblcompanyrequestdetail',
            name='request_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa.tblcompanyrequestmaster'),
        ),
    ]
