# Generated by Django 5.2.1 on 2025-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0021_alter_tblcompanycommitmentdetail_commitment_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanycommitmentmaster',
            name='_cached_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
