# Generated by Django 5.2.7 on 2026-04-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0023_alter_tblcompanycommitmentmaster__cached_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lkpitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='item_name'),
        ),
        migrations.AlterField(
            model_name='tblcompanypaymentmethod',
            name='ref_key',
            field=models.CharField(max_length=100, verbose_name='reference_key'),
        ),
        migrations.AlterField(
            model_name='tblcompanyrequestreceive',
            name='receiver_name',
            field=models.CharField(max_length=100, verbose_name='receiver_name'),
        ),
    ]
