# Generated by Django 5.2.7 on 2026-04-26 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0024_alter_lkpitem_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompanypaymentmaster',
            name='odoo_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Odoo ID'),
        ),
        migrations.AddField(
            model_name='tblcompanyrequestmaster',
            name='odoo_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Odoo ID'),
        ),
        migrations.CreateModel(
            name='OdooConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('url', models.URLField(help_text='e.g. http://odoo.example.com', verbose_name='Odoo URL')),
                ('db', models.CharField(max_length=100, verbose_name='Odoo Database')),
                ('username', models.CharField(max_length=100, verbose_name='Odoo Username')),
                ('password', models.CharField(max_length=100, verbose_name='Odoo Password/API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Odoo Configuration',
                'verbose_name_plural': 'Odoo Configurations',
            },
        ),
    ]
