# Generated by Django 5.2.7 on 2026-04-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0025_tblcompanypaymentmaster_odoo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcompanypaymentmaster',
            name='odoo_id',
        ),
        migrations.RemoveField(
            model_name='tblcompanyrequestmaster',
            name='odoo_id',
        ),
    ]
