# Generated by Django 5.2.1 on 2025-08-03 14:39

import company_profile_entaj.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0131_alter_appaddarea_reject_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblCompanyEntaj',
            fields=[
            ],
            options={
                'verbose_name': 'Production Company',
                'verbose_name_plural': 'Production Companies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('company_profile.tblcompanyproduction',),
        ),
        migrations.CreateModel(
            name='ForeignerProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('procedure_from', models.DateField(help_text='Ex: 2025-01-31', verbose_name='procedure_from')),
                ('procedure_to', models.DateField(help_text='Ex: 2025-12-31', verbose_name='procedure_to')),
                ('procedure_cause', models.TextField(max_length=1000, verbose_name='procedure_cause')),
                ('state', models.IntegerField(choices=[(1, 'draft'), (2, 'تأكيد الطلب'), (3, 'اعتماد الطلب')], default=1, verbose_name='record_state')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.tblcompanyproduction', verbose_name='company')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('procedure_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpforeignerproceduretype', verbose_name='procedure_type')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Application: Foreigner procedure',
                'verbose_name_plural': 'Application: Foreigner procedure',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ForeignerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employment_history', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to=company_profile_entaj.models.company_applications_path)),
                ('state', models.IntegerField(choices=[(1, 'draft'), (2, 'تأكيد الطلب'), (3, 'اعتماد الطلب')], default=1, verbose_name='record_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreigner_company', to='company_profile_entaj.tblcompanyentaj', verbose_name='company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForeignerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('permission_type', models.CharField(choices=[('passport', 'Passport'), ('visa', 'Visa'), ('residence', 'Residence'), ('work_permit', 'Work Permit')], max_length=50)),
                ('type_id', models.CharField(max_length=50)),
                ('validity_due_date', models.DateField()),
                ('attachment', models.FileField(upload_to=company_profile_entaj.models.company_applications_path)),
                ('state', models.IntegerField(choices=[(1, 'draft'), (2, 'تأكيد الطلب'), (3, 'اعتماد الطلب')], default=1, verbose_name='record_state')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('foreigner_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='company_profile_entaj.foreignerrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
