# Generated by Django 5.2.1 on 2025-08-03 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_entaj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignerProcedureDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreigner_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_entaj.foreignerrecord')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_entaj.foreignerprocedure')),
            ],
        ),
    ]
