# Generated by Django 5.2.1 on 2025-08-03 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_entaj', '0002_foreignerproceduredetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignerProcedureApproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreigner_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_entaj.foreignerrecord', verbose_name='الاجنبي')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_entaj.foreignerprocedure')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='ForeignerProcedureOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreigner_record', models.CharField(max_length=100, verbose_name='الاجنبي')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_entaj.foreignerprocedure')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.DeleteModel(
            name='ForeignerProcedureDetails',
        ),
    ]
