# Generated by Django 5.2.1 on 2025-08-03 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0131_alter_appaddarea_reject_comments_and_more'),
        ('company_profile_entaj', '0003_foreignerprocedureapproved_foreignerprocedureother_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignerPermissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نوع الوثيقة')),
            ],
        ),
        migrations.AlterField(
            model_name='foreignerpermission',
            name='type_id',
            field=models.CharField(max_length=50, verbose_name='رقم الوثيقة'),
        ),
        migrations.AlterField(
            model_name='foreignerpermission',
            name='permission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_entaj.foreignerpermissiontype'),
        ),
        migrations.CreateModel(
            name='ForeignerProcedureRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.ManyToManyField(to='company_profile_entaj.foreignerpermissiontype')),
                ('child_procedure_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile.lkpforeignerproceduretype', verbose_name='procedure_type')),
                ('parent_procedure_type', models.ManyToManyField(related_name='+', to='company_profile.lkpforeignerproceduretype')),
            ],
        ),
    ]
