# Generated by Django 5.2.1 on 2025-08-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_entaj', '0004_foreignerpermissiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignerpermissiontype',
            name='minimum_no_months',
            field=models.IntegerField(default=0, verbose_name='نوع الوثيقة'),
        ),
    ]
