# Generated by Django 5.2.1 on 2025-08-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_entaj', '0005_foreignerpermissiontype_minimum_no_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignerprocedureother',
            name='reason',
            field=models.CharField(default='', max_length=150, verbose_name='سبب الطلب'),
            preserve_default=False,
        ),
    ]
