# Generated by Django 5.2.1 on 2025-08-04 09:31

import company_profile_entaj.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0131_alter_appaddarea_reject_comments_and_more'),
        ('company_profile_entaj', '0006_foreignerprocedureother_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foreignerprocedureapproved',
            options={'verbose_name': 'اجنبي معتمد', 'verbose_name_plural': 'اجانب معتمدين'},
        ),
        migrations.AlterModelOptions(
            name='foreignerprocedureother',
            options={'verbose_name': 'اجنبي غير مضاف في السجلات', 'verbose_name_plural': 'اجانب غير مضافين في السجلات'},
        ),
        migrations.AlterField(
            model_name='foreignerpermission',
            name='attachment',
            field=models.FileField(upload_to=company_profile_entaj.models.company_applications_path, verbose_name='مرفق الوثيقة'),
        ),
        migrations.AlterField(
            model_name='foreignerpermission',
            name='foreigner_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='company_profile_entaj.foreignerrecord'),
        ),
        migrations.AlterField(
            model_name='foreignerpermission',
            name='permission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_profile_entaj.foreignerpermissiontype', verbose_name='نوع الوثيقة'),
        ),
        migrations.AlterField(
            model_name='foreignerpermission',
            name='validity_due_date',
            field=models.DateField(verbose_name='صالحة حتى'),
        ),
        migrations.AlterField(
            model_name='foreignerprocedurerequirements',
            name='cert_type',
            field=models.ManyToManyField(to='company_profile_entaj.foreignerpermissiontype', verbose_name='الوثيقة'),
        ),
        migrations.AlterField(
            model_name='foreignerprocedurerequirements',
            name='parent_procedure_type',
            field=models.ManyToManyField(related_name='+', to='company_profile.lkpforeignerproceduretype', verbose_name='الاجراءات اللازمة'),
        ),
        migrations.AlterField(
            model_name='foreignerrecord',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=company_profile_entaj.models.company_applications_path, verbose_name='السيرة الذاتية'),
        ),
        migrations.AlterField(
            model_name='foreignerrecord',
            name='department',
            field=models.CharField(max_length=150, verbose_name='الادارة'),
        ),
        migrations.AlterField(
            model_name='foreignerrecord',
            name='employment_history',
            field=models.TextField(verbose_name='السجل الوظيفي'),
        ),
        migrations.AlterField(
            model_name='foreignerrecord',
            name='name',
            field=models.CharField(max_length=150, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='foreignerrecord',
            name='position',
            field=models.CharField(max_length=150, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='foreignerrecord',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المرتب'),
        ),
    ]
