# Generated by Django 5.2.1 on 2025-08-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_entaj', '0007_alter_foreignerprocedureapproved_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foreignerpermission',
            options={'verbose_name': 'وثائق اجنبي', 'verbose_name_plural': 'وثائق اجنبي'},
        ),
        migrations.AlterModelOptions(
            name='foreignerpermissiontype',
            options={'verbose_name': 'نوع الوثيقة', 'verbose_name_plural': 'نوع الوثيقة'},
        ),
        migrations.AlterModelOptions(
            name='foreignerprocedurerequirements',
            options={'verbose_name': 'متطلبات اجراء اجنبي', 'verbose_name_plural': 'متطلبات اجراء اجنبي'},
        ),
        migrations.AlterModelOptions(
            name='foreignerrecord',
            options={'verbose_name': 'سجل اجنبي', 'verbose_name_plural': 'سجلات اجانب'},
        ),
    ]
