# Generated by Django 5.2.1 on 2025-08-04 13:24

import company_profile_entaj.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_entaj', '0008_alter_foreignerpermission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignerpermission',
            name='attachment',
            field=models.FileField(upload_to=company_profile_entaj.models.company_applications_path_certificates, verbose_name='مرفق الوثيقة'),
        ),
        migrations.AlterField(
            model_name='foreignerpermission',
            name='foreigner_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='company_profile_entaj.foreignerrecord', verbose_name='اسم اجنبي'),
        ),
    ]
