# Generated by Django 5.2.1 on 2025-08-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0131_alter_appaddarea_reject_comments_and_more'),
        ('company_profile_entaj', '0009_alter_foreignerpermission_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignerpermissiontype',
            name='minimum_no_months',
            field=models.IntegerField(default=0, help_text='مثلاً الجواز يعتبر ساري اذا كان عدد الشهور المتبقي اكثر من 8 شهور', verbose_name='عدد الشهور الادنى لتعتبر الوثيقة سارية'),
        ),
        migrations.AlterField(
            model_name='foreignerprocedurerequirements',
            name='parent_procedure_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='company_profile.lkpforeignerproceduretype', verbose_name='الاجراءات اللازمة'),
        ),
    ]
