# Generated by Django 5.2.1 on 2025-08-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0131_alter_appaddarea_reject_comments_and_more'),
        ('company_profile_entaj', '0010_alter_foreignerpermissiontype_minimum_no_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignerprocedurerequirements',
            name='parent_procedure_type',
            field=models.ManyToManyField(blank=True, related_name='+', to='company_profile.lkpforeignerproceduretype', verbose_name='الاجراءات اللازمة'),
        ),
    ]
