# Generated by Django 5.2.1 on 2025-08-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_entaj', '0011_alter_foreignerprocedurerequirements_parent_procedure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignerrecord',
            name='employment_type',
            field=models.IntegerField(choices=[(1, 'موظف دائم'), (2, 'مقاول'), (3, 'زيارة')], default=1, verbose_name='نوع التوظيف'),
        ),
    ]
