# Generated by Django 5.2.1 on 2025-09-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_entaj', '0012_foreignerrecord_employment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreignerrecord',
            name='employment_history',
        ),
        migrations.AlterField(
            model_name='foreignerrecord',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المرتب'),
        ),
    ]
