# Generated by Django 5.2.1 on 2025-09-02 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_entaj', '0013_remove_foreignerrecord_employment_history_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignerpermissiontype',
            name='name',
            field=models.CharField(choices=[('passport', 'Passport'), ('visa', 'Visa'), ('residence', 'Residence'), ('work_permit', 'Work Permit')], max_length=50, verbose_name='نوع الوثيقة'),
        ),
        migrations.AddConstraint(
            model_name='foreignerpermission',
            constraint=models.UniqueConstraint(fields=('permission_type', 'type_id'), name='unique_permission'),
        ),
    ]
