# Generated by Django 5.2.1 on 2025-09-02 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_entaj', '0014_alter_foreignerpermissiontype_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForeignerProcedureApproved',
            new_name='ForeignerProcedurePermanent',
        ),
        migrations.RenameModel(
            old_name='ForeignerProcedureOther',
            new_name='ForeignerProcedureVisitor',
        ),
        migrations.AlterField(
            model_name='foreignerpermissiontype',
            name='name',
            field=models.CharField(choices=[('passport', 'جواز سفر'), ('employment_contract', 'عقد عمل'), ('experience_certificate', 'شهادة خبرة'), ('curriculum_vitae', 'سيرة ذاتية'), ('work_card', 'كرت عمل'), ('annual_residence', 'إقامة سنوية'), ('multiple_visa', 'تأشيرة خروج وعودة متعددة'), ('entry_visa', 'تأشيرة دخول'), ('movement_permit', 'إذن تحرك')], max_length=50, verbose_name='نوع الوثيقة'),
        ),
        migrations.RemoveConstraint(
            model_name='foreignerpermission',
            name='unique_permission',
        ),
        migrations.AddConstraint(
            model_name='foreignerpermission',
            constraint=models.UniqueConstraint(fields=('permission_type', 'type_id'), name='unique_permission', violation_error_message='الوثيقة بذات الرقم موجودة مسبقاً'),
        ),
    ]
