# Generated by Django 5.2.7 on 2026-08-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_entaj', '0015_rename_foreignerprocedureapproved_foreignerprocedurepermanent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignerpermission',
            name='security_comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='تعليق أفراد الأمن'),
        ),
        migrations.AddField(
            model_name='foreignerprocedure',
            name='security_comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='تعليق أفراد الأمن'),
        ),
        migrations.AddField(
            model_name='foreignerrecord',
            name='security_comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='تعليق أفراد الأمن'),
        ),
    ]
