# Generated by Django 5.2.7 on 2026-09-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_entaj', '0017_create_security_officer_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignerpermission',
            name='state',
            field=models.IntegerField(choices=[(1, 'draft'), (4, 'موافقة الأمن'), (2, 'تأكيد الطلب'), (3, 'اعتماد الطلب'), (5, 'رفض أمني')], default=1, verbose_name='record_state'),
        ),
        migrations.AlterField(
            model_name='foreignerprocedure',
            name='state',
            field=models.IntegerField(choices=[(1, 'draft'), (4, 'موافقة الأمن'), (2, 'تأكيد الطلب'), (3, 'اعتماد الطلب'), (5, 'رفض أمني')], default=1, verbose_name='record_state'),
        ),
        migrations.AlterField(
            model_name='foreignerrecord',
            name='state',
            field=models.IntegerField(choices=[(1, 'draft'), (4, 'موافقة الأمن'), (2, 'تأكيد الطلب'), (3, 'اعتماد الطلب'), (5, 'رفض أمني')], default=1, verbose_name='record_state'),
        ),
    ]
