# Generated by Django 5.2.7 on 2026-09-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile_entaj', '0018_alter_foreignerpermission_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreignerprocedure',
            name='security_comment',
        ),
        migrations.AlterField(
            model_name='foreignerprocedure',
            name='state',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'تأكيد الطلب'), (3, 'اعتماد الطلب')], default=1, verbose_name='record_state'),
        ),
    ]
