# Generated by Django 5.1.7 on 2025-05-12 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0114_employeebankaccount_unique_bank_account'),
        ('sandog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesolarsystem',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='solar_system_category_choice', to='hr.employeebasic', verbose_name='employee_name'),
        ),
    ]
