# Generated by Django 5.1.7 on 2025-05-12 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandog', '0002_alter_employeesolarsystem_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LkpSolarSystemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=150, verbose_name='category name')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'Solar System Category',
                'verbose_name_plural': 'Solar System Category',
            },
        ),
        migrations.AlterField(
            model_name='employeesolarsystem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sandog.lkpsolarsystemcategory', verbose_name='المجموعة'),
        ),
    ]
