# Generated by Django 5.1.7 on 2025-05-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandog', '0003_lkpsolarsystemcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lkpsolarsystemcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lkpsolarsystemcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lkpsolarsystemcategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lkpsolarsystemcategory',
            name='updated_by',
        ),
    ]
