# Generated by Django 5.0.2 on 2025-10-06 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandog', '0004_remove_lkpsolarsystemcategory_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LkpSolarSystemPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'طريقة الدفع',
                'verbose_name_plural': 'طرق الدفع',
            },
        ),
        migrations.AlterField(
            model_name='employeesolarsystem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sandog.lkpsolarsystemcategory', verbose_name='نوع المنظومة'),
        ),
        migrations.AddField(
            model_name='employeesolarsystem',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sandog.lkpsolarsystempaymentmethod', verbose_name='طريقة الدفع'),
            preserve_default=False,
        ),
    ]
