# Generated by Django 5.0.2 on 2025-10-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0122_payrolldetail_mokaf2at_2da2_fi_mokaf2_and_more'),
        ('sandog', '0005_lkpsolarsystempaymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesolarsystem',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name'),
        ),
    ]
