# Generated by Django 5.0.2 on 2025-10-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandog', '0006_alter_employeesolarsystem_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lkpsolarsystemcategory',
            options={'ordering': ['id'], 'verbose_name': 'Solar System Category', 'verbose_name_plural': 'Solar System Category'},
        ),
        migrations.AlterModelOptions(
            name='lkpsolarsystempaymentmethod',
            options={'ordering': ['id'], 'verbose_name': 'طريقة الدفع', 'verbose_name_plural': 'طرق الدفع'},
        ),
    ]
