# Generated by Django 5.2.7 on 2025-11-16 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0124_employeesalafiatsandog_and_more'),
        ('sandog', '0007_alter_lkpsolarsystemcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LkpOmraCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='طريقة التقسيط')),
            ],
            options={
                'verbose_name': 'طريقة التقسيط',
                'verbose_name_plural': 'طريقة التقسيط',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOmra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('count', models.IntegerField(default=1, verbose_name='عدد الاشخاص')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employeebasic', verbose_name='employee_name')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sandog.lkpomracategory', verbose_name='طريقة التقسيط')),
            ],
            options={
                'verbose_name': 'عرض العمرة',
                'verbose_name_plural': 'عروض العمرة',
            },
        ),
    ]
