# Generated by Django 5.2.7 on 2025-11-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandog', '0008_lkpomracategory_employeeomra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lkpomracategory',
            options={'ordering': ['id'], 'verbose_name': 'طريقة تقسيط العمرة', 'verbose_name_plural': 'طريقة تقسيط العمرة'},
        ),
    ]
