# Generated by Django 5.2.7 on 2025-11-16 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandog', '0009_alter_lkpomracategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeomra',
            name='count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الاشخاص'),
        ),
    ]
