"""
Django settings for e_service project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

from decouple import config,Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY') 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

#Site id: django.contrib.sites
SITE_ID = 2

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

# Force https
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)

# Inforce browsers to interact only via https
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=2592000, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config("SECURE_HSTS_INCLUDE_SUBDOMAINS",default=True, cast=bool)
SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=True, cast=bool)

#Cookie over https only
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=True, cast=bool)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=True, cast=bool)

# Application definition

INSTALLED_APPS = [
    # "admin_interface",
    # "colorfield",    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'django.contrib.gis',
    'django.contrib.humanize',
    
    # 3rd party
    'allauth', 
    'allauth.account', 
    'allauth.socialaccount',     
    
    'django_fsm',
    
    'bootstrap3',    
    
    'django_tables2',
    'django_filters',

    'import_export',

    'bootstrap_datepicker_plus',
    'auditlog',

    # 'django_crontab',
    'mptt',
    'treewidget',
    
    # Local                
    'accounts',
    # 'company_profile',    
    # 'check_cordinates',
    # 'pa',
    'bpmn_workflow',
    'help_request',
    'hr',
    'hr_bot',
    'sandog',
    'fleet',
    'it',
    'needs_request',
    'hr_employee_survey',
    # Debug
    # 'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    #3rd party
    'allauth.account.middleware.AccountMiddleware',
    'rollbar.contrib.django.middleware.RollbarNotifierMiddleware',
    'auditlog.middleware.AuditlogMiddleware',

    # Debug
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',

]

ROOT_URLCONF = 'e_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',   
                # 'company_profile.context_processors.in_progress_apps',
                'django.template.context_processors.media'
            ],
        },
    },
]

WSGI_APPLICATION = 'e_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        # "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": config('DB_NAME'),
        "USER": config('DB_USER'),
        "PASSWORD": config('DB_PASSWD'),
        "HOST": config('DB_HOST'),
        "PORT": config('DB_PORT'),
        "CONN_MAX_AGE": 300,
        "CONN_HEALTH_CHECKS": True,
        "ATOMIC_REQUESTS": True,
        "DISABLE_SERVER_SIDE_CURSORS": True,
    }    
}

if not DEBUG:

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": "media",
                "region_name": "sfo3",
                "endpoint_url": "https://hr1-mineralsgate-space.sfo3.digitaloceanspaces.com",
                "file_overwrite": False,
                "querystring_auth": True,
                "access_key": config('S3_ACCESS_KEY'),
                "secret_key": config('S3_SECRET_KEY'),
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": "static",
                "region_name": "sfo3",
                "endpoint_url": "https://hr1-mineralsgate-space.sfo3.digitaloceanspaces.com",
                "file_overwrite": False,
                "default_acl": "public-read",
                "querystring_auth": False,
                "access_key": config('S3_ACCESS_KEY'),
                "secret_key": config('S3_SECRET_KEY'),
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ar'  #en-us

TIME_ZONE = 'Africa/Khartoum'

USE_I18N = True

USE_TZ = True


LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

LANGUAGES = [
	("ar","Arabic"),
    # ("en","English"),
]
    
FORMAT_MODULE_PATH = [
    'hr.formats'
]

# USE_THOUSAND_SEPARATOR = True

# Media configurations
if DEBUG:
    MEDIA_ROOT = config('MEDIA_ROOT') #os.path.join(BASE_DIR, 'media')
# MEDIA_ROOT = config('MEDIA_ROOT') #os.path.join(BASE_DIR, 'media')

STATIC_URL = 'static/'
if DEBUG:
    STATIC_ROOT = config('STATIC_ROOT')
# STATIC_ROOT = config('STATIC_ROOT')
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",

    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
)

AUTH_USER_MODEL = 'accounts.CustomUser'

#ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*']
#ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*']
#ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*']
ACCOUNT_SESSION_REMEMBER = True
#ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_CHANGE_EMAIL = False
ACCOUNT_MAX_EMAIL_ADDRESSES = 1

ACCOUNT_ADAPTER = 'accounts.adapter.NoNewUsersAccountAdapter'

LOGIN_URL = config('LOGIN_URL')
LOGIN_REDIRECT_URL = 'acceptance_home'
ACCOUNT_LOGOUT_REDIRECT_URL = 'acceptance_home'

ACCOUNT_DEFAULT_PASSWORD = "changethispassword"

# Auditlog
AUDITLOG_INCLUDE_ALL_MODELS=True
AUDITLOG_DISABLE_REMOTE_ADDR = True

AUDITLOG_EXCLUDE_TRACKING_MODELS = (
    "sessions",
    # "<app_name>.<model>"
)

# logging 
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'formatters': {
        'verbose': {
            'format': '[contactor] %(levelname)s %(asctime)s %(message)s'
        },
    },
    'handlers': {
        # Send all messages to console
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        # This is the "catch all" logger
        '': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    }
}

# Debug
INTERNAL_IPS = [
    "127.0.0.1",
]

if not DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    DEFAULT_FROM_EMAIL = "system@mineralsgate.com"  # if you don't already have this in settings
    SERVER_EMAIL = "system@mineralsgate.com"  # ditto (default from-email for Django errors)

    EMAIL_HOST = config('EMAIL_HOST_NAME')
    EMAIL_PORT = config('EMAIL_HOST_PORT')
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = config('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

SHOW_REQUESTS_URL = "profile:pa_request_show"

# CRONJOBS = [
#     ('*/5 * * * *', 'pa.cron.generate_requests')
# ]

BOOTSTRAP3 = {
    "form_renderers": {"default": "e_service.renderers.FormRenderer"},
}

TREEWIDGET_SETTINGS = {
    "show_buttons": True,
    "search": True,
}

if not DEBUG:
    ROLLBAR = {
        'access_token': config('ROLLBAR_TOKEN'),
        'environment': 'development' if DEBUG else 'production',
        'code_version': '1.0',
        'root': BASE_DIR,
    }

    TELEGRAM_TOKEN_ID = config('TELEGRAM_HR_TOKEN_ID')
    TELEGRAM_IT_TOKEN_ID = config('TELEGRAM_IT_TOKEN_ID')

    TELEGRAM_DEVELOPER_CHAT_ID = config('TELEGRAM_DEVELOPER_CHAT_ID')

    OPENAI_API_KEY = config('OPENAI_API_KEY')
    OPENAI_BASE_URL = config('OPENAI_BASE_URL')
else:
    TELEGRAM_TOKEN_ID = ''
    TELEGRAM_IT_TOKEN_ID = ''

    TELEGRAM_DEVELOPER_CHAT_ID = ''

    OPENAI_API_KEY = ''
    OPENAI_BASE_URL = ''
